### PR TITLE
[frontend] Store comments.body as utf8mb4

### LINKED ISSUE #3547: No emojis in comments. Scandalous!
comments#create threw this 0 times
<pre>
Mysql2::Error: Incorrect string value: &#39;\xF0\x9F\x99\x86&#39; for column &#39;body&#39; at row 1: INSERT INTO `comments` (`body`, `created_at`, `updated_at`, `user_id`, `commentable_type`, `commentable_id`) VALUES (&#39;🙆&#39;, &#39;2017-08-08 13:15:38&#39;, &#39;2017-08-08 13:15:38.400795&#39;, 142, &#39;Project&#39;, 412)
</pre>
[https://build.opensuse.org/comments](https://build.opensuse.org/comments)"

~~[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5989b97aa8653800064f84d0)~~

~~[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5acb7126b6b7e400060a7b65)~~

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b3792fe1e111a0006749bc6)

### PR DESCRIPTION
**Pull request by coolo**
Allows emojis and fixes #3547

This charset change requires mysql 5.5, which was released 2012
but is still not the default. See more details about the problem
on https://railsmachine.com/articles/2017/05/19/converting-a-rails-database-to-utf8mb4.html

I borrowed the migration from there - but limited it to comments,
the charset is backward compatible, but requires changes to database.yml
in production (to store emojis not to apply the migration)

### CODE REVIEW

**Comment by hennevogel** [comment]
One down, countless tables to go...

**Comment by coolo** [comment]
Yeah, emojis may also appear in requests and changelogs nowaday. See the link for a full featured solution

**Comment by hennevogel** [comment]
Basically in all text inputs...

**Comment by coolo** [comment]
yeah, it's easy to add - I just wanted to play careful to avoid massive downtime on the change.

But it's tricky to deploy nonetheless

**Comment by coolo** [comment]
Whoever tagged the issue as 'junior' obviously didn't have this solution in mind - mysql really doesn't shine here :(

Having to modify old migrations is never nice, but it had to be done to give you :cow2: :heart: :milk_glass:

File: src/api/db/migrate/20140624101042_add_package_tracking.rb [hunk 1]
```diff
@@ -7,7 +7,7 @@ def up
 
       t.integer :release_package_id
 
-      t.string :binary_name, null: false
+      t.string :binary_name, null: false, charset: 'utf8'
```
Comment (hennevogel) [inline src/api/db/migrate/20140624101042_add_package_tracking.rb]: Please don't alter old migrations. If you need to change the charset (before switching to utf8mb) write a migration in between.

Comment (hennevogel) [reply src/api/db/migrate/20140624101042_add_package_tracking.rb]: > the rake task to replay history is using the same database.yml that we need for other tests

Then change that

Comment (coolo) [reply src/api/db/migrate/20140624101042_add_package_tracking.rb]: Thought about that - but it will only help for this very moment. All future migrations you'd expect to work on utf8mb4

Comment (hennevogel) [reply src/api/db/migrate/20140624101042_add_package_tracking.rb]: >  All future migrations you'd expect to work on utf8mb4

Hm isn't that clear if we switch to it? I don't get it...

Comment (coolo) [reply src/api/db/migrate/20140624101042_add_package_tracking.rb]: the dev:lint:db rake task replays all migration history in one go. Right now (master) this is done with a database.yml that contains since forever encoding: utf8 and all is good - unless you want to write real unicode.

now we want to switch, so we switch the database table format to barracuda to erase the index limit and change some columns. Perfect migration, no harm done.

*BUT*: to actually use this feature you also have to switch your DB connection to use the utf8mb4 encoding and this is done in database.yml. But if we change database.yml, all *old* add_column calls suddenly find themselves caught in new the index limit not matching a varchar(255). My solution to that problem is: make the old add_column calls use the old encoding, so we don't change history.

What you propose is *not* changing database.yml for migration testing, so they don't break and we don't have to touch them. But then you have to ask yourself: why are we doing migration testing - now and in the future. We do that so that users can run the old migrations no mater how our new code looks like. And future migrations we'd write with utf8mb4 requirement, so we wouldn't be able to test *them* correctly with an old database.yml.
