### PR TITLE
Fix url format for staging workflow

### LINKED ISSUE #8791: Staging dashboard: URL inconsistent
The Leap staging dashboard is at https://build.opensuse.org/staging_workflows/136 which is pretty non-obvious and different than any other URLs OBS.

Judging from the staging tab in a project it looks like a 1:1 relation so a more straight forward  URL would be e.g https://build.opensuse.org/staging_workflows/openSUSE:Leap:15.2

### PR DESCRIPTION
**Pull request by vpereira**
Fixes #8791 

We are still have a lot of todo here:

TODO:

- [x] Make sure that all helpers and variables names make sense
- [x] Fix all specs

### CODE REVIEW

**Comment by vpereira** [comment]
[Address StagingWorkflow Feedback](https://trello.com/c/3FiBmuTX/1317-address-stagingworkflow-feedback)

**Comment by vpereira** [comment]
```
frontend@3f58864e5664:/obs/src/api> rake routes -c 'webui/staging/workflows'
               Prefix Verb   URI Pattern                                         Controller#Action
    staging_workflows POST   /staging_workflows(.:format)                        webui/staging/workflows#create
 new_staging_workflow GET    /staging_workflows/new(.:format)                    webui/staging/workflows#new
edit_staging_workflow GET    /staging_workflows/:workflow_project/edit(.:format) webui/staging/workflows#edit {:workflow_project=>/[^\/]*/}
     staging_workflow GET    /staging_workflows/:workflow_project(.:format)      webui/staging/workflows#show {:workflow_project=>/[^\/]*/}
                      PATCH  /staging_workflows/:workflow_project(.:format)      webui/staging/workflows#update {:workflow_project=>/[^\/]*/}
                      PUT    /staging_workflows/:workflow_project(.:format)      webui/staging/workflows#update {:workflow_project=>/[^\/]*/}
                      DELETE /staging_workflows/:workflow_project(.:format)      webui/staging/workflows#destroy {:workflow_project=>/[^\/]*/}
frontend@3f58864e5664:/obs/src/api> 

```

File: src/api/app/controllers/webui/staging/workflows_controller.rb [hunk 1]
```diff
@@ -89,17 +89,21 @@ def update
...
+  end
+
   def set_staging_workflow
-    @staging_workflow = ::Staging::Workflow.find_by(id: params[:id])
+    @staging_workflow = @project.staging
     return if @staging_workflow
 
     redirect_back(fallback_location: root_path)
-    flash[:error] = "Staging with id = #{params[:id]} doesn't exist"
+    flash[:error] = 'Staging project not found'
```
Comment (DavidKang) [inline src/api/app/controllers/webui/staging/workflows_controller.rb]: This message could be confusing, because what we don't found is the `Staging` and not the `Staging project`, maybe something like ``` "Project #{@project} doesn't have a Staging"```

Comment (vpereira) [reply src/api/app/controllers/webui/staging/workflows_controller.rb]: done
