### PR TITLE
Fix error when processing bad group updates via xml

### LINKED ISSUE #16434: [production][group#update] undefined method `value' for nil:NilClass

    raise InvalidParameterError, 'group name from path...
[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/66812ea384bf4608c2d88ebd)
# undefined method `value&#39; for nil:NilClass

    raise InvalidParameterError, &#39;group name from path and xml mismatch&#39; unless group.title == xmlhash.value(&#39;title&#39;)
                                                                                                      ^^^^^^ #
### URL ###
[https://api.opensuse.org/group/factory-maintainers](https://api.opensuse.org/group/factory-maintainers)"
### Where ###
group#update

### Occured ###
Jun 30 10:08am

### Similar ###
3

## Params ##
~~~
{
  &quot;action&quot; =&gt; &quot;update&quot;,
  &quot;controller&quot; =&gt; &quot;group&quot;,
  &quot;title&quot; =&gt; &quot;factory-maintainers&quot;
}
~~~

## Session ##
~~~
{}
~~~

## Backtrace ##
~~~
57:  app/controllers/group_controller.rb -> **update**
6:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/basic_implicit_render.rb -> **send_action**
215:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/abstract_controller/base.rb -> **process_action**
165:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/rendering.rb -> **process_action**
234:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/abstract_controller/callbacks.rb -> **block in process_action**
107:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb -> **run_callbacks**
233:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/abstract_controller/callbacks.rb -> **process_action**
23:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/rescue.rb -> **process_action**
67:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/instrumentation.rb -> **block in process_action**
206:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications/instrumenter.rb -> **instrument**
206:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **instrument**
66:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/instrumentation.rb -> **process_action**
259:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/params_wrapper.rb -> **process_action**
27:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/railties/controller_runtime.rb -> **process_action**
151:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/abstract_controller/base.rb -> **process**
39:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/rendering.rb -> **process**
188:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal.rb -> **dispatch**
251:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal.rb -> **dispatch**
49:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/route_set.rb -> **dispatch**
32:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/route_set.rb -> **serve**
18:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/mapper.rb -> **block in &lt;class:Constraints&gt;**
48:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/mapper.rb -> **serve**
50:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/journey/router.rb -> **block in serve**
32:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/journey/router.rb -> **each**
32:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/journey/router.rb -> **serve**
852:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/route_set.rb -> **call**
87:  /GEM_ROOT/gems/flipper-1.3.0/lib/flipper/middleware/memoizer.rb -> **memoized_call**
45:  /GEM_ROOT/gems/flipper-1.3.0/lib/flipper/middleware/memoizer.rb -> **call**
15:  config/initializers/prefer_xml_over_html.rb -> **call**
44:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/deflater.rb -> **call**
15:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/tempfile_reaper.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/etag.rb -> **call**
40:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/conditional_get.rb -> **call**
12:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/head.rb -> **call**
38:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/http/permissions_policy.rb -> **call**
36:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/http/content_security_policy.rb -> **call**
266:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/session/abstract/id.rb -> **context**
260:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/session/abstract/id.rb -> **call**
704:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/cookies.rb -> **call**
27:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/callbacks.rb -> **block in call**
99:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb -> **run_callbacks**
26:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/callbacks.rb -> **call**
32:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call!**
21:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call**
28:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/debug_exceptions.rb -> **call**
29:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/show_exceptions.rb -> **call**
18:  /GEM_ROOT/gems/lograge-0.14.0/lib/lograge/rails_ext/rack/logger.rb -> **call_app**
25:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/rack/logger.rb -> **block in call**
99:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/tagged_logging.rb -> **block in tagged**
37:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/tagged_logging.rb -> **tagged**
99:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/tagged_logging.rb -> **tagged**
25:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/rack/logger.rb -> **call**
93:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/remote_ip.rb -> **call**
93:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/remote_ip.rb -> **call**
19:  /GEM_ROOT/gems/request_store-1.7.0/lib/request_store/middleware.rb -> **call**
26:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/request_id.rb -> **call**
24:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/method_override.rb -> **call**
22:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/runtime.rb -> **call**
29:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/cache/strategy/local_cache_middleware.rb -> **call**
14:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/executor.rb -> **call**
18:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/lock.rb -> **call**
110:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/sendfile.rb -> **call**
131:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/host_authorization.rb -> **call**
530:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/engine.rb -> **call**
226:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/railtie.rb -> **public_send**
226:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/railtie.rb -> **method_missing**
74:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/urlmap.rb -> **block in call**
58:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/urlmap.rb -> **each**
58:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/urlmap.rb -> **call**
107:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb -> **process_request**
157:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **accept_and_process_next_request**
110:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **main_loop**
419:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/request_handler.rb -> **block (3 levels) in start_threads**
113:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/utils.rb -> **block in create_thread_and_abort_on_exception**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| program_name | Passenger RubyApp: /srv/www/obs/api (production) |
| HTTP_USER_AGENT | osc/1.5.1 |

### PR DESCRIPTION
**Pull request by danidoni**
Instead of crashing, we now raise an InvalidParameterError when receiving an invalid XML when trying to update a group.

Fixes #16434

### CODE REVIEW

**Comment by hennevogel** [comment]
We validate XML input and output with `validate_action`...

**Comment by danidoni** [comment]
> We validate XML input and output with `validate_action`...

Alright, how about that?

**Comment by hennevogel** [comment]
> Alright, how about that?

Please don't invent another way to do this...

https://github.com/openSUSE/open-build-service/blob/41d9eb2df1eb0de891e7142a8c693ea323b49a39/src/api/app/controllers/application_controller.rb#L60-L86

**Comment by danidoni** [comment]
> Please don't invent another way to do this...

My bad, I didn't understood properly before.

File: src/api/spec/controllers/group_controller_spec.rb [hunk 1]
```diff
@@ -105,7 +105,21 @@
     end
 
     context 'when the group does not exist' do
-      before { put :update, body: '<group><title>new_group</title></group>', params: { title: 'new_group', format: :xml } }
+      let(:new_member) { create(:confirmed_user) }
```
Comment (eduardoj) [inline src/api/spec/controllers/group_controller_spec.rb:108]:
```suggestion
```
This `let` is redundant. See line 77. We can get rid of it.

File: src/api/test/functional/group_test.rb [hunk 2]
```diff
@@ -43,7 +43,10 @@ def test_get_group
   end
 
   def test_create_modify_and_delete_group
-    xml = '<group><title>new_group</title></group>'
+    FactoryBot.create(:confirmed_user, login: 'hans')
+    FactoryBot.create(:confirmed_user, login: 'luke')
+
+    xml = '<group><title>new_group</title><maintainer userid="hans"/><person><person userid="luke"/></person></group>'
```
Comment (hennevogel) [inline src/api/test/functional/group_test.rb:49]: Why is this necessary now?

File: src/api/spec/controllers/group_controller_spec.rb (hunk 1 above)
Comment (danidoni) [reply src/api/spec/controllers/group_controller_spec.rb:108]: Alright

File: src/api/test/functional/group_test.rb (hunk 2 above)
Comment (danidoni) [reply src/api/test/functional/group_test.rb:49]: Because now the validation is done against the schema, and the schema requires a `maintainer` and a `person` elements present.

Comment (hennevogel) [reply src/api/test/functional/group_test.rb:49]: Alright...

File: src/api/test/functional/group_test.rb [hunk 3]
```diff
@@ -43,7 +43,10 @@ def test_get_group
   end
 
   def test_create_modify_and_delete_group
-    xml = '<group><title>new_group</title></group>'
+    FactoryBot.create(:confirmed_user, login: 'hans')
+    FactoryBot.create(:confirmed_user, login: 'luke')
```
Comment (hennevogel) [inline src/api/test/functional/group_test.rb:47]: Please use fixtures...

**Review by hennevogel — APPROVED** [review]
