### PR TITLE
Fixes deletion of devel tags from a package's meta

### LINKED ISSUE #18084: cannot remove devel project reference
# Issue Description

From the meta of a package, I tried to drop `<devel project="Devel:Galaxy:Manager:Head" package="grafana-formula"/>` via WebUI or CLI from the IBS projects:

- `Devel:Galaxy:Manager:5.0`
- `Devel:Galaxy:Manager:4.3`

but as soon as I save, that devel tag is back again.

Expected Result
============
When the change is saved and no error has been reported, the saved change should persist

How to Reproduce
===============
1. Go to https://build.suse.de/projects/Devel:Galaxy:Manager:4.3/packages/grafana-formula/meta'
2. Remove the line `<devel project="Devel:Galaxy:Manager:Head" package="grafana-formula"/>`
3. Save
4. Check again the meta

or

1. `osc -A https://api.suse.de meta pkg -e Devel:Galaxy:Manager:5.0 grafana-formula`
2. Remove the line `<devel project="Devel:Galaxy:Manager:Head" package="grafana-formula"/>`
3. Save
4. check with `osc -A https://api.suse.de meta pkg Devel:Galaxy:Manager:5.0 grafana-formula`

Further Information
===============
* https://build.suse.de/projects/Devel:Galaxy:Manager:4.3/packages/grafana-formula/meta
* I reproduced this in IBS, I didn't test in OBS.

### PR DESCRIPTION
**Pull request by danidoni**
When we refactored Package#update_from_xml in
https://github.com/openSUSE/open-build-service/pull/16227 we forgot to clear the develpackage before updating the values coming from an xml.

This commit clears the develpackage before updating the values, so if someone deletes the devel tag from the xml meta, we remove it from the model as well.

Fixes #18084

### CODE REVIEW

File: src/api/spec/controllers/webui/packages/meta_controller_spec.rb [hunk 1]
```diff
@@ -110,5 +110,41 @@
       it { expect(flash[:error]).to eq('Error while saving the Meta file: fake message.') }
       it { expect(response).to have_http_status(:bad_request) }
     end
+
+    context 'when adding a devel section' do
```
Comment (hennevogel) [inline src/api/spec/controllers/webui/packages/meta_controller_spec.rb]: Don't test this through a controller spec, it's model code...

**Review by hennevogel — CHANGES_REQUESTED** [review]

File: src/api/spec/controllers/webui/packages/meta_controller_spec.rb (hunk 1 above)
Comment (danidoni) [reply src/api/spec/controllers/webui/packages/meta_controller_spec.rb]: You're right

**Review by saraycp — APPROVED** [review]
