### PR TITLE
[frontend] Sanitize patchinfo input before saving it

### LINKED ISSUE #4662: patchinfo rating tag allowed spaces
Issue/Feature description
====================

checking in patchinfos with spaces in <rating> is possible.

We had a patchinfo with <rating>SPACEmoderate</rating> that caused our tools to fail.

This is probably not intended.

Expected result
============
checking of <rating> with space should fail

How to Reproduce
===============
1. checkin a patchinfo file
2. <rating> moderate</rating> is the rating with a space
3. validator should not allow checkin

Further information
===============
* OBS
* deployed state of 2018 03 15

### PR DESCRIPTION
**Pull request by bgeuken**
Remove leading / trailing whitespaces from rating and category.

Fixes #4662

### CODE REVIEW

File: src/api/app/controllers/webui/patchinfo_controller.rb [hunk 1]
```diff
@@ -138,8 +138,8 @@ def save
           issue[0].gsub!(/^(CVE|cve)-/, '') if issue[1] == 'cve'
           node.issue(issue[2], tracker: issue[1], id: issue[0])
         end
-        node.category params[:category]
-        node.rating params[:rating]
+        node.category params[:category].try(:strip)
+        node.rating params[:rating].try(:strip)
         node.summary params[:summary]
```
Comment (ChrisBr) [inline src/api/app/controllers/webui/patchinfo_controller.rb]: What about summary?
