### PR TITLE
Only use GET for search index endpoint

### LINKED ISSUE #10196: Search on the 404 page doesn't work
Issue Description
=============
The search button on the 404 page doesn't react on clicks and after a hit on the `return`-key the search forwards to a 403 error page.

Expected Result
============
The search button and search should behave normally.

How to Reproduce
===============
1. Go to not existing URL. For example https://build.opensuse.org/notexistingsite
2. Type something in the search box
3. Click on the 'Search' buttons.
4. See that nothing happens
5. Hit the `return` key.
6. See the 403 error

Further Information
===============
Here is a screencapture:
obs-404-search

### PR DESCRIPTION
**Pull request by krauselukas**
The search#index endpoint doesnt modify or
store and any data. Therefore we shouldn't allow
or use POST request to access the resource.
This will also prevent issues with our 404 page
which is a static html file that doesn't include a
CSRF token (which would be require for POST).

Fixes #10196

### CODE REVIEW

File: src/api/app/controllers/webui/search_controller.rb [hunk 1]
```diff
@@ -2,6 +2,7 @@ class Webui::SearchController < Webui::WebuiController
   before_action :set_attribute_list
   before_action :set_tracker_list
   before_action :set_parameters, except: :issue
+  skip_before_action :verify_authenticity_token, only: [:index]
```
Comment (hennevogel) [inline src/api/app/controllers/webui/search_controller.rb:5]: Why is this a `POST` route at all? We are not changing/storing any data?

**Review by hennevogel — CHANGES_REQUESTED** [review]

File: src/api/app/controllers/webui/search_controller.rb (hunk 1 above)
Comment (krauselukas) [reply src/api/app/controllers/webui/search_controller.rb:5]: :facepalm: true

Comment (krauselukas) [reply src/api/app/controllers/webui/search_controller.rb:5]: its allows both POST and GET, I will check

Comment (krauselukas) [reply src/api/app/controllers/webui/search_controller.rb]: @hennevogel I changed all the POST' to GET', no idea why we used POST', couldn't find a reason for it

**Review by hennevogel — APPROVED** [review]

**Comment by hennevogel** [comment]
Hmmm.
