### PR TITLE
Fix the badge#show error

### LINKED ISSUE #13320: [production][badge#show] undefined method `[]' for nil:NilClass

        file = Rails.application.assets[filename].source
...
[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/63636e0b84bf46052570d67e)
# undefined method `[]&#39; for nil:NilClass

        return Rails.application.assets[filename].source if results.blank?
                                       ^^^^^^^^^^ #
### URL ###
[https://build.opensuse.org/projects/home:hellcp-work/packages/test/badge.svg](https://build.opensuse.org/projects/home:hellcp-work/packages/test/badge.svg)"
### Where ###
badge#show

### Occured ###
Nov 03  7:30am

### Similar ###
7

## Params ##
~~~
{
  &quot;action&quot; =&gt; &quot;show&quot;,
  &quot;controller&quot; =&gt; &quot;webui/packages/badge&quot;,
  &quot;format&quot; =&gt; &quot;svg&quot;,
  &quot;package_name&quot; =&gt; &quot;test&quot;,
  &quot;project_name&quot; =&gt; &quot;home:hellcp-work&quot;
}
~~~

## Session ##
~~~
{
  &quot;_csrf_token&quot; =&gt; &quot;F-xdxlLkdnCjl8ZXAwihZoOtp-m1Q04aDUSxsjDq01U=&quot;,
  &quot;session_id&quot; =&gt; &quot;d5acac234bd896d8d4f0f9327e1e1b97&quot;
}
~~~

## Backtrace ##
~~~
18:  app/controllers/webui/packages/badge_controller.rb -> **create_badge**
11:  app/controllers/webui/packages/badge_controller.rb -> **show**
6:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_controller/metal/basic_implicit_render.rb -> **send_action**
215:  /GEM_ROOT/gems/actionpack-7.0.4/lib/abstract_controller/base.rb -> **process_action**
53:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_controller/metal/rendering.rb -> **process_action**
234:  /GEM_ROOT/gems/actionpack-7.0.4/lib/abstract_controller/callbacks.rb -> **block in process_action**
107:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/callbacks.rb -> **run_callbacks**
233:  /GEM_ROOT/gems/actionpack-7.0.4/lib/abstract_controller/callbacks.rb -> **process_action**
22:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_controller/metal/rescue.rb -> **process_action**
67:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_controller/metal/instrumentation.rb -> **block in process_action**
206:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/notifications/instrumenter.rb -> **instrument**
206:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/notifications.rb -> **instrument**
66:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_controller/metal/instrumentation.rb -> **process_action**
259:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_controller/metal/params_wrapper.rb -> **process_action**
27:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/railties/controller_runtime.rb -> **process_action**
151:  /GEM_ROOT/gems/actionpack-7.0.4/lib/abstract_controller/base.rb -> **process**
39:  /GEM_ROOT/gems/actionview-7.0.4/lib/action_view/rendering.rb -> **process**
188:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_controller/metal.rb -> **dispatch**
251:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_controller/metal.rb -> **dispatch**
49:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/routing/route_set.rb -> **dispatch**
32:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/routing/route_set.rb -> **serve**
18:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/routing/mapper.rb -> **block in &lt;class:Constraints&gt;**
48:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/routing/mapper.rb -> **serve**
50:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/journey/router.rb -> **block in serve**
32:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/journey/router.rb -> **each**
32:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/journey/router.rb -> **serve**
852:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/routing/route_set.rb -> **call**
72:  /GEM_ROOT/gems/flipper-0.25.2/lib/flipper/middleware/memoizer.rb -> **memoized_call**
37:  /GEM_ROOT/gems/flipper-0.25.2/lib/flipper/middleware/memoizer.rb -> **call**
15:  config/initializers/prefer_xml_over_html.rb -> **call**
44:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/deflater.rb -> **call**
15:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/tempfile_reaper.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/etag.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/conditional_get.rb -> **call**
12:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/head.rb -> **call**
38:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/http/permissions_policy.rb -> **call**
36:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/http/content_security_policy.rb -> **call**
266:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/session/abstract/id.rb -> **context**
260:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/session/abstract/id.rb -> **call**
696:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/middleware/cookies.rb -> **call**
27:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/middleware/callbacks.rb -> **block in call**
99:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/callbacks.rb -> **run_callbacks**
26:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/middleware/callbacks.rb -> **call**
32:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call!**
21:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call**
28:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/middleware/debug_exceptions.rb -> **call**
26:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/middleware/show_exceptions.rb -> **call**
18:  /GEM_ROOT/gems/lograge-0.12.0/lib/lograge/rails_ext/rack/logger.rb -> **call_app**
25:  /GEM_ROOT/gems/railties-7.0.4/lib/rails/rack/logger.rb -> **block in call**
99:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/tagged_logging.rb -> **block in tagged**
37:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/tagged_logging.rb -> **tagged**
99:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/tagged_logging.rb -> **tagged**
25:  /GEM_ROOT/gems/railties-7.0.4/lib/rails/rack/logger.rb -> **call**
93:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/middleware/remote_ip.rb -> **call**
93:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/middleware/remote_ip.rb -> **call**
19:  /GEM_ROOT/gems/request_store-1.5.1/lib/request_store/middleware.rb -> **call**
26:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/middleware/request_id.rb -> **call**
24:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/method_override.rb -> **call**
22:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/runtime.rb -> **call**
29:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/cache/strategy/local_cache_middleware.rb -> **call**
14:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/middleware/executor.rb -> **call**
18:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/lock.rb -> **call**
110:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/sendfile.rb -> **call**
131:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/middleware/host_authorization.rb -> **call**
530:  /GEM_ROOT/gems/railties-7.0.4/lib/rails/engine.rb -> **call**
226:  /GEM_ROOT/gems/railties-7.0.4/lib/rails/railtie.rb -> **public_send**
226:  /GEM_ROOT/gems/railties-7.0.4/lib/rails/railtie.rb -> **method_missing**
74:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/urlmap.rb -> **block in call**
58:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/urlmap.rb -> **each**
58:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/urlmap.rb -> **call**
107:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb -> **process_request**
149:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **accept_and_process_next_request**
110:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **main_loop**
419:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/request_handler.rb -> **block (3 levels) in start_threads**
113:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/utils.rb -> **block in create_thread_and_abort_on_exception**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| program_name | Passenger RubyApp: /srv/www/obs/api (production) |
| HTTP_USER_AGENT | Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0 |

### PR DESCRIPTION
**Pull request by hellcp-work**
This should fix the error from #13320. It replaces the Rails.application.assets function with directly referenced filesystem location of the files.

Closes #13320

### CODE REVIEW

File: src/api/app/controllers/webui/packages/badge_controller.rb [hunk 1]
```diff
@@ -15,7 +15,7 @@ def show
 
       def create_badge(results)
         filename = 'badge-unknown.svg'
-        return Rails.application.assets[filename].source if results.blank?
+        return assets_file(filename) if results.blank?
```
Comment (danidoni) [inline src/api/app/controllers/webui/packages/badge_controller.rb:18]: I cannot comment on already commited code, but it's much better if this function does not access the `params` hash in line 22: it will be easier to change in the future if the code in this function consumes local variables only.

File: src/api/app/controllers/webui/packages/badge_controller.rb [hunk 2]
```diff
@@ -24,13 +24,17 @@ def create_badge(results)
       end
 
       def get_badge_file(filename, results)
-        file = Rails.application.assets[filename].source
+        file = assets_file(filename)
         return file unless params[:type] == 'percent'
 
         succeeded = results.select { |r| r.code == 'succeeded' }.try(:length).to_i
         file.gsub!('#e05d44', '#4c1') if succeeded == results.length
```
Comment (danidoni) [inline src/api/app/controllers/webui/packages/badge_controller.rb:31]: What are those values? Can we extract some meaningful constant?

File: src/api/app/controllers/webui/packages/badge_controller.rb [hunk 3]
```diff
@@ -3,34 +3,40 @@ module Packages
...
+        file = assets_file(filename)
+        return file unless type == 'percent'
 
         succeeded = results.select { |r| r.code == 'succeeded' }.try(:length).to_i
-        file.gsub!('#e05d44', '#4c1') if succeeded == results.length
+        file.gsub!(RED, GREEN) if succeeded == results.length
         file.gsub('%PERCENTAGE%', "#{100 * succeeded / results.length}%")
       end
+
+      def assets_file(filename)
```
Comment (hennevogel) [inline src/api/app/controllers/webui/packages/badge_controller.rb:37]: This is not an assets file. No need for this method.

File: src/api/app/controllers/webui/packages/badge_controller.rb [hunk 4]
```diff
@@ -3,32 +3,34 @@ module Packages
...
         results = results.select { |r| r.architecture == params[:architecture] } if params[:architecture]
         results = results.select { |r| r.repository == params[:repository] } if params[:repository]
-        send_data(create_badge(results), type: 'image/svg+xml', disposition: 'inline')
+        send_data(create_badge(results, params[:type]), type: 'image/svg+xml', disposition: 'inline')
       end
 
       private
 
-      def create_badge(results)
+      def create_badge(results, type)
```
Comment (danidoni) [inline src/api/app/controllers/webui/packages/badge_controller.rb:18]: This looks like an object by itself (`Badge.new(results, type`) with it's own tests and so on... :)

**Comment by hennevogel** [comment]
Please squash the commits...

File: src/api/app/models/badge.rb [hunk 5]
```diff
@@ -0,0 +1,26 @@
...
+  GREEN = '#4c1'.freeze
+
+  def initialize(results, type)
+    @results = results
+    @type = type
+    @filename = 'badge-unknown.svg'
+    @unknown = true
+    return if @results.blank?
+
+    @filename = 'badge-failed.svg' if @results.any? { |r| r.code == 'failed' }
```
[the remark this answers is not in the document]
Comment (dmarcoux) [reply src/api/app/models/badge.rb:14]: My point still stands. This method is confusing, it's called `status!`, but has nothing to do with a status. This is setting the filename based on the results. How about having an instance method which is called `filename` and contains the logic regarding the filename (so all those `if` statements, in addition to this line `@filename = 'badge-unknown.svg'` from `initialize`.

File: src/api/app/models/badge.rb [hunk 6]
```diff
@@ -0,0 +1,27 @@
...
+    @filename = 'badge-succeeded.svg' if @results.all? { |r| r.code == 'succeeded' }
+    @filename = 'badge-percent.svg' if @type == 'percent'
+  end
+
+  def xml
+    file = Rails.public_path.join(@filename).read
+    return file unless @filename == 'badge-percent.svg'
```
Comment (dmarcoux) [inline src/api/app/models/badge.rb:21]: Checking for `@type == 'percent'` instead of `@filename == 'badge-percent.svg'` would allow to extract  `@type == 'percent'` into a private helper method and reusing this code here and in the `filename` instance method I wrote about in my other comment above.

**Review by dmarcoux — APPROVED** [review]

File: src/api/spec/models/badge_spec.rb [hunk 7]
```diff
@@ -0,0 +1,77 @@
...
+  let(:request) do
+    stub_request(:get, "#{CONFIG['source_url']}/build/#{user.home_project}/_result?locallink=1&multibuild=1&lastbuild=1" \
+                       "&package=#{source_package}&view=status").and_return(body: body)
+  end
+  let(:results) { request && source_package.buildresult(source_project, false, true).results[source_package.name] }
+  let(:badge) { Badge.new(type, results) }
+
+  describe '#new' do
+    RSpec.shared_examples 'tests for badge xml' do
+      describe 'empty restultlist' do
```
Comment (eduardoj) [inline src/api/spec/models/badge_spec.rb:16]:
```suggestion
      describe 'empty resultlist' do
```
Typo. It happens a couple of times more in this same file.

**Review by eduardoj — APPROVED** [review]
