### PR TITLE
Handle the comment js errors

### LINKED ISSUE #4524: Crash page rendered inside comment box
Issue/Feature description
====================
If `Comment` creation crashes, the `500.html` is rendered inside the comment box.

Expected result
============
If `Comment` creation crashes, the `500.html` is rendered inside by browser.

Further information
===============
screenshot-2018-2-19 show home hennevogel - test instance of opensuse build service

### LINKED ISSUE #17750: After writing comments, get blank page
When I write a comment in a request page that's been open for some time (at least 30 minutes), when I click in "Add comment", my comment doesn't get submitted and instead I get some kind of deformed page again with big white squares. If I refresh the page, it renders correctly but of course, my comment is lost.

This have happened a few times since last Thursday / Friday.

It just happened in the minutes previous to writing this issue with https://build.opensuse.org/request/show/1270912 if you want to check.

### PR DESCRIPTION
**Pull request by hellcp-work**
All proper responses from the controller now return status code 200, while any other kind of response will render an alert at the top of the page

Fixes #17750
Fixes #4524

### CODE REVIEW

File: src/api/app/controllers/webui/comments_controller.rb [hunk 1]
```diff
@@ -11,22 +11,18 @@ def create
...
 
-    status = if @comment.save
-               flash.now[:success] = 'Comment created successfully.'
-               :ok
-             else
-               flash.now[:error] = "Failed to create comment: #{@comment.errors.full_messages.to_sentence}."
-               :unprocessable_entity
-             end
+    if @comment.save
+      flash.now[:success] = 'Comment created successfully.'
```
Comment (hennevogel) [inline src/api/app/controllers/webui/comments_controller.rb:15]: This also happens with the ajax request right? Why? There are "standard" ways to do this

https://github.com/hennevogel/rails7/blob/41c86906a98e6e24a63fc349e6badaa27ed60d43/app/controllers/things_controller.rb#L23-L35

Comment (hellcp-work) [reply src/api/app/controllers/webui/comments_controller.rb:15]: Not sure what you mean

Comment (hellcp-work) [reply src/api/app/controllers/webui/comments_controller.rb:15]: But there are no redirects involved here

Comment (danidoni) [reply src/api/app/controllers/webui/comments_controller.rb:15]: Okay, but there is a render just below: https://github.com/hennevogel/rails7/blob/41c86906a98e6e24a63fc349e6badaa27ed60d43/app/controllers/things_controller.rb#L29

Comment (hellcp-work) [reply src/api/app/controllers/webui/comments_controller.rb:15]: While redirect_to supports that: https://api.rubyonrails.org/v7.1.0/classes/ActionController/Redirecting.html#method-i-redirect_to, I don't see render support specifying notice: https://api.rubyonrails.org/classes/ActionController/Rendering.html#method-i-render

Comment (danidoni) [reply src/api/app/controllers/webui/comments_controller.rb:15]: True, but when in a `create` action, when the save goes well, we redirect to the show page, we only render when the save fails... That's the rails way. In this case, you need to use the `redirect_to` with the `notice: ...` option

Comment (hellcp-work) [reply src/api/app/controllers/webui/comments_controller.rb:15]: `redirect_to` in ajax to render the partial in the view? Does that even work?

Comment (danidoni) [reply src/api/app/controllers/webui/comments_controller.rb:15]: Oh, right, it's an ajax request... Then there is no redirect, only render

File: src/api/app/assets/javascripts/webui/comment.js [hunk 2]
```diff
@@ -45,11 +58,19 @@ function handlingCommentEvents() {
...
+      commentError('Failed to submit the comment.');
+      return;
+    }
     $(this).closest('.comments-thread').html(data.responseText);
   });
 
   // This is being used to render a new root comment by the beta request show view
   $(document).on('ajax:complete', '.comment_new .post-comment-form', function(_, data) {
+    if (data.status !== 200) {
+      commentError('Failed to create a comment.');
```
[the remark this answers is not in the document]
Comment (hennevogel) [reply src/api/app/assets/javascripts/webui/comment.js]: It makes little sense, but okay...

**Review by hennevogel — APPROVED** [review]
