### PR TITLE
Make sure a changed manager group gets the reviewer role

### LINKED ISSUE #16205: changing the manager group for a staging workflow fails
just tried on IBS but the same should be reproducible on OBS as well:

so if you are on the staging page:
https://build.suse.de/staging_workflows/SUSE:ALP:Source:Standard:1.0

and then on the left black bar in "Actions on this page" click "edit staging"
(and I really would have expected this on the top with all the other nav items)

you get to:
https://build.suse.de/staging_workflows/SUSE:ALP:Source:Standard:1.0/edit

and again on the left you click "change managers"
and get a pop-up to change the managers group.

there you enter "maintenance-staging-managers" and click "Accept"

but at least for me and eli this ends up with "404: Not Found" trying to go to https://build.suse.de/staging_workflows/71 

if you try this via api call on osc you get:
> iosc api -X PUT -T staging-workflow-manager.xml /staging/SUSE:ALP:Source:Standard:1.0/workflow

gives me:
x-request-id: 4dce0119-fd99-425a-9824-47d3a60f422f
status: 500 Internal Server Error

probably this one:
https://errbit.suse.de/apps/53bac9aad9d1af372d012a0c/problems/66506fffd9d1af07c6d3e5ce

undefined method `destroy' for nil:NilClass relationship.destroy ^^^^^^^^

app/models/staging/workflow.rb:132→ update_managers_group
activesupport-7.0.8.1/lib/active_support/callbacks.rb:400→ block in make_lambda
activesupport-7.0.8.1/lib/active_support/callbacks.rb:199→ block (2 levels) in halting
activesupport-7.0.8.1/lib/active_support/callbacks.rb:687→ block (2 levels) in default_terminator
activesupport-7.0.8.1/lib/active_support/callbacks.rb:686→ catch

### PR DESCRIPTION
**Pull request by eduardoj**
The manager group of a staging workflow could have lost its review role of the project attached to a staging workflow. That made updating the manager group to throw an error.

Remove reviewer role for old managers role and add reviewer role for new
managers role.

Fixes #16205.

### CODE REVIEW

File: src/api/app/models/staging/workflow.rb [hunk 1]
```diff
@@ -129,13 +130,16 @@ def update_managers_group
     reviewer_role = Role.find_by_title('reviewer')
     relationship = project.relationships.find_by(group: old_managers_group, role: reviewer_role)
     if project.relationships.exists?(group: new_managers_group, role: reviewer_role)
-      relationship.destroy
-    else
+      relationship.destroy if relationship.present?
```
Comment (hennevogel) [inline src/api/app/models/staging/workflow.rb:133]: I don't get it. How would it not be present if it exists?

Comment (eduardoj) [reply src/api/app/models/staging/workflow.rb:133]: > I don't get it. How would it not be present if it exists?

In few words: `exists?` is for `old_managers_group`, `.present?` is for `new_managers_group`.

`relationship` (assigned in line 130) is the current record from the table relationships, with the group `old_managers_group`.

The first `if` (line 131) checks for a relationship with the group `new_managers_group`. In this case, we don't have to create a new record for the `new_managers_group` group. However, we have to remove the relationship with the old group, only if that one is present.

Comment (eduardoj) [reply src/api/app/models/staging/workflow.rb]: I followed your suggestion and modified the code. Please take a look again.

**Review by hennevogel — APPROVED** [review]
