### PR TITLE
Show a proper error message when excluding a request

### LINKED ISSUE #8355: Exclude requests which are `ready`
In the staging workflow, it should be possible to exclude requests which are `ready`.

To reproduce, create a staging workflow for a project (`home:Admin` for example) and have a request open for this project.

Then run this command (by adapting it to your project name and request ID):
```
osc api staging/PROJECT_NAME/excluded_requests -X POST -d "<excluded_requests><request number='REQUEST_ID' description='invalid request' /></excluded_requests>"
```

This will fail:
```
Server returned an error: HTTP Error 400: Bad Request
Excluding requests for #<Staging::Workflow:0x00007f1eea77f410> failed: Request : Number can't be blank and Request is not a number.
```

### PR DESCRIPTION
**Pull request by eduardoj**
Make API and web UI consistent with the same behaviour and error messages.

Fixes #8355.

Co-authored-by: David Kang <dkang@suse.com>

### CODE REVIEW

**Comment by eduardoj** [comment]
[Address Feedback](https://trello.com/c/6UXRNR8X/1294-address-feedback)

File: src/api/app/models/staging/request_excluder.rb [hunk 1]
```diff
@@ -34,11 +26,36 @@ def valid?
...
     [requests_xml_hash[:number]].flatten.map(&:to_i)
   end
+
+  def valid_request?(bs_request, request_number)
+    return true if bs_request && bs_request.staging_project.nil?
+
+    errors << if bs_request
+                "Request #{request_number} could not be excluded because is staged in: #{bs_request.staging_project}"
+              else
+                "Request #{request_number} doesn't exist or it doesn't belong to this project"
```
Comment (dmarcoux) [inline src/api/app/models/staging/request_excluder.rb]: It would be nice to provide a more accurate error message to the user.

To make this possible, we need to retrieve the request and if it exists, check if it belongs to the project. Right now, we only retrieve the request if it belongs to the project, so it's preventing us from knowing if this request simply doesn't exist.

Comment (eduardoj) [reply src/api/app/models/staging/request_excluder.rb]: True. I will take care of #7355. Can we accept this pull request then, as it is only fixing #8355? Or do you think it is needed to fix #8355 in this same pull request?

**Comment by hennevogel** [comment]
codecov hangs. coveralls is fine. merging!
