### PR TITLE
[webui] Fix make admin link

### LINKED ISSUE #3705: 'Make user admin' link ends up in a 500 error
I'm logged in as the Admin user, click `Configuration > Manage Users > Select a user > "Make user admin"` then I get a 500 error.

From the error logs:
```
I, [2017-08-29T18:48:01.116880 #1911]  INFO -- : [c257e545-e9a0-42e3-a900-15a3f7f89775] [1911:154.14] Started POST "/user/admin?user=manuel" for xxx at 2017-08-29 18:48:01 +0200
I, [2017-08-29T18:48:01.119071 #1911]  INFO -- : [c257e545-e9a0-42e3-a900-15a3f7f89775] [1911:154.14] Processing by Webui::UserController#admin as HTML
I, [2017-08-29T18:48:01.119232 #1911]  INFO -- : [c257e545-e9a0-42e3-a900-15a3f7f89775] [1911:154.14]   Parameters: {"authenticity_token"=>"M3RJ9l8skBwSmcWHbC5jkd7R51a0/pj4CLjclTNtQYG7pyV3bT
AbdGLuYA7vKG1qZ0titAfZJJ2bF+sBgxYzvg==", "user"=>"manuel"}
I, [2017-08-29T18:48:01.135247 #1911]  INFO -- : [c257e545-e9a0-42e3-a900-15a3f7f89775] [1911:154.16] Completed 500 Internal Server Error in 16ms (ActiveRecord: 2.5ms | Backend: 0.0ms | XML:
 0.0ms)
F, [2017-08-29T18:48:01.137127 #1911] FATAL -- : [c257e545-e9a0-42e3-a900-15a3f7f89775] [1911:154.16]   
F, [2017-08-29T18:48:01.137261 #1911] FATAL -- : [c257e545-e9a0-42e3-a900-15a3f7f89775] [1911:154.16] ActiveRecord::AssociationTypeMismatch (Role(#45496940) expected, got "Admin" which is an
 instance of String(#7659300)):
F, [2017-08-29T18:48:01.137340 #1911] FATAL -- : [c257e545-e9a0-42e3-a900-15a3f7f89775] [1911:154.16]   
F, [2017-08-29T18:48:01.137418 #1911] FATAL -- : [c257e545-e9a0-42e3-a900-15a3f7f89775] [1911:154.16] app/models/user.rb:865:in `update_globalroles'
[c257e545-e9a0-42e3-a900-15a3f7f89775] app/controllers/webui/user_controller.rb:125:in `admin'
[c257e545-e9a0-42e3-a900-15a3f7f89775] config/initializers/wrap_parameters.rb:38:in `call`
```

But it's still possible to make a user an admin on the edit page.

### PR DESCRIPTION
**Pull request by mschnitzer**
The `make admin` link did not work anymore. This fixes #3705

### CODE REVIEW

File: src/api/spec/controllers/webui/user_controller_spec.rb [hunk 1]
```diff
@@ -271,8 +271,15 @@
...
-  describe "GET #admin" do
-    skip
+  describe "POST #admin" do
+    before do
+      login admin_user
+      post :admin, params: { user: user.login }
+    end
+
+    it 'applies the Admin role properly' do
+      expect(user.roles.find_by(title: 'Admin')).to_not be_nil
```
Comment (Ana06) [inline src/api/spec/controllers/webui/user_controller_spec.rb]: This is not testing what we want as the `admin_user` also has the admin role, and we want to check if the admin role was assigned to `user`. :disappointed:  You have to test that `user` is included in `user.roles.find_by(title: 'Admin')` :wink:

Comment (mschnitzer) [reply src/api/spec/controllers/webui/user_controller_spec.rb]: user.roles holds all roles a user has. not every role. this is a relation.

Comment (Ana06) [reply src/api/spec/controllers/webui/user_controller_spec.rb]: I read it wrong :wink:
