### PR TITLE
Don't send emails to groups without an email

### LINKED ISSUE #9114: [production][] SMTP To address may not be blank: []
threw this 116 times
<pre>
SMTP To address may not be blank: []
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5e1e477f34c7c50008957a59)

### PR DESCRIPTION
**Pull request by eduardoj**
The corner case of sending a mail to only a group, that hasn't an email defined, was not taken into account.

This patch makes the code not to send an email in this case.

Fixes #9114.

Co-authored-by: David Kang <dkang@suse.com>

### CODE REVIEW

File: src/api/app/mailers/event_mailer.rb [hunk 1]
```diff
@@ -21,6 +21,9 @@ def event(subscribers, e)
     subscribers = subscribers.to_a
     return if subscribers.empty?
 
+    tos = subscribers.map(&:display_name).reject(&:blank?)
```
Comment (vpereira) [inline src/api/app/mailers/event_mailer.rb]: Shouldn't we test this condition on `src/api/spec/mailers/event_mailer_spec.rb`

Comment (dmarcoux) [reply src/api/app/mailers/event_mailer.rb]: What is `tos`?

Comment (danidoni) [reply src/api/app/mailers/event_mailer.rb]: I'm working on specs for this change

Comment (danidoni) [reply src/api/app/mailers/event_mailer.rb]: `tos` is the plural of `to` addresses :stuck_out_tongue:

Comment (dmarcoux) [reply src/api/app/mailers/event_mailer.rb]: Ishhhh, could we have a better name for this?

Comment (danidoni) [reply src/api/app/mailers/event_mailer.rb]: Yeah, I'll change it

**Comment by vpereira** [comment]
@danidoni please squash those commits together

**Comment by danidoni** [comment]
> I had to look at the code changes to understand what this does since the commit message is not very clear. Could we reword the commit message to something like `Don't send emails to groups without an email`?

Sure
