### PR TITLE
Fix user denied deletion of its own subprojects

### LINKED ISSUE #16328: Unabled to delete project in home:user namespace
# Issue Description
I cannot delete a project in my home:user namespace:
https://build.opensuse.org/project/show/home:ddiss:bsc1226031_aa_policy_unpack_tw
I was able to request deletion via https://build.opensuse.org/request/show/1180328 but I'm not able to accept the request via web UI or `osc rq accept 1180328` (`HTTP Error 403: Forbidden`).

The project was created using the kernel-source `./scripts/osc_wrapper upload` helper script, with `ddiss` user credentials. The script can be found at:
https://github.com/openSUSE/kernel-source/blob/stable/scripts/osc_wrapper

Expected Result
============
I should be able to delete the project.

How to Reproduce
===============
1. `git clone https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git`
1. `export LINUX_GIT="$(realpath linux)"`
1. `git clone https://github.com/opensuse/kernel-source`
1. `cd kernel-source && git checkout origin/stable`
1. `./scripts/tar-up.sh`
1. `./scripts/osc_wrapper upload home:<user>:kernel_source_obs_test`
1. attempt to delete the `home:<user>:kernel_source_obs_test` project

`scripts/osc_wrapper` uses open build service credentials from oscrc.

### PR DESCRIPTION
**Pull request by danidoni**
Users can delete its own home project and they can create subprojects without the parent project being present.

In both cases you would end up having a hierarchy of projects that you were left out without having permission to do anything on them.

This PR allows a user full control over its subprojects.

Fixes #16328

### CODE REVIEW

File: src/api/app/models/user.rb [hunk 1]
```diff
@@ -552,9 +552,9 @@ def has_local_permission?(perm_string, object)
     when Project
       logger.debug "running local permission check: user #{login}, project #{object.name}, permission '#{perm_string}'"
 
-      # Users have permissions to manage their own home project
+      # Users have permissions to manage their own home project and it's subprojects
       # This is needed since users sometimes remove themselves from the maintainers of their own home project
-      return true if object.name == home_project_name
+      return true if object.name == "home:#{login}" || object.name.include?("home:#{login}:")
```
Comment (bmwiedemann) [inline src/api/app/models/user.rb:557]: The `include?` also gives access to `home:someoneelse:branches:home:LOGIN:foo` - I think, `start_with?` would be better here.

**Review by bmwiedemann — CHANGES_REQUESTED** [review]

File: src/api/app/models/user.rb (hunk 1 above)
Comment (danidoni) [reply src/api/app/models/user.rb:557]: Ahh good catch! Fixing...

File: src/api/app/models/user.rb [hunk 2]
```diff
@@ -552,9 +552,9 @@ def has_local_permission?(perm_string, object)
     when Project
       logger.debug "running local permission check: user #{login}, project #{object.name}, permission '#{perm_string}'"
 
-      # Users have permissions to manage their own home project
+      # Users have permissions to manage their own home project and it's subprojects
       # This is needed since users sometimes remove themselves from the maintainers of their own home project
-      return true if object.name == home_project_name
+      return true if object.name == "home:#{login}" || object.name.starts_with?("home:#{login}:")
```
Comment (hennevogel) [inline src/api/app/models/user.rb:557]:
```suggestion
      return true if object.name == home_project_name || object.name.starts_with?("#{home_project_name}:")
```

**Review by hennevogel — CHANGES_REQUESTED** [review]

**Review by bmwiedemann — APPROVED** [review]

File: src/api/spec/models/user_spec.rb [hunk 3]
```diff
@@ -623,4 +623,48 @@
       end
     end
   end
+
+  describe '#can_modify?' do
```
Comment (hennevogel) [inline src/api/spec/models/user_spec.rb:627]: There are also some leftovers in `test/unit/user_test.rb` you should retire IMHO

File: src/api/spec/models/user_spec.rb [hunk 4]
```diff
@@ -623,4 +623,48 @@
...
+    context 'when dealing with projects' do
+      context 'when checking against a home project' do
+        it { expect(user.can_modify?(project)).to be true }
+      end
+
+      context 'when checking against a child of a home project' do
+        let(:child_project) { create(:project, name: "#{project.name}:something") }
+
+        before do
+          child_project.relationships.build(user: user,
```
Comment (hennevogel) [inline src/api/spec/models/user_spec.rb:640]: Why do you need to do this? There are not relationships involved in your changes right?

File: src/api/spec/models/user_spec.rb [hunk 5]
```diff
@@ -623,4 +623,48 @@
       end
     end
   end
+
+  describe '#can_modify?' do
+    let(:user) { create(:confirmed_user, :with_home, login: 'hans') }
+    let(:project) { user.home_project }
+
+    context 'when dealing with projects' do
```
Comment (hennevogel) [inline src/api/spec/models/user_spec.rb:631]:
```suggestion
    context 'projects' do
```

File: src/api/spec/models/user_spec.rb [hunk 6]
```diff
@@ -623,4 +623,48 @@
...
+      context 'when checking against a home project' do
```
Comment (hennevogel) [inline src/api/spec/models/user_spec.rb:632]:
```suggestion
      context 'can modify home project' do
```

File: src/api/spec/models/user_spec.rb [hunk 7]
```diff
@@ -623,4 +623,48 @@
...
+        it { expect(user.can_modify?(project)).to be true }
+      end
+
+      context 'when checking against a child of a home project' do
```
Comment (hennevogel) [inline src/api/spec/models/user_spec.rb:636]:
```suggestion
      context 'can modify sub-projects of home project' do
```

File: src/api/spec/models/user_spec.rb [hunk 8]
```diff
@@ -623,4 +623,48 @@
...
+
+        before do
+          child_project.relationships.build(user: user,
+                                            role: Role.find_by_title('maintainer'))
+        end
+
+        it { expect(user.can_modify?(child_project)).to be true }
+      end
+
+      context 'when the project has no parent project' do
```
Comment (hennevogel) [inline src/api/spec/models/user_spec.rb:647]: Not sure why you are testing this?

File: src/api/spec/models/user_spec.rb [hunk 9]
```diff
@@ -623,4 +623,48 @@
...
+        end
+      end
+
+      context 'when checking other users home projects' do
+        let(:other_user) { create(:confirmed_user, :with_home, login: 'hans2') }
+
+        it { expect(user.can_modify?(other_user.home_project)).to be false }
+      end
+
+      context 'when checking branched projects' do
```
Comment (hennevogel) [inline src/api/spec/models/user_spec.rb:663]: Not sure why you are testing this?

**Review by hennevogel — CHANGES_REQUESTED** [review]

File: src/api/spec/models/user_spec.rb (hunk 8 above)
Comment (danidoni) [reply src/api/spec/models/user_spec.rb:647]: Because before this change, `has_local_permission?` tries to go up the project hierarchy to check for permissions and stops when no parent is found, leaving you stranded without permissions.

File: src/api/spec/models/user_spec.rb (hunk 9 above)
Comment (danidoni) [reply src/api/spec/models/user_spec.rb:663]: To ensure permissions don't allow modifying other people's projects

File: src/api/spec/models/user_spec.rb (hunk 8 above)
Comment (hennevogel) [reply src/api/spec/models/user_spec.rb:642]: So? Who cares about before? :)

File: src/api/spec/models/user_spec.rb [hunk 10]
```diff
@@ -623,4 +623,43 @@
...
+        end
+      end
+
+      context "cannot modify other user's home projects" do
+        let(:other_user) { create(:confirmed_user, :with_home, login: 'hans2') }
+
+        it { expect(user.can_modify?(other_user.home_project)).to be false }
+      end
+
+      context "cannot modify other people's projects" do
```
Comment (hennevogel) [inline src/api/spec/models/user_spec.rb:658]: What's the difference to the spec above?

File: src/api/spec/models/user_spec.rb (hunk 8 above)
Comment (danidoni) [reply src/api/spec/models/user_spec.rb:642]: Whoever changes that method and triggers a regression.

File: src/api/spec/models/user_spec.rb (hunk 10 above)
Comment (danidoni) [reply src/api/spec/models/user_spec.rb:658]: None, I'll use this context as it's more generic.

File: src/api/spec/models/user_spec.rb (hunk 8 above)
Comment (hennevogel) [reply src/api/spec/models/user_spec.rb:642]: Whoever changes that method will also change the spec...

Comment (danidoni) [reply src/api/spec/models/user_spec.rb:642]: I'm fine with that, but at least it has to read the use case and think about what's going to happen. Don't you think?

Comment (hennevogel) [reply src/api/spec/models/user_spec.rb:642]: What use case? The use case that isn't considered anymore in the code? Test existing implementation and *not* the previous implementation or the knowledge of potential future committers of a previous implementation.

Comment (danidoni) [reply src/api/spec/models/user_spec.rb:642]: Alright

**Review by hennevogel — APPROVED** [review]
