### PR TITLE
Do not fetch package's meta data when it's an scmsync project

### LINKED ISSUE #17690: [production][meta#show] undefined method 'render_xml' for nil
[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/67ee8ae984bf460a5b16c288)
# undefined method &#39;render_xml&#39; for nil #
### URL ###
[https://build.opensuse.org/projects/devel:languages:javascript/packages/mujs/meta](https://build.opensuse.org/projects/devel:languages:javascript/packages/mujs/meta)"
### Where ###
meta#show

### Occured ###
Apr 03  1:19pm

### Similar ###
38

## Params ##
~~~
{
  &quot;action&quot; =&gt; &quot;show&quot;,
  &quot;controller&quot; =&gt; &quot;webui/packages/meta&quot;,
  &quot;package_name&quot; =&gt; &quot;mujs&quot;,
  &quot;project_name&quot; =&gt; &quot;devel:languages:javascript&quot;
}
~~~

## Session ##
~~~
{}
~~~

## Backtrace ##
~~~
15:  app/controllers/webui/packages/meta_controller.rb -> **&#39;Webui::Packages::MetaController#show&#39;**
6:  /GEM_ROOT/gems/actionpack-7.0.8.7/lib/action_controller/metal/basic_implicit_render.rb -> **&#39;ActionController::BasicImplicitRender#send_action&#39;**
215:  /GEM_ROOT/gems/actionpack-7.0.8.7/lib/abstract_controller/base.rb -> **&#39;AbstractController::Base#process_action&#39;**
165:  /GEM_ROOT/gems/actionpack-7.0.8.7/lib/action_controller/metal/rendering.rb -> **&#39;ActionController::Rendering#process_action&#39;**
234:  /GEM_ROOT/gems/actionpack-7.0.8.7/lib/abstract_controller/callbacks.rb -> **&#39;block in AbstractController::Callbacks#process_action&#39;**
118:  /GEM_ROOT/gems/activesupport-7.0.8.7/lib/active_support/callbacks.rb -> **&#39;block in ActiveSupport::Callbacks#run_callbacks&#39;**
24:  /GEM_ROOT/gems/turbo-rails-2.0.12/lib/turbo-rails.rb -> **&#39;Turbo.with_request_id&#39;**
10:  /GEM_ROOT/gems/turbo-rails-2.0.12/app/controllers/concerns/turbo/request_id_tracking.rb -> **&#39;Turbo::RequestIdTracking#turbo_tracking_request_id&#39;**
127:  /GEM_ROOT/gems/activesupport-7.0.8.7/lib/active_support/callbacks.rb -> **&#39;block in ActiveSupport::Callbacks#run_callbacks&#39;**
138:  /GEM_ROOT/gems/activesupport-7.0.8.7/lib/active_support/callbacks.rb -> **&#39;ActiveSupport::Callbacks#run_callbacks&#39;**
233:  /GEM_ROOT/gems/actionpack-7.0.8.7/lib/abstract_controller/callbacks.rb -> **&#39;AbstractController::Callbacks#process_action&#39;**
23:  /GEM_ROOT/gems/actionpack-7.0.8.7/lib/action_controller/metal/rescue.rb -> **&#39;ActionController::Rescue#process_action&#39;**
67:  /GEM_ROOT/gems/actionpack-7.0.8.7/lib/action_controller/metal/instrumentation.rb -> **&#39;block in ActionController::Instrumentation#process_action&#39;**
206:  /GEM_ROOT/gems/activesupport-7.0.8.7/lib/active_support/notifications.rb -> **&#39;block in ActiveSupport::Notifications.instrument&#39;**
24:  /GEM_ROOT/gems/activesupport-7.0.8.7/lib/active_support/notifications/instrumenter.rb -> **&#39;ActiveSupport::Notifications::Instrumenter#instrument&#39;**
206:  /GEM_ROOT/gems/activesupport-7.0.8.7/lib/active_support/notifications.rb -> **&#39;ActiveSupport::Notifications.instrument&#39;**
66:  /GEM_ROOT/gems/actionpack-7.0.8.7/lib/action_controller/metal/instrumentation.rb -> **&#39;ActionController::Instrumentation#process_action&#39;**
259:  /GEM_ROOT/gems/actionpack-7.0.8.7/lib/action_controller/metal/params_wrapper.rb -> **&#39;ActionController::ParamsWrapper#process_action&#39;**
27:  /GEM_ROOT/gems/activerecord-7.0.8.7/lib/active_record/railties/controller_runtime.rb -> **&#39;ActiveRecord::Railties::ControllerRuntime#process_action&#39;**
151:  /GEM_ROOT/gems/actionpack-7.0.8.7/lib/abstract_controller/base.rb -> **&#39;AbstractController::Base#process&#39;**
39:  /GEM_ROOT/gems/actionview-7.0.8.7/lib/action_view/rendering.rb -> **&#39;ActionView::Rendering#process&#39;**
188:  /GEM_ROOT/gems/actionpack-7.0.8.7/lib/action_controller/metal.rb -> **&#39;ActionController::Metal#dispatch&#39;**
251:  /GEM_ROOT/gems/actionpack-7.0.8.7/lib/action_controller/metal.rb -> **&#39;ActionController::Metal.dispatch&#39;**
49:  /GEM_ROOT/gems/actionpack-7.0.8.7/lib/action_dispatch/routing/route_set.rb -> **&#39;ActionDispatch::Routing::RouteSet::Dispatcher#dispatch&#39;**
32:  /GEM_ROOT/gems/actionpack-7.0.8.7/lib/action_dispatch/routing/route_set.rb -> **&#39;ActionDispatch::Routing::RouteSet::Dispatcher#serve&#39;**
18:  /GEM_ROOT/gems/actionpack-7.0.8.7/lib/action_dispatch/routing/mapper.rb -> **&#39;block in &lt;class:Constraints&gt;&#39;**
48:  /GEM_ROOT/gems/actionpack-7.0.8.7/lib/action_dispatch/routing/mapper.rb -> **&#39;ActionDispatch::Routing::Mapper::Constraints#serve&#39;**
50:  /GEM_ROOT/gems/actionpack-7.0.8.7/lib/action_dispatch/journey/router.rb -> **&#39;block in ActionDispatch::Journey::Router#serve&#39;**
32:  /GEM_ROOT/gems/actionpack-7.0.8.7/lib/action_dispatch/journey/router.rb -> **&#39;Array#each&#39;**
32:  /GEM_ROOT/gems/actionpack-7.0.8.7/lib/action_dispatch/journey/router.rb -> **&#39;ActionDispatch::Journey::Router#serve&#39;**
852:  /GEM_ROOT/gems/actionpack-7.0.8.7/lib/action_dispatch/routing/route_set.rb -> **&#39;ActionDispatch::Routing::RouteSet#call&#39;**
87:  /GEM_ROOT/gems/flipper-1.3.4/lib/flipper/middleware/memoizer.rb -> **&#39;Flipper::Middleware::Memoizer#memoized_call&#39;**
45:  /GEM_ROOT/gems/flipper-1.3.4/lib/flipper/middleware/memoizer.rb -> **&#39;Flipper::Middleware::Memoizer#call&#39;**
15:  config/initializers/prefer_xml_over_html.rb -> **&#39;PreferXmlOverHtml#call&#39;**
44:  /GEM_ROOT/gems/rack-2.2.13/lib/rack/deflater.rb -> **&#39;Rack::Deflater#call&#39;**
15:  /GEM_ROOT/gems/rack-2.2.13/lib/rack/tempfile_reaper.rb -> **&#39;Rack::TempfileReaper#call&#39;**
27:  /GEM_ROOT/gems/rack-2.2.13/lib/rack/etag.rb -> **&#39;Rack::ETag#call&#39;**
27:  /GEM_ROOT/gems/rack-2.2.13/lib/rack/conditional_get.rb -> **&#39;Rack::ConditionalGet#call&#39;**
12:  /GEM_ROOT/gems/rack-2.2.13/lib/rack/head.rb -> **&#39;Rack::Head#call&#39;**
38:  /GEM_ROOT/gems/actionpack-7.0.8.7/lib/action_dispatch/http/permissions_policy.rb -> **&#39;ActionDispatch::PermissionsPolicy::Middleware#call&#39;**
39:  /GEM_ROOT/gems/actionpack-7.0.8.7/lib/action_dispatch/http/content_security_policy.rb -> **&#39;ActionDispatch::ContentSecurityPolicy::Middleware#call&#39;**
266:  /GEM_ROOT/gems/rack-2.2.13/lib/rack/session/abstract/id.rb -> **&#39;Rack::Session::Abstract::Persisted#context&#39;**
260:  /GEM_ROOT/gems/rack-2.2.13/lib/rack/session/abstract/id.rb -> **&#39;Rack::Session::Abstract::Persisted#call&#39;**
704:  /GEM_ROOT/gems/actionpack-7.0.8.7/lib/action_dispatch/middleware/cookies.rb -> **&#39;ActionDispatch::Cookies#call&#39;**
27:  /GEM_ROOT/gems/actionpack-7.0.8.7/lib/action_dispatch/middleware/callbacks.rb -> **&#39;block in ActionDispatch::Callbacks#call&#39;**
99:  /GEM_ROOT/gems/activesupport-7.0.8.7/lib/active_support/callbacks.rb -> **&#39;ActiveSupport::Callbacks#run_callbacks&#39;**
26:  /GEM_ROOT/gems/actionpack-7.0.8.7/lib/action_dispatch/middleware/callbacks.rb -> **&#39;ActionDispatch::Callbacks#call&#39;**
32:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **&#39;Airbrake::Rack::Middleware#call!&#39;**
21:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **&#39;Airbrake::Rack::Middleware#call&#39;**
28:  /GEM_ROOT/gems/actionpack-7.0.8.7/lib/action_dispatch/middleware/debug_exceptions.rb -> **&#39;ActionDispatch::DebugExceptions#call&#39;**
29:  /GEM_ROOT/gems/actionpack-7.0.8.7/lib/action_dispatch/middleware/show_exceptions.rb -> **&#39;ActionDispatch::ShowExceptions#call&#39;**
18:  /GEM_ROOT/gems/lograge-0.14.0/lib/lograge/rails_ext/rack/logger.rb -> **&#39;Rails::Rack::Logger#call_app&#39;**
25:  /GEM_ROOT/gems/railties-7.0.8.7/lib/rails/rack/logger.rb -> **&#39;block in Rails::Rack::Logger#call&#39;**
99:  /GEM_ROOT/gems/activesupport-7.0.8.7/lib/active_support/tagged_logging.rb -> **&#39;block in ActiveSupport::TaggedLogging#tagged&#39;**
37:  /GEM_ROOT/gems/activesupport-7.0.8.7/lib/active_support/tagged_logging.rb -> **&#39;ActiveSupport::TaggedLogging::Formatter#tagged&#39;**
99:  /GEM_ROOT/gems/activesupport-7.0.8.7/lib/active_support/tagged_logging.rb -> **&#39;ActiveSupport::TaggedLogging#tagged&#39;**
25:  /GEM_ROOT/gems/railties-7.0.8.7/lib/rails/rack/logger.rb -> **&#39;Rails::Rack::Logger#call&#39;**
93:  /GEM_ROOT/gems/actionpack-7.0.8.7/lib/action_dispatch/middleware/remote_ip.rb -> **&#39;ActionDispatch::RemoteIp#call&#39;**
93:  /GEM_ROOT/gems/actionpack-7.0.8.7/lib/action_dispatch/middleware/remote_ip.rb -> **&#39;ActionDispatch::RemoteIp#call&#39;**
19:  /GEM_ROOT/gems/request_store-1.7.0/lib/request_store/middleware.rb -> **&#39;RequestStore::Middleware#call&#39;**
26:  /GEM_ROOT/gems/actionpack-7.0.8.7/lib/action_dispatch/middleware/request_id.rb -> **&#39;ActionDispatch::RequestId#call&#39;**
24:  /GEM_ROOT/gems/rack-2.2.13/lib/rack/method_override.rb -> **&#39;Rack::MethodOverride#call&#39;**
22:  /GEM_ROOT/gems/rack-2.2.13/lib/rack/runtime.rb -> **&#39;Rack::Runtime#call&#39;**
29:  /GEM_ROOT/gems/activesupport-7.0.8.7/lib/active_support/cache/strategy/local_cache_middleware.rb -> **&#39;ActiveSupport::Cache::Strategy::LocalCache::Middleware#call&#39;**
14:  /GEM_ROOT/gems/actionpack-7.0.8.7/lib/action_dispatch/middleware/executor.rb -> **&#39;ActionDispatch::Executor#call&#39;**
18:  /GEM_ROOT/gems/rack-2.2.13/lib/rack/lock.rb -> **&#39;Rack::Lock#call&#39;**
110:  /GEM_ROOT/gems/rack-2.2.13/lib/rack/sendfile.rb -> **&#39;Rack::Sendfile#call&#39;**
131:  /GEM_ROOT/gems/actionpack-7.0.8.7/lib/action_dispatch/middleware/host_authorization.rb -> **&#39;ActionDispatch::HostAuthorization#call&#39;**
530:  /GEM_ROOT/gems/railties-7.0.8.7/lib/rails/engine.rb -> **&#39;Rails::Engine#call&#39;**
226:  /GEM_ROOT/gems/railties-7.0.8.7/lib/rails/railtie.rb -> **&#39;Kernel#public_send&#39;**
226:  /GEM_ROOT/gems/railties-7.0.8.7/lib/rails/railtie.rb -> **&#39;Rails::Railtie.method_missing&#39;**
74:  /GEM_ROOT/gems/rack-2.2.13/lib/rack/urlmap.rb -> **&#39;block in Rack::URLMap#call&#39;**
58:  /GEM_ROOT/gems/rack-2.2.13/lib/rack/urlmap.rb -> **&#39;Array#each&#39;**
58:  /GEM_ROOT/gems/rack-2.2.13/lib/rack/urlmap.rb -> **&#39;Rack::URLMap#call&#39;**
107:  /usr/lib64/ruby/gems/3.4.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb -> **&#39;PhusionPassenger::Rack::ThreadHandlerExtension#process_request&#39;**
149:  /usr/lib64/ruby/gems/3.4.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **&#39;PhusionPassenger::RequestHandler::ThreadHandler#accept_and_process_next_request&#39;**
110:  /usr/lib64/ruby/gems/3.4.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **&#39;PhusionPassenger::RequestHandler::ThreadHandler#main_loop&#39;**
419:  /usr/lib64/ruby/gems/3.4.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/request_handler.rb -> **&#39;block (3 levels) in PhusionPassenger::RequestHandler#start_threads&#39;**
113:  /usr/lib64/ruby/gems/3.4.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/utils.rb -> **&#39;block in PhusionPassenger::Utils#create_thread_and_abort_on_exception&#39;**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| program_name | Passenger RubyApp: /srv/www/obs/api (production) |
| HTTP_USER_AGENT | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 |

### PR DESCRIPTION
**Pull request by danidoni**
The package does not exist locally, so we cannot get the meta data like we usually do

Fixes #17690

### CODE REVIEW

File: src/api/spec/controllers/webui/packages/meta_controller_spec.rb [hunk 1]
```diff
@@ -6,12 +6,29 @@
...
-      expect(assigns(:meta)).to eq(source_package.render_xml)
+    context 'when its a project managed via scmsync' do
+      before do
+        source_project.update(scmsync: 'https://src.opensuse.org/lua/_ObsPrj.git#master')
+        get :show, params: { project_name: source_project, package_name: 'some_package' }
+      end
+
+      it { expect(response).to have_http_status(:ok) }
+
+      it 'sends the xml representation of a package' do
```
Comment (krauselukas) [inline src/api/spec/controllers/webui/packages/meta_controller_spec.rb:29]:
```suggestion
      it 'does not send the xml representation of a package' do
```

File: src/api/app/controllers/webui/packages/meta_controller.rb [hunk 2]
```diff
@@ -12,6 +12,8 @@ class MetaController < Webui::WebuiController
       after_action :verify_authorized, only: :update
 
       def show
+        return if @project.scmsync.present?
```
Comment (hennevogel) [inline src/api/app/controllers/webui/packages/meta_controller.rb:15]: Return isn't how you handle a on existing object in a route right?

**Review by hennevogel — CHANGES_REQUESTED** [review]

File: src/api/app/controllers/webui/packages/meta_controller.rb (hunk 2 above)
Comment (danidoni) [reply src/api/app/controllers/webui/packages/meta_controller.rb]: Right, please take a look again.

File: src/api/app/controllers/webui/packages/meta_controller.rb [hunk 3]
```diff
@@ -12,9 +12,12 @@ class MetaController < Webui::WebuiController
       after_action :verify_authorized, only: :update
 
       def show
-        return if @project.scmsync.present?
-
-        @meta = @package.render_xml
+        if @project.scmsync.present?
+          flash.now[:error] = "Error while retrieving the Meta file: package not found."
```
Comment (hennevogel) [inline src/api/app/controllers/webui/packages/meta_controller.rb:16]: This will be *very* confusing for people as other parts of the UI work with scmsync packages.

Comment (hennevogel) [reply src/api/app/controllers/webui/packages/meta_controller.rb:16]: https://github.com/openSUSE/open-build-service/blob/545e6c90210708322055c9aa197823cac2c8d3f3/src/api/app/controllers/webui/package_controller.rb#L39-L44

Comment (danidoni) [reply src/api/app/controllers/webui/packages/meta_controller.rb:16]: Excellent

**Review by hennevogel — APPROVED** [review]
