### PR TITLE
Fix some bugs in the Kiwi editor

### LINKED ISSUE #3829: Kiwi image editor: Adding the same repository is possible
Issue/Feature description
====================
Adding the same repository several times is possible. There should be a validation that it is only possible to add the same repository once to the image.

When starting a build, kiwi will fail with
```
Specified repo alias 'openSUSE_Leap_42\.2\@home\:cbruckmayer\:oSC17' not unique across active repositoriesSep-14 10:06:23 <3> : KIWI exited with error(s)
```

Expected result
============
You get an error message that this repository already exists.

How to Reproduce
===============
1. Go to a image
2. Add a repository (e.g. obs://home:cbruckmayer:oSC17/standard)
3. Add the same repository from step 2 again
4. Check the resulted kiwi file

### LINKED ISSUE #3830: Kiwi image editor: Repository wizards uses wrong type
Issue/Feature description
====================
Adding repositories with the repository wizard ("Basic Mode") will add repositories with type ``apt-deb``. It should be ``rpm-md`` otherwise kiwi will fail building.

Expected result
============
Adding repositories with wizard will use the correct type (``rpm-md``). Also the expert mode should default to ``rpm-md`` (I'm unsure if it is even possible to use any other type except ``rpm-md``.

### PR DESCRIPTION
**Pull request by mdeniz**
It fixes #3830 and fixes #3829 
Also other bug not reported that caused a 500 when importing a non xml file content in a *.kiwi file

### CODE REVIEW

File: src/api/app/models/kiwi/repository.rb [hunk 1]
```diff
@@ -44,7 +45,8 @@ def source_path_format
     return if source_path =~ /^(dir|iso|smb|this):\/\/.+/
     return if source_path =~ /\A#{URI.regexp(['ftp', 'http', 'https', 'plain'])}\z/
     if source_path =~ /^obs:\/\/([^\/]+)\/([^\/]+)$/
-      return if Project.valid_name?(Regexp.last_match(1)) && Project.valid_name?(Regexp.last_match(2))
+      return if Project.valid_name?(Regexp.last_match(1)) && Project.valid_name?(Regexp.last_match(2)) && repo_type == 'rpm-md'
```
Comment (ChrisBr) [inline src/api/app/models/kiwi/repository.rb]: [nitpick] Codeclimate reports complex method, maybe we can split it?

Comment (DavidKang) [reply src/api/app/models/kiwi/repository.rb]: Maybe we can move it into a new method :thinking:

File: src/api/app/models/kiwi/repository.rb [hunk 2]
```diff
@@ -17,6 +17,7 @@ class Kiwi::Repository < ApplicationRecord
   #### Scopes (first the default_scope macro if is used)
 
   #### Validations macros
+  validates :alias, uniqueness: { scope: :image }
```
Comment (ChrisBr) [inline src/api/app/models/kiwi/repository.rb]: [nitpick] Seems like it would not trigger a build failure, however, it might make sense to also check for the uniqueness of the path. Doesn't really make sense to have two different repositories with the same path and would produce also "overhead" as you would query the packages several times etc etc

File: src/api/app/models/kiwi/repository.rb [hunk 3]
```diff
@@ -3,7 +3,7 @@ class Kiwi::Repository < ApplicationRecord
   #### Includes and extends
 
   #### Constants
-  REPO_TYPES = ['apt-deb', 'rpm-dir', 'rpm-md', 'yast2'].freeze
+  REPO_TYPES = ['rpm-md', 'rpm-dir', 'yast2', 'apt-deb'].freeze
```
Comment (ChrisBr) [inline src/api/app/models/kiwi/repository.rb]: Depending on which PR gets merged first, please make sure to not introduce the bug again:
https://github.com/openSUSE/open-build-service/pull/3862

Comment (DavidKang) [reply src/api/app/models/kiwi/repository.rb]: @ChrisBr, I will take care of this, thanks

Comment (mdeniz) [reply src/api/app/models/kiwi/repository.rb]: Don't worry, there tests that rely on "rpm-md" being the default one, and I guess @DavidKang did the same for the "rpm-dir" and "yast2" values...

File: src/api/app/models/kiwi/repository.rb (hunk 2 above)
Comment (mdeniz) [reply src/api/app/models/kiwi/repository.rb]: Ok, I will add it BTW 😄

File: src/api/app/models/kiwi/repository.rb (hunk 3 above)
Comment (ChrisBr) [reply src/api/app/models/kiwi/repository.rb]: Thanks, just wanted to point it out :smile:

File: src/api/app/models/kiwi/repository.rb (hunk 2 above)
Comment (ChrisBr) [reply src/api/app/models/kiwi/repository.rb]: Thank you very much!

**Comment by mdeniz** [comment]
@ChrisBr please re-review it 👍

**Comment by ChrisBr** [comment]
Merging as the codecov/patch decrease is a known issue and Hakiri seems to be broken right now for all PRs, I checked on the website that there are no issues.
