### PR TITLE
Check info for both array and hash objects

### LINKED ISSUE #18415: [production][request#chart_build_results] no implicit conversion of String into Integer
[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/68ad706184bf460c8f7f0bfa)
# no implicit conversion of String into Integer #
### URL ###
[https://build.opensuse.org/request/1301354/chart_build_results](https://build.opensuse.org/request/1301354/chart_build_results)"
### Where ###
request#chart_build_results

### Occured ###
Aug 26  8:29am

### Similar ###
9

## Params ##
~~~
{
  &quot;action&quot; =&gt; &quot;chart_build_results&quot;,
  &quot;controller&quot; =&gt; &quot;webui/request&quot;,
  &quot;number&quot; =&gt; &quot;1301354&quot;
}
~~~

## Session ##
~~~
{}
~~~

## Backtrace ##
~~~
37:  app/models/local_build_result/for_package.rb -> **&#39;Hash#dig&#39;**
37:  app/models/local_build_result/for_package.rb -> **&#39;LocalBuildResult::ForPackage#local_build_result&#39;**
29:  app/models/local_build_result/for_package.rb -> **&#39;block (2 levels) in LocalBuildResult::ForPackage#buildresults&#39;**
23:  app/models/local_build_result/for_package.rb -> **&#39;Array#each&#39;**
23:  app/models/local_build_result/for_package.rb -> **&#39;block in LocalBuildResult::ForPackage#buildresults&#39;**
22:  app/models/local_build_result/for_package.rb -> **&#39;Array#each&#39;**
22:  app/models/local_build_result/for_package.rb -> **&#39;LocalBuildResult::ForPackage#buildresults&#39;**
11:  app/models/local_build_result/for_package.rb -> **&#39;LocalBuildResult::ForPackage#initialize&#39;**
929:  app/models/package.rb -> **&#39;Class#new&#39;**
929:  app/models/package.rb -> **&#39;Package#buildresult&#39;**
41:  app/services/action_build_results_service/chart_data_extractor.rb -> **&#39;ActionBuildResultsService::ChartDataExtractor#package_build_results&#39;**
16:  app/services/action_build_results_service/chart_data_extractor.rb -> **&#39;block in ActionBuildResultsService::ChartDataExtractor#call&#39;**
98:  /GEM_ROOT/gems/activerecord-7.2.2.2/lib/active_record/relation/delegation.rb -> **&#39;Array#each&#39;**
98:  /GEM_ROOT/gems/activerecord-7.2.2.2/lib/active_record/relation/delegation.rb -> **&#39;ActiveRecord::Delegation#each&#39;**
12:  app/services/action_build_results_service/chart_data_extractor.rb -> **&#39;Enumerable#filter_map&#39;**
12:  app/services/action_build_results_service/chart_data_extractor.rb -> **&#39;ActionBuildResultsService::ChartDataExtractor#call&#39;**
539:  app/controllers/webui/request_controller.rb -> **&#39;Webui::RequestController#build_results_data&#39;**
361:  app/controllers/webui/request_controller.rb -> **&#39;Webui::RequestController#chart_build_results&#39;**
8:  /GEM_ROOT/gems/actionpack-7.2.2.2/lib/action_controller/metal/basic_implicit_render.rb -> **&#39;ActionController::BasicImplicitRender#send_action&#39;**
226:  /GEM_ROOT/gems/actionpack-7.2.2.2/lib/abstract_controller/base.rb -> **&#39;AbstractController::Base#process_action&#39;**
193:  /GEM_ROOT/gems/actionpack-7.2.2.2/lib/action_controller/metal/rendering.rb -> **&#39;ActionController::Rendering#process_action&#39;**
261:  /GEM_ROOT/gems/actionpack-7.2.2.2/lib/abstract_controller/callbacks.rb -> **&#39;block in AbstractController::Callbacks#process_action&#39;**
121:  /GEM_ROOT/gems/activesupport-7.2.2.2/lib/active_support/callbacks.rb -> **&#39;block in ActiveSupport::Callbacks#run_callbacks&#39;**
24:  /GEM_ROOT/gems/turbo-rails-2.0.16/lib/turbo-rails.rb -> **&#39;Turbo.with_request_id&#39;**
10:  /GEM_ROOT/gems/turbo-rails-2.0.16/app/controllers/concerns/turbo/request_id_tracking.rb -> **&#39;Turbo::RequestIdTracking#turbo_tracking_request_id&#39;**
130:  /GEM_ROOT/gems/activesupport-7.2.2.2/lib/active_support/callbacks.rb -> **&#39;block in ActiveSupport::Callbacks#run_callbacks&#39;**
141:  /GEM_ROOT/gems/activesupport-7.2.2.2/lib/active_support/callbacks.rb -> **&#39;ActiveSupport::Callbacks#run_callbacks&#39;**
260:  /GEM_ROOT/gems/actionpack-7.2.2.2/lib/abstract_controller/callbacks.rb -> **&#39;AbstractController::Callbacks#process_action&#39;**
27:  /GEM_ROOT/gems/actionpack-7.2.2.2/lib/action_controller/metal/rescue.rb -> **&#39;ActionController::Rescue#process_action&#39;**
77:  /GEM_ROOT/gems/actionpack-7.2.2.2/lib/action_controller/metal/instrumentation.rb -> **&#39;block in ActionController::Instrumentation#process_action&#39;**
210:  /GEM_ROOT/gems/activesupport-7.2.2.2/lib/active_support/notifications.rb -> **&#39;block in ActiveSupport::Notifications.instrument&#39;**
58:  /GEM_ROOT/gems/activesupport-7.2.2.2/lib/active_support/notifications/instrumenter.rb -> **&#39;ActiveSupport::Notifications::Instrumenter#instrument&#39;**
210:  /GEM_ROOT/gems/activesupport-7.2.2.2/lib/active_support/notifications.rb -> **&#39;ActiveSupport::Notifications.instrument&#39;**
76:  /GEM_ROOT/gems/actionpack-7.2.2.2/lib/action_controller/metal/instrumentation.rb -> **&#39;ActionController::Instrumentation#process_action&#39;**
259:  /GEM_ROOT/gems/actionpack-7.2.2.2/lib/action_controller/metal/params_wrapper.rb -> **&#39;ActionController::ParamsWrapper#process_action&#39;**
39:  /GEM_ROOT/gems/activerecord-7.2.2.2/lib/active_record/railties/controller_runtime.rb -> **&#39;ActiveRecord::Railties::ControllerRuntime#process_action&#39;**
163:  /GEM_ROOT/gems/actionpack-7.2.2.2/lib/abstract_controller/base.rb -> **&#39;AbstractController::Base#process&#39;**
40:  /GEM_ROOT/gems/actionview-7.2.2.2/lib/action_view/rendering.rb -> **&#39;ActionView::Rendering#process&#39;**
252:  /GEM_ROOT/gems/actionpack-7.2.2.2/lib/action_controller/metal.rb -> **&#39;ActionController::Metal#dispatch&#39;**
335:  /GEM_ROOT/gems/actionpack-7.2.2.2/lib/action_controller/metal.rb -> **&#39;ActionController::Metal.dispatch&#39;**
67:  /GEM_ROOT/gems/actionpack-7.2.2.2/lib/action_dispatch/routing/route_set.rb -> **&#39;ActionDispatch::Routing::RouteSet::Dispatcher#dispatch&#39;**
50:  /GEM_ROOT/gems/actionpack-7.2.2.2/lib/action_dispatch/routing/route_set.rb -> **&#39;ActionDispatch::Routing::RouteSet::Dispatcher#serve&#39;**
32:  /GEM_ROOT/gems/actionpack-7.2.2.2/lib/action_dispatch/routing/mapper.rb -> **&#39;block in &lt;class:Constraints&gt;&#39;**
62:  /GEM_ROOT/gems/actionpack-7.2.2.2/lib/action_dispatch/routing/mapper.rb -> **&#39;ActionDispatch::Routing::Mapper::Constraints#serve&#39;**
53:  /GEM_ROOT/gems/actionpack-7.2.2.2/lib/action_dispatch/journey/router.rb -> **&#39;block in ActionDispatch::Journey::Router#serve&#39;**
133:  /GEM_ROOT/gems/actionpack-7.2.2.2/lib/action_dispatch/journey/router.rb -> **&#39;block in ActionDispatch::Journey::Router#find_routes&#39;**
126:  /GEM_ROOT/gems/actionpack-7.2.2.2/lib/action_dispatch/journey/router.rb -> **&#39;Array#each&#39;**
126:  /GEM_ROOT/gems/actionpack-7.2.2.2/lib/action_dispatch/journey/router.rb -> **&#39;ActionDispatch::Journey::Router#find_routes&#39;**
34:  /GEM_ROOT/gems/actionpack-7.2.2.2/lib/action_dispatch/journey/router.rb -> **&#39;ActionDispatch::Journey::Router#serve&#39;**
896:  /GEM_ROOT/gems/actionpack-7.2.2.2/lib/action_dispatch/routing/route_set.rb -> **&#39;ActionDispatch::Routing::RouteSet#call&#39;**
87:  /GEM_ROOT/gems/flipper-1.3.6/lib/flipper/middleware/memoizer.rb -> **&#39;Flipper::Middleware::Memoizer#memoized_call&#39;**
45:  /GEM_ROOT/gems/flipper-1.3.6/lib/flipper/middleware/memoizer.rb -> **&#39;Flipper::Middleware::Memoizer#call&#39;**
15:  config/initializers/prefer_xml_over_html.rb -> **&#39;PreferXmlOverHtml#call&#39;**
44:  /GEM_ROOT/gems/rack-2.2.17/lib/rack/deflater.rb -> **&#39;Rack::Deflater#call&#39;**
15:  /GEM_ROOT/gems/rack-2.2.17/lib/rack/tempfile_reaper.rb -> **&#39;Rack::TempfileReaper#call&#39;**
27:  /GEM_ROOT/gems/rack-2.2.17/lib/rack/etag.rb -> **&#39;Rack::ETag#call&#39;**
27:  /GEM_ROOT/gems/rack-2.2.17/lib/rack/conditional_get.rb -> **&#39;Rack::ConditionalGet#call&#39;**
12:  /GEM_ROOT/gems/rack-2.2.17/lib/rack/head.rb -> **&#39;Rack::Head#call&#39;**
38:  /GEM_ROOT/gems/actionpack-7.2.2.2/lib/action_dispatch/http/permissions_policy.rb -> **&#39;ActionDispatch::PermissionsPolicy::Middleware#call&#39;**
38:  /GEM_ROOT/gems/actionpack-7.2.2.2/lib/action_dispatch/http/content_security_policy.rb -> **&#39;ActionDispatch::ContentSecurityPolicy::Middleware#call&#39;**
266:  /GEM_ROOT/gems/rack-2.2.17/lib/rack/session/abstract/id.rb -> **&#39;Rack::Session::Abstract::Persisted#context&#39;**
260:  /GEM_ROOT/gems/rack-2.2.17/lib/rack/session/abstract/id.rb -> **&#39;Rack::Session::Abstract::Persisted#call&#39;**
704:  /GEM_ROOT/gems/actionpack-7.2.2.2/lib/action_dispatch/middleware/cookies.rb -> **&#39;ActionDispatch::Cookies#call&#39;**
31:  /GEM_ROOT/gems/actionpack-7.2.2.2/lib/action_dispatch/middleware/callbacks.rb -> **&#39;block in ActionDispatch::Callbacks#call&#39;**
101:  /GEM_ROOT/gems/activesupport-7.2.2.2/lib/active_support/callbacks.rb -> **&#39;ActiveSupport::Callbacks#run_callbacks&#39;**
30:  /GEM_ROOT/gems/actionpack-7.2.2.2/lib/action_dispatch/middleware/callbacks.rb -> **&#39;ActionDispatch::Callbacks#call&#39;**
32:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **&#39;Airbrake::Rack::Middleware#call!&#39;**
21:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **&#39;Airbrake::Rack::Middleware#call&#39;**
31:  /GEM_ROOT/gems/actionpack-7.2.2.2/lib/action_dispatch/middleware/debug_exceptions.rb -> **&#39;ActionDispatch::DebugExceptions#call&#39;**
32:  /GEM_ROOT/gems/actionpack-7.2.2.2/lib/action_dispatch/middleware/show_exceptions.rb -> **&#39;ActionDispatch::ShowExceptions#call&#39;**
18:  /GEM_ROOT/gems/lograge-0.14.0/lib/lograge/rails_ext/rack/logger.rb -> **&#39;Rails::Rack::Logger#call_app&#39;**
29:  /GEM_ROOT/gems/railties-7.2.2.2/lib/rails/rack/logger.rb -> **&#39;Rails::Rack::Logger#call&#39;**
96:  /GEM_ROOT/gems/actionpack-7.2.2.2/lib/action_dispatch/middleware/remote_ip.rb -> **&#39;ActionDispatch::RemoteIp#call&#39;**
96:  /GEM_ROOT/gems/actionpack-7.2.2.2/lib/action_dispatch/middleware/remote_ip.rb -> **&#39;ActionDispatch::RemoteIp#call&#39;**
19:  /GEM_ROOT/gems/request_store-1.7.0/lib/request_store/middleware.rb -> **&#39;RequestStore::Middleware#call&#39;**
33:  /GEM_ROOT/gems/actionpack-7.2.2.2/lib/action_dispatch/middleware/request_id.rb -> **&#39;ActionDispatch::RequestId#call&#39;**
24:  /GEM_ROOT/gems/rack-2.2.17/lib/rack/method_override.rb -> **&#39;Rack::MethodOverride#call&#39;**
22:  /GEM_ROOT/gems/rack-2.2.17/lib/rack/runtime.rb -> **&#39;Rack::Runtime#call&#39;**
29:  /GEM_ROOT/gems/activesupport-7.2.2.2/lib/active_support/cache/strategy/local_cache_middleware.rb -> **&#39;ActiveSupport::Cache::Strategy::LocalCache::Middleware#call&#39;**
16:  /GEM_ROOT/gems/actionpack-7.2.2.2/lib/action_dispatch/middleware/executor.rb -> **&#39;ActionDispatch::Executor#call&#39;**
18:  /GEM_ROOT/gems/rack-2.2.17/lib/rack/lock.rb -> **&#39;Rack::Lock#call&#39;**
110:  /GEM_ROOT/gems/rack-2.2.17/lib/rack/sendfile.rb -> **&#39;Rack::Sendfile#call&#39;**
535:  /GEM_ROOT/gems/railties-7.2.2.2/lib/rails/engine.rb -> **&#39;Rails::Engine#call&#39;**
226:  /GEM_ROOT/gems/railties-7.2.2.2/lib/rails/railtie.rb -> **&#39;Kernel#public_send&#39;**
226:  /GEM_ROOT/gems/railties-7.2.2.2/lib/rails/railtie.rb -> **&#39;Rails::Railtie.method_missing&#39;**
74:  /GEM_ROOT/gems/rack-2.2.17/lib/rack/urlmap.rb -> **&#39;block in Rack::URLMap#call&#39;**
58:  /GEM_ROOT/gems/rack-2.2.17/lib/rack/urlmap.rb -> **&#39;Array#each&#39;**
58:  /GEM_ROOT/gems/rack-2.2.17/lib/rack/urlmap.rb -> **&#39;Rack::URLMap#call&#39;**
107:  /usr/lib64/ruby/gems/3.4.0/gems/passenger-6.0.27/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb -> **&#39;PhusionPassenger::Rack::ThreadHandlerExtension#process_request&#39;**
149:  /usr/lib64/ruby/gems/3.4.0/gems/passenger-6.0.27/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **&#39;PhusionPassenger::RequestHandler::ThreadHandler#accept_and_process_next_request&#39;**
110:  /usr/lib64/ruby/gems/3.4.0/gems/passenger-6.0.27/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **&#39;PhusionPassenger::RequestHandler::ThreadHandler#main_loop&#39;**
419:  /usr/lib64/ruby/gems/3.4.0/gems/passenger-6.0.27/src/ruby_supportlib/phusion_passenger/request_handler.rb -> **&#39;block (3 levels) in PhusionPassenger::RequestHandler#start_threads&#39;**
111:  /usr/lib64/ruby/gems/3.4.0/gems/passenger-6.0.27/src/ruby_supportlib/phusion_passenger/utils.rb -> **&#39;block in PhusionPassenger::Utils#create_thread_and_abort_on_exception&#39;**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| program_name | /usr/lib64/passenger/6.0.27//helper-scripts/rack-preloader.rb |
| HTTP_USER_AGENT | Mozilla/5.0 (X11; Linux x86_64; rv:141.0) Gecko/20100101 Firefox/141.0 |

### PR DESCRIPTION
**Pull request by rubhanazeem**
fixes #18415

### CODE REVIEW

File: src/api/app/models/local_build_result/for_package.rb [hunk 1]
```diff
@@ -32,9 +32,11 @@ def buildresults
     end
 
     def local_build_result(result, status)
+      result['info'] ||= {}
+      buildtype = [result['info']].flatten.first['buildtype']
```
Comment (hennevogel) [inline src/api/app/models/local_build_result/for_package.rb:36]: Sounds like something you should address in `backend_build_result` instead to me...

**Comment by eduardoj** [comment]
Given that `info` can either be a single hash object or an array of hashes, I would add these cases to [the specs](https://github.com/openSUSE/open-build-service/blob/41092d4be3eda5b80e494f21d4f0d6f58887facb/src/api/spec/models/local_build_result/for_package_spec.rb).

File: src/api/app/models/local_build_result/for_package.rb (hunk 1 above)
Comment (rubhanazeem) [reply src/api/app/models/local_build_result/for_package.rb:36]: `backend_build_result` is only responsible for making a backend request and returning a list of results. This change applies to a single result object. `local_build_result` is responsible for initializing a new object for each result. I think it fits right here.

Comment (hennevogel) [reply src/api/app/models/local_build_result/for_package.rb:36]: So `backend_build_result` is only responsible for the collection but not the items in the collection? If you say so...
