### PR TITLE
Remove unnecesary retrying on creating events

### LINKED ISSUE #16953: [production][] Failed to create Event : "BUILD_FAIL": {"arch"=>"x86_64", "bcnt"=>"1", "buildtype"=>"spec", "endt...
[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/670d2a5584bf460c5bef1380)
# Failed to create Event : &quot;BUILD_FAIL&quot;: {&quot;arch&quot;=&gt;&quot;x86_64&quot;, &quot;bcnt&quot;=&gt;&quot;1&quot;, &quot;buildtype&quot;=&gt;&quot;spec&quot;, &quot;endtime&quot;=&gt;&quot;1728914357&quot;, &quot;package&quot;=&gt;&quot;keepassxc&quot;, &quot;previouslyfailed&quot;=&gt;&quot;1&quot;, &quot;project&quot;=&gt;&quot;security:keepassxc:stable&quot;, &quot;readytime&quot;=&gt;&quot;1728914313&quot;, &quot;reason&quot;=&gt;&quot;source change&quot;, &quot;release&quot;=&gt;&quot;3637.1&quot;, &quot;repository&quot;=&gt;&quot;Fedora_40&quot;, &quot;rev&quot;=&gt;&quot;3637&quot;, &quot;srcmd5&quot;=&gt;&quot;cef1c486be5f3e0c64f3944d153e84d9&quot;, &quot;starttime&quot;=&gt;&quot;1728914317&quot;, &quot;successive_failcount&quot;=&gt;&quot;170&quot;, &quot;verifymd5&quot;=&gt;&quot;d7f413f6e3fa4ad4ee7a328ae9a9f8a1&quot;, &quot;versrel&quot;=&gt;&quot;0-3637&quot;, &quot;workerid&quot;=&gt;&quot;h02-ch1a:26&quot;} Mysql2::Error::ConnectionError: Can&#39;t connect to MySQL server on &#39;src-opensuse.suse.de&#39; (115) #
### Occured ###
Oct 14  1:59pm

### Similar ###
24

## Params ##
~~~
{}
~~~

## Session ##
~~~
{}
~~~

## Backtrace ##
~~~
24:  app/models/update_notification_events.rb -> **rescue in block (2 levels) in create_events**
18:  app/models/update_notification_events.rb -> **block (2 levels) in create_events**
32:  /GEM_ROOT/gems/xmlhash-1.3.9/lib/xmlhash.rb -> **block in elements**
31:  /GEM_ROOT/gems/xmlhash-1.3.9/lib/xmlhash.rb -> **each**
31:  /GEM_ROOT/gems/xmlhash-1.3.9/lib/xmlhash.rb -> **elements**
11:  app/models/update_notification_events.rb -> **block in create_events**
319:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/transaction.rb -> **block in within_new_transaction**
25:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **handle_interrupt**
25:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **block in synchronize**
21:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **handle_interrupt**
21:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **synchronize**
317:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/transaction.rb -> **within_new_transaction**
316:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/database_statements.rb -> **transaction**
209:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/transactions.rb -> **transaction**
9:  app/models/update_notification_events.rb -> **create_events**
67:  app/models/update_notification_events.rb -> **block (2 levels) in perform**
50:  app/models/update_notification_events.rb -> **synchronize**
50:  app/models/update_notification_events.rb -> **block in perform**
49:  app/models/update_notification_events.rb -> **loop**
49:  app/models/update_notification_events.rb -> **perform**
21:  config/clock.rb -> **block (2 levels) in &lt;module:Clockwork&gt;**
215:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/connection_pool.rb -> **with_connection**
19:  config/clock.rb -> **block in &lt;module:Clockwork&gt;**
61:  /GEM_ROOT/gems/clockwork-3.0.2/lib/clockwork/event.rb -> **execute**
41:  /GEM_ROOT/gems/clockwork-3.0.2/lib/clockwork/event.rb -> **block in run**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| program_name | clockworkd.clock |
| HTTP_USER_AGENT |  |

### PR DESCRIPTION
**Pull request by eduardoj**
Also unifies the way database errors are reported. Fixes #16953.

This PR is the first of a group of pull requests:
1. **Remove unnecesary retrying on creating events**
1. #16956
1. #16957

### CODE REVIEW

**Comment by eduardoj** [comment]
After three months of tracking if a retry was triggered, no retries were performed. The retrying code can be safely removed.

File: src/api/app/models/update_notification_events.rb [hunk 1]
```diff
@@ -14,20 +14,8 @@ def create_events
...
-          retries -= 1
-          if retries.positive?
-            Airbrake.notify("Failed to create Event : #{type.inspect}: #{data} #{e}")
-            retry
-          end
-          Airbrake.notify("Failed to create Event : #{type.inspect}: #{data} #{e}")
-        rescue StandardError => e
-          Airbrake.notify("Failed to create Event : #{type.inspect}: #{data} #{e}")
-        end
+        event = Event::Factory.new_from_type(type, data)
```
Comment (hennevogel) [inline src/api/app/models/update_notification_events.rb:17]: How would you know *which* `Airbrake.notify` you look at?

Comment (eduardoj) [reply src/api/app/models/update_notification_events.rb:17]: > How would you know _which_ `Airbrake.notify` you look at in errbit?

In errbit we could have received three different messages, starting with:
- 1: "Failed to create Event :"
- 2: "Failed to update PackageIssue :"
- 3: "Failed while running PackageUpdateIfDirtyJob:"

We only have received messages for this one: 2: "Failed to update PackageIssue :".

Now we are confident we potentially won't receive any "Failed to create Event :" messages, we don't need to identify _which_ `Airbrake.notify` we need to send. That's why we remove this unnecessary code to distinguish between `Aribrake.notify` options.

Comment (hennevogel) [reply src/api/app/models/update_notification_events.rb:17]: Well that only means there was never *any* problem that required retrying right?

Comment (hennevogel) [reply src/api/app/models/update_notification_events.rb:17]: There are cases of this still in errbit...

https://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/670d2a5584bf460c5bef1380
https://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/65f2e3fa84bf4608f8817fd6

Comment (eduardoj) [reply src/api/app/models/update_notification_events.rb:17]: > Well that only means there was never _any_ problem that required retrying right?

Exactly. That's why don't need retrying.

Comment (eduardoj) [reply src/api/app/models/update_notification_events.rb:17]: > There are cases of this still in errbit...
> 
> https://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/670d2a5584bf460c5bef1380 https://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/65f2e3fa84bf4608f8817fd6

Both cases happened due to general failures with the database, affecting the whole application. Nothing that retrying in this part of the code code make a difference.

Comment (hennevogel) [reply src/api/app/models/update_notification_events.rb:17]: That may be but how do you know this never saved us? You can't because every exception looks the same...

Comment (eduardoj) [reply src/api/app/models/update_notification_events.rb:17]: This could have saved us in the past: we had another version/set-up of the database and the codebase was different.

Now, just describing with other words the same written in the commit body, we don't need this code to handle in a different way potential failures happening accessing the database.

Fortunately, we have the backtrace for every exception saved in Errbit. Even if they look the same, we can always know were the exceptions have been triggered.
