### PR TITLE
Remove EventSubscription for token and package if repository doesnt

### LINKED ISSUE #11818: [production][] "" is invalid as a repository identifier. Use the user/repo (String) format, or the repository ID...
[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/60bff83684bf4607a946599e)
# &quot;&quot; is invalid as a repository identifier. Use the user/repo (String) format, or the repository ID (Integer), or a hash containing :repo and :user keys. #
### Occured ###
Jun 08 11:07pm

### Similar ###
9

## Params ##
~~~
{
  &quot;failed_job&quot; =&gt; &quot;f8f8a097-a3a4-4dad-9ec5-c03dbaf776b8&quot;
}
~~~

## Session ##
~~~
{}
~~~

## Backtrace ##
~~~
92:  /GEM_ROOT/gems/octokit-4.21.0/lib/octokit/repository.rb -> **raise_invalid_repository!**
34:  /GEM_ROOT/gems/octokit-4.21.0/lib/octokit/repository.rb -> **initialize**
58:  /GEM_ROOT/gems/octokit-4.21.0/lib/octokit/repository.rb -> **new**
58:  /GEM_ROOT/gems/octokit-4.21.0/lib/octokit/repository.rb -> **path**
43:  /GEM_ROOT/gems/octokit-4.21.0/lib/octokit/client/statuses.rb -> **create_status**
15:  app/services/scm_status_reporter.rb -> **call**
22:  app/jobs/report_to_scm_job.rb -> **block in perform**
87:  /GEM_ROOT/gems/activerecord-6.0.3.6/lib/active_record/relation/delegation.rb -> **each**
87:  /GEM_ROOT/gems/activerecord-6.0.3.6/lib/active_record/relation/delegation.rb -> **each**
19:  app/jobs/report_to_scm_job.rb -> **perform**
40:  /GEM_ROOT/gems/activejob-6.0.3.6/lib/active_job/execution.rb -> **block in perform_now**
112:  /GEM_ROOT/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb -> **block in run_callbacks**
314:  /GEM_ROOT/gems/i18n-1.8.10/lib/i18n.rb -> **with_locale**
9:  /GEM_ROOT/gems/activejob-6.0.3.6/lib/active_job/translation.rb -> **block (2 levels) in &lt;module:Translation&gt;**
121:  /GEM_ROOT/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb -> **instance_exec**
121:  /GEM_ROOT/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb -> **block in run_callbacks**
66:  /GEM_ROOT/gems/activesupport-6.0.3.6/lib/active_support/core_ext/time/zones.rb -> **use_zone**
9:  /GEM_ROOT/gems/activejob-6.0.3.6/lib/active_job/timezones.rb -> **block (2 levels) in &lt;module:Timezones&gt;**
121:  /GEM_ROOT/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb -> **instance_exec**
121:  /GEM_ROOT/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb -> **block in run_callbacks**
25:  /GEM_ROOT/gems/activejob-6.0.3.6/lib/active_job/logging.rb -> **block (4 levels) in &lt;module:Logging&gt;**
180:  /GEM_ROOT/gems/activesupport-6.0.3.6/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-6.0.3.6/lib/active_support/notifications/instrumenter.rb -> **instrument**
180:  /GEM_ROOT/gems/activesupport-6.0.3.6/lib/active_support/notifications.rb -> **instrument**
24:  /GEM_ROOT/gems/activejob-6.0.3.6/lib/active_job/logging.rb -> **block (3 levels) in &lt;module:Logging&gt;**
45:  /GEM_ROOT/gems/activejob-6.0.3.6/lib/active_job/logging.rb -> **block in tag_logger**
80:  /GEM_ROOT/gems/activesupport-6.0.3.6/lib/active_support/tagged_logging.rb -> **block in tagged**
28:  /GEM_ROOT/gems/activesupport-6.0.3.6/lib/active_support/tagged_logging.rb -> **tagged**
80:  /GEM_ROOT/gems/activesupport-6.0.3.6/lib/active_support/tagged_logging.rb -> **tagged**
45:  /GEM_ROOT/gems/activejob-6.0.3.6/lib/active_job/logging.rb -> **tag_logger**
21:  /GEM_ROOT/gems/activejob-6.0.3.6/lib/active_job/logging.rb -> **block (2 levels) in &lt;module:Logging&gt;**
121:  /GEM_ROOT/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb -> **instance_exec**
121:  /GEM_ROOT/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb -> **block in run_callbacks**
139:  /GEM_ROOT/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb -> **run_callbacks**
39:  /GEM_ROOT/gems/activejob-6.0.3.6/lib/active_job/execution.rb -> **perform_now**
25:  /GEM_ROOT/gems/activejob-6.0.3.6/lib/active_job/execution.rb -> **block in execute**
112:  /GEM_ROOT/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb -> **block in run_callbacks**
43:  /GEM_ROOT/gems/activejob-6.0.3.6/lib/active_job/railtie.rb -> **block (4 levels) in &lt;class:Railtie&gt;**
88:  /GEM_ROOT/gems/activesupport-6.0.3.6/lib/active_support/execution_wrapper.rb -> **wrap**
72:  /GEM_ROOT/gems/activesupport-6.0.3.6/lib/active_support/reloader.rb -> **block in wrap**
88:  /GEM_ROOT/gems/activesupport-6.0.3.6/lib/active_support/execution_wrapper.rb -> **wrap**
71:  /GEM_ROOT/gems/activesupport-6.0.3.6/lib/active_support/reloader.rb -> **wrap**
42:  /GEM_ROOT/gems/activejob-6.0.3.6/lib/active_job/railtie.rb -> **block (3 levels) in &lt;class:Railtie&gt;**
121:  /GEM_ROOT/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb -> **instance_exec**
121:  /GEM_ROOT/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb -> **block in run_callbacks**
139:  /GEM_ROOT/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb -> **run_callbacks**
23:  /GEM_ROOT/gems/activejob-6.0.3.6/lib/active_job/execution.rb -> **execute**
42:  /GEM_ROOT/gems/activejob-6.0.3.6/lib/active_job/queue_adapters/delayed_job_adapter.rb -> **perform**
81:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/backend/base.rb -> **block in invoke_job**
10:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/delayed_job.rb -> **block (2 levels) in &lt;class:Airbrake&gt;**
79:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb -> **block (2 levels) in add**
61:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb -> **block in initialize**
79:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb -> **block in add**
66:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb -> **execute**
40:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb -> **run_callbacks**
78:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/backend/base.rb -> **invoke_job**
230:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/worker.rb -> **block (2 levels) in run**
93:  /usr/lib64/ruby/2.5.0/timeout.rb -> **block in timeout**
103:  /usr/lib64/ruby/2.5.0/timeout.rb -> **timeout**
230:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/worker.rb -> **block in run**
308:  /usr/lib64/ruby/2.5.0/benchmark.rb -> **realtime**
229:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/worker.rb -> **run**
312:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/worker.rb -> **block in reserve_and_run_one_job**
61:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb -> **block in initialize**
66:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb -> **execute**
40:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb -> **run_callbacks**
312:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/worker.rb -> **reserve_and_run_one_job**
213:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/worker.rb -> **block in work_off**
212:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/worker.rb -> **times**
212:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/worker.rb -> **work_off**
175:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/worker.rb -> **block (4 levels) in start**
308:  /usr/lib64/ruby/2.5.0/benchmark.rb -> **realtime**
174:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/worker.rb -> **block (3 levels) in start**
61:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb -> **block in initialize**
66:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb -> **execute**
40:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb -> **run_callbacks**
173:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/worker.rb -> **block (2 levels) in start**
172:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/worker.rb -> **loop**
172:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/worker.rb -> **block in start**
7:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/plugins/clear_locks.rb -> **block (2 levels) in &lt;class:ClearLocks&gt;**
79:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb -> **block (2 levels) in add**
61:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb -> **block in initialize**
79:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb -> **block in add**
66:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb -> **execute**
40:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb -> **run_callbacks**
171:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/worker.rb -> **start**
137:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/command.rb -> **run**
125:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/command.rb -> **block in run_process**
277:  /GEM_ROOT/gems/daemons-1.4.0/lib/daemons/application.rb -> **block in start_proc**
84:  /GEM_ROOT/gems/daemons-1.4.0/lib/daemons/daemonize.rb -> **call_as_daemon**
281:  /GEM_ROOT/gems/daemons-1.4.0/lib/daemons/application.rb -> **start_proc**
307:  /GEM_ROOT/gems/daemons-1.4.0/lib/daemons/application.rb -> **start**
56:  /GEM_ROOT/gems/daemons-1.4.0/lib/daemons/controller.rb -> **run**
199:  /GEM_ROOT/gems/daemons-1.4.0/lib/daemons.rb -> **block in run_proc**
124:  /GEM_ROOT/gems/daemons-1.4.0/lib/daemons/cmdline.rb -> **catch_exceptions**
198:  /GEM_ROOT/gems/daemons-1.4.0/lib/daemons.rb -> **run_proc**
123:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/command.rb -> **run_process**
98:  /GEM_ROOT/gems/delayed_job-4.1.9/lib/delayed/command.rb -> **daemonize**
5:  script/delayed_job.api.rb -> **&lt;top (required)&gt;**
74:  /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb -> **load**
74:  /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb -> **kernel_load**
28:  /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb -> **run**
463:  /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli.rb -> **exec**
27:  /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/command.rb -> **run**
126:  /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/invocation.rb -> **invoke_command**
387:  /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor.rb -> **dispatch**
27:  /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli.rb -> **dispatch**
466:  /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/base.rb -> **start**
18:  /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli.rb -> **start**
30:  /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.17.1/exe/bundle -> **block in &lt;top (required)&gt;**
124:  /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/friendly_errors.rb -> **with_friendly_errors**
22:  /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.17.1/exe/bundle -> **&lt;top (required)&gt;**
23:  /usr/bin/bundle.ruby2.5 -> **load**
23:  /usr/bin/bundle.ruby2.5 -> **&lt;main&gt;**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| program_name | delayed_job.1070 |
| HTTP_USER_AGENT |  |

### PR DESCRIPTION
**Pull request by vpereira**
Fixes #11818

If the repository doesn't exist, we destroy the `EventSubscription` associated with that. If the repository is accessible again, after the first push, a new `EventSubscription` will be created.

### CODE REVIEW

File: src/api/app/services/scm_status_reporter.rb [hunk 1]
```diff
@@ -24,7 +24,12 @@ def call
                                          @state,
                                          status_options)
     end
-  rescue Octokit::Error, Octokit::InvalidRepository, Gitlab::Error::Error => e
+  rescue Octokit::InvalidRepository
+    package = Package.find_by(name: @event_payload[:package])
```
Comment (dmarcoux) [inline src/api/app/services/scm_status_reporter.rb:28]: This needs to be scoped on the project as well:

```suggestion
    package = Package.find_by_project_and_name(@event_payload[:project], @event_payload[:package])
```

**Comment by vpereira** [comment]
[Catch error for invalid GitHub repositories in Workflows::YAMLDownloader](https://trello.com/c/Oc1PJo0j/1797-catch-error-for-invalid-github-repositories-in-workflowsyamldownloader)

File: src/api/app/services/scm_status_reporter.rb [hunk 2]
```diff
@@ -24,7 +24,15 @@ def call
                                          @state,
                                          status_options)
     end
-  rescue Octokit::Error, Octokit::InvalidRepository, Gitlab::Error::Error => e
+  rescue Octokit::InvalidRepository
+    package = Package.find_by_project_and_name(@event_payload[:project], @event_payload[:package])
+    return if package.blank?
+
+    token = Token::Workflow.find_by(scm_token: @scm_token)
```
Comment (dmarcoux) [inline src/api/app/services/scm_status_reporter.rb:31]: A user can create multiple tokens with the same *scm_token*. We need to handle this. I haven't tested the following code, but something like that should be fine:

```ruby
    tokens = Token::Workflow.where(scm_token: @scm_token).pluck(:id)
    return if tokens.none?

    EventSubscription.where(channel: 'scm', token: tokens, package: package).delete_all
```

Comment (vpereira) [reply src/api/app/services/scm_status_reporter.rb]: nice!

File: src/api/spec/services/scm_status_reporter_spec.rb [hunk 3]
```diff
@@ -36,5 +36,36 @@
 
       it { expect(subject.state).to eq('failed') }
     end
+
+    context "repository doesn't exist" do
```
Comment (dmarcoux) [inline src/api/spec/services/scm_status_reporter_spec.rb:40]: This context should be under `describe '#call'`, not under `describe '.new'`.

**Review by krauselukas — COMMENTED** [review]
Besides the last comment of @dmarcoux it looks pretty good to me

**Review by krauselukas — APPROVED** [review]

**Review by dmarcoux — APPROVED** [review]

File: src/api/spec/services/scm_status_reporter_spec.rb [hunk 4]
```diff
@@ -37,4 +37,37 @@
...
+      let!(:event_subscription) do
+        EventSubscription.create(channel: 'scm', package: package, eventtype: event_type, receiver_role: 'reader', token: workflow_token)
+      end
+
+      let(:octokit_client) { Octokit::Client.new }
+
+      subject { scm_status_reporter.call }
+
+      before do
+        allow(Octokit::Client).to receive(:new).and_return(octokit_client)
```
Comment (eduardoj) [inline src/api/spec/services/scm_status_reporter_spec.rb:66]:
```suggestion
```
This `allow` sentence is not needed. `octokit_client` is already defined with a `let` in line 61.

Comment (dmarcoux) [reply src/api/spec/services/scm_status_reporter_spec.rb:66]: Without this, we couldn't mock `Octokit::Client` to raise `Octokit::InvalidRepository` when `create_status` is called. This happens on the next line.

Comment (eduardoj) [reply src/api/spec/services/scm_status_reporter_spec.rb:66]: Funny thing is that the test passes anyways.

Comment (vpereira) [reply src/api/spec/services/scm_status_reporter_spec.rb:66]: Exactly @dmarcoux. Eduardo as I wrote you privately, the test passes because the repository is wrong anyway. But that's not deterministic. Forcing it to a specific state is deterministic and avoid any flaky condition.

File: src/api/spec/services/scm_status_reporter_spec.rb [hunk 5]
```diff
@@ -37,4 +37,37 @@
...
+        allow(octokit_client).to receive(:create_status).and_raise(Octokit::InvalidRepository)
+      end
```
Comment (eduardoj) [inline src/api/spec/services/scm_status_reporter_spec.rb:68]:
```suggestion
      subject { scm_status_reporter.call }
                                                                                                                                                                                            
      before do
        allow(Octokit::Client).to receive(:create_status).and_raise(Octokit::InvalidRepository)
      end
```
I would have found this one a cleaner approach.

Comment (dmarcoux) [reply src/api/spec/services/scm_status_reporter_spec.rb:68]: This suggestion wouldn't work, because `create_status` isn't a class method, it's an instance method.

Mocking `Octokit::Client.new` to return a mocked instance of `Octokit::Client` is needed, otherwise we cannot mock the instance method `create_status`.

Comment (eduardoj) [reply src/api/spec/services/scm_status_reporter_spec.rb:68]: Right, I see it now. But it is unfortunate, that with a wrong setup like the one I suggested the tests still keep passing.

File: src/api/spec/services/scm_status_reporter_spec.rb (hunk 4 above)
Comment (eduardoj) [reply src/api/spec/services/scm_status_reporter_spec.rb:66]: Now I get it. Thanks for the explanations.

Maybe it could help to check for an invalid token, also. I guess if Octokit also raises an `Octokit::InvalidRepository` exception when the token is invalid.
