### PR TITLE
Marking a notification as read: couple of fixes

### LINKED ISSUE #10173: Current pagination page is not preserved after marking a notification as read
# Issue Description
After marking a notification as "Read", the curent pagination is not preserved. Instead, after marking a notification as "Read", the first page of the results is always shown.

Expected Result
============
After marking a notification as "Read", the current pagination page is shown.

How to Reproduce
===============
1. Generate enough notifications to create pagination:
   - SSH into running _frontend_ container;
   - Execute `bundle exec rake ts:start`;
   - Then run `bundle exec rake dev:notifications:data[30]`.
1. Log in to the application;
1. Go to Notifications Page (e.g. click on the bell in the top-right or proceed by the link: http://localhost:3000/my/notifications);
1. Click in the pagination button "2" at the bottom of the page;
1. Mark any notification as read;
1. Observe that the results of the first page of the pagination are shown, instead of the results of the second page.

### LINKED ISSUE #10181: "Show all" disabled after marking a notification as "Read"
# Issue Description
`Show all` is disabled after marking a notification as `Read`.

Expected Result
============
I expect `Show all` to still be enabled after marking a notification as `Read`.

How to Reproduce
===============
1. Go to the notifications page (http://localhost:3000/my/notifications or https://build.opensuse.org/my/notifications)
2. Make sure you have plenty of notifications to have the `Show all` button appear. In development, run `bundle exec rake dev:notifications:data[30]` and login as `Admin` to fulfill this requirement.
3. Click on the `Show all` button
4. Mark a notification as `Read`
5. `Show all` is disabled

Further Information
===============
show-all-lost-after-marking-as-read

### PR DESCRIPTION
**Pull request by eduardoj**
Preserve `page` and `show_all` parameters after marking a notification as read. Fixes #10173 and fixes #10181.

Also related, take the user to the last pagination page, when the only notification of the last page is marked as read. Reported  in [#10173](https://github.com/openSUSE/open-build-service/issues/10173#issuecomment-696027112).

And last, after clicking in a page of several notifications (not the first page), and then clicking on the "Show all" button, show the first page of all the results. It makes no sense to preserve the `page` paramenter in the "Show all"/"Show less" button link.

I will setup a lot of notifications on the review-app instance, to make it easier to do a review.

### CODE REVIEW

File: src/api/app/controllers/webui/users/notifications_controller.rb [hunk 1]
```diff
@@ -79,6 +79,7 @@ def fetch_notifications
                     else
                       NotificationsFinder.new(notifications_for_subscribed_user).for_notifiable_type(params[:type])
                     end
+    params[:page] = notifications.page(params[:page]).total_pages if notifications.page(params[:page]).out_of_range?
     params['show_all'] ? show_all(notifications) : notifications.page(params[:page])
```
Comment (dmarcoux) [inline src/api/app/controllers/webui/users/notifications_controller.rb:83]: Just to be consistent with the changes in `_notifications_list.html.haml`:
```suggestion
    params[:show_all] ? show_all(notifications) : notifications.page(params[:page])
```

**Review by dmarcoux — APPROVED** [review]

File: src/api/app/controllers/webui/users/notifications_controller.rb (hunk 1 above)
Comment (eduardoj) [reply src/api/app/controllers/webui/users/notifications_controller.rb]: :+1: Changed.

**Review by dmarcoux — APPROVED** [review]
