### PR TITLE
Rescue Octokit and Gitlab exceptions and report to errbit

### LINKED ISSUE #11438: [production][] POST https://api.github.com/repos/vpereira/hello_world/statuses/5ca5adbea86f15e42a708deef2189f8b0...
threw this 162 times
<pre>
POST https://api.github.com/repos/vpereira/hello_world/statuses/5ca5adbea86f15e42a708deef2189f8b06551d68: 401 - Bad credentials // See: https://docs.github.com/rest
</pre>

[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/6102920084bf4607ebfd7302)

### PR DESCRIPTION
**Pull request by rubhanazeem**
Closes #11438, #11408

### CODE REVIEW

**Comment by rubhanazeem** [comment]
[Handle Gitlab/Octokit Errors in SCMStatusReporter](https://trello.com/c/NgyLPdA8/1745-handle-gitlab-octokit-errors-in-scmstatusreporter)

File: src/api/app/services/scm_status_reporter.rb [hunk 1]
```diff
@@ -13,18 +13,26 @@ def call
...
-                                  @event_subscription_payload[:commit_sha],
-                                  @state,
-                                  status_options)
+      begin
+        github_client.create_status(@event_subscription_payload[:target_repository_full_name],
+                                    @event_subscription_payload[:commit_sha],
+                                    @state,
+                                    status_options)
+      rescue Octokit::NotFound, Octokit::InternalServerError => e
+        Airbrake.notify(e)
```
Comment (hennevogel) [inline src/api/app/services/scm_status_reporter.rb:22]: This makes very little sense as *exactly* this will happen automatically right?

Comment (rubhanazeem) [reply src/api/app/services/scm_status_reporter.rb:22]: Do you mean `errbit` will be informed automatically?

Comment (dmarcoux) [reply src/api/app/services/scm_status_reporter.rb:22]: Yes, whenever an exception is raised without being rescued, Errbit is notified.

Comment (rubhanazeem) [reply src/api/app/services/scm_status_reporter.rb]: Thanks for the correction. It's updated.

File: src/api/app/services/scm_status_reporter.rb [hunk 2]
```diff
@@ -26,6 +78,9 @@ def call
                                          @state,
                                          status_options)
     end
+  rescue StandardError => e
```
Comment (rubhanazeem) [inline src/api/app/services/scm_status_reporter.rb:81]: Rubocop prefers to use `StandardError` for blind exceptions.

Comment (vpereira) [reply src/api/app/services/scm_status_reporter.rb:81]: wouldn't that be easier to do something like
```
ALL_AUTH_EXCEPTIONS = OCTOKIT_USER_ERRORS + GITLAB_USER_ERRORS
...

rescue *ALL_AUTH_EXCEPTIONS => e
  Airbreak.notify(e)
end
```

Comment (rubhanazeem) [reply src/api/app/services/scm_status_reporter.rb:31]: This will only notify about the auth exceptions. What we need is to catch every possible exception. If the exception is coming from the list defined above then inform the user about that, otherwise, send it to errbit.

Comment (vpereira) [reply src/api/app/services/scm_status_reporter.rb:31]: hm, but "catch" all exceptions `StandardError` but notify just the auth exceptions, isn't task of this service.

Comment (hennevogel) [reply src/api/app/services/scm_status_reporter.rb:31]: You don't have to catch the other exceptions to re-raise them. Just let me bubble up, if no one else catches them they end up with Airbrake.

File: src/api/app/services/scm_status_reporter.rb [hunk 3]
```diff
@@ -26,6 +28,8 @@ def call
...
+    rescue_with_handler(e) || raise(e)
   end
```
Comment (hennevogel) [inline src/api/app/services/scm_status_reporter.rb:33]:
```suggestion
  rescue Octokit, Gitlab::Error => e
    rescue_with_handler(e)
  end
```

File: src/api/app/services/scm_status_reporter.rb (hunk 2 above)
Comment (rubhanazeem) [reply src/api/app/services/scm_status_reporter.rb:31]: I don't have the list of exceptions available anymore. I've removed that list. I can still add that list and catch only those but there will be some duplication which I want to avoid. Have at this one https://github.com/openSUSE/open-build-service/pull/11592/files#diff-bc3a2624b259363910c0947fe29487b8d34e43ceccb8b0fe35efd463c84cd755R4

File: src/api/app/services/scm_status_reporter.rb (hunk 3 above)
Comment (rubhanazeem) [reply src/api/app/services/scm_status_reporter.rb]: @hennevogel the rescue exceptions list has been updated but we still need to use this `raise(e)`. `rescue_with_handler` apparently ignores every exception that is not mentioned in the rescue statement.

File: src/api/app/services/scm_status_reporter.rb [hunk 4]
```diff
@@ -1,7 +1,9 @@
-class SCMStatusReporter
+class SCMStatusReporter < SCMExceptionHandler
   attr_accessor :event_payload, :event_subscription_payload, :scm_token, :state
 
   def initialize(event_payload, event_subscription_payload, scm_token, event_type = nil)
+    super()
```
Comment (vpereira) [inline src/api/app/services/scm_status_reporter.rb:5]: do you need the parenthesis here?

Comment (rubhanazeem) [reply src/api/app/services/scm_status_reporter.rb:5]: Yes, otherwise it passes all parameters to the parent class. To avoid parameters I need paranthesis.

File: src/api/app/services/scm_exception_handler.rb [hunk 5]
```diff
@@ -0,0 +1,38 @@
...
+    # FIXME: Inform users about the exceptions
+  end
+
+  rescue_from Gitlab::Error::Conflict,
+              Gitlab::Error::Forbidden,
+              Gitlab::Error::InternalServerError,
+              Gitlab::Error::MissingCredentials,
+              Gitlab::Error::NotFound,
+              Gitlab::Error::ServiceUnavailable,
+              Gitlab::Error::Unauthorized do |exception|
```
Comment (dmarcoux) [inline src/api/app/services/scm_exception_handler.rb:35]: I think we should add `Gitlab::Error::TooManyRequests` to this list if somehow the user gets rate-limited. They could always try later. It's quite unlikely, but who knows...

File: src/api/app/services/scm_exception_handler.rb [hunk 6]
```diff
@@ -0,0 +1,38 @@
...
+              Octokit::InstallationSuspended,
+              Octokit::SAMLProtected,
+              Octokit::TooLargeContent,
+              Octokit::TooManyLoginAttempts,
+              Octokit::UnverifiedEmail,
+              Octokit::InvalidRepository,
+              Octokit::PathDiffTooLarge,
+              Octokit::ServiceUnavailable,
+              Octokit::InternalServerError do |exception|
+    # FIXME: Inform users about the exceptions
```
Comment (hennevogel) [inline src/api/app/services/scm_exception_handler.rb:26]: Can we at least log this so we have something to debug the problems of people?

**Review by hennevogel — CHANGES_REQUESTED** [review]

File: src/api/app/services/scm_exception_handler.rb (hunk 6 above)
Comment (vpereira) [reply src/api/app/services/scm_exception_handler.rb:26]: if we have the request id, couldn't we just grep the log file for that and get the stacktrace from there - or from errbit?

Comment (rubhanazeem) [reply src/api/app/services/scm_exception_handler.rb:26]: It won't add anything to errbit. I'm not sure about the request id.

Comment (rubhanazeem) [reply src/api/app/services/scm_exception_handler.rb:26]: I've added an error logger.

Comment (vpereira) [reply src/api/app/services/scm_exception_handler.rb:27]: my question was to @hennevogel. I wanted exactly to avoid the "Rails logger" calls everywhere. There should be better way to introspect code in 2021, other than custom stuff on error logger, right?

Comment (hennevogel) [reply src/api/app/services/scm_exception_handler.rb:27]: Logging is a temporary measure, just to be able to debug this for people for now. In the future we are going to expose this to the users. Because it is *them* who can do something about this. we can't.

**Review by dmarcoux — APPROVED** [review]

File: src/api/app/services/scm_exception_handler.rb [hunk 7]
```diff
@@ -0,0 +1,55 @@
...
+  def initialize(event_payload, event_subscription_payload, scm_token)
+    @event_payload = event_payload.deep_symbolize_keys
+    @event_subscription_payload = event_subscription_payload.deep_symbolize_keys
+    @scm_token = scm_token
+  end
+
+  private
+
+  def log(exception)
+    token = Token::Workflow.find_by(scm_token: @scm_token)
```
Comment (dmarcoux) [inline src/api/app/services/scm_exception_handler.rb:52]: It could be possible that two tokens have the same `scm_token`, although it's really an edge case... It's fine to not handle this.

**Review by dmarcoux — APPROVED** [review]
:+1: for the changes with the `log` method.

File: src/api/app/services/scm_exception_handler.rb (hunk 6 above)
Comment (dmarcoux) [reply src/api/app/services/scm_exception_handler.rb:27]: @hennevogel Please have another look.
