### PR TITLE
Fix filter text for involved projects/packages

### LINKED ISSUE #10811: Text for Empty List of a User's Involved Projects/Packages Is Sometimes Wrong
# Issue Description
On the profile page of a user, the text for an empty list of involved projects/packages is sometimes wrong. For example, if a user is only involved in projects and we filter by _Packages_, a text is displayed to let the current user that there are no involved projects/packages. This is wrong since the user is involved in some projects.

Expected Result
============
We should take into consideration whether the user is involved in projects/packages when filtering by _Packages_ or _Projects_ and change the text if needed.

How to Reproduce
===============

It's quite easy to reproduce in our development environment. Create some test data by running `bundle exec rake dev:development_testdata:create` in the frontend container.

1. Go to http://localhost:3000/users/Iggy and see that Iggy is involved in the project `home:Iggy`
2. Filter by _Packages_
3. See the wrong text `

Further Information
===============

Iggy's profile and the list of involved projects/packages:
iggy

Filter by _Packages_ of Iggy's involved projects/packages (with the wrong text):
wrong-text

### PR DESCRIPTION
**Pull request by rubhanazeem**
Filter message was hardcoded and was showing the wrong text.

Fixes #10811

### CODE REVIEW

**Comment by dmarcoux** [comment]
I'm pretty sure I created an issue for that, right? If it's the case, please link it in the commit description so we can close the issue when merging this PR.

**Comment by dmarcoux** [comment]
The commit message `Updated filter message.` is also quite generic, could you be a bit more specific?

**Comment by hennevogel** [comment]
We even have some [suggestions for commit messages](https://github.com/openSUSE/open-build-service/blob/master/CONTRIBUTING.md#proper-commit-messages)

File: src/api/app/helpers/webui/user_helper.rb [hunk 1]
```diff
@@ -86,6 +86,17 @@ def activity_date_commits(projects)
     end
   end
 
+  def filter_message(params)
```
Comment (dmarcoux) [inline src/api/app/helpers/webui/user_helper.rb:89]: This code is only considering the `Projects / Packages` filter, although we also need to consider the `Role` filter. See the screenshot below, the message is also wrong because it should be `This user is not involved in any project or package for the selected role`. Multiple roles can be selected, so to pluralize or not the word `role`, you can use [pluralize](https://api.rubyonrails.org/classes/ActionView/Helpers/TextHelper.html#method-i-pluralize).

role-filter

**Comment by dmarcoux** [comment]
It's me again :wave:... Regarding commit messages, if you use the present tense, they will be shorter and you won't miss any detail. It's a win-win situation, you type less and it's conveying the same information. You can also drop the dot at the end of the commit message, it's not needed.

So with all this, `Fixed filter text for involved projects/packages.` becomes `Fix filter text for involved projects/packages`.

**Review by dmarcoux — APPROVED** [review]
