### PR TITLE
[ci][webui] Fix handling global roles in user edit

### LINKED ISSUE #3566: 'Edit account' save button on profile pages removes admin privileges
An admin can either edit themselves via the `Configuration` or at their profile page. If the admin updates themselves over the profile page, the admin rights get revoked since it posts to the action `#save` without the `globalrole` param.

### PR DESCRIPTION
**Pull request by bgeuken**
Fixes #3566

The user save action is handling editing user accounts by users that want
to update their account as well as admins that edit other user's
accounts or their own.
In the latter case the code was accidentally dropping all global roles
of the admin user.

In addition there was a mismatch between the model implementation (allows
multiple roles) and the views (only showed the Admin role).
Since this changed recently with the introduction of the 'staff' role,
we had to fix this.
We now show all available global roles in the admin user edit page.

Or in short:

* Fixes dropping of global roles when an admin edits his own account (#3566)
* Allow admins to see and edit all global roles available for a user
* Improve tests for save action

### CODE REVIEW

**Comment by bgeuken** [comment]
I don't think we need to mention this for 2.9.

Once this is merged, I am going to cherry pick this to 2.8 and add it to the release notes there.

File: src/api/app/helpers/webui/user_helper.rb [hunk 1]
```diff
@@ -0,0 +1,5 @@
+module Webui::UserHelper
+  def user_states_for_edit
+    %w(confirmed unconfirmed deleted locked)
```
Comment (evanrolfe) [inline src/api/app/helpers/webui/user_helper.rb]: [Nitpick] You're defining which states a user is allowed to choose when editing their own accounts, so this seems more like business logic to me so I think it would be better placed in the User model.
