### PR TITLE
Return an error when filter definition is wrong

### LINKED ISSUE #12742: [production][trigger_workflow#create] undefined method `to_sym' for {:event=>"push"}:Hash

    @unsupported_filters ||= @workflow_instr...
[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/62bcaf5b84bf460539e65c4f)
# undefined method `to_sym&#39; for {:event=&gt;&quot;push&quot;}:Hash

    @unsupported_filters ||= @workflow_instructions[:filters].select { |key, _value| Workflow::SUPPORTED_FILTERS.exclude?(key.to_sym) }
                                                                                                                             ^^^^^^^
Did you mean?  to_s
               to_set #
### URL ###
[https://build.opensuse.org/trigger/workflow?id=6239](https://build.opensuse.org/trigger/workflow?id=6239)"
### Where ###
trigger_workflow#create

### Occured ###
Jun 29  8:00pm

### Similar ###
2

## Params ##
~~~
{
  &quot;action&quot; =&gt; &quot;create&quot;,
  &quot;after&quot; =&gt; &quot;5c46925dbdd948293fdb3efd53e6ac0841259306&quot;,
  &quot;base_ref&quot; =&gt; nil,
  &quot;before&quot; =&gt; &quot;0000000000000000000000000000000000000000&quot;,
  &quot;commits&quot; =&gt; [{&quot;id&quot;=&gt;&quot;5c46925dbdd948293fdb3efd53e6ac0841259306&quot;, &quot;tree_id&quot;=&gt;&quot;bb530ac845f60a00b7ae79968289f3b7a43df9a5&quot;, &quot;distinct&quot;=&gt;true, &quot;message&quot;=&gt;&quot;Initial version&quot;, &quot;timestamp&quot;=&gt;&quot;2022-06-29T16:58:39-03:00&quot;, &quot;url&quot;=&gt;&quot;https://github.com/gyr/toolbox-osc/commit/5c46925dbdd948293fdb3efd53e6ac0841259306&quot;, &quot;author&quot;=&gt;{&quot;name&quot;=&gt;&quot;Gustavo Yokoyama Ribeiro&quot;, &quot;email&quot;=&gt;&quot;gyribeiro@suse.com&quot;, &quot;username&quot;=&gt;&quot;gyr&quot;}, &quot;committer&quot;=&gt;{&quot;name&quot;=&gt;&quot;Gustavo Yokoyama Ribeiro&quot;, &quot;email&quot;=&gt;&quot;gyribeiro@suse.com&quot;, &quot;username&quot;=&gt;&quot;gyr&quot;}, &quot;added&quot;=&gt;[&quot;.obs/workflows.yml&quot;, &quot;Dockerfile&quot;], &quot;removed&quot;=&gt;[], &quot;modified&quot;=&gt;[]}],
  &quot;compare&quot; =&gt; &quot;https://github.com/gyr/toolbox-osc/commit/5c46925dbdd9&quot;,
  &quot;controller&quot; =&gt; &quot;trigger_workflow&quot;,
  &quot;created&quot; =&gt; true,
  &quot;deleted&quot; =&gt; false,
  &quot;forced&quot; =&gt; false,
  &quot;head_commit&quot; =&gt; {
    &quot;added&quot; =&gt; [&quot;.obs/workflows.yml&quot;, &quot;Dockerfile&quot;],
    &quot;author&quot; =&gt; {
      &quot;email&quot; =&gt; &quot;gyribeiro@suse.com&quot;,
      &quot;name&quot; =&gt; &quot;Gustavo Yokoyama Ribeiro&quot;,
      &quot;username&quot; =&gt; &quot;gyr&quot;
    },
    &quot;committer&quot; =&gt; {
      &quot;email&quot; =&gt; &quot;gyribeiro@suse.com&quot;,
      &quot;name&quot; =&gt; &quot;Gustavo Yokoyama Ribeiro&quot;,
      &quot;username&quot; =&gt; &quot;gyr&quot;
    },
    &quot;distinct&quot; =&gt; true,
    &quot;id&quot; =&gt; &quot;5c46925dbdd948293fdb3efd53e6ac0841259306&quot;,
    &quot;message&quot; =&gt; &quot;Initial version&quot;,
    &quot;modified&quot; =&gt; [],
    &quot;removed&quot; =&gt; [],
    &quot;timestamp&quot; =&gt; &quot;2022-06-29T16:58:39-03:00&quot;,
    &quot;tree_id&quot; =&gt; &quot;bb530ac845f60a00b7ae79968289f3b7a43df9a5&quot;,
    &quot;url&quot; =&gt; &quot;https://github.com/gyr/toolbox-osc/commit/5c46925dbdd948293fdb3efd53e6ac0841259306&quot;
  },
  &quot;id&quot; =&gt; &quot;6239&quot;,
  &quot;pusher&quot; =&gt; {
    &quot;email&quot; =&gt; &quot;gyr@users.noreply.github.com&quot;,
    &quot;name&quot; =&gt; &quot;gyr&quot;
  },
  &quot;ref&quot; =&gt; &quot;refs/heads/master&quot;,
  &quot;repository&quot; =&gt; {
    &quot;allow_forking&quot; =&gt; true,
    &quot;archive_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/{archive_format}{/ref}&quot;,
    &quot;archived&quot; =&gt; false,
    &quot;assignees_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/assignees{/user}&quot;,
    &quot;blobs_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/git/blobs{/sha}&quot;,
    &quot;branches_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/branches{/branch}&quot;,
    &quot;clone_url&quot; =&gt; &quot;https://github.com/gyr/toolbox-osc.git&quot;,
    &quot;collaborators_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/collaborators{/collaborator}&quot;,
    &quot;comments_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/comments{/number}&quot;,
    &quot;commits_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/commits{/sha}&quot;,
    &quot;compare_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/compare/{base}...{head}&quot;,
    &quot;contents_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/contents/{+path}&quot;,
    &quot;contributors_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/contributors&quot;,
    &quot;created_at&quot; =&gt; 1656530078,
    &quot;default_branch&quot; =&gt; &quot;master&quot;,
    &quot;deployments_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/deployments&quot;,
    &quot;description&quot; =&gt; nil,
    &quot;disabled&quot; =&gt; false,
    &quot;downloads_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/downloads&quot;,
    &quot;events_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/events&quot;,
    &quot;fork&quot; =&gt; false,
    &quot;forks&quot; =&gt; 0,
    &quot;forks_count&quot; =&gt; 0,
    &quot;forks_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/forks&quot;,
    &quot;full_name&quot; =&gt; &quot;gyr/toolbox-osc&quot;,
    &quot;git_commits_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/git/commits{/sha}&quot;,
    &quot;git_refs_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/git/refs{/sha}&quot;,
    &quot;git_tags_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/git/tags{/sha}&quot;,
    &quot;git_url&quot; =&gt; &quot;git://github.com/gyr/toolbox-osc.git&quot;,
    &quot;has_downloads&quot; =&gt; true,
    &quot;has_issues&quot; =&gt; true,
    &quot;has_pages&quot; =&gt; false,
    &quot;has_projects&quot; =&gt; true,
    &quot;has_wiki&quot; =&gt; true,
    &quot;homepage&quot; =&gt; nil,
    &quot;hooks_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/hooks&quot;,
    &quot;html_url&quot; =&gt; &quot;https://github.com/gyr/toolbox-osc&quot;,
    &quot;id&quot; =&gt; 508817178,
    &quot;is_template&quot; =&gt; false,
    &quot;issue_comment_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/issues/comments{/number}&quot;,
    &quot;issue_events_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/issues/events{/number}&quot;,
    &quot;issues_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/issues{/number}&quot;,
    &quot;keys_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/keys{/key_id}&quot;,
    &quot;labels_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/labels{/name}&quot;,
    &quot;language&quot; =&gt; nil,
    &quot;languages_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/languages&quot;,
    &quot;license&quot; =&gt; nil,
    &quot;master_branch&quot; =&gt; &quot;master&quot;,
    &quot;merges_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/merges&quot;,
    &quot;milestones_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/milestones{/number}&quot;,
    &quot;mirror_url&quot; =&gt; nil,
    &quot;name&quot; =&gt; &quot;toolbox-osc&quot;,
    &quot;node_id&quot; =&gt; &quot;R_kgDOHlPvGg&quot;,
    &quot;notifications_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/notifications{?since,all,participating}&quot;,
    &quot;open_issues&quot; =&gt; 0,
    &quot;open_issues_count&quot; =&gt; 0,
    &quot;owner&quot; =&gt; {
      &quot;avatar_url&quot; =&gt; &quot;https://avatars.githubusercontent.com/u/1413436?v=4&quot;,
      &quot;email&quot; =&gt; &quot;gyr@users.noreply.github.com&quot;,
      &quot;events_url&quot; =&gt; &quot;https://api.github.com/users/gyr/events{/privacy}&quot;,
      &quot;followers_url&quot; =&gt; &quot;https://api.github.com/users/gyr/followers&quot;,
      &quot;following_url&quot; =&gt; &quot;https://api.github.com/users/gyr/following{/other_user}&quot;,
      &quot;gists_url&quot; =&gt; &quot;https://api.github.com/users/gyr/gists{/gist_id}&quot;,
      &quot;gravatar_id&quot; =&gt; &quot;&quot;,
      &quot;html_url&quot; =&gt; &quot;https://github.com/gyr&quot;,
      &quot;id&quot; =&gt; 1413436,
      &quot;login&quot; =&gt; &quot;gyr&quot;,
      &quot;name&quot; =&gt; &quot;gyr&quot;,
      &quot;node_id&quot; =&gt; &quot;MDQ6VXNlcjE0MTM0MzY=&quot;,
      &quot;organizations_url&quot; =&gt; &quot;https://api.github.com/users/gyr/orgs&quot;,
      &quot;received_events_url&quot; =&gt; &quot;https://api.github.com/users/gyr/received_events&quot;,
      &quot;repos_url&quot; =&gt; &quot;https://api.github.com/users/gyr/repos&quot;,
      &quot;site_admin&quot; =&gt; false,
      &quot;starred_url&quot; =&gt; &quot;https://api.github.com/users/gyr/starred{/owner}{/repo}&quot;,
      &quot;subscriptions_url&quot; =&gt; &quot;https://api.github.com/users/gyr/subscriptions&quot;,
      &quot;type&quot; =&gt; &quot;User&quot;,
      &quot;url&quot; =&gt; &quot;https://api.github.com/users/gyr&quot;
    },
    &quot;private&quot; =&gt; false,
    &quot;pulls_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/pulls{/number}&quot;,
    &quot;pushed_at&quot; =&gt; 1656532825,
    &quot;releases_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/releases{/id}&quot;,
    &quot;size&quot; =&gt; 0,
    &quot;ssh_url&quot; =&gt; &quot;git@github.com:gyr/toolbox-osc.git&quot;,
    &quot;stargazers&quot; =&gt; 0,
    &quot;stargazers_count&quot; =&gt; 0,
    &quot;stargazers_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/stargazers&quot;,
    &quot;statuses_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/statuses/{sha}&quot;,
    &quot;subscribers_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/subscribers&quot;,
    &quot;subscription_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/subscription&quot;,
    &quot;svn_url&quot; =&gt; &quot;https://github.com/gyr/toolbox-osc&quot;,
    &quot;tags_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/tags&quot;,
    &quot;teams_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/teams&quot;,
    &quot;topics&quot; =&gt; [],
    &quot;trees_url&quot; =&gt; &quot;https://api.github.com/repos/gyr/toolbox-osc/git/trees{/sha}&quot;,
    &quot;updated_at&quot; =&gt; &quot;2022-06-29T19:14:38Z&quot;,
    &quot;url&quot; =&gt; &quot;https://github.com/gyr/toolbox-osc&quot;,
    &quot;visibility&quot; =&gt; &quot;public&quot;,
    &quot;watchers&quot; =&gt; 0,
    &quot;watchers_count&quot; =&gt; 0,
    &quot;web_commit_signoff_required&quot; =&gt; false
  },
  &quot;sender&quot; =&gt; {
    &quot;avatar_url&quot; =&gt; &quot;https://avatars.githubusercontent.com/u/1413436?v=4&quot;,
    &quot;events_url&quot; =&gt; &quot;https://api.github.com/users/gyr/events{/privacy}&quot;,
    &quot;followers_url&quot; =&gt; &quot;https://api.github.com/users/gyr/followers&quot;,
    &quot;following_url&quot; =&gt; &quot;https://api.github.com/users/gyr/following{/other_user}&quot;,
    &quot;gists_url&quot; =&gt; &quot;https://api.github.com/users/gyr/gists{/gist_id}&quot;,
    &quot;gravatar_id&quot; =&gt; &quot;&quot;,
    &quot;html_url&quot; =&gt; &quot;https://github.com/gyr&quot;,
    &quot;id&quot; =&gt; 1413436,
    &quot;login&quot; =&gt; &quot;gyr&quot;,
    &quot;node_id&quot; =&gt; &quot;MDQ6VXNlcjE0MTM0MzY=&quot;,
    &quot;organizations_url&quot; =&gt; &quot;https://api.github.com/users/gyr/orgs&quot;,
    &quot;received_events_url&quot; =&gt; &quot;https://api.github.com/users/gyr/received_events&quot;,
    &quot;repos_url&quot; =&gt; &quot;https://api.github.com/users/gyr/repos&quot;,
    &quot;site_admin&quot; =&gt; false,
    &quot;starred_url&quot; =&gt; &quot;https://api.github.com/users/gyr/starred{/owner}{/repo}&quot;,
    &quot;subscriptions_url&quot; =&gt; &quot;https://api.github.com/users/gyr/subscriptions&quot;,
    &quot;type&quot; =&gt; &quot;User&quot;,
    &quot;url&quot; =&gt; &quot;https://api.github.com/users/gyr&quot;
  }
}
~~~

## Session ##
~~~
{}
~~~

## Backtrace ##
~~~
36:  app/validators/workflow_filters_validator.rb -> **block in unsupported_filters**
36:  app/validators/workflow_filters_validator.rb -> **select**
36:  app/validators/workflow_filters_validator.rb -> **unsupported_filters**
24:  app/validators/workflow_filters_validator.rb -> **validate_filters**
9:  app/validators/workflow_filters_validator.rb -> **validate**
427:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **block in make_lambda**
198:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **block (2 levels) in halting**
604:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **block (2 levels) in default_terminator**
603:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **catch**
603:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **block in default_terminator**
199:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **block in halting**
512:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **block in invoke_before**
512:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **each**
512:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **invoke_before**
105:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **run_callbacks**
824:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **_run_validate_callbacks**
406:  /GEM_ROOT/gems/activemodel-6.1.5.1/lib/active_model/validations.rb -> **run_validations!**
337:  /GEM_ROOT/gems/activemodel-6.1.5.1/lib/active_model/validations.rb -> **valid?**
58:  app/models/token/workflow.rb -> **block in validation_errors**
57:  app/models/token/workflow.rb -> **each**
57:  app/models/token/workflow.rb -> **validation_errors**
32:  app/models/token/workflow.rb -> **call**
13:  app/controllers/trigger_workflow_controller.rb -> **block in create**
876:  app/models/user.rb -> **run_as**
12:  app/controllers/trigger_workflow_controller.rb -> **create**
6:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal/basic_implicit_render.rb -> **send_action**
228:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/abstract_controller/base.rb -> **process_action**
30:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal/rendering.rb -> **process_action**
42:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/abstract_controller/callbacks.rb -> **block in process_action**
106:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **run_callbacks**
41:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/abstract_controller/callbacks.rb -> **process_action**
22:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal/rescue.rb -> **process_action**
34:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal/instrumentation.rb -> **block in process_action**
203:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/notifications/instrumenter.rb -> **instrument**
203:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/notifications.rb -> **instrument**
33:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal/instrumentation.rb -> **process_action**
249:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal/params_wrapper.rb -> **process_action**
27:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/railties/controller_runtime.rb -> **process_action**
165:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/abstract_controller/base.rb -> **process**
39:  /GEM_ROOT/gems/actionview-6.1.5.1/lib/action_view/rendering.rb -> **process**
190:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal.rb -> **dispatch**
254:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal.rb -> **dispatch**
50:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/routing/route_set.rb -> **dispatch**
33:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/routing/route_set.rb -> **serve**
19:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/routing/mapper.rb -> **block in &lt;class:Constraints&gt;**
49:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/routing/mapper.rb -> **serve**
50:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/journey/router.rb -> **block in serve**
32:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/journey/router.rb -> **each**
32:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/journey/router.rb -> **serve**
842:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/routing/route_set.rb -> **call**
72:  /GEM_ROOT/gems/flipper-0.25.0/lib/flipper/middleware/memoizer.rb -> **memoized_call**
37:  /GEM_ROOT/gems/flipper-0.25.0/lib/flipper/middleware/memoizer.rb -> **call**
37:  config/initializers/wrap_parameters.rb -> **call**
44:  /GEM_ROOT/gems/rack-2.2.3.1/lib/rack/deflater.rb -> **call**
15:  /GEM_ROOT/gems/rack-2.2.3.1/lib/rack/tempfile_reaper.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.3.1/lib/rack/etag.rb -> **call**
40:  /GEM_ROOT/gems/rack-2.2.3.1/lib/rack/conditional_get.rb -> **call**
12:  /GEM_ROOT/gems/rack-2.2.3.1/lib/rack/head.rb -> **call**
22:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/http/permissions_policy.rb -> **call**
19:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/http/content_security_policy.rb -> **call**
266:  /GEM_ROOT/gems/rack-2.2.3.1/lib/rack/session/abstract/id.rb -> **context**
260:  /GEM_ROOT/gems/rack-2.2.3.1/lib/rack/session/abstract/id.rb -> **call**
689:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/cookies.rb -> **call**
27:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/callbacks.rb -> **block in call**
98:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **run_callbacks**
26:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/callbacks.rb -> **call**
18:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/actionable_exceptions.rb -> **call**
32:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call!**
21:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call**
29:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/debug_exceptions.rb -> **call**
33:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/show_exceptions.rb -> **call**
18:  /GEM_ROOT/gems/lograge-0.12.0/lib/lograge/rails_ext/rack/logger.rb -> **call_app**
26:  /GEM_ROOT/gems/railties-6.1.5.1/lib/rails/rack/logger.rb -> **block in call**
99:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/tagged_logging.rb -> **block in tagged**
37:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/tagged_logging.rb -> **tagged**
99:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/tagged_logging.rb -> **tagged**
26:  /GEM_ROOT/gems/railties-6.1.5.1/lib/rails/rack/logger.rb -> **call**
81:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/remote_ip.rb -> **call**
81:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/remote_ip.rb -> **call**
19:  /GEM_ROOT/gems/request_store-1.5.1/lib/request_store/middleware.rb -> **call**
26:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/request_id.rb -> **call**
24:  /GEM_ROOT/gems/rack-2.2.3.1/lib/rack/method_override.rb -> **call**
22:  /GEM_ROOT/gems/rack-2.2.3.1/lib/rack/runtime.rb -> **call**
29:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/cache/strategy/local_cache_middleware.rb -> **call**
14:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/executor.rb -> **call**
18:  /GEM_ROOT/gems/rack-2.2.3.1/lib/rack/lock.rb -> **call**
110:  /GEM_ROOT/gems/rack-2.2.3.1/lib/rack/sendfile.rb -> **call**
142:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/host_authorization.rb -> **call**
539:  /GEM_ROOT/gems/railties-6.1.5.1/lib/rails/engine.rb -> **call**
207:  /GEM_ROOT/gems/railties-6.1.5.1/lib/rails/railtie.rb -> **public_send**
207:  /GEM_ROOT/gems/railties-6.1.5.1/lib/rails/railtie.rb -> **method_missing**
74:  /GEM_ROOT/gems/rack-2.2.3.1/lib/rack/urlmap.rb -> **block in call**
58:  /GEM_ROOT/gems/rack-2.2.3.1/lib/rack/urlmap.rb -> **each**
58:  /GEM_ROOT/gems/rack-2.2.3.1/lib/rack/urlmap.rb -> **call**
107:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.12/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb -> **process_request**
157:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.12/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **accept_and_process_next_request**
110:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.12/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **main_loop**
419:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.12/src/ruby_supportlib/phusion_passenger/request_handler.rb -> **block (3 levels) in start_threads**
113:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.12/src/ruby_supportlib/phusion_passenger/utils.rb -> **block in create_thread_and_abort_on_exception**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| program_name | Passenger RubyApp: /srv/www/obs/api (production) |
| HTTP_USER_AGENT | GitHub-Hookshot/f8f406d |

### PR DESCRIPTION
**Pull request by danidoni**
This filter definition is wrong:

```
rebuild_master:
  steps:
    - rebuild_package:
        source_project: home:gyribeiro:containers
        source_package: toolbox-osc
        project: home:gyribeiro:containers
        package: toolbox-osc
  filters:
    - event: push
 ```
 
It should be like:

```
  filters:
    event: push
```

When we detect something like this, we return a validation error to notify the user.

Fixes #12742

### CODE REVIEW

File: src/api/app/validators/workflow_filters_validator.rb [hunk 1]
```diff
@@ -32,6 +33,10 @@ def validate_filters
                                    "#{SUPPORTED_FILTER_VALUES.map { |key| "'#{key}'" }.to_sentence} are the only supported values.")
   end
 
+  def valid_filters_definition?
```
Comment (hennevogel) [inline src/api/app/validators/workflow_filters_validator.rb:36]:
```suggestion
  # FIXME: Remove once we have general workflow.yml validation
  def valid_filters_definition?
```

**Review by hennevogel — CHANGES_REQUESTED** [review]

**Review by hennevogel — APPROVED** [review]
