### PR TITLE
Fix DelegateRequestTarget migration

### LINKED ISSUE #9762: Initial database setup broken
From /srv/www/obs/api/log/db_migrate.log

```
[strong_migrations] DANGER: Lock timeout is longer than 10 seconds: 86400
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Duplicate entry '1-DelegateRequestTarget' for key 'index_attrib_types_on_attrib_namespace_id_and_name'
/srv/www/obs/api/db/data/20200527135426_request_delegate_attribute.rb:9:in `up'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

Caused by:
ActiveRecord::RecordNotUnique: Mysql2::Error: Duplicate entry '1-DelegateRequestTarget' for key 'index_attrib_types_on_attrib_namespace_id_and_name'
/srv/www/obs/api/db/data/20200527135426_request_delegate_attribute.rb:9:in `up'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

Caused by:
Mysql2::Error: Duplicate entry '1-DelegateRequestTarget' for key 'index_attrib_types_on_attrib_namespace_id_and_name'
/srv/www/obs/api/db/data/20200527135426_request_delegate_attribute.rb:9:in `up'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate:with_data
(See full trace by running task with --trace)
```

IMHO this commit broke it:

https://github.com/openSUSE/open-build-service/pull/9616

### PR DESCRIPTION
**Pull request by hennevogel**
Do not crash if the attribute already exists. Can happen when seeds are loaded
and then people apply migrations.

Fixes #9762

### CODE REVIEW

File: src/api/db/data/20200527135426_request_delegate_attribute.rb [hunk 1]
```diff
@@ -6,10 +6,10 @@ def self.up
 
     AttribTypeModifiableBy.reset_column_information
 
-    at = AttribType.create(attrib_namespace: ans, name: 'DelegateRequestTarget')
+    at = AttribType.find_or_create_by(attrib_namespace: ans, name: 'DelegateRequestTarget')
 
     role = Role.find_by_title('maintainer')
-    AttribTypeModifiableBy.create(role_id: role.id, attrib_type_id: at.id)
```
Comment (dmarcoux) [inline src/api/db/data/20200527135426_request_delegate_attribute.rb:12]: This could have created duplicates in the database, but happily for us, it couldn't happen since `AttribType.create` always failed with `Duplicate entry` before.
