### PR TITLE
Show link to add a package to the watchlist for multibuild packages

### LINKED ISSUE #12242: [production][package#live_build_log] undefined method `persisted?' for "glibc:utils":String
[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/6214fdde84bf46054908884e)
# undefined method `persisted?&#39; for &quot;glibc:utils&quot;:String #
### URL ###
[https://build.opensuse.org/package/live_build_log/openSUSE:Factory:zSystems/glibc:utils/standard/s390x](https://build.opensuse.org/package/live_build_log/openSUSE:Factory:zSystems/glibc:utils/standard/s390x)"
### Where ###
package#live_build_log

### Occured ###
Feb 22  3:14pm

### Similar ###
15

## Params ##
~~~
{
  &quot;action&quot; =&gt; &quot;live_build_log&quot;,
  &quot;arch&quot; =&gt; &quot;s390x&quot;,
  &quot;controller&quot; =&gt; &quot;webui/package&quot;,
  &quot;format&quot; =&gt; &quot;html&quot;,
  &quot;package&quot; =&gt; &quot;glibc:utils&quot;,
  &quot;project&quot; =&gt; &quot;openSUSE:Factory:zSystems&quot;,
  &quot;repository&quot; =&gt; &quot;standard&quot;
}
~~~

## Session ##
~~~
{
  &quot;_csrf_token&quot; =&gt; &quot;KMiZ5UwPUW8PpEVPm2I7Q5Z3Y8ezmBqZaX8w52bNl8s=&quot;,
  &quot;session_id&quot; =&gt; &quot;6acdd0124c8c557025d799bfbfeb39a5&quot;
}
~~~

## Backtrace ##
~~~
7:  app/components/watchlist_component.html.haml -> **call**
130:  /GEM_ROOT/gems/view_component-2.49.0/lib/view_component/compiler.rb -> **render_template_for**
90:  /GEM_ROOT/gems/view_component-2.49.0/lib/view_component/base.rb -> **render_in**
43:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/helpers/rendering_helper.rb -> **render**
13:  /GEM_ROOT/gems/haml-5.2.2/lib/haml/helpers/action_view_mods.rb -> **block in render**
93:  /GEM_ROOT/gems/haml-5.2.2/lib/haml/helpers.rb -> **non_haml**
13:  /GEM_ROOT/gems/haml-5.2.2/lib/haml/helpers/action_view_mods.rb -> **render**
80:  app/views/layouts/webui/webui.html.haml -> **_app_views_layouts_webui_webui_html_haml__1844980283924757759_47211480355340**
247:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/base.rb -> **public_send**
247:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/base.rb -> **_run**
154:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/template.rb -> **block in render**
205:  /GEM_ROOT/gems/activesupport-6.1.4.6/lib/active_support/notifications.rb -> **instrument**
345:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/template.rb -> **instrument_render_template**
152:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/template.rb -> **render**
72:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/renderer/template_renderer.rb -> **block in render_with_layout**
205:  /GEM_ROOT/gems/activesupport-6.1.4.6/lib/active_support/notifications.rb -> **instrument**
70:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/renderer/template_renderer.rb -> **render_with_layout**
55:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/renderer/template_renderer.rb -> **render_template**
11:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/renderer/template_renderer.rb -> **render**
61:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/renderer/renderer.rb -> **render_template_to_object**
29:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/renderer/renderer.rb -> **render_to_object**
117:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/rendering.rb -> **block in _render_template**
273:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/base.rb -> **in_rendering_context**
116:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/rendering.rb -> **_render_template**
218:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal/streaming.rb -> **_render_template**
103:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/rendering.rb -> **render_to_body**
52:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal/rendering.rb -> **render_to_body**
142:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal/renderers.rb -> **render_to_body**
25:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/abstract_controller/rendering.rb -> **render**
36:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal/rendering.rb -> **render**
46:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal/instrumentation.rb -> **block (2 levels) in render**
308:  /usr/lib64/ruby/2.5.0/benchmark.rb -> **realtime**
14:  /GEM_ROOT/gems/activesupport-6.1.4.6/lib/active_support/core_ext/benchmark.rb -> **ms**
46:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal/instrumentation.rb -> **block in render**
86:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal/instrumentation.rb -> **cleanup_view_runtime**
34:  /GEM_ROOT/gems/activerecord-6.1.4.6/lib/active_record/railties/controller_runtime.rb -> **cleanup_view_runtime**
45:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal/instrumentation.rb -> **render**
35:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal/implicit_render.rb -> **default_render**
6:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal/basic_implicit_render.rb -> **block in send_action**
6:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal/basic_implicit_render.rb -> **tap**
6:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal/basic_implicit_render.rb -> **send_action**
228:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/abstract_controller/base.rb -> **process_action**
30:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal/rendering.rb -> **process_action**
42:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/abstract_controller/callbacks.rb -> **block in process_action**
106:  /GEM_ROOT/gems/activesupport-6.1.4.6/lib/active_support/callbacks.rb -> **run_callbacks**
41:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/abstract_controller/callbacks.rb -> **process_action**
22:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal/rescue.rb -> **process_action**
34:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal/instrumentation.rb -> **block in process_action**
203:  /GEM_ROOT/gems/activesupport-6.1.4.6/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-6.1.4.6/lib/active_support/notifications/instrumenter.rb -> **instrument**
203:  /GEM_ROOT/gems/activesupport-6.1.4.6/lib/active_support/notifications.rb -> **instrument**
33:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal/instrumentation.rb -> **process_action**
249:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal/params_wrapper.rb -> **process_action**
27:  /GEM_ROOT/gems/activerecord-6.1.4.6/lib/active_record/railties/controller_runtime.rb -> **process_action**
165:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/abstract_controller/base.rb -> **process**
39:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/rendering.rb -> **process**
190:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal.rb -> **dispatch**
254:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal.rb -> **dispatch**
50:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/routing/route_set.rb -> **dispatch**
33:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/routing/route_set.rb -> **serve**
19:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/routing/mapper.rb -> **block in &lt;class:Constraints&gt;**
49:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/routing/mapper.rb -> **serve**
50:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/journey/router.rb -> **block in serve**
32:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/journey/router.rb -> **each**
32:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/journey/router.rb -> **serve**
842:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/routing/route_set.rb -> **call**
77:  /GEM_ROOT/gems/flipper-0.23.1/lib/flipper/middleware/memoizer.rb -> **memoized_call**
42:  /GEM_ROOT/gems/flipper-0.23.1/lib/flipper/middleware/memoizer.rb -> **call**
37:  config/initializers/wrap_parameters.rb -> **call**
44:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/deflater.rb -> **call**
15:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/etag.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/conditional_get.rb -> **call**
12:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/head.rb -> **call**
22:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/http/permissions_policy.rb -> **call**
18:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/http/content_security_policy.rb -> **call**
266:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/session/abstract/id.rb -> **context**
260:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/session/abstract/id.rb -> **call**
689:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/middleware/cookies.rb -> **call**
27:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/middleware/callbacks.rb -> **block in call**
98:  /GEM_ROOT/gems/activesupport-6.1.4.6/lib/active_support/callbacks.rb -> **run_callbacks**
26:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/middleware/callbacks.rb -> **call**
18:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/middleware/actionable_exceptions.rb -> **call**
32:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call!**
21:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call**
29:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/middleware/debug_exceptions.rb -> **call**
33:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/middleware/show_exceptions.rb -> **call**
15:  /GEM_ROOT/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb -> **call_app**
26:  /GEM_ROOT/gems/railties-6.1.4.6/lib/rails/rack/logger.rb -> **block in call**
99:  /GEM_ROOT/gems/activesupport-6.1.4.6/lib/active_support/tagged_logging.rb -> **block in tagged**
37:  /GEM_ROOT/gems/activesupport-6.1.4.6/lib/active_support/tagged_logging.rb -> **tagged**
99:  /GEM_ROOT/gems/activesupport-6.1.4.6/lib/active_support/tagged_logging.rb -> **tagged**
26:  /GEM_ROOT/gems/railties-6.1.4.6/lib/rails/rack/logger.rb -> **call**
81:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/middleware/remote_ip.rb -> **call**
81:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/middleware/remote_ip.rb -> **call**
19:  /GEM_ROOT/gems/request_store-1.5.1/lib/request_store/middleware.rb -> **call**
26:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/middleware/request_id.rb -> **call**
24:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/method_override.rb -> **call**
22:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/runtime.rb -> **call**
29:  /GEM_ROOT/gems/activesupport-6.1.4.6/lib/active_support/cache/strategy/local_cache_middleware.rb -> **call**
14:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/middleware/executor.rb -> **call**
18:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/lock.rb -> **call**
110:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/sendfile.rb -> **call**
113:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/middleware/host_authorization.rb -> **call**
539:  /GEM_ROOT/gems/railties-6.1.4.6/lib/rails/engine.rb -> **call**
207:  /GEM_ROOT/gems/railties-6.1.4.6/lib/rails/railtie.rb -> **public_send**
207:  /GEM_ROOT/gems/railties-6.1.4.6/lib/rails/railtie.rb -> **method_missing**
74:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/urlmap.rb -> **block in call**
58:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/urlmap.rb -> **each**
58:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/urlmap.rb -> **call**
107:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.12/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb -> **process_request**
149:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.12/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **accept_and_process_next_request**
110:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.12/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **main_loop**
419:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.12/src/ruby_supportlib/phusion_passenger/request_handler.rb -> **block (3 levels) in start_threads**
113:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.12/src/ruby_supportlib/phusion_passenger/utils.rb -> **block in create_thread_and_abort_on_exception**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| program_name | Passenger RubyApp: /srv/www/obs/api (production) |
| HTTP_USER_AGENT | Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0 |

### PR DESCRIPTION
**Pull request by eduardoj**
With the new watchlist implementation, an error was thrown when browsing the live build log for a multibuild package. The guilty was `@package` returning a string instead of an object.

This PR includes the following changes:
- In case of a multibuild package: `@package` used to be a string, now `@package` contains an object.
- `@package_name` is introduced and contains the package string.
- The retrieval of build logs of remote projects was not supported. This code was removed. This means that `@package` is no longer nil.
- Thanks to the previous changes, checking for the permissions is more straight forward, as `@package` is no longer nil.

These changes imply some improvements in the UI for the live build log page for a multibuild package.

**Before:**
- The tabs where not shown
- The breadcrums contained a link to a package with the multibuild flavor. This always redirected to the base package (the package without the flavor).

Screenshot from 2022-02-25 09-41-49

**Now:**
- The tabs are shown.
- The breadcrums contains a link the the base package.

Screenshot from 2022-02-25 09-42-10

Fixes #12242 .

Co-authored-by: Saray Cabrera Padrón <scabrerapadron@suse.de>

**TODO:**
- [x] Add tests.

### CODE REVIEW

File: src/api/app/components/watchlist_component.rb [hunk 1]
```diff
@@ -14,8 +14,11 @@ class WatchlistComponent < ApplicationComponent
   def initialize(user:, project: nil, package: nil, bs_request: nil)
     super
 
+    # NOTE: package can be also a String. For example, the live build log for multibuild packages.
+    package = Package.find_by_project_and_name(project.name, Package.striping_multibuild_suffix(package)) if package.is_a?(String)
```
Comment (dmarcoux) [inline src/api/app/components/watchlist_component.rb:18]: If we provide a package which isn't really a package, but a string to this component, we should change the code where this component is instantiated.

A view component should deal with view code, not fetching data from the database. We already do this here in methods like `projects`, `packages` and `bs_requests`, but this should be refactored too in another PR.

**Review by dmarcoux — CHANGES_REQUESTED** [review]

File: src/api/app/components/watchlist_component.rb (hunk 1 above)
Comment (saraycp) [reply src/api/app/components/watchlist_component.rb:18]: Good advice @dmarcoux, thanks! I created a [card in the backlog](https://trello.com/c/toTBZ8aS/2529-extract-retrieving-objects-from-db-from-view-component) for this.

Comment (dmarcoux) [reply src/api/app/components/watchlist_component.rb:18]: Thank you @saraycp :slightly_smiling_face:

File: src/api/app/controllers/webui/package_controller.rb [hunk 2]
```diff
@@ -705,29 +705,30 @@ def check_build_log_access
...
+
+    # NOTE: @package is nil for remote projects
     if @package && !@package.check_source_access?
-      redirect_to package_show_path(project: @project.name, package: @package.name),
+      redirect_to package_show_path(project: @project.name, package: @package_name),
                   error: 'Could not access build log'
       return false
     end
 
     @can_modify = User.possibly_nobody.can_modify?(@project) || User.possibly_nobody.can_modify?(@package)
```
Comment (hennevogel) [inline src/api/app/controllers/webui/package_controller.rb:730]: `User.possibly_nobody.can_modify?(nil)` is something different then `User.possibly_nobody.can_modify?(Package)`

did you check what `@can_modify` does?

Comment (eduardoj) [reply src/api/app/controllers/webui/package_controller.rb:727]: Ops, true. I moved down the `Package.find_by_project_and_name...` line, below the `can_modify?` check. This should fix it.

File: src/api/app/components/watchlist_component.rb (hunk 1 above)
Comment (eduardoj) [reply src/api/app/components/watchlist_component.rb]: Finally I opted for revisiting the package controller methods related to the live build log, and make sure that:
- `@package` always returns an object.
- the new instance variable `@package_name` keeps the package name to be shown in the views. It will contain what is passed from `param[:package]`.

For example, having `params[:package] = 'obs-server:flavor1'`:
- `@package` will contain the package object 'obs-server'. There isn't any package object for 'obs-server:flavor1'.
- `@package_name` will be the string 'obs-server:flavor1'.

I also renamed the `package` variables in `mixins/build_log_support.rb` to `package_name`, to make it clear that they are strings.

File: src/api/app/controllers/webui/package_controller.rb [hunk 3]
```diff
@@ -705,28 +705,29 @@ def check_build_log_access
...
 
-    # for remote and multibuild / local link packages
-    @package = params[:package] if @package.try(:name) != params[:package]
+    # NOTE: @package is a String for multibuild packages
```
Comment (danidoni) [inline src/api/app/controllers/webui/package_controller.rb:729]: And for remote packages, right?

Comment (eduardoj) [reply src/api/app/controllers/webui/package_controller.rb:729]: For remote packages it is an object, yes.

But for local link packages `@package` is nil, so the code I changed breaks.

I will change the PR to draft until I fix this and add tests.

**Comment by eduardoj** [comment]
The PR was updated. The changes are described in the description and commit messages. Please have another look.

**Review by danidoni — APPROVED** [review]

**Comment by hennevogel** [comment]
I would feel way more comfortable with this if you would separate refactoring from functional changes.

**Comment by eduardoj** [comment]
> I would feel way more comfortable with this change if you would separate refactoring from functional changes. At least in commits.

I will try removing the third commit.

**Comment by eduardoj** [comment]
> > I would feel way more comfortable with this change if you would separate refactoring from functional changes. At least in commits.
> 
> I will try removing the third commit.

Hm... it is not possible. The 3rd commit introduces a variable that is necessary to introduce after the variable `@package` has been changed in the 2nd commit. Otherwise the code is broken.
