### PR TITLE
Accept a parameter to remove exclusion from requests before staging

### LINKED ISSUE #8525: Allow to stage an excluded request in one step
If I exclude a request, I do so to ease managing the backlog. But once I have free staging projects, I would like to give it a 2nd chance. To do so right now, I need to:

1. remove from excluded requests

1. stage into project of choice

because if I skip to step 2, I'll get:
```
Server returned an error: HTTP Error 400: Bad Request
Assigning requests to openSUSE:Factory:Staging:B failed: Request 114 not found in Staging for project openSUSE:Factory.
```

(which is yet another misleading error, I'd file an issue for this but I prefer if this is solved within the context of this very issue)

I would prefer if I could ACK that it's currently excluded (to avoid races between 2 staging managers, where one excludes a request from backlog and another selects it into a project) and have `add --unignore`

### PR DESCRIPTION
**Pull request by danidoni**
Stage request action now accepts the new parameter `remove_exclusion`

Right now, you can't stage an excluded request. You have to:

1. remove the exclusion first
2. stage the request afterwards

This opens a time window where maintainers can compete to stage the
same request.

This PR implements the acceptance of a new parameter during the
request staging to do 1. and 2. in the same action.

Fixes #8525

### CODE REVIEW

File: src/api/app/controllers/staging/staged_requests_controller.rb [hunk 1]
```diff
@@ -15,6 +15,19 @@ def index
...
     authorize @staging_project, :update?
 
+    if params[:remove_exclusion] == '1'
+      result = ::Staging::RequestExcluder.new(requests_xml_hash: { number: @request_numbers },
+                                              staging_workflow: @staging_workflow).destroy
+      unless result.valid?
+        render_error(
+          status: 400,
+          errorcode: 'invalid_request',
+          message: "Error while unexcluding requests: #{result.errors.join(' ')}"
```
[the remark this answers is not in the document]
Comment (danidoni) [reply src/api/app/controllers/staging/staged_requests_controller.rb]: Yeah

File: src/api/spec/controllers/staging/staged_requests_controller_spec.rb [hunk 2]
```diff
@@ -99,6 +99,45 @@
       it { expect(staging_project.staged_requests).to include(bs_request) }
       it { assert_select 'status[code=ok]' }
     end
+
+    context 'with an excluded request', vcr: true do
+      context 'when not providing the remove exclusion parameter' do
+        before do
+          Staging::RequestExclusion.new(bs_request: bs_request,
```
[the remark this answers is not in the document]
Comment (danidoni) [reply src/api/spec/controllers/staging/staged_requests_controller_spec.rb]: I don't know. I'll try to build one

File: src/api/app/controllers/staging/staged_requests_controller.rb [hunk 3]
```diff
@@ -15,6 +15,19 @@ def index
   def create
     authorize @staging_project, :update?
 
+    if params[:remove_exclusion] == '1'
```
[the remark this answers is not in the document]
Comment (danidoni) [reply src/api/app/controllers/staging/staged_requests_controller.rb]: Ok, I'll just check for parameter presence

**Comment by hennevogel** [comment]
Listen to codeclimate! ;-)

File: src/api/spec/controllers/staging/staged_requests_controller_spec.rb [hunk 4]
```diff
@@ -99,6 +99,65 @@
...
+    end
+
+    context 'when providing the remove exclusion parameter' do
+      context 'and not having any excluded request' do
+        before do
+          login user
+          post :create,
+               params: { staging_workflow_project: staging_workflow.project.name,
+                         staging_project_name: staging_project.name,
+                         remove_exclusion: true,
```
Comment (saraycp) [inline src/api/spec/controllers/staging/staged_requests_controller_spec.rb]: The same as before, `true`or `1`?

File: src/api/spec/controllers/staging/staged_requests_controller_spec.rb [hunk 5]
```diff
@@ -99,6 +99,65 @@
...
+
+        it { expect(response).to have_http_status(:success) }
+        it { expect(staging_project.packages.pluck(:name)).to match_array([target_package.name]) }
+        it { expect(staging_project.staged_requests).to include(bs_request) }
+        it { assert_select 'status[code=ok]' }
+      end
+    end
+
+    context 'when providing the remove exclusion parameter' do
+      context 'and not having any excluded request' do
```
Comment (saraycp) [inline src/api/spec/controllers/staging/staged_requests_controller_spec.rb]: What about merging this with the context in 122? We could have something like:

```
context 'when providing the remove exclusion parameter'
  context 'having any excluded request'
  context 'not having any excluded request'
```
And maybe try to share a single before block for both.

File: src/api/spec/controllers/staging/staged_requests_controller_spec.rb [hunk 6]
```diff
@@ -99,6 +99,65 @@
...
+        before do
+          create(:request_exclusion,
+                 bs_request: bs_request,
+                 number: bs_request.number,
+                 staging_workflow: staging_workflow)
+          login user
+          post :create,
+               params: { staging_workflow_project: staging_workflow.project.name,
+                         staging_project_name: staging_project.name,
+                         remove_exclusion: true,
```
Comment (saraycp) [inline src/api/spec/controllers/staging/staged_requests_controller_spec.rb]: I wonder if it's better to set '1' instead of 'true' :thinking:  All in all, '1' is the value in the query string.

File: src/api/spec/controllers/staging/staged_requests_controller_spec.rb (hunk 4 above)
Comment (danidoni) [reply src/api/spec/controllers/staging/staged_requests_controller_spec.rb]: @hennevogel and I discussed this yesterday and agreed on not caring what the content of the variable is as long as its "truthy", to be consistent with the rest of the API.

File: src/api/spec/controllers/staging/staged_requests_controller_spec.rb (hunk 5 above)
Comment (danidoni) [reply src/api/spec/controllers/staging/staged_requests_controller_spec.rb]: I'll look at it

Comment (danidoni) [reply src/api/spec/controllers/staging/staged_requests_controller_spec.rb]: Ah, I remember now. It will be a bit strange, if we show every context in the hierarchy we will have this:
```
context 'with an excluded request'
  context 'when providing the remove exclusion parameter'
    context 'and not having any excluded request'
```
To me its kind of strange having this excluded-but-not-excluded use case.
What do you think?

**Comment by danidoni** [comment]
[Allow to stage an excluded request in one step](https://trello.com/c/yXQcl7VA/1309-allow-to-stage-an-excluded-request-in-one-step)

File: src/api/spec/controllers/staging/staged_requests_controller_spec.rb (hunk 5 above)
Comment (saraycp) [reply src/api/spec/controllers/staging/staged_requests_controller_spec.rb]: Ok I understand it's more complex than I thought. What do you think of switching the last two contexts?

This remains the same
```
context 'with an excluded request'
  context 'when not providing the remove exclusion parameter'
  context 'when providing the remove exclusion parameter'
```

```
context 'without an excluded request'  # Before: context 'and not having any excluded request'
  context 'when providing the remove exclusion parameter' 
```

File: src/api/spec/controllers/staging/staged_requests_controller_spec.rb (hunk 4 above)
Comment (vpereira) [reply src/api/spec/controllers/staging/staged_requests_controller_spec.rb]: however as @saraycp say, consistence is the key. Everywhere else, AFAICR, we use 1. It is expected to have 1 here too.

File: src/api/spec/controllers/staging/staged_requests_controller_spec.rb (hunk 6 above)
Comment (danidoni) [reply src/api/spec/controllers/staging/staged_requests_controller_spec.rb]: As we talked offline, we are just checking parameter presence, so we don't really care what's inside that parameter

File: src/api/spec/controllers/staging/staged_requests_controller_spec.rb (hunk 4 above)
Comment (danidoni) [reply src/api/spec/controllers/staging/staged_requests_controller_spec.rb]: I'll use a `'1'` in the specs and documentation, but just check for parameter presence in the controller

File: src/api/spec/controllers/staging/staged_requests_controller_spec.rb (hunk 5 above)
Comment (danidoni) [reply src/api/spec/controllers/staging/staged_requests_controller_spec.rb]: We agreed offline to not switching the contexts

**Comment by danidoni** [comment]
> To be consistent, please change the parameter from true to 1.

Done

**Comment by danidoni** [comment]
> You are missing api documentation.

Added API Documentation

**Comment by danidoni** [comment]
@vpereira @hennevogel please review again

**Comment by vpereira** [comment]
> @vpereira @hennevogel please review again

Now would be nice if you could squash the commits. For example the specs related could  be squashed in one commit.

File: src/api/app/models/staging/staged_requests.rb [hunk 7]
```diff
@@ -81,6 +90,10 @@ def not_found_requests
     request_numbers - requests.pluck(:number).map(&:to_s)
   end
 
+  def excluded_requests
```
Comment (coolo) [inline src/api/app/models/staging/staged_requests.rb]: I find this a very unfortunate function name taking that it does not return requests, but strings of numbers. And I find it unfortunate to call such an expensive query in a loop - is this codeclimate speaking? :)

File: docs/api/api/api.txt [hunk 8]
```diff
@@ -2012,7 +2012,9 @@ GET /staging/<staging_workflow_project>/staging_projects/<staging_project>/stage
 XmlResult: staged_requests
 
 POST /staging/<staging_workflow_project>/staging_projects/<staging_project>/staged_requests
-  Add one or multiple bs_requests to the staged requests of a staging project.
+  Add one or multiple bs_requests to the staged requests of a staging project
+  remove_exclusion: If remove_exclusion is set (any value will work) it will allow the removal of the exclusions over a request before staging a request.
```
Comment (coolo) [inline docs/api/api/api.txt]: If I read the code right, a value of 0 will not 'work'. the api.txt is generally bad in giving valid values - so in line with other paragraphs in the same document I find: `remove_exclusion: removes the request from exclusion before staging` to be enough.

**Comment by danidoni** [comment]
> > @vpereira @hennevogel please review again
> 
> Now would be nice if you could squash the commits. For example the specs related could be squashed in one commit.

Of course!

File: src/api/app/models/staging/staged_requests.rb (hunk 7 above)
Comment (danidoni) [reply src/api/app/models/staging/staged_requests.rb]: You are right. On it

Comment (danidoni) [reply src/api/app/models/staging/staged_requests.rb]: Fixed, check it out, please.

File: docs/api/api/api.txt (hunk 8 above)
Comment (danidoni) [reply docs/api/api/api.txt]: If you put a '0' in it, it would behave as if you put a '1' in it. That's what I wanted to say with `any value will work`. But let's use your suggestion.

Comment (coolo) [reply docs/api/api/api.txt]: ah, I always forget that ruby is not perl :)

Comment (coolo) [reply docs/api/api/api.txt]:
```
~>perl -e 'my $a="0"; print "no\n" unless $a;'
no
```

**Comment by danidoni** [comment]
@coolo check it out again please

File: src/api/app/controllers/staging/staged_requests_controller.rb [hunk 9]
```diff
@@ -15,22 +15,27 @@ def index
...
-      render_ok
-    else
-      render_error(
-        status: 400,
-        errorcode: 'invalid_request',
-        message: "Assigning requests to #{@staging_project} failed: #{result.errors.to_sentence}."
-      )
-    end
+    render_ok
+  rescue Staging::ExcludedRequestNotFound => e
```
Comment (coolo) [inline src/api/app/controllers/staging/staged_requests_controller.rb]: this is all api, no? then better not use `StandardError` but ` APIError`, then you don't need to rescue at all. Just

```
class ExcludedRequestNotFound < APIError
   setup 'invalid_request'
end
```

And it will render a 400 - and if you throw it, you give it the message

Comment (vpereira) [reply src/api/app/controllers/staging/staged_requests_controller.rb]: and why you care here but not https://github.com/openSUSE/open-build-service/pull/8695 @coolo ? That's what I was suggesting - specially because the code there happens in `show` and `accept`

File: src/api/app/controllers/staging/staged_requests_controller.rb [hunk 10]
```diff
@@ -15,22 +15,27 @@ def index
...
+
+    ::Staging::StagedRequests.new(
       request_numbers: @request_numbers,
       staging_workflow: @staging_workflow,
       staging_project: @staging_project,
       user_login: User.session!.login
-    ).create
+    ).create!
 
-    if result.valid?
```
Comment (vpereira) [inline src/api/app/controllers/staging/staged_requests_controller.rb]: as the code was before, was perfect to be extracted to a service...

File: src/api/app/controllers/staging/staged_requests_controller.rb (hunk 9 above)
Comment (danidoni) [reply src/api/app/controllers/staging/staged_requests_controller.rb]: I've applied the changes @coolo suggested. I need to close this PR now. @victor, @coolo we can review error managing later in another issue.

**Comment by danidoni** [comment]
@coolo please, can you review it again?

File: src/api/app/models/staging/excluded_request_not_found.rb [hunk 11]
```diff
@@ -0,0 +1,9 @@
+class Staging::ExcludedRequestNotFound < APIError
+  attr_reader :message
```
Comment (coolo) [inline src/api/app/models/staging/excluded_request_not_found.rb]: you really don't need all that. APIError already brings that. Including the render_error if caught in application_controller. All you need to have is `setup 'invalid_request'` in the class.

File: src/api/app/controllers/staging/staged_requests_controller.rb (hunk 9 above)
Comment (victor) [reply src/api/app/controllers/staging/staged_requests_controller.rb]: please don’t mention-spam. Thanks

Comment (danidoni) [reply src/api/app/controllers/staging/staged_requests_controller.rb]: Oops sorry, my bad. I wanted to reach @vpereira

File: src/api/app/models/staging/excluded_request_not_found.rb (hunk 11 above)
Comment (vpereira) [reply src/api/app/models/staging/excluded_request_not_found.rb]: @coolo is that the change request or just a comment? Please help @danidoni to get this PR done.

Comment (coolo) [reply src/api/app/models/staging/excluded_request_not_found.rb]: Overriding initialize of APIError to is basically just making a StandardError again - and I said previously this is wrong.

Comment (danidoni) [reply src/api/app/models/staging/excluded_request_not_found.rb]: Done
