### PR TITLE
[webui][api] Fix delete request diff for packages

### LINKED ISSUE #5107: delete SRs show an incorrect error message
# Issue Description
See https://build.opensuse.org/request/show/610472 . This says "Project diff is not implemented". The message is incorrect, as the SR is about a package, not a project.

# Expected Result
Do not print any error message. Delete requests only have a trivial diff (all red lines) which does not need to be shown.

### PR DESCRIPTION
**Pull request by ChrisBr**
The if statements were completely messed up.
This got introduced by a refactoring in
214ba835ddcb6fc02a216dd3108c27c1ad12f724.

The DiffError should only raise if there is no
package and no repository (messed with the unless).
Also the guard clause should only return and empty
string if there is no target_package.
In case there is package, we can do a normal diff.

Fix #5107

### CODE REVIEW

File: src/api/app/models/bs_request_action_delete.rb [hunk 1]
```diff
@@ -41,8 +41,8 @@ def render_xml_attributes(node)
   end
 
   def sourcediff(opts = {})
-    raise DiffError, "Project diff isn't implemented yet" unless target_package && target_repository
-    return '' unless target_repository
+    raise DiffError, "Project diff isn't implemented yet" unless target_package || target_repository
+    return '' unless target_package
```
Comment (coolo) [inline src/api/app/models/bs_request_action_delete.rb]: without cassettes I have the prroblem in spec/models/bs_request_action/differ/for_source_spec.rb - is this related? If not, it would be good to have one more spec :)

```
     context 'with error' do
+      skip('NOVCR nothing was raised')
       it { expect { subject.perform }.to raise_error(BsRequestAction::DiffError) }
     end

Comment (ChrisBr) [reply src/api/app/models/bs_request_action_delete.rb]: No, this seems unrelated.

**Comment by DavidKang** [comment]
Why has the `total-coverage` decreased? In fact, it should be had increased, maybe rebasing with master could solve it? :thinking:

**Comment by ChrisBr** [comment]
> Why has the total-coverage decreased? In fact, it should be had increased. Maybe rebasing with master could solve it?

Seems to be broken ... @bgeuken is working on getting codecov working again
