### PR TITLE
Don't crash if the disturl is incomplete

### LINKED ISSUE #5510: [production][search#index] undefined method `start_with?' for nil:NilClass
search#index threw this 1 times
<pre>
undefined method `start_with?&#39; for nil:NilClass
</pre>
[https://build.opensuse.org/search?name=1&amp;package=1&amp;project=1](https://build.opensuse.org/search?name=1&amp;package=1&amp;project=1)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b58a73a4f520500063c6460)

### PR DESCRIPTION
**Pull request by coolo**
Fixes #5510

### CODE REVIEW

File: src/api/app/controllers/webui/search_controller.rb [hunk 1]
```diff
@@ -56,7 +56,7 @@ def search
       unless disturl_pkgrev.nil?
         disturl_rev, disturl_package = disturl_pkgrev.split('-', 2)
       end
-      if Package.exists_by_project_and_name(disturl_project, disturl_package, follow_multibuild: true)
+      if disturl_project.present? && disturl_package.present? && Package.exists_by_project_and_name(disturl_project, disturl_package, follow_multibuild: true)
```
Comment (bgeuken) [inline src/api/app/controllers/webui/search_controller.rb]: Looks like we need a disturl lib that parses such a dist url and returns a package object :thinking:

Comment (coolo) [reply src/api/app/controllers/webui/search_controller.rb]: better than moving more things into the package model :)

Comment (bgeuken) [reply src/api/app/controllers/webui/search_controller.rb]: That's why I said disturl lib :wink:
