### PR TITLE
[webui] Refactor package save_file

### LINKED ISSUE #1253: [production][webui/package#save_file] Suse::ValidationError: service validation error: Start tag expected, '<' not found
webui/package#save_file threw this 0 times
<pre>
Suse::ValidationError: service validation error: Start tag expected, &#39;&lt;&#39; not found
</pre>
[https://build.opensuse.org/package/save_file/home:scalpel4k/libmlt](https://build.opensuse.org/package/save_file/home:scalpel4k/libmlt)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5620fcd3764b23000c00000d)

### PR DESCRIPTION
**Pull request by ChrisBr**
* file is sometimes a UploadedFile object which is handled now
* catches ValidationExceptions and Exception
* some simplifications

This will fix #1253

### CODE REVIEW

File: src/api/app/controllers/webui/package_controller.rb [hunk 1]
```diff
@@ -645,82 +642,64 @@ def save_file
...
+        filename = file.original_filename if filename.blank?
         @package.save_file(file: file, filename: filename, :comment => params[:comment])
-      rescue Timeout::Error => e
-        if request.xhr?
-          render(json: { error: 'Timeout when saving file. Please try again.'}, status: 400)
-        else
-          redirect_to(:back, :error => 'Timeout when saving file. Please try again.')
+      elsif file_url.present?
+        # we have a remote file URI, so we have to download and save it
+        @services = Service.find(project: @project, package: @package.name)
```
Comment (mdeniz) [inline src/api/app/controllers/webui/package_controller.rb]: Use the proper method for that:
```
@services = @package.services
```

File: src/api/app/controllers/webui/package_controller.rb [hunk 2]
```diff
@@ -645,82 +642,64 @@ def save_file
...
+      errors << exception.message
+    rescue Timeout::Error => exception
+      errors << exception.message
+    rescue ActiveXML::Transport::Error => exception
+      errors << exception.message
+    rescue Exception => exception
+      # Package.verify_file! and Suse.validator are
+      # throwing exceptions (e.g. illegal filenames)
+      errors << exception.message
+    end
```
Comment (mdeniz) [inline src/api/app/controllers/webui/package_controller.rb]: I think that you can use this sintax for those cases:
```
rescue Suse::ValidationError, Timeout::Error, ActiveXML::Transport::Error, Exception => exception
```

File: src/api/app/controllers/webui/package_controller.rb [hunk 3]
```diff
@@ -645,82 +642,64 @@ def save_file
...
+
+    if errors.empty?
+      message = "The file '#{filename}' has been successfully saved."
```
Comment (mdeniz) [inline src/api/app/controllers/webui/package_controller.rb]: If you changed the message maybe some tests are broken ;)

File: src/api/app/models/package.rb [hunk 4]
```diff
@@ -1194,6 +1194,14 @@ def commit( rev = nil )
   end
 
   def self.verify_file!(pkg, name, content)
+    if name.blank?
```
Comment (mdeniz) [inline src/api/app/models/package.rb]: I like it more:
```
raise 'No file or URI given.' if name.blank?
```

File: src/api/app/models/package.rb [hunk 5]
```diff
@@ -1194,6 +1194,14 @@ def commit( rev = nil )
...
+     raise 'No file or URI given.'
+    end
+
+    if !name.present? && !name =~ %r{^[^\/]+$}
```
Comment (mdeniz) [inline src/api/app/models/package.rb]: Also here:
```
 raise "'#{name}' is not a valid filename." if !name.present? && !name =~ %r{^[^\/]+$}
```

File: src/api/app/models/package.rb [hunk 6]
```diff
@@ -1242,9 +1250,16 @@ def self.verify_file!(pkg, name, content)
   def save_file(opt = {})
     content = '' # touch an empty file first
     content = opt[:file] if opt[:file]
+
```
Comment (mdeniz) [inline src/api/app/models/package.rb]: Same here:
```
content = File.open(content.path).read if content.kind_of?(ActionDispatch::Http::UploadedFile)
```

File: src/api/app/controllers/webui/package_controller.rb [hunk 7]
```diff
@@ -645,82 +642,64 @@ def save_file
...
-        if request.xhr?
-          render(json: { error: e.summary }, status: 400)
-        else
-          redirect_to(:back, :error => e.summary)
+
+        # detects automatically git://, src.rpm formats
+        @services.addDownloadURL(file_url, filename)
+
+        unless @services.save
+          errors << "Failed to add file from URL '#{file_url}'"
```
Comment (mdeniz) [inline src/api/app/controllers/webui/package_controller.rb]: I would change it for:
```
errors << "Failed to add file from URL '#{file_url}'" unless @services.save
```

File: src/api/app/controllers/webui/package_controller.rb (hunk 1 above)
Comment (ChrisBr) [inline src/api/app/controllers/webui/package_controller.rb]: Ok

File: src/api/app/controllers/webui/package_controller.rb (hunk 2 above)
Comment (ChrisBr) [inline src/api/app/controllers/webui/package_controller.rb]: I'll try it!

File: src/api/app/controllers/webui/package_controller.rb (hunk 3 above)
Comment (ChrisBr) [inline src/api/app/controllers/webui/package_controller.rb]: I know! I'm currently refactoring the tests also ...

File: src/api/app/models/package.rb (hunk 6 above)
Comment (ChrisBr) [inline src/api/app/models/package.rb]: Moved it to ``verify_file!``! Only there it's causing issues because we call to_s on the UploadedFile object!

File: src/api/app/controllers/webui/package_controller.rb [hunk 8]
```diff
@@ -645,83 +642,57 @@ def save_file
...
-      return unless add_file_url(file_url, filename)
-    else
-      return unless add_file_filename(filename)
-    end
-    if request.xhr?
-      render(json: { status: 'ok' })
-    else
-      redirect_to({:action => :show, :project => @project, :package => @package}, :success => "The file #{filename} has been added.")
+
+    rescue APIException, StandardError => exception
```
Comment (ChrisBr) [inline src/api/app/controllers/webui/package_controller.rb]: With APIException & StandardError we can catch all possible exceptions (Suse::ValidationError is an APIException and  ActiveXML::Transport::Error is a StandardError etc.)

File: src/api/app/models/package.rb [hunk 9]
```diff
@@ -1194,6 +1194,12 @@ def commit( rev = nil )
   end
 
   def self.verify_file!(pkg, name, content)
+    raise IllegalFileName, "'#{name}' is not a valid filename" if (!name.present? || !(name =~ %r{^[^\/]+$}))
+
+    # file is an ActionDispatch::Http::UploadedFile and Suse::Validator.validate
+    # will call to_s therefore we have to read the content first
+    content = File.open(content.path).read if content.kind_of?(ActionDispatch::Http::UploadedFile)
```
Comment (ChrisBr) [inline src/api/app/models/package.rb]: Suse::Validator.validate calls to_s which fails is for a new file because it's an ActionDispatch::Http::UploadedFile object!

File: src/api/lib/opensuse/validator.rb [hunk 10]
```diff
@@ -91,12 +91,12 @@ def validate(opt, content)
         end
 
         if content.nil?
-          raise "illegal option; need content for #{schema_base_filename}"
+          raise "illegal option; need content for #{schema_file}"
```
Comment (ChrisBr) [inline src/api/lib/opensuse/validator.rb]: The full_path is not interesting for the user so changed it to schema_file!

File: src/api/lib/opensuse/validator.rb [hunk 11]
```diff
@@ -91,12 +91,12 @@ def validate(opt, content)
...
         end
         content = content.to_s
         if content.empty?
           logger.debug "no content, skipping validation for #{schema_file}"
-          raise ValidationError, "Document is empty, not allowed for #{schema_base_filename}"
+          raise ValidationError, "Document is empty, not allowed for #{schema_file}"
```
Comment (ChrisBr) [inline src/api/lib/opensuse/validator.rb]: The full_path is not interesting for the user so changed it to schema_file!

File: src/api/test/functional/webui/package_controller_test.rb [hunk 12]
```diff
@@ -346,10 +346,6 @@ def test_submit_package
     page.wont_have_field('supersede_request_ids[]')
   end
 
-  def test_save_file
```
Comment (ChrisBr) [inline src/api/test/functional/webui/package_controller_test.rb]: Covered in src/api/test/functional/webui/package_edit_source_test.rb

**Comment by ChrisBr** [comment]
@adrianschroeter & @mdeniz 

* fixed your suggestions
* fixed, refactored and added tests

Please review!

**Comment by mdeniz** [comment]
LGTM

**Comment by hennevogel** [comment]
:+1:
