### PR TITLE
Fix flickering cloud upload job

### LINKED ISSUE #4958: Cloud::Backend::UploadJob.all with a valid backend response with more than one upload job
From: https://travis-ci.org/openSUSE/open-build-service/jobs/374303333#L1339

```
Cloud::Backend::UploadJob.all with a valid backend response with more than one upload job 
Failure/Error: let(:another_upload_job) { create(:upload_job, user: user) }
     
     ActiveRecord::RecordInvalid:
       Validation failed: Job has already been taken
     # ./spec/models/cloud/backend/upload_job_spec.rb:194:in `block (5 levels) in <top (required)>'
     # ./spec/models/cloud/backend/upload_job_spec.rb:228:in `block (5 levels) in <top (required)>'
     # ./spec/models/cloud/backend/upload_job_spec.rb:231:in `block (5 levels) in <top (required)>'
     # ./spec/support/logging.rb:4:in `block (2 levels) in <top (required)>'
```

### PR DESCRIPTION
**Pull request by bgeuken**
Use a number generator with higher "randomness" to avoid
cloud jobs with duplicated job_id entries.
The job_id comes from the backend. So we can not use another
factory for this.

Fixes #4958

### CODE REVIEW

File: src/api/spec/factories/upload_job.rb [hunk 1]
```diff
@@ -1,6 +1,6 @@
 FactoryBot.define do
   factory :upload_job, class: Cloud::User::UploadJob do
     user
-    job_id { Faker::Number.between(100, 1000) }
+    job_id { rand(1_000_000_000) }
```
Comment (Ana06) [inline src/api/spec/factories/upload_job.rb]: can the `job_id` be 0? :thinking:  I think it should be fine...

Comment (bgeuken) [reply src/api/spec/factories/upload_job.rb]: It can^^ Might not make much sense, but it wouldn't break anything
