### PR TITLE
Do not fail when acknowledging twice

### LINKED ISSUE #9714: [production][status_messages#acknowledge] Validation failed: Status message You have already acknowledged the message
status_messages#acknowledge threw this 5 times
<pre>
Validation failed: Status message You have already acknowledged the message
</pre>
[https://build.opensuse.org/my/status_messages/440](https://build.opensuse.org/my/status_messages/440)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5edb21a30348cc0008d291ef)

### PR DESCRIPTION
**Pull request by danidoni**
Now an exception is raised when acknowledging an already acknowledged status message.

This PR makes OBS ignore a re-acknowledging. OBS will show an error to the user only when the failure is something else.

Fixes #9714

### CODE REVIEW

File: src/api/app/models/status_message.rb [hunk 1]
```diff
@@ -29,6 +29,16 @@ def delete
 
   def acknowledge!
     users << User.session!
```
Comment (krauselukas) [inline src/api/app/models/status_message.rb:31]:
```suggestion
unless users.include?(User.session!)
    users << User.session!
```

Comment (krauselukas) [reply src/api/app/models/status_message.rb:31]: Then you dont need the `elsif` in the controller

Comment (danidoni) [reply src/api/app/models/status_message.rb:31]: Yeah I already had this in consideration when thinking on the solution. The point is the code in the suggestion is checking the association against the database every time the user clicks on the `Got it` button. The code in the PR will only make the check against the association when we're not in the happy path.

But thanks anyway @krauselukas !

File: src/api/app/controllers/webui/status_messages_controller.rb [hunk 2]
```diff
@@ -35,7 +35,7 @@ def acknowledge
     status_message = StatusMessage.find(params[:id])
     if status_message.acknowledge!
       RabbitmqBus.send_to_bus('metrics', "user.acknowledged_status_message status_message_id=#{status_message.id}")
-    else
+    elsif !status_message.acknowledged?
       flash.now[:error] = "Could not accept status message: #{status_message.errors.full_messages.to_sentence}"
```
Comment (dmarcoux) [inline src/api/app/controllers/webui/status_messages_controller.rb:39]: The flash won't have any error message when `status_message.acknowledge!` is `false` due to a user already acknowledged. We could add an error to `status_message` so this would be addressed.

File: src/api/app/models/status_message.rb [hunk 3]
```diff
@@ -29,6 +29,16 @@ def delete
...
+  rescue ActiveRecord::RecordInvalid => e
+    return false if users.include?(User.session!)
```
Comment (dmarcoux) [inline src/api/app/models/status_message.rb:33]: This could be `return false if acknowledged?`

File: src/api/app/controllers/webui/status_messages_controller.rb (hunk 2 above)
Comment (dmarcoux) [reply src/api/app/controllers/webui/status_messages_controller.rb:39]: Oh wait, this won't happen because we're checking again if the status message is acknowledged.

File: src/api/app/models/status_message.rb (hunk 3 above)
Comment (danidoni) [reply src/api/app/models/status_message.rb:33]: Yes

File: src/api/app/models/status_message.rb (hunk 1 above)
Comment (vpereira) [reply src/api/app/models/status_message.rb:31]: I don't get it @danidoni , the user should click just once on the "Got it", so I don't see the issue with @krauselukas suggestion

Comment (danidoni) [reply src/api/app/models/status_message.rb:31]: Mmm you are both right, I got confused somehow. I'm addressing it now.

Comment (danidoni) [reply src/api/app/models/status_message.rb]: Check it out again, please!
