### PR TITLE
[webui] Show submit request ApiExceptions in flash

### LINKED ISSUE #1021: Packet submission to openSUSE:42:SLE12-Picks fails
Submitting a package to openSUSE:42:SLE12-Picks (via Web frontend) results in 'unable to submit' error messages.

The CLI is a bit more verbose:
docb@T520:~/buildservice/network:telephony> osc sr  -m 'hylafax' network:telephony/hylafax+ openSUSE:42:SLE12-Picks
Warning: failed to fetch meta data for 'openSUSE:42:SLE12-Picks' package 'hylafax+' (new package?) 
Server returned an error: HTTP Error 403: Forbidden
The target project openSUSE:42:SLE12-Picks is not accepting requests because: please submit to openSUSE:42 instead
docb@T520:~/buildservice/network:telephony> osc sr  -m 'hylafax' network:telephony/hylafax+ openSUSE:42
created request id 321802

The error message in the web frontend should be more verbose. Just a 'unable to submit' does not give enough information to solve the problem

### PR DESCRIPTION
**Pull request by ChrisBr**
fixes #1021

### CODE REVIEW

File: src/api/app/controllers/webui/package_controller.rb [hunk 1]
```diff
@@ -246,7 +246,7 @@ def submit_request_dialog
   end
 
   def submit_request
-    required_parameters :project, :package
+    required_parameters :project, :package, :targetproject
```
Comment (adrianschroeter) [inline src/api/app/controllers/webui/package_controller.rb]: The target project should still be optional, since it is by default the link target. Except when you fill this in the webui by default. Do you?

Small side note: There seems to be code missing in webui to change a submit request to a maintenance request, if the target is a maintenance_release project. osc is doing automatically so when it gets a "submit_request_rejected" error on creating the request, but the webui could be more clever since it has all the information by default.

This is more then you want to achieve with this patch, but we should IMHO not overwrite the automatic target detection in the api code.

Is something else broken when you do this without a targetproject? (on a linked package)

Comment (ChrisBr) [inline src/api/app/controllers/webui/package_controller.rb]: ``target_project_name = params[:targetproject].strip`` will raise a nil pointer exception so I assumed the ``:targetproject`` is mandatory! However, I'm fine with dropping this line for this PR and fix it in another PR later ...

Comment (bgeuken) [inline src/api/app/controllers/webui/package_controller.rb]: .try(:strip) should work

Comment (ChrisBr) [inline src/api/app/controllers/webui/package_controller.rb]: okay, will do it in another PR

**Comment by bgeuken** [comment]
LGTM :+1:
