### PR TITLE
Show an error message for statistics of a package of a scmsync project

### LINKED ISSUE #16855: [production][package#statistics] No route matches {:action=>"show", :arch=>"x86_64", :controller=>"webui/package", :format=>"html"...
[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/66e98c3284bf460be37f86fd)
# No route matches {:action=&gt;&quot;show&quot;, :arch=&gt;&quot;x86_64&quot;, :controller=&gt;&quot;webui/package&quot;, :format=&gt;&quot;html&quot;, :package=&gt;nil, :project=&gt;#&lt;Project id: 1053614, name: &quot;isv:Rancher:Elemental:Dev&quot;, title: &quot;Development area for Elemental project&quot;, description: &quot;Packages included here are meant to be based on la...&quot;, created_at: &quot;2022-10-04 13:54:11.000000000 +0000&quot;, updated_at: &quot;2024-09-17 13:19:43.948950000 +0000&quot;, remoteurl: nil, remoteproject: nil, develproject_id: nil, delta: true, kind: &quot;standard&quot;, url: &quot;https://github.com/rancher/elemental-obs/tree/dev&quot;, required_checks: [], staging_workflow_id: nil, scmsync: &quot;https://github.com/rancher/elemental-obs#dev&quot;, report_bug_url: nil&gt;, :repository=&gt;&quot;standardALP&quot;}, possible unmatched constraints: [:package]
Did you mean?  package_show_url #
### URL ###
[https://build.opensuse.org/package/statistics/isv:Rancher:Elemental:Dev/libisoburn/standardALP/x86_64](https://build.opensuse.org/package/statistics/isv:Rancher:Elemental:Dev/libisoburn/standardALP/x86_64)"
### Where ###
package#statistics

### Occured ###
Sep 17  2:03pm

### Similar ###
3

## Params ##
~~~
{
  &quot;action&quot; =&gt; &quot;statistics&quot;,
  &quot;arch&quot; =&gt; &quot;x86_64&quot;,
  &quot;controller&quot; =&gt; &quot;webui/package&quot;,
  &quot;format&quot; =&gt; &quot;html&quot;,
  &quot;package&quot; =&gt; &quot;libisoburn&quot;,
  &quot;project&quot; =&gt; &quot;isv:Rancher:Elemental:Dev&quot;,
  &quot;repository&quot; =&gt; &quot;standardALP&quot;
}
~~~

## Session ##
~~~
{}
~~~

## Backtrace ##
~~~
44:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/journey/formatter.rb -> **path**
824:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/route_set.rb -> **url_for**
271:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/route_set.rb -> **call**
327:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/route_set.rb -> **block in define_url_helper**
3:  app/views/webui/package/_tabs.html.haml -> **_app_views_webui_package__tabs_html_haml___4455341343407111009_111320**
244:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/base.rb -> **public_send**
244:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/base.rb -> **_run**
157:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/template.rb -> **block in render**
208:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **instrument**
361:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/template.rb -> **instrument_render_template**
155:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/template.rb -> **render**
251:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/partial_renderer.rb -> **block in render_partial_template**
206:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications/instrumenter.rb -> **instrument**
206:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **instrument**
246:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/partial_renderer.rb -> **render_partial_template**
237:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/partial_renderer.rb -> **render**
81:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/renderer.rb -> **render_partial_to_object**
27:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/renderer.rb -> **render_to_object**
22:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/renderer.rb -> **render**
37:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/helpers/rendering_helper.rb -> **block in render**
270:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/base.rb -> **in_rendering_context**
33:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/helpers/rendering_helper.rb -> **render**
5:  app/views/webui/package/statistics.html.haml -> **_app_views_webui_package_statistics_html_haml__4466454778355454375_156140**
244:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/base.rb -> **public_send**
244:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/base.rb -> **_run**
157:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/template.rb -> **block in render**
208:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **instrument**
361:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/template.rb -> **instrument_render_template**
155:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/template.rb -> **render**
65:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/template_renderer.rb -> **block (2 levels) in render_template**
206:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications/instrumenter.rb -> **instrument**
206:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **instrument**
60:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/template_renderer.rb -> **block in render_template**
75:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/template_renderer.rb -> **block in render_with_layout**
208:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **instrument**
74:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/template_renderer.rb -> **render_with_layout**
59:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/template_renderer.rb -> **render_template**
11:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/template_renderer.rb -> **render**
61:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/renderer.rb -> **render_template_to_object**
29:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/renderer.rb -> **render_to_object**
117:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/rendering.rb -> **block in _render_template**
270:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/base.rb -> **in_rendering_context**
116:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/rendering.rb -> **_render_template**
216:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/streaming.rb -> **_render_template**
103:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/rendering.rb -> **render_to_body**
158:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/rendering.rb -> **render_to_body**
141:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/renderers.rb -> **render_to_body**
27:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/abstract_controller/rendering.rb -> **render**
139:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/rendering.rb -> **render**
22:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/instrumentation.rb -> **block (2 levels) in render**
311:  /usr/lib64/ruby/3.1.0/benchmark.rb -> **realtime**
14:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/core_ext/benchmark.rb -> **ms**
22:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/instrumentation.rb -> **block in render**
91:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/instrumentation.rb -> **cleanup_view_runtime**
34:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/railties/controller_runtime.rb -> **cleanup_view_runtime**
21:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/instrumentation.rb -> **render**
35:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/implicit_render.rb -> **default_render**
7:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/basic_implicit_render.rb -> **send_action**
215:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/abstract_controller/base.rb -> **process_action**
165:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/rendering.rb -> **process_action**
234:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/abstract_controller/callbacks.rb -> **block in process_action**
107:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb -> **run_callbacks**
233:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/abstract_controller/callbacks.rb -> **process_action**
23:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/rescue.rb -> **process_action**
67:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/instrumentation.rb -> **block in process_action**
206:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications/instrumenter.rb -> **instrument**
206:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **instrument**
66:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/instrumentation.rb -> **process_action**
259:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/params_wrapper.rb -> **process_action**
27:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/railties/controller_runtime.rb -> **process_action**
151:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/abstract_controller/base.rb -> **process**
39:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/rendering.rb -> **process**
188:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal.rb -> **dispatch**
251:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal.rb -> **dispatch**
49:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/route_set.rb -> **dispatch**
32:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/route_set.rb -> **serve**
18:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/mapper.rb -> **block in &lt;class:Constraints&gt;**
48:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/mapper.rb -> **serve**
50:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/journey/router.rb -> **block in serve**
32:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/journey/router.rb -> **each**
32:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/journey/router.rb -> **serve**
852:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/route_set.rb -> **call**
87:  /GEM_ROOT/gems/flipper-1.3.1/lib/flipper/middleware/memoizer.rb -> **memoized_call**
45:  /GEM_ROOT/gems/flipper-1.3.1/lib/flipper/middleware/memoizer.rb -> **call**
15:  config/initializers/prefer_xml_over_html.rb -> **call**
44:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/deflater.rb -> **call**
15:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/tempfile_reaper.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/etag.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/conditional_get.rb -> **call**
12:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/head.rb -> **call**
38:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/http/permissions_policy.rb -> **call**
36:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/http/content_security_policy.rb -> **call**
266:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/session/abstract/id.rb -> **context**
260:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/session/abstract/id.rb -> **call**
704:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/cookies.rb -> **call**
27:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/callbacks.rb -> **block in call**
99:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb -> **run_callbacks**
26:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/callbacks.rb -> **call**
32:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call!**
21:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call**
28:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/debug_exceptions.rb -> **call**
29:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/show_exceptions.rb -> **call**
18:  /GEM_ROOT/gems/lograge-0.14.0/lib/lograge/rails_ext/rack/logger.rb -> **call_app**
25:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/rack/logger.rb -> **block in call**
99:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/tagged_logging.rb -> **block in tagged**
37:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/tagged_logging.rb -> **tagged**
99:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/tagged_logging.rb -> **tagged**
25:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/rack/logger.rb -> **call**
93:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/remote_ip.rb -> **call**
93:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/remote_ip.rb -> **call**
19:  /GEM_ROOT/gems/request_store-1.7.0/lib/request_store/middleware.rb -> **call**
26:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/request_id.rb -> **call**
24:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/method_override.rb -> **call**
22:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/runtime.rb -> **call**
29:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/cache/strategy/local_cache_middleware.rb -> **call**
14:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/executor.rb -> **call**
18:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/lock.rb -> **call**
110:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/sendfile.rb -> **call**
131:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/host_authorization.rb -> **call**
530:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/engine.rb -> **call**
226:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/railtie.rb -> **public_send**
226:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/railtie.rb -> **method_missing**
74:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/urlmap.rb -> **block in call**
58:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/urlmap.rb -> **each**
58:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/urlmap.rb -> **call**
107:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb -> **process_request**
149:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **accept_and_process_next_request**
110:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **main_loop**
419:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/request_handler.rb -> **block (3 levels) in start_threads**
113:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/utils.rb -> **block in create_thread_and_abort_on_exception**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| program_name | Passenger RubyApp: /srv/www/obs/api (production) |
| HTTP_USER_AGENT | Mozilla/5.0 (compatible; ImagesiftBot; +imagesift.com) |

### PR DESCRIPTION
**Pull request by eduardoj**
Avoid throwing a 500 error.

Fixes #16855.

Related to #16857.

### CODE REVIEW

File: src/api/spec/controllers/webui/package_controller_spec.rb [hunk 1]
```diff
@@ -388,6 +388,17 @@
 
       it { expect(assigns(:statistics)).to be_nil }
     end
+
+    context 'the project is a scmsync project' do
```
Comment (danidoni) [inline src/api/spec/controllers/webui/package_controller_spec.rb:392]:
```suggestion
    context 'the project is an scmsync project' do
```

Comment (eduardoj) [reply src/api/spec/controllers/webui/package_controller_spec.rb]: Fixed. Thanks!

**Review by danidoni — APPROVED** [review]
