### PR TITLE
Catch CodeRay exception for invalid language

### LINKED ISSUE #6960: [production][comments#create] Invalid id given: '%''{version}'```
comments#create threw this 5 times
<pre>
Invalid id given: &#39;%&#39;&#39;{version}&#39;```
</pre>
[https://build.opensuse.org/comments](https://build.opensuse.org/comments)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5c617bb695b37e00085b77e5)

### PR DESCRIPTION
**Pull request by hennevogel**
CodeRay throws an exception if you give it a language it doesn't find a plugin
for. Reported as rubychan/coderay#245

Fixes #6960

Co-authored-by: Dany Marcoux <dmarcoux@suse.com>

### CODE REVIEW

File: src/api/lib/obsapi/markdown_renderer.rb [hunk 1]
```diff
@@ -41,7 +41,9 @@ def link(link, title, content)
 
     def block_code(code, language)
       language ||= :plaintext
-      CodeRay.scan(code, language).div(css: :class)
+      CodeRay.scan(code, language).div
```
Comment (vpereira) [inline src/api/lib/obsapi/markdown_renderer.rb]: I'm assuming you are removing the `css: :class` because it's the default?

Comment (hennevogel) [reply src/api/lib/obsapi/markdown_renderer.rb]: yeah
