### PR TITLE
Deny access to binaries page if project is scmsync managed

### LINKED ISSUE #17684: [production][binaries#index] No route matches {:action=>"show", :controller=>"webui/package", :format=>"html", :package=>nil, ...
[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/67e222b884bf460beef95034)
# No route matches {:action=&gt;&quot;show&quot;, :controller=&gt;&quot;webui/package&quot;, :format=&gt;&quot;html&quot;, :package=&gt;nil, :package_name=&gt;&quot;lua-luassert&quot;, :project=&gt;#&lt;Project id: 435, name: &quot;devel:languages:lua&quot;, title: &quot;Lua is a powerful light-weight programming languag...&quot;, description: &quot;This is the development repository of the Lua prog...&quot;, created_at: &quot;2005-01-01 00:00:01.000000000 +0000&quot;, updated_at: &quot;2025-03-17 17:58:18.776265000 +0000&quot;, remoteurl: nil, remoteproject: nil, develproject_id: nil, delta: false, kind: &quot;standard&quot;, url: nil, required_checks: [], staging_workflow_id: nil, scmsync: &quot;https://src.opensuse.org/lua/_ObsPrj.git#master&quot;, report_bug_url: nil&gt;, :project_name=&gt;&quot;devel:languages:lua&quot;, :repository_name=&gt;&quot;openSUSE_Tumbleweed&quot;}, possible unmatched constraints: [:package]
Did you mean?  package_show_url #
### URL ###
[https://build.opensuse.org/projects/devel:languages:lua/packages/lua-luassert/repositories/openSUSE_Tumbleweed/binaries](https://build.opensuse.org/projects/devel:languages:lua/packages/lua-luassert/repositories/openSUSE_Tumbleweed/binaries)"
### Where ###
binaries#index

### Occured ###
Mar 25  3:27am

### Similar ###
60

## Params ##
~~~
{
  &quot;action&quot; =&gt; &quot;index&quot;,
  &quot;controller&quot; =&gt; &quot;webui/packages/binaries&quot;,
  &quot;package_name&quot; =&gt; &quot;lua-luassert&quot;,
  &quot;project_name&quot; =&gt; &quot;devel:languages:lua&quot;,
  &quot;repository_name&quot; =&gt; &quot;openSUSE_Tumbleweed&quot;
}
~~~

## Session ##
~~~
{}
~~~

## Backtrace ##
~~~
44:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/journey/formatter.rb -> **path**
824:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/route_set.rb -> **url_for**
271:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/route_set.rb -> **call**
327:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/route_set.rb -> **block in define_url_helper**
3:  app/views/webui/package/_tabs.html.haml -> **_app_views_webui_package__tabs_html_haml__2069105738346762534_116480**
244:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/base.rb -> **public_send**
244:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/base.rb -> **_run**
157:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/template.rb -> **block in render**
208:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **instrument**
361:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/template.rb -> **instrument_render_template**
155:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/template.rb -> **render**
251:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/partial_renderer.rb -> **block in render_partial_template**
206:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications/instrumenter.rb -> **instrument**
206:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **instrument**
246:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/partial_renderer.rb -> **render_partial_template**
237:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/partial_renderer.rb -> **render**
81:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/renderer.rb -> **render_partial_to_object**
27:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/renderer.rb -> **render_to_object**
22:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/renderer.rb -> **render**
37:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/helpers/rendering_helper.rb -> **block in render**
270:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/base.rb -> **in_rendering_context**
33:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/helpers/rendering_helper.rb -> **render**
4:  app/views/webui/packages/binaries/index.html.haml -> **_app_views_webui_packages_binaries_index_html_haml__1322241711075704729_179400**
244:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/base.rb -> **public_send**
244:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/base.rb -> **_run**
157:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/template.rb -> **block in render**
208:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **instrument**
361:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/template.rb -> **instrument_render_template**
155:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/template.rb -> **render**
65:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/template_renderer.rb -> **block (2 levels) in render_template**
206:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications/instrumenter.rb -> **instrument**
206:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **instrument**
60:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/template_renderer.rb -> **block in render_template**
75:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/template_renderer.rb -> **block in render_with_layout**
208:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **instrument**
74:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/template_renderer.rb -> **render_with_layout**
59:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/template_renderer.rb -> **render_template**
11:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/template_renderer.rb -> **render**
61:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/renderer.rb -> **render_template_to_object**
29:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/renderer.rb -> **render_to_object**
117:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/rendering.rb -> **block in _render_template**
270:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/base.rb -> **in_rendering_context**
116:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/rendering.rb -> **_render_template**
216:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/streaming.rb -> **_render_template**
103:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/rendering.rb -> **render_to_body**
158:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/rendering.rb -> **render_to_body**
141:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/renderers.rb -> **render_to_body**
27:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/abstract_controller/rendering.rb -> **render**
139:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/rendering.rb -> **render**
22:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/instrumentation.rb -> **block (2 levels) in render**
311:  /usr/lib64/ruby/3.1.0/benchmark.rb -> **realtime**
14:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/core_ext/benchmark.rb -> **ms**
22:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/instrumentation.rb -> **block in render**
91:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/instrumentation.rb -> **cleanup_view_runtime**
34:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/railties/controller_runtime.rb -> **cleanup_view_runtime**
21:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/instrumentation.rb -> **render**
35:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/implicit_render.rb -> **default_render**
7:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/basic_implicit_render.rb -> **send_action**
215:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/abstract_controller/base.rb -> **process_action**
165:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/rendering.rb -> **process_action**
234:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/abstract_controller/callbacks.rb -> **block in process_action**
107:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb -> **run_callbacks**
233:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/abstract_controller/callbacks.rb -> **process_action**
23:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/rescue.rb -> **process_action**
67:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/instrumentation.rb -> **block in process_action**
206:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications/instrumenter.rb -> **instrument**
206:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **instrument**
66:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/instrumentation.rb -> **process_action**
259:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/params_wrapper.rb -> **process_action**
27:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/railties/controller_runtime.rb -> **process_action**
151:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/abstract_controller/base.rb -> **process**
39:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/rendering.rb -> **process**
188:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal.rb -> **dispatch**
251:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal.rb -> **dispatch**
49:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/route_set.rb -> **dispatch**
32:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/route_set.rb -> **serve**
18:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/mapper.rb -> **block in &lt;class:Constraints&gt;**
48:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/mapper.rb -> **serve**
50:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/journey/router.rb -> **block in serve**
32:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/journey/router.rb -> **each**
32:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/journey/router.rb -> **serve**
852:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/route_set.rb -> **call**
87:  /GEM_ROOT/gems/flipper-1.3.4/lib/flipper/middleware/memoizer.rb -> **memoized_call**
45:  /GEM_ROOT/gems/flipper-1.3.4/lib/flipper/middleware/memoizer.rb -> **call**
15:  config/initializers/prefer_xml_over_html.rb -> **call**
44:  /GEM_ROOT/gems/rack-2.2.13/lib/rack/deflater.rb -> **call**
15:  /GEM_ROOT/gems/rack-2.2.13/lib/rack/tempfile_reaper.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.13/lib/rack/etag.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.13/lib/rack/conditional_get.rb -> **call**
12:  /GEM_ROOT/gems/rack-2.2.13/lib/rack/head.rb -> **call**
38:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/http/permissions_policy.rb -> **call**
36:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/http/content_security_policy.rb -> **call**
266:  /GEM_ROOT/gems/rack-2.2.13/lib/rack/session/abstract/id.rb -> **context**
260:  /GEM_ROOT/gems/rack-2.2.13/lib/rack/session/abstract/id.rb -> **call**
704:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/cookies.rb -> **call**
27:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/callbacks.rb -> **block in call**
99:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb -> **run_callbacks**
26:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/callbacks.rb -> **call**
32:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call!**
21:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call**
28:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/debug_exceptions.rb -> **call**
29:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/show_exceptions.rb -> **call**
18:  /GEM_ROOT/gems/lograge-0.14.0/lib/lograge/rails_ext/rack/logger.rb -> **call_app**
25:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/rack/logger.rb -> **block in call**
99:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/tagged_logging.rb -> **block in tagged**
37:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/tagged_logging.rb -> **tagged**
99:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/tagged_logging.rb -> **tagged**
25:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/rack/logger.rb -> **call**
93:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/remote_ip.rb -> **call**
93:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/remote_ip.rb -> **call**
19:  /GEM_ROOT/gems/request_store-1.7.0/lib/request_store/middleware.rb -> **call**
26:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/request_id.rb -> **call**
24:  /GEM_ROOT/gems/rack-2.2.13/lib/rack/method_override.rb -> **call**
22:  /GEM_ROOT/gems/rack-2.2.13/lib/rack/runtime.rb -> **call**
29:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/cache/strategy/local_cache_middleware.rb -> **call**
14:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/executor.rb -> **call**
18:  /GEM_ROOT/gems/rack-2.2.13/lib/rack/lock.rb -> **call**
110:  /GEM_ROOT/gems/rack-2.2.13/lib/rack/sendfile.rb -> **call**
131:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/host_authorization.rb -> **call**
530:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/engine.rb -> **call**
226:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/railtie.rb -> **public_send**
226:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/railtie.rb -> **method_missing**
74:  /GEM_ROOT/gems/rack-2.2.13/lib/rack/urlmap.rb -> **block in call**
58:  /GEM_ROOT/gems/rack-2.2.13/lib/rack/urlmap.rb -> **each**
58:  /GEM_ROOT/gems/rack-2.2.13/lib/rack/urlmap.rb -> **call**
107:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb -> **process_request**
149:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **accept_and_process_next_request**
110:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **main_loop**
419:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/request_handler.rb -> **block (3 levels) in start_threads**
113:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/utils.rb -> **block in create_thread_and_abort_on_exception**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| program_name | Passenger RubyApp: /srv/www/obs/api (production) |
| HTTP_USER_AGENT | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 |

### PR DESCRIPTION
**Pull request by danidoni**
It makes no sense to access the page given we have no local packages and the page will break left and right.

We just block the access to the binaries with an error and redirect to the project index.

Fixes #17684

### CODE REVIEW

File: src/api/app/controllers/webui/packages/binaries_controller.rb [hunk 1]
```diff
@@ -13,6 +14,7 @@ class BinariesController < Webui::WebuiController
       before_action :require_login, except: [:index]
       before_action :set_project
       before_action :set_package
+      before_action :check_scmsync
```
Comment (eduardoj) [inline src/api/app/controllers/webui/packages/binaries_controller.rb]:
```suggestion
      before_action :check_scmsync
      before_action :set_package
```

We could check for a scmsync project right after setting the project. I don't think it's necessary to set the package.

Comment (danidoni) [reply src/api/app/controllers/webui/packages/binaries_controller.rb]: Right, good catch

**Comment by danidoni** [comment]
It probably makes no sense at all to let users access the rest of the tabs either if the project is scmsync managed... But that's for another collection of PR's

**Review by eduardoj — APPROVED** [review]
