### PR TITLE
Skip before_destroy of repository when we destroy a project

### LINKED ISSUE #3735: Project delete may modify project meta in backend before delete
Issue/Feature description
====================

Project restore may not restore the exact same project meta, if a repository builds against the same project. The restored project will point to "deleted" repository instead.

Expected result
============

Restore the same project meta, which existed when the project delete was executed..

How to Reproduce
===============
1. Create project A with repo B and C
2. Repo B need to have repo C in path
3. delete and undelete project.

Further information
===============
* This is caused by automatic store in Repository model, leading to a project meta PUT before DELETE operation

Example (The repository `home_Admin_project_abc_openSUSE_Leap_15.0` will be gone after `undelete`:
issue

### PR DESCRIPTION
**Pull request by DavidKang**
When we destroy a project we run the `before_action`
`cleanup_before_destroy`  from the project and also from the
repositories. Now when we destroy a project we skip the `before_action`
of the repositories.

Fix #3735

### CODE REVIEW

File: src/api/app/models/path_element.rb [hunk 1]
```diff
@@ -1,7 +1,9 @@
 class PathElement < ApplicationRecord
+  # FIXME: This should be called parent
```
Comment (Ana06) [inline src/api/app/models/path_element.rb]: how are this FIXME related with the commit? :confused:

File: src/api/app/models/project.rb [hunk 2]
```diff
@@ -332,31 +334,31 @@ def cleanup_linking_projects
...
   def cleanup_linking_targets
     # replace links to this projects with links to the "deleted" project
-    find_repos(:linking_target_repositories) do |link_rep|
-      link_rep.release_targets.includes(:target_repository).each do |rt|
-        next unless Repository.find(rt.repository_id).db_project_id == id
-        rt.target_repository = Repository.deleted_instance
-        rt.save
+    find_repos(:linking_target_repositories) do |linking_target_repository|
+      linking_target_repository.release_targets.includes(:target_repository).each do |release_target|
+        next unless release_target.link.db_project_id == id
```
Comment (Ana06) [inline src/api/app/models/project.rb]: N+1 queries! :see_no_evil: (before as well, but now it is easier to fix....
you could even to this filtering in an SQL query in the previous line :bulb:

File: src/api/app/models/repository.rb [hunk 3]
```diff
@@ -150,6 +150,7 @@ def cycles(arch)
   # or empty list
   def linking_repositories
     return [] if links.size.zero?
+    # FIXME: This is the same as using a `has_many through:` association
```
Comment (Ana06) [inline src/api/app/models/repository.rb]: [nitpick] not exactly... this returns an array...  but yes... it shouldn't be like that

Comment (dmarcoux) [reply src/api/app/models/repository.rb]: It's mostly to help us in the future (to hopefully refactor this)

File: src/api/app/models/path_element.rb (hunk 1 above)
Comment (dmarcoux) [reply src/api/app/models/path_element.rb]: It's mostly to help us in the future (to hopefully refactor this).

File: src/api/app/models/project.rb (hunk 2 above)
Comment (dmarcoux) [reply src/api/app/models/project.rb]: True about the N+1... we spent so much time digging and debugging while trying to understand this whole process, we didn't see it.

**Comment by DavidKang** [comment]
@Ana06, @dmarcoux, could you review it again, please? :smile_cat:

**Comment by dmarcoux** [comment]
I just had a look, it works. What did we forget before?

**Comment by hennevogel** [comment]
@adrianschroeter can you have a look at the new test case?

File: src/api/app/models/repository.rb (hunk 3 above)
Comment (Ana06) [reply src/api/app/models/repository.rb]: That is fine, but the comment could be more accurate :rofl: it is just a nitpick

File: src/api/app/models/path_element.rb (hunk 1 above)
Comment (Ana06) [reply src/api/app/models/path_element.rb]: That's fine, bit it is not related with the commit. IMO it should be in a different one, let's say it is a nitpick....

**Comment by DavidKang** [comment]
@Ana06, the commit already has a description but I forget to add the issue :disappointed:

File: src/api/app/models/path_element.rb (hunk 1 above)
Comment (bgeuken) [reply src/api/app/models/path_element.rb]: It doesn't look like changing this would require a migration. So I would prefer to change the names instead of adding a fixme that will stay there forever.
And if there isn't time for this, let's open an issue. Maybe someone else wants to jump in.

File: src/api/app/models/repository.rb (hunk 3 above)
Comment (bgeuken) [reply src/api/app/models/repository.rb]: Please just change this. We only use this at [one](https://github.com/openSUSE/open-build-service/search?q=linking_repositories&unscoped_q=linking_repositories). So this shouldn't take much time.

File: src/api/app/models/repository.rb [hunk 4]
```diff
@@ -164,6 +165,7 @@ def is_local_channel?
 
   def linking_target_repositories
     return [] if targetlinks.size.zero?
+    # FIXME: This is the same as using a `has_many through:` association
```
Comment (bgeuken) [inline src/api/app/models/repository.rb]: same here

File: src/api/app/models/project.rb [hunk 5]
```diff
@@ -332,31 +334,31 @@ def cleanup_linking_projects
...
   def cleanup_linking_targets
     # replace links to this projects with links to the "deleted" project
-    find_repos(:linking_target_repositories) do |link_rep|
-      link_rep.release_targets.includes(:target_repository).each do |rt|
-        next unless Repository.find(rt.repository_id).db_project_id == id
-        rt.target_repository = Repository.deleted_instance
-        rt.save
+    find_repos(:linking_target_repositories) do |linking_target_repository|
+      linking_target_repository.release_targets.includes(:target_repository, :link).each do |release_target|
+        next unless release_target.link.db_project_id == id
```
Comment (bgeuken) [inline src/api/app/models/project.rb]: I think you could use a join here... Though I didn't check how much impact that would make here.

Comment (Ana06) [reply src/api/app/models/project.rb]: a join? :confused:
