### PR TITLE
Avoid double encoding parameters to the backend

### LINKED ISSUE #7866: Wiping binaries from multibuild flavors redirects to wrong flavor
Go to binaries list of Package:Flavor, wipe for one architecture and you'll get redirected to the binaries list of Package with a flash saying binaries for architecture X were wiped.

I almost got an heart attack seeing no binaries left - before I noticed it's the wrong package/flavor I'm looking at.

### LINKED ISSUE #12913: Can't wipe binaries of multibuild flavors in the webui
https://build.opensuse.org/package/binaries/home:coolo:alp/libappindicator:gtk2/standard got a "Delete Binaries" icon (for me obviously, most others not) but I click it, I end up on 
https://build.opensuse.org/package/binaries/home:coolo:alp/libappindicator/standard with an error flash saying "Error while triggering wipe binaries for home:coolo:alp/libappindicator: unknown package: libappindicator%3Agtk2 404 unknown package: libappindicator%3Agtk2 ."

### PR DESCRIPTION
**Pull request by hellcp-work**
Fixes #12913 and fixes #7866 and some other issues with multibuild packages, by not double encoding the parameters. The backend received `package%3Amultibuild` instead of `package:multibuild`, which meant it didn't know what package the frontend was referring to.

### CODE REVIEW

File: src/api/app/models/package.rb [hunk 1]
```diff
@@ -1268,15 +1268,45 @@ def rebuild(params)
   end
 
   def wipe_binaries(params)
-    backend_build_command(:wipe, params[:project], params.slice(:package, :arch, :repository))
+    begin
+      Project.find_by(name: params[:project]).check_write_access!
```
Comment (hennevogel) [inline src/api/app/models/package.rb:1272]: We don't do this in this API anywhere...

File: src/api/app/models/package.rb [hunk 2]
```diff
@@ -1268,15 +1268,27 @@ def rebuild(params)
   end
 
   def wipe_binaries(params)
-    backend_build_command(:wipe, params[:project], params.slice(:package, :arch, :repository))
+    begin
```
Comment (hennevogel) [inline src/api/app/models/package.rb:1271]: Those methods sound like a useless abstraction to me....

Comment (hennevogel) [reply src/api/app/models/package.rb]: Indeed. It's controller code inside a model...

**Review by hennevogel — APPROVED** [review]
