### PR TITLE
Prevent the linktobranch command to work when there is no @package

### LINKED ISSUE #17305: [production][source#package_command] undefined method `project' for nil:NilClass

    Backend::Connection.post "/source/#{@package.pro...
[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/67944c1284bf460beb3766a2)
# undefined method `project&#39; for nil:NilClass

    Backend::Connection.post &quot;/source/#{@package.project.name}/#{@package.name}?cmd=linktobranch&amp;user=#{CGI.escape(params[:user])}#{rev}#{linkrev}&quot;
                                                ^^^^^^^^ #
### URL ###
[https://api.opensuse.org/source/server:Kolab:16.2/_pattern?cmd=linktobranch](https://api.opensuse.org/source/server:Kolab:16.2/_pattern?cmd=linktobranch)"
### Where ###
source#package_command

### Occured ###
Jan 25  2:27am

### Similar ###
10

## Params ##
~~~
{
  &quot;action&quot; =&gt; &quot;package_command&quot;,
  &quot;cmd&quot; =&gt; &quot;linktobranch&quot;,
  &quot;controller&quot; =&gt; &quot;source&quot;,
  &quot;package&quot; =&gt; &quot;_pattern&quot;,
  &quot;project&quot; =&gt; &quot;server:Kolab:16.2&quot;
}
~~~

## Session ##
~~~
{}
~~~

## Backtrace ##
~~~
1079:  app/controllers/source_controller.rb -> **package_command_linktobranch**
206:  app/controllers/application_controller.rb -> **dispatch_command**
157:  app/controllers/source_controller.rb -> **package_command**
6:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/basic_implicit_render.rb -> **send_action**
215:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/abstract_controller/base.rb -> **process_action**
165:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/rendering.rb -> **process_action**
234:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/abstract_controller/callbacks.rb -> **block in process_action**
107:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb -> **run_callbacks**
233:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/abstract_controller/callbacks.rb -> **process_action**
23:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/rescue.rb -> **process_action**
67:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/instrumentation.rb -> **block in process_action**
206:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications/instrumenter.rb -> **instrument**
206:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **instrument**
66:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/instrumentation.rb -> **process_action**
259:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/params_wrapper.rb -> **process_action**
27:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/railties/controller_runtime.rb -> **process_action**
151:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/abstract_controller/base.rb -> **process**
39:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/rendering.rb -> **process**
188:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal.rb -> **dispatch**
251:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal.rb -> **dispatch**
49:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/route_set.rb -> **dispatch**
32:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/route_set.rb -> **serve**
50:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/journey/router.rb -> **block in serve**
32:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/journey/router.rb -> **each**
32:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/journey/router.rb -> **serve**
852:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/route_set.rb -> **call**
87:  /GEM_ROOT/gems/flipper-1.3.2/lib/flipper/middleware/memoizer.rb -> **memoized_call**
45:  /GEM_ROOT/gems/flipper-1.3.2/lib/flipper/middleware/memoizer.rb -> **call**
15:  config/initializers/prefer_xml_over_html.rb -> **call**
44:  /GEM_ROOT/gems/rack-2.2.10/lib/rack/deflater.rb -> **call**
15:  /GEM_ROOT/gems/rack-2.2.10/lib/rack/tempfile_reaper.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.10/lib/rack/etag.rb -> **call**
40:  /GEM_ROOT/gems/rack-2.2.10/lib/rack/conditional_get.rb -> **call**
12:  /GEM_ROOT/gems/rack-2.2.10/lib/rack/head.rb -> **call**
38:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/http/permissions_policy.rb -> **call**
36:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/http/content_security_policy.rb -> **call**
266:  /GEM_ROOT/gems/rack-2.2.10/lib/rack/session/abstract/id.rb -> **context**
260:  /GEM_ROOT/gems/rack-2.2.10/lib/rack/session/abstract/id.rb -> **call**
704:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/cookies.rb -> **call**
27:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/callbacks.rb -> **block in call**
99:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb -> **run_callbacks**
26:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/callbacks.rb -> **call**
32:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call!**
21:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call**
28:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/debug_exceptions.rb -> **call**
29:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/show_exceptions.rb -> **call**
18:  /GEM_ROOT/gems/lograge-0.14.0/lib/lograge/rails_ext/rack/logger.rb -> **call_app**
25:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/rack/logger.rb -> **block in call**
99:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/tagged_logging.rb -> **block in tagged**
37:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/tagged_logging.rb -> **tagged**
99:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/tagged_logging.rb -> **tagged**
25:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/rack/logger.rb -> **call**
93:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/remote_ip.rb -> **call**
93:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/remote_ip.rb -> **call**
19:  /GEM_ROOT/gems/request_store-1.7.0/lib/request_store/middleware.rb -> **call**
26:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/request_id.rb -> **call**
24:  /GEM_ROOT/gems/rack-2.2.10/lib/rack/method_override.rb -> **call**
22:  /GEM_ROOT/gems/rack-2.2.10/lib/rack/runtime.rb -> **call**
29:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/cache/strategy/local_cache_middleware.rb -> **call**
14:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/executor.rb -> **call**
18:  /GEM_ROOT/gems/rack-2.2.10/lib/rack/lock.rb -> **call**
110:  /GEM_ROOT/gems/rack-2.2.10/lib/rack/sendfile.rb -> **call**
131:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/host_authorization.rb -> **call**
530:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/engine.rb -> **call**
226:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/railtie.rb -> **public_send**
226:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/railtie.rb -> **method_missing**
74:  /GEM_ROOT/gems/rack-2.2.10/lib/rack/urlmap.rb -> **block in call**
58:  /GEM_ROOT/gems/rack-2.2.10/lib/rack/urlmap.rb -> **each**
58:  /GEM_ROOT/gems/rack-2.2.10/lib/rack/urlmap.rb -> **call**
107:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb -> **process_request**
157:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **accept_and_process_next_request**
110:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **main_loop**
419:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/request_handler.rb -> **block (3 levels) in start_threads**
113:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/utils.rb -> **block in create_thread_and_abort_on_exception**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| program_name | Passenger RubyApp: /srv/www/obs/api (production) |
| HTTP_USER_AGENT | osc/1.11.1 |

### PR DESCRIPTION
**Pull request by danidoni**
When the package name is `_pattern` the code does not set the `@package` variable. So we need to avoid calling the command if we have no package to work on.

Fixes #17305

### CODE REVIEW

File: src/api/app/controllers/source_controller.rb [hunk 1]
```diff
@@ -1068,6 +1068,10 @@ def package_command_deleteuploadrev
 
   # POST /source/<project>/<package>?cmd=linktobranch
   def package_command_linktobranch
+    if @package.nil?
```
Comment (hennevogel) [inline src/api/app/controllers/source_controller.rb:1071]: This should rather be done wherever `@package` is set right?

Comment (danidoni) [reply src/api/app/controllers/source_controller.rb:1071]: The package is set here https://github.com/openSUSE/open-build-service/blob/5396dff38018284d5be6963b9c32c1201260046a/src/api/app/controllers/source_controller.rb#L537 and there is a specific ban for `_pattern`, so...

Comment (hennevogel) [reply src/api/app/controllers/source_controller.rb:1071]: You will have to connect this somehow or no one after you will understand this `if`...

Comment (danidoni) [reply src/api/app/controllers/source_controller.rb]: I think I made it more explicit, please check it out again.

File: src/api/app/controllers/source_controller.rb [hunk 2]
```diff
@@ -1068,6 +1068,10 @@ def package_command_deleteuploadrev
 
   # POST /source/<project>/<package>?cmd=linktobranch
   def package_command_linktobranch
+    if @target_package_name.in?(%w[_project _pattern])
+      render_error status: 400, message: 'package is not a link'
```
Comment (hennevogel) [inline src/api/app/controllers/source_controller.rb:1072]:
```suggestion
      render_error status: 400, message: "can not link or branch a #{@target_package_name} package"
```

File: src/api/spec/controllers/source_controller_spec.rb [hunk 3]
```diff
@@ -207,4 +207,34 @@
       it { expect(response).to have_http_status(:ok) }
     end
   end
+
+  describe 'POST #linktobranch' do
```
Comment (hennevogel) [inline src/api/spec/controllers/source_controller_spec.rb:211]: You are testing `if`...

Comment (danidoni) [reply src/api/spec/controllers/source_controller_spec.rb:211]: Now, yes. Initially I didn't know... But you are right, I can remove that test.

**Review by ncounter — APPROVED** [review]
