### PR TITLE
Record unsupported webhook event errors in the workflow

### LINKED ISSUE #13849: [production][trigger_workflow#create] undefined method `payload' for nil:NilClass

    raise Token::Errors::MissingPayload, 'A payload ...
[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/633e39aa84bf46052743f21c)
# undefined method `payload&#39; for nil:NilClass

    raise Token::Errors::MissingPayload, &#39;A payload is required&#39; if @scm_webhook.payload.blank?
                                                                                ^^^^^^^^ #
### URL ###
[https://api.opensuse.org/trigger/runservice](https://api.opensuse.org/trigger/runservice)"
### Where ###
trigger#create

### Occured ###
Oct 06  2:12am

### Similar ###
5

## Params ##
~~~
{
  &quot;action&quot; =&gt; &quot;create&quot;,
  &quot;controller&quot; =&gt; &quot;trigger&quot;
}
~~~

## Session ##
~~~
{}
~~~

## Backtrace ##
~~~
25:  app/models/token/workflow.rb -> **call**
34:  app/controllers/trigger_controller.rb -> **block in create**
887:  app/models/user.rb -> **run_as**
31:  app/controllers/trigger_controller.rb -> **create**
6:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal/basic_implicit_render.rb -> **send_action**
228:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/abstract_controller/base.rb -> **process_action**
30:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal/rendering.rb -> **process_action**
42:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/abstract_controller/callbacks.rb -> **block in process_action**
106:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **run_callbacks**
41:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/abstract_controller/callbacks.rb -> **process_action**
22:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal/rescue.rb -> **process_action**
34:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal/instrumentation.rb -> **block in process_action**
203:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/notifications/instrumenter.rb -> **instrument**
203:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/notifications.rb -> **instrument**
33:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal/instrumentation.rb -> **process_action**
249:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal/params_wrapper.rb -> **process_action**
27:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/railties/controller_runtime.rb -> **process_action**
165:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/abstract_controller/base.rb -> **process**
39:  /GEM_ROOT/gems/actionview-6.1.5.1/lib/action_view/rendering.rb -> **process**
190:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal.rb -> **dispatch**
254:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal.rb -> **dispatch**
50:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/routing/route_set.rb -> **dispatch**
33:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/routing/route_set.rb -> **serve**
19:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/routing/mapper.rb -> **block in &lt;class:Constraints&gt;**
49:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/routing/mapper.rb -> **serve**
50:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/journey/router.rb -> **block in serve**
32:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/journey/router.rb -> **each**
32:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/journey/router.rb -> **serve**
842:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/routing/route_set.rb -> **call**
72:  /GEM_ROOT/gems/flipper-0.25.2/lib/flipper/middleware/memoizer.rb -> **memoized_call**
37:  /GEM_ROOT/gems/flipper-0.25.2/lib/flipper/middleware/memoizer.rb -> **call**
15:  config/initializers/prefer_xml_over_html.rb -> **call**
44:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/deflater.rb -> **call**
15:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/tempfile_reaper.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/etag.rb -> **call**
40:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/conditional_get.rb -> **call**
12:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/head.rb -> **call**
22:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/http/permissions_policy.rb -> **call**
19:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/http/content_security_policy.rb -> **call**
266:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/session/abstract/id.rb -> **context**
260:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/session/abstract/id.rb -> **call**
689:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/cookies.rb -> **call**
27:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/callbacks.rb -> **block in call**
98:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **run_callbacks**
26:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/callbacks.rb -> **call**
18:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/actionable_exceptions.rb -> **call**
32:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call!**
21:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call**
29:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/debug_exceptions.rb -> **call**
33:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/show_exceptions.rb -> **call**
18:  /GEM_ROOT/gems/lograge-0.12.0/lib/lograge/rails_ext/rack/logger.rb -> **call_app**
26:  /GEM_ROOT/gems/railties-6.1.5.1/lib/rails/rack/logger.rb -> **block in call**
99:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/tagged_logging.rb -> **block in tagged**
37:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/tagged_logging.rb -> **tagged**
99:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/tagged_logging.rb -> **tagged**
26:  /GEM_ROOT/gems/railties-6.1.5.1/lib/rails/rack/logger.rb -> **call**
81:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/remote_ip.rb -> **call**
81:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/remote_ip.rb -> **call**
19:  /GEM_ROOT/gems/request_store-1.5.1/lib/request_store/middleware.rb -> **call**
26:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/request_id.rb -> **call**
24:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/method_override.rb -> **call**
22:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/runtime.rb -> **call**
29:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/cache/strategy/local_cache_middleware.rb -> **call**
14:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/executor.rb -> **call**
18:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/lock.rb -> **call**
110:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/sendfile.rb -> **call**
142:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/host_authorization.rb -> **call**
539:  /GEM_ROOT/gems/railties-6.1.5.1/lib/rails/engine.rb -> **call**
207:  /GEM_ROOT/gems/railties-6.1.5.1/lib/rails/railtie.rb -> **public_send**
207:  /GEM_ROOT/gems/railties-6.1.5.1/lib/rails/railtie.rb -> **method_missing**
74:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/urlmap.rb -> **block in call**
58:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/urlmap.rb -> **each**
58:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/urlmap.rb -> **call**
107:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb -> **process_request**
157:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **accept_and_process_next_request**
110:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **main_loop**
419:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/request_handler.rb -> **block (3 levels) in start_threads**
113:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/utils.rb -> **block in create_thread_and_abort_on_exception**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| program_name | Passenger RubyApp: /srv/www/obs/api (production) |
| HTTP_USER_AGENT | Python-urllib/3.6 |

### PR DESCRIPTION
**Pull request by danidoni**
When we receive events we don't have mapped in the [Scm Payload Extractor map](https://github.com/openSUSE/open-build-service/blob/0134d09bb1a2ef85a37763ab760888aa396a9a44/src/api/app/services/trigger_controller_service/scm_extractor.rb#L3) (for example, a [new branch gets created](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#create)), we end up having no payload extractor (receiving Nil [here](https://github.com/openSUSE/open-build-service/blob/0134d09bb1a2ef85a37763ab760888aa396a9a44/src/api/app/services/trigger_controller_service/scm_extractor.rb#L28)). This nil bubbles up [to the controller](https://github.com/openSUSE/open-build-service/blob/0134d09bb1a2ef85a37763ab760888aa396a9a44/src/api/app/controllers/trigger_workflow_controller.rb#L13) and crashes inside the [Token Workflow](https://github.com/openSUSE/open-build-service/blob/0134d09bb1a2ef85a37763ab760888aa396a9a44/src/api/app/models/token/workflow.rb#L29).

This PR adds a new validation to notify the user is using an unsupported event. 

Fixes #13849

### CODE REVIEW

**Review by krauselukas — COMMENTED** [review]
@danidoni wouldn't it be enough to add the case of receiving `nil` here in this line? https://github.com/openSUSE/open-build-service/blob/0134d09bb1a2ef85a37763ab760888aa396a9a44/src/api/app/controllers/trigger_workflow_controller.rb#L86 I think we can simply ignore unsupported events, since there is nothing we can do about it.

**Comment by krauselukas** [comment]
> > @danidoni wouldn't it be enough to add the case of receiving `nil` here in this line?
> > https://github.com/openSUSE/open-build-service/blob/0134d09bb1a2ef85a37763ab760888aa396a9a44/src/api/app/controllers/trigger_workflow_controller.rb#L86
> > 
> > I think we can simply ignore unsupported events, since there is nothing we can do about it.
> 
> I thought about that and as a user I would be puzzled by an integration that does not fail but does nothing. So I went and implemented the validation error to help users figure out what's going on.

I'm just not sure if its good to have a lot of workflow runs marked as failed for events that are not supported and also not mentioned in the documentation. I assume that most of them come from not setting specific events on the webhook, so simply everything is send. But I dont want to block this, its simply another way of dealing with the same problem. Will have a look on the code

File: src/api/app/services/trigger_controller_service/scm_extractor.rb [hunk 1]
```diff
@@ -16,19 +18,30 @@ class SCMExtractor
       }
     }.freeze
 
+    # FIXME: This is a factory
     def initialize(scm, event, webhook_payload)
-      # TODO: What should we do when the user sends a wwwurlencoded payload? Raise an exception?
-      @webhook_payload = webhook_payload.deep_symbolize_keys
       @scm = scm
       @event = event
+      # TODO: What should we do when the user sends a wwwurlencoded payload? Raise an exception?
```
Comment (krauselukas) [inline src/api/app/services/trigger_controller_service/scm_extractor.rb:25]: Would transform this TODO into a card in the backlog to deal with it and remove the comment, its a bit lost here IMO

File: src/api/app/services/trigger_controller_service/scm_extractor.rb [hunk 2]
```diff
@@ -16,19 +18,30 @@ class SCMExtractor
...
     end
+
+    def valid?
+      @scm.present? && @extractor.present?
+    end
+
+    def error_message
+      return 'Only GitHub, GitLab and Gitea are supported. Could not find the required HTTP request headers X-GitHub-Event, X-Gitlab-Event or X-Gitea-Event.' if @scm.nil?
+
+      'This SCM event is not yet supported' if @extractor.nil?
```
Comment (krauselukas) [inline src/api/app/services/trigger_controller_service/scm_extractor.rb:44]:
```suggestion
      'This SCM event is not supported' if @extractor.nil?
```

Comment (krauselukas) [reply src/api/app/services/trigger_controller_service/scm_extractor.rb:44]: @danidoni most likely we will never support it, so I would remove the `yet` part

File: src/api/app/services/trigger_controller_service/scm_extractor.rb [hunk 3]
```diff
@@ -16,19 +18,30 @@ class SCMExtractor
       }
     }.freeze
 
+    # FIXME: This is a factory
```
[the remark this answers is not in the document]
Comment (danidoni) [reply src/api/app/services/trigger_controller_service/scm_extractor.rb:21]: I'll remove it

File: src/api/app/services/trigger_controller_service/scm_extractor.rb (hunk 1 above)
Comment (danidoni) [reply src/api/app/services/trigger_controller_service/scm_extractor.rb:25]: [Done](https://trello.com/c/FFw9eU5r/244-what-should-we-do-when-the-user-sends-a-wwwurlencoded-payload-raise-an-exception)

File: src/api/app/services/trigger_controller_service/scm_extractor.rb (hunk 2 above)
Comment (danidoni) [reply src/api/app/services/trigger_controller_service/scm_extractor.rb:44]: Removed

**Comment by danidoni** [comment]
I'll squash them all

**Review by krauselukas — APPROVED** [review]

**Comment by krauselukas** [comment]
codecov passed... going to merge
