### PR TITLE
 Avoid calling strptime with an empty string

### LINKED ISSUE #6240: [production][] invalid strptime format - `%s'
threw this 77 times
<pre>
invalid strptime format - `%s&#39;
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5be17e86de01d500060df131)

### PR DESCRIPTION
**Pull request by Ana06**
This was caused by https://github.com/openSUSE/open-build-service/commit/e9f6f907bc6af777fe244745baf3d5067c17ca4d#diff-49563098f1992cafd3f7c8195f53a383. Although the code was wrong at that point, because it didn't return `false` if both build times were nil.

Fixes #6240 :bowtie:

### CODE REVIEW

File: src/api/app/models/binary_release.rb [hunk 1]
```diff
@@ -202,9 +202,11 @@ def reset_cache
   end
 
   def indentical_to?(binary_hash)
+    time = Time.strptime(binary_hash['buildtime'].to_s, '%s') if binary_hash['buildtime'].present?
+
     binary_disturl == binary_hash['disturl'] &&
       binary_supportstatus == binary_hash['supportstatus'] &&
-      binary_buildtime == Time.strptime(binary_hash['buildtime'].to_s, '%s')
+      binary_buildtime == time
```
Comment (coolo) [inline src/api/app/models/binary_release.rb]: what value of 'time' is used if the hash is empty? as there is no assignment the variable is not there, so does it take the function?

**Comment by marcus-h** [comment]
On 2018-11-13 15:14:22 +0000, Stephan Kulow wrote:
> >      binary_disturl == binary_hash['disturl'] &&
>        binary_supportstatus == binary_hash['supportstatus'] &&
> -      binary_buildtime == Time.strptime(binary_hash['buildtime'].to_s, '%s')
> +      binary_buildtime == time
> 
> what value of 'time' is used if the hash is empty? as there is no assignment the variable is not there, so does it take the function?
> 
nil according to [1].

[1] https://docs.ruby-lang.org/en/2.5.0/syntax/assignment_rdoc.html#label-Local+Variables+and+Methods

**Comment by adrianschroeter** [comment]
On Dienstag, 13. November 2018, 16:44:50 CET Marcus Hüwe wrote:
> On 2018-11-13 15:14:22 +0000, Stephan Kulow wrote:
> > >      binary_disturl == binary_hash['disturl'] &&
> > >      
> >        binary_supportstatus == binary_hash['supportstatus'] &&
> > 
> > -      binary_buildtime == Time.strptime(binary_hash['buildtime'].to_s,
> > '%s') +      binary_buildtime == time
> > 
> > what value of 'time' is used if the hash is empty? as there is no
> > assignment the variable is not there, so does it take the function?
> nil according to [1].

ha, just refactored that earlier this day:

  https://github.com/openSUSE/open-build-service/pull/6246

-- 

Adrian Schroeter
SUSE Linux Products GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
email: adrian@suse.de

File: src/api/app/models/binary_release.rb (hunk 1 above)
Comment (Ana06) [reply src/api/app/models/binary_release.rb]: of course it does! If both times are nil then the hashes are also equal. We have to take this case into account. :nerd_face:

**Comment by Ana06** [comment]
@adrianschroeter 

> ha, just refactored that earlier this day:
>   #6246

How is your refactoring related to this PR? :confused:
