### PR TITLE
Inform user when the provided token is wrong 

### LINKED ISSUE #12176: [production][trigger_workflow#create] undefined method `workflow_runs' for #<Token::Service:0x000055d287e6d200>
[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/62017fc084bf460543e2cf2c)
# undefined method `workflow_runs&#39; for #&lt;Token::Service:0x0000557e87a01148&gt; #
### URL ###
[https://build.opensuse.org/trigger/workflow?id=5869](https://build.opensuse.org/trigger/workflow?id=5869)"
### Where ###
trigger_workflow#create

### Occured ###
Feb 07  8:23pm

### Similar ###
8

## Params ##
~~~
{
  &quot;action&quot; =&gt; &quot;create&quot;,
  &quot;controller&quot; =&gt; &quot;trigger_workflow&quot;,
  &quot;hook&quot; =&gt; {
    &quot;active&quot; =&gt; true,
    &quot;config&quot; =&gt; {
      &quot;content_type&quot; =&gt; &quot;json&quot;,
      &quot;insecure_ssl&quot; =&gt; &quot;0&quot;,
      &quot;secret&quot; =&gt; &quot;********&quot;,
      &quot;url&quot; =&gt; &quot;https://build.opensuse.org/trigger/workflow?id=5869&quot;
    },
    &quot;created_at&quot; =&gt; &quot;2022-02-07T20:23:27Z&quot;,
    &quot;deliveries_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/hooks/342089725/deliveries&quot;,
    &quot;events&quot; =&gt; [&quot;push&quot;],
    &quot;id&quot; =&gt; 342089725,
    &quot;last_response&quot; =&gt; {
      &quot;code&quot; =&gt; nil,
      &quot;message&quot; =&gt; nil,
      &quot;status&quot; =&gt; &quot;unused&quot;
    },
    &quot;name&quot; =&gt; &quot;web&quot;,
    &quot;ping_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/hooks/342089725/pings&quot;,
    &quot;test_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/hooks/342089725/test&quot;,
    &quot;type&quot; =&gt; &quot;Repository&quot;,
    &quot;updated_at&quot; =&gt; &quot;2022-02-07T20:23:27Z&quot;,
    &quot;url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/hooks/342089725&quot;
  },
  &quot;hook_id&quot; =&gt; 342089725,
  &quot;id&quot; =&gt; &quot;5869&quot;,
  &quot;repository&quot; =&gt; {
    &quot;allow_forking&quot; =&gt; true,
    &quot;archive_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/{archive_format}{/ref}&quot;,
    &quot;archived&quot; =&gt; false,
    &quot;assignees_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/assignees{/user}&quot;,
    &quot;blobs_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/git/blobs{/sha}&quot;,
    &quot;branches_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/branches{/branch}&quot;,
    &quot;clone_url&quot; =&gt; &quot;https://github.com/X0rg/CPU-X.git&quot;,
    &quot;collaborators_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/collaborators{/collaborator}&quot;,
    &quot;comments_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/comments{/number}&quot;,
    &quot;commits_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/commits{/sha}&quot;,
    &quot;compare_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/compare/{base}...{head}&quot;,
    &quot;contents_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/contents/{+path}&quot;,
    &quot;contributors_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/contributors&quot;,
    &quot;created_at&quot; =&gt; &quot;2014-09-21T14:17:56Z&quot;,
    &quot;default_branch&quot; =&gt; &quot;master&quot;,
    &quot;deployments_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/deployments&quot;,
    &quot;description&quot; =&gt; &quot;CPU-X is a Free software that gathers information on CPU, motherboard and more&quot;,
    &quot;disabled&quot; =&gt; false,
    &quot;downloads_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/downloads&quot;,
    &quot;events_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/events&quot;,
    &quot;fork&quot; =&gt; false,
    &quot;forks&quot; =&gt; 77,
    &quot;forks_count&quot; =&gt; 77,
    &quot;forks_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/forks&quot;,
    &quot;full_name&quot; =&gt; &quot;X0rg/CPU-X&quot;,
    &quot;git_commits_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/git/commits{/sha}&quot;,
    &quot;git_refs_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/git/refs{/sha}&quot;,
    &quot;git_tags_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/git/tags{/sha}&quot;,
    &quot;git_url&quot; =&gt; &quot;git://github.com/X0rg/CPU-X.git&quot;,
    &quot;has_downloads&quot; =&gt; true,
    &quot;has_issues&quot; =&gt; true,
    &quot;has_pages&quot; =&gt; true,
    &quot;has_projects&quot; =&gt; true,
    &quot;has_wiki&quot; =&gt; true,
    &quot;homepage&quot; =&gt; &quot;https://x0rg.github.io/CPU-X&quot;,
    &quot;hooks_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/hooks&quot;,
    &quot;html_url&quot; =&gt; &quot;https://github.com/X0rg/CPU-X&quot;,
    &quot;id&quot; =&gt; 24292801,
    &quot;is_template&quot; =&gt; false,
    &quot;issue_comment_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/issues/comments{/number}&quot;,
    &quot;issue_events_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/issues/events{/number}&quot;,
    &quot;issues_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/issues{/number}&quot;,
    &quot;keys_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/keys{/key_id}&quot;,
    &quot;labels_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/labels{/name}&quot;,
    &quot;language&quot; =&gt; &quot;C&quot;,
    &quot;languages_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/languages&quot;,
    &quot;license&quot; =&gt; {
      &quot;key&quot; =&gt; &quot;gpl-3.0&quot;,
      &quot;name&quot; =&gt; &quot;GNU General Public License v3.0&quot;,
      &quot;node_id&quot; =&gt; &quot;MDc6TGljZW5zZTk=&quot;,
      &quot;spdx_id&quot; =&gt; &quot;GPL-3.0&quot;,
      &quot;url&quot; =&gt; &quot;https://api.github.com/licenses/gpl-3.0&quot;
    },
    &quot;merges_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/merges&quot;,
    &quot;milestones_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/milestones{/number}&quot;,
    &quot;mirror_url&quot; =&gt; nil,
    &quot;name&quot; =&gt; &quot;CPU-X&quot;,
    &quot;node_id&quot; =&gt; &quot;MDEwOlJlcG9zaXRvcnkyNDI5MjgwMQ==&quot;,
    &quot;notifications_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/notifications{?since,all,participating}&quot;,
    &quot;open_issues&quot; =&gt; 2,
    &quot;open_issues_count&quot; =&gt; 2,
    &quot;owner&quot; =&gt; {
      &quot;avatar_url&quot; =&gt; &quot;https://avatars.githubusercontent.com/u/2873785?v=4&quot;,
      &quot;events_url&quot; =&gt; &quot;https://api.github.com/users/X0rg/events{/privacy}&quot;,
      &quot;followers_url&quot; =&gt; &quot;https://api.github.com/users/X0rg/followers&quot;,
      &quot;following_url&quot; =&gt; &quot;https://api.github.com/users/X0rg/following{/other_user}&quot;,
      &quot;gists_url&quot; =&gt; &quot;https://api.github.com/users/X0rg/gists{/gist_id}&quot;,
      &quot;gravatar_id&quot; =&gt; &quot;&quot;,
      &quot;html_url&quot; =&gt; &quot;https://github.com/X0rg&quot;,
      &quot;id&quot; =&gt; 2873785,
      &quot;login&quot; =&gt; &quot;X0rg&quot;,
      &quot;node_id&quot; =&gt; &quot;MDQ6VXNlcjI4NzM3ODU=&quot;,
      &quot;organizations_url&quot; =&gt; &quot;https://api.github.com/users/X0rg/orgs&quot;,
      &quot;received_events_url&quot; =&gt; &quot;https://api.github.com/users/X0rg/received_events&quot;,
      &quot;repos_url&quot; =&gt; &quot;https://api.github.com/users/X0rg/repos&quot;,
      &quot;site_admin&quot; =&gt; false,
      &quot;starred_url&quot; =&gt; &quot;https://api.github.com/users/X0rg/starred{/owner}{/repo}&quot;,
      &quot;subscriptions_url&quot; =&gt; &quot;https://api.github.com/users/X0rg/subscriptions&quot;,
      &quot;type&quot; =&gt; &quot;User&quot;,
      &quot;url&quot; =&gt; &quot;https://api.github.com/users/X0rg&quot;
    },
    &quot;private&quot; =&gt; false,
    &quot;pulls_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/pulls{/number}&quot;,
    &quot;pushed_at&quot; =&gt; &quot;2022-02-07T19:49:02Z&quot;,
    &quot;releases_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/releases{/id}&quot;,
    &quot;size&quot; =&gt; 8849,
    &quot;ssh_url&quot; =&gt; &quot;git@github.com:X0rg/CPU-X.git&quot;,
    &quot;stargazers_count&quot; =&gt; 925,
    &quot;stargazers_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/stargazers&quot;,
    &quot;statuses_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/statuses/{sha}&quot;,
    &quot;subscribers_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/subscribers&quot;,
    &quot;subscription_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/subscription&quot;,
    &quot;svn_url&quot; =&gt; &quot;https://github.com/X0rg/CPU-X&quot;,
    &quot;tags_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/tags&quot;,
    &quot;teams_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/teams&quot;,
    &quot;topics&quot; =&gt; [&quot;benchmark&quot;, &quot;bsd-app&quot;, &quot;cpu&quot;, &quot;gpu&quot;, &quot;gtk3&quot;, &quot;linux-app&quot;, &quot;motherboard&quot;, &quot;ncurses&quot;, &quot;portable&quot;, &quot;ram&quot;],
    &quot;trees_url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X/git/trees{/sha}&quot;,
    &quot;updated_at&quot; =&gt; &quot;2022-02-06T10:52:21Z&quot;,
    &quot;url&quot; =&gt; &quot;https://api.github.com/repos/X0rg/CPU-X&quot;,
    &quot;visibility&quot; =&gt; &quot;public&quot;,
    &quot;watchers&quot; =&gt; 925,
    &quot;watchers_count&quot; =&gt; 925
  },
  &quot;sender&quot; =&gt; {
    &quot;avatar_url&quot; =&gt; &quot;https://avatars.githubusercontent.com/u/2873785?v=4&quot;,
    &quot;events_url&quot; =&gt; &quot;https://api.github.com/users/X0rg/events{/privacy}&quot;,
    &quot;followers_url&quot; =&gt; &quot;https://api.github.com/users/X0rg/followers&quot;,
    &quot;following_url&quot; =&gt; &quot;https://api.github.com/users/X0rg/following{/other_user}&quot;,
    &quot;gists_url&quot; =&gt; &quot;https://api.github.com/users/X0rg/gists{/gist_id}&quot;,
    &quot;gravatar_id&quot; =&gt; &quot;&quot;,
    &quot;html_url&quot; =&gt; &quot;https://github.com/X0rg&quot;,
    &quot;id&quot; =&gt; 2873785,
    &quot;login&quot; =&gt; &quot;X0rg&quot;,
    &quot;node_id&quot; =&gt; &quot;MDQ6VXNlcjI4NzM3ODU=&quot;,
    &quot;organizations_url&quot; =&gt; &quot;https://api.github.com/users/X0rg/orgs&quot;,
    &quot;received_events_url&quot; =&gt; &quot;https://api.github.com/users/X0rg/received_events&quot;,
    &quot;repos_url&quot; =&gt; &quot;https://api.github.com/users/X0rg/repos&quot;,
    &quot;site_admin&quot; =&gt; false,
    &quot;starred_url&quot; =&gt; &quot;https://api.github.com/users/X0rg/starred{/owner}{/repo}&quot;,
    &quot;subscriptions_url&quot; =&gt; &quot;https://api.github.com/users/X0rg/subscriptions&quot;,
    &quot;type&quot; =&gt; &quot;User&quot;,
    &quot;url&quot; =&gt; &quot;https://api.github.com/users/X0rg&quot;
  },
  &quot;zen&quot; =&gt; &quot;Favor focus over features.&quot;
}
~~~

## Session ##
~~~
{}
~~~

## Backtrace ##
~~~
469:  /GEM_ROOT/gems/activemodel-6.1.4/lib/active_model/attribute_methods.rb -> **method_missing**
62:  app/controllers/trigger_workflow_controller.rb -> **create_workflow_run**
427:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/callbacks.rb -> **block in make_lambda**
198:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/callbacks.rb -> **block (2 levels) in halting**
34:  /GEM_ROOT/gems/actionpack-6.1.4/lib/abstract_controller/callbacks.rb -> **block (2 levels) in &lt;module:Callbacks&gt;**
199:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/callbacks.rb -> **block in halting**
512:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/callbacks.rb -> **block in invoke_before**
512:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/callbacks.rb -> **each**
512:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/callbacks.rb -> **invoke_before**
105:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/callbacks.rb -> **run_callbacks**
41:  /GEM_ROOT/gems/actionpack-6.1.4/lib/abstract_controller/callbacks.rb -> **process_action**
22:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal/rescue.rb -> **process_action**
34:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal/instrumentation.rb -> **block in process_action**
203:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/notifications/instrumenter.rb -> **instrument**
203:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/notifications.rb -> **instrument**
33:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal/instrumentation.rb -> **process_action**
249:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal/params_wrapper.rb -> **process_action**
27:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/railties/controller_runtime.rb -> **process_action**
165:  /GEM_ROOT/gems/actionpack-6.1.4/lib/abstract_controller/base.rb -> **process**
39:  /GEM_ROOT/gems/actionview-6.1.4/lib/action_view/rendering.rb -> **process**
190:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal.rb -> **dispatch**
254:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal.rb -> **dispatch**
50:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/routing/route_set.rb -> **dispatch**
33:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/routing/route_set.rb -> **serve**
19:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/routing/mapper.rb -> **block in &lt;class:Constraints&gt;**
49:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/routing/mapper.rb -> **serve**
50:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/journey/router.rb -> **block in serve**
32:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/journey/router.rb -> **each**
32:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/journey/router.rb -> **serve**
842:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/routing/route_set.rb -> **call**
77:  /GEM_ROOT/gems/flipper-0.23.1/lib/flipper/middleware/memoizer.rb -> **memoized_call**
42:  /GEM_ROOT/gems/flipper-0.23.1/lib/flipper/middleware/memoizer.rb -> **call**
37:  config/initializers/wrap_parameters.rb -> **call**
44:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/deflater.rb -> **call**
15:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/etag.rb -> **call**
40:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/conditional_get.rb -> **call**
12:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/head.rb -> **call**
22:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/http/permissions_policy.rb -> **call**
18:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/http/content_security_policy.rb -> **call**
266:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/session/abstract/id.rb -> **context**
260:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/session/abstract/id.rb -> **call**
689:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/cookies.rb -> **call**
27:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/callbacks.rb -> **block in call**
98:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/callbacks.rb -> **run_callbacks**
26:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/callbacks.rb -> **call**
18:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/actionable_exceptions.rb -> **call**
32:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call!**
21:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call**
29:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/debug_exceptions.rb -> **call**
33:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/show_exceptions.rb -> **call**
15:  /GEM_ROOT/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb -> **call_app**
26:  /GEM_ROOT/gems/railties-6.1.4/lib/rails/rack/logger.rb -> **block in call**
99:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/tagged_logging.rb -> **block in tagged**
37:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/tagged_logging.rb -> **tagged**
99:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/tagged_logging.rb -> **tagged**
26:  /GEM_ROOT/gems/railties-6.1.4/lib/rails/rack/logger.rb -> **call**
81:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/remote_ip.rb -> **call**
81:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/remote_ip.rb -> **call**
19:  /GEM_ROOT/gems/request_store-1.5.1/lib/request_store/middleware.rb -> **call**
26:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/request_id.rb -> **call**
24:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/method_override.rb -> **call**
22:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/runtime.rb -> **call**
29:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/cache/strategy/local_cache_middleware.rb -> **call**
14:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/executor.rb -> **call**
18:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/lock.rb -> **call**
110:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/sendfile.rb -> **call**
92:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/host_authorization.rb -> **call**
539:  /GEM_ROOT/gems/railties-6.1.4/lib/rails/engine.rb -> **call**
207:  /GEM_ROOT/gems/railties-6.1.4/lib/rails/railtie.rb -> **public_send**
207:  /GEM_ROOT/gems/railties-6.1.4/lib/rails/railtie.rb -> **method_missing**
74:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/urlmap.rb -> **block in call**
58:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/urlmap.rb -> **each**
58:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/urlmap.rb -> **call**
107:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.8/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb -> **process_request**
157:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.8/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **accept_and_process_next_request**
110:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.8/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **main_loop**
416:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.8/src/ruby_supportlib/phusion_passenger/request_handler.rb -> **block (3 levels) in start_threads**
113:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.8/src/ruby_supportlib/phusion_passenger/utils.rb -> **block in create_thread_and_abort_on_exception**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| program_name | Passenger RubyApp: /srv/www/obs/api (production) |
| HTTP_USER_AGENT | GitHub-Hookshot/5fb002b |

### PR DESCRIPTION
**Pull request by vpereira**
Fixes #12176

In this PR I'm fixing two issues:

- When user has two valid work flow tokens, but then assigns the wrong ID on the github side
- When user has two valid tokens, but for different types and then assign the wrong ID on the github side

### CODE REVIEW

**Comment by vpereira** [comment]
[Inform user when the provided token is wrong (M)](https://trello.com/c/Pbv42RrE/1863-inform-user-when-the-provided-token-is-wrong-m)

File: src/api/app/controllers/concerns/rescue_handler.rb [hunk 1]
```diff
@@ -31,6 +31,10 @@ module RescueHandler
       render plain: text, status: http_status
     end
 
+    rescue_from Trigger::Errors::InvalidToken do |exception|
+      render_error status: 403, errcode: 'invalid_token', message: exception.message
```
Comment (dmarcoux) [inline src/api/app/controllers/concerns/rescue_handler.rb:35]: There's a typo:

```suggestion
      render_error status: 403, errorcode: 'invalid_token', message: exception.message
```

What is the error message users will see? Is it generic?

**Comment by dmarcoux** [comment]
Rescuing from `Trigger::Errors::InvalidToken` isn't enough, since it can happen that `TriggerControllerService::TokenExtractor` returns a token which isn't an instance of `Token::Workflow`. When this happens, we get the issue which you linked in this PR's description.

File: src/api/app/controllers/concerns/rescue_handler.rb (hunk 1 above)
Comment (vpereira) [reply src/api/app/controllers/concerns/rescue_handler.rb]: if you look the [code](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/controllers/trigger/errors.rb#L7), we have there "No valid token found"

File: src/api/app/controllers/trigger_workflow_controller.rb [hunk 2]
```diff
@@ -58,6 +58,8 @@ def payload
   end
 
   def create_workflow_run
+    raise Trigger::Errors::InvalidToken, 'Wrong type of Token. Please use Workflow tokens only.' unless @token.respond_to?(:workflow_runs)
```
Comment (dmarcoux) [inline src/api/app/controllers/trigger_workflow_controller.rb:61]:
```suggestion
    raise Trigger::Errors::InvalidToken, 'Wrong token type. Please use workflow tokens only.' unless @token.respond_to?(:workflow_runs)
```

File: src/api/spec/controllers/trigger_workflow_controller_spec.rb [hunk 3]
```diff
@@ -48,6 +48,53 @@
...
+        allow(token_extractor_instance).to receive(:call).and_return(token)
+        request.headers['ACCEPT'] = '*/*'
+        request.headers['CONTENT_TYPE'] = 'application/json'
+        request.headers['HTTP_X_GITHUB_EVENT'] = 'pull_request'
+
+        post :create, body: github_payload.to_json
+      end
+
+      it { expect(response).to have_http_status(:forbidden) }
+      it { expect(response.body).to include('Please use Workflow tokens only') }
```
Comment (dmarcoux) [inline src/api/spec/controllers/trigger_workflow_controller_spec.rb:83]: The string in `include(...)` will have to be updated due to the proposed changes from my previous comment.

File: src/api/test/functional/trigger_controller_test.rb [hunk 4]
```diff
@@ -27,7 +27,7 @@ def test_rebuild_via_token
     reset_auth
     post '/trigger/rebuild'
     assert_response 403
-    assert_xml_tag tag: 'status', attributes: { code: 'permission_denied' }
+    assert_xml_tag tag: 'invalid_token', attributes: { code: 'permission_denied' }
```
Comment (adrianschroeter) [inline src/api/test/functional/trigger_controller_test.rb:30]: that is an api incompatible change, we do not do that usually. Or at least write a reasoning why it can not be avoided to release notes.

Comment (vpereira) [reply src/api/test/functional/trigger_controller_test.rb]: ok, could you please check if this comment still relevant @adrianschroeter ?

Comment (adrianschroeter) [reply src/api/test/functional/trigger_controller_test.rb]: just changing the code without changing the xml structure should be fine.
