### PR TITLE
[ci] Make sure the staging_project_spec works offline

### LINKED ISSUE #5404: Package build failures due to openqa tests
The package builds have no network access - and we really shouldn't query openqa as part of the tests

```
[22166s]   3) ObsFactory::StagingProject#openqa_jobs @openqa_jobs is nil openqa results are relevant 
[22166s]      Failure/Error: resp = Net::HTTP.start(uri.host, use_ssl: uri.scheme == "https") { |http| http.request(req) }
[22166s] 
[22166s]      SocketError:
[22166s]        Failed to open TCP connection to openqa.opensuse.org:80 (getaddrinfo: Temporary failure in name resolution)
[22166s]      # ./app/models/obs_factory/openqa_api.rb:50:in `block in _get'
[22166s]      # ./app/models/obs_factory/openqa_api.rb:50:in `_get'
[22166s]      # ./app/models/obs_factory/openqa_api.rb:35:in `get'
[22166s]      # ./app/models/obs_factory/openqa_job.rb:78:in `find_all_by'
[22166s]      # ./app/models/obs_factory/staging_project.rb:100:in `openqa_jobs'
[22166s]      # ./spec/models/obs_factory/staging_project_spec.rb:210:in `block (5 levels) in <top (required)>'
[22166s]      # ./spec/support/logging.rb:4:in `block (2 levels) in <top (required)>'
[22166s]      # ------------------
[22166s]      # --- Caused by: ---
[22166s]      # SocketError:
[22166s]      #   getaddrinfo: Temporary failure in name resolution
[22166s]      #   ./app/models/obs_factory/openqa_api.rb:50:in `block in _get'

### PR DESCRIPTION
**Pull request by coolo**
by stubbing requests to openqa.opensuse.org

Fixes #5404

### CODE REVIEW

File: src/api/spec/models/obs_factory/staging_project_spec.rb [hunk 1]
```diff
@@ -205,6 +205,8 @@
       context 'openqa results are relevant' do
         before do
           allow_any_instance_of(ObsFactory::StagingProject).to receive(:openqa_results_relevant?).and_return(true)
+          url = 'http://openqa.opensuse.org/api/v1/jobs?iso=openSUSE-Staging:A-Staging-DVD-x86_64-Build1036.1-Media.iso&scope=current'
+          stub_request(:get, url).and_return(body: '{"jobs":[]}')
```
Comment (coolo) [inline src/api/spec/models/obs_factory/staging_project_spec.rb]: I tried a glob, but stub_request doesn't seem to like that.

**Comment by bgeuken** [comment]
argh, I was just about to open a PR^^
