### PR TITLE
Don't show build logs when rmplint logs are not available

### LINKED ISSUE #16555: rpmlint log tab in the WebUI is showing build logs for non SUSE OSs
# Issue Description
It seems that the `RPM Lint` tab in the OBS WebUI is showing the wrong content when the OS is not  a SUSE based system.

Expected Result
============
In case of RPM based OSs, the `RPM Lint` tab in the WebUI should show the rpmlint logs. For non RPM based OSs it should show that there's no rpmlint log available or any similar message.

How to Reproduce
===============
1. Go to https://build.opensuse.org/package/show/systemsmanagement:Uyuni:Master/spacecmd
2. Click on `RPM Lint` tab on the WebUI
3. Select any non SUSE repo like for example `AlmaLinux_8`
4. The rpmlint log shows the content of the build log.

Further Information
===============
* The same issue is reproducible when checking Deb based distros like for example
  * https://build.opensuse.org/package/show/systemsmanagement:Uyuni:Master:Debian12-Uyuni-Client-Tools/spacecmd
  * https://build.opensuse.org/package/show/systemsmanagement:Uyuni:Master:Ubuntu2204-Uyuni-Client-Tools/spacecmd
* @eduardoj suggested that this issue could be related to https://github.com/openSUSE/open-build-service/pull/15477

### PR DESCRIPTION
**Pull request by rubhanazeem**
fixes #16555

Currently, if a user has signed up for the Request Show Redesign Beta feature, we display build logs for all repositories if rpmlint logs are not available. This is not correct because it's confusing for reviewers. This PR changes that behavior to show the correct message, indicating that no rpmlint logs are available.

### CODE REVIEW

File: src/api/spec/fixtures/files/rpmlint_log_extractor_log [hunk 1]
```diff
@@ -1,21 +1,21 @@
...
+Content-Type: text/plain
+Content-Disposition: inline
+Content-Transfer-Encoding: binary
+X-Opensuse-Runtimes: {"view":null,"db":16.376543004065752,"backend":0}
+Cache-Control: no-cache
+X-Request-Id: f030558c-aed3-4f72-8113-d434b8e40ba7
+X-Runtime: 0.900190
+Server-Timing: sql.active_record;dur=34.83, start_processing.action_controller;dur=0.18, instantiation.active_record;dur=24.52, cache_read.active_support;dur=1.77, cache_write.active_support;dur=0.60, send_file.action_controller;dur=0.36, process_action.action_controller;dur=662.78
+Content-Length: 34454
+
```
Comment (eduardoj) [inline src/api/spec/fixtures/files/rpmlint_log_extractor_log:18]: I don't think these space only chnages are needed... Are them?

File: src/api/spec/services/rpmlint_log_extractor_spec.rb [hunk 2]
```diff
@@ -40,15 +40,15 @@
...
           allow(Backend::Api::BuildResults::Binaries).to receive(:file)
             .with('home:user1', 'repo1', 'arch1', 'package1', '_log')
-            .and_return(invalid_byte_sequence_in_utf8)
+            .and_return(file_fixture('rpmlint_log_extractor_log_without_mark').read)
         end
 
-        it 'extracts the summary from the build log file' do
-          expect(subject).to eq('this is an invalid byte sequence �')
+        it 'returns empty results' do
+          expect(subject).to be_nil
```
Comment (eduardoj) [inline src/api/spec/services/rpmlint_log_extractor_spec.rb:51]: Here we are substituting one test with another one. Could we preserve the previous test? Do you find a reason not to keep it?

Comment (rubhanazeem) [reply src/api/spec/services/rpmlint_log_extractor_spec.rb:51]: Yes we don't need this test anymore. Because with the new changes if RPM mark is not available, we just return nil. And before this change if the mark is not found we used to return the full log file. This is why we were seeing build logs in place of rpmlint.

File: src/api/spec/fixtures/files/rpmlint_log_extractor_log (hunk 1 above)
Comment (rubhanazeem) [reply src/api/spec/fixtures/files/rpmlint_log_extractor_log]: Ugh, this was unintentional. Happened automatically because of IDE. I've reverted it

File: src/api/spec/services/rpmlint_log_extractor_spec.rb (hunk 2 above)
Comment (eduardoj) [reply src/api/spec/services/rpmlint_log_extractor_spec.rb:51]: With the previous tests I was referring to:
```
context 'when the _log file contains invalid byte sequences in UTF-8' do
  [...]
  it 'extracts the summary from the build log file' do
```
Maybe the test should have said `'when the _log file contains the RPM mark and invalid byte sequences in UTF-8'`.

I Just want to make sure we don't face again the #15905 issue if we don't provide this test.

Comment (rubhanazeem) [reply src/api/spec/services/rpmlint_log_extractor_spec.rb:51]: I've added a new test to check invalid byte sequences without mark. And adapted an existing test for `file contains the RPM mark and invalid byte sequences` to address the cases you mentioned above

File: src/api/spec/fixtures/files/rpmlint_log_extractor_log (hunk 1 above)
Comment (rubhanazeem) [reply src/api/spec/fixtures/files/rpmlint_log_extractor_log:18]: All this change is happening because of some weird encoding change in IDE. The only important change here is that I have added an invalid byte sequence in this file

**Review by eduardoj — APPROVED** [review]

**Comment by deneb-alpha** [comment]
thanks a lot for the quick fix folks! :tada: 
KUDOS!
