### PR TITLE
Bugfix 11035

### LINKED ISSUE #11035: rebuild via token and project links are not working anymore
I got reports that using the rebuild token broke for builds where the packages are derived via project links are not working anymore since some days.

Please verify in test cases that backend gets a rebuild trigger in such situations after last weeks refactoring

(no more regression label?)

### PR DESCRIPTION
**Pull request by hennevogel**
Fixes #11035

### CODE REVIEW

File: src/api/app/models/token/rebuild.rb [hunk 1]
```diff
@@ -5,7 +5,7 @@ def self.token_name
 
   def call(options)
     # FIXME: Use the Package#rebuild? instead of calling the Backend directly
-    Backend::Api::Sources::Package.rebuild(package_from_association_or_params.project.name,
+    Backend::Api::Sources::Package.rebuild(project_from_association_or_params.name,
```
Comment (adrianschroeter) [inline src/api/app/models/token/rebuild.rb:8]: most likely crashing in remote project case?

Comment (hennevogel) [reply src/api/app/models/token/rebuild.rb:8]: It will never get here as `package_from_association_or_params` will be nil in the controller. You can't instantiate remote packages. It would also not make much sense to trigger a rebuild *for* a project that comes from remote right?

Comment (hennevogel) [reply src/api/app/models/token/rebuild.rb:8]:
```ruby
[6] pry(main)> Project.find_by(name: 'openSUSE.org').remoteurl
  Project Load (1.3ms)  SELECT `projects`.* FROM `projects` WHERE `projects`.`id` != 0 AND `projects`.`name` = 'openSUSE.org' LIMIT 1
=> "https://api.opensuse.org/public"
[7] pry(main)> Package.get_by_project_and_name('openSUSE.org:home:hennevogel', 'ponysay')
Trying to find local project openSUSE.org:home, remote_project hennevogel
  Project Load (1.1ms)  SELECT `projects`.* FROM `projects` WHERE `projects`.`id` != 0 AND `projects`.`name` = 'openSUSE.org:home' LIMIT 1
Trying to find local project openSUSE.org, remote_project home:hennevogel
  Project Load (0.8ms)  SELECT `projects`.* FROM `projects` WHERE `projects`.`id` != 0 AND `projects`.`name` = 'openSUSE.org' LIMIT 1
Found local project openSUSE.org for home:hennevogel with remoteurl https://api.opensuse.org/public
=> nil
```

**Review by vpereira — APPROVED** [review]

**Comment by adrianschroeter** [comment]
On Dienstag, 27. April 2021, 16:31:04 CEST Henne Vogelsang wrote:
> @hennevogel commented on this pull request.
> 
> 
> 
> > @@ -5,7 +5,7 @@ def self.token_name
>  
>    def call(options)
>      # FIXME: Use the Package#rebuild? instead of calling the Backend directly
> -    Backend::Api::Sources::Package.rebuild(package_from_association_or_params.project.name,
> +    Backend::Api::Sources::Package.rebuild(project_from_association_or_params.name,
> 
> It will never get here as `package_from_association_or_params` will be nil in the controller. You can't instantiate remote packages. It would also not make much sense to trigger a rebuild *for* a project that comes from remote right?

the package source may come from remote, but the build is local.

-- 

Adrian Schroeter ***@***.***>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by hennevogel** [comment]
> the package source may come from remote, but the build is local.

So a project with a project-link to a project that has a project-link to remote?

We did not support this before.  [Have been using](https://github.com/openSUSE/open-build-service/blob/87ff5c460f00f0bc8aecd62f644c7a86f6ec19fc/src/api/app/controllers/trigger_controller.rb#L101) `Package.get_by_project_and_name` on the project and package parameters. It does not support remote projects. See https://github.com/openSUSE/open-build-service/blob/master/src/api/app/models/package.rb#L173

**Comment by adrianschroeter** [comment]
On Dienstag, 27. April 2021, 17:53:48 CEST Henne Vogelsang wrote:
> > the package source may come from remote, but the build is local.
> 
> So a project with a project-link to a project that has a project-link to remote?

can also be a direct link, but also this scenario.

> We did not support this before.

we always support it in the api (or have an explicit exception when not).

> [Have been using](https://github.com/openSUSE/open-build-service/blob/87ff5c460f00f0bc8aecd62f644c7a86f6ec19fc/src/api/app/controllers/trigger_controller.rb#L101) `Package.get_by_project_and_name` on the project and package parameters. It does not support remote projects. See https://github.com/openSUSE/open-build-service/blob/master/src/api/app/models/package.rb#L173

this is exactly the situation when you have to check for the remote case. nil means that it
may exist remote. it would be an exception when it does not exist.

-- 

Adrian Schroeter ***@***.***>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by hennevogel** [comment]
> we always support it in the api (or have an explicit exception when not).

Not in this endpoint. At least not for a long time. Let me see what I can do...
