### PR TITLE
Fix Relationship.forbidden_project_ids for groups

### LINKED ISSUE #11302: Group membership ignored for hidden projects
As an OBS instance admin, I want to be able to add groups of users at once to hidden projects (projects with access=disabled flag), so that I don’t have to maintain lists of users in multiple places by hand or write scripts to automate synchronising them.

Expected Result
============
When I add a group as a member of a hidden project, the members of the group are granted appropriate permissions to the hidden project.

Further Information
===============

I identified the issue to stem from the following:
* `check_access?` method does `return true unless Relationship.forbidden_project_ids.include?(project.id)`
* not sure what exactly this does, but also `default_scope { where.not('projects.id' => Relationship.forbidden_project_ids) }`
* `forbidden_project_ids` method uses the following SQL query:
    ```sql
    SELECT ur.project_id, ur.user_id from flags f,
          relationships ur where f.flag = 'access' and
          f.status = 'disable' and ur.project_id = f.project_id
    ```
    thus completely ignoring the `group_id` column.

For example, this is a print from my test database:

```
> SELECT f.flag, ur.project_id, ur.user_id, ur.group_id from flags f, relationships ur where f.flag = 'access' and f.status = 'disable' and ur.project_id = f.project_id;
+--------+------------+---------+----------+
| flag   | project_id | user_id | group_id |
+--------+------------+---------+----------+
| access |         26 |       1 |     NULL |
| access |         26 |    NULL |        1 |
| access |         26 |    NULL |        1 |
| access |         26 |    NULL |        1 |
| access |         26 |    NULL |        1 |
| access |         26 |    NULL |        1 |
+--------+------------+---------+----------+
6 rows in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by coolo**
Fixes #11302

### CODE REVIEW

File: src/api/db/seeds.rb [hunk 1]
```diff
@@ -151,9 +151,9 @@
 at = ans.attrib_types.where(name: 'EmbargoDate').first_or_create(value_count: 1)
 at.attrib_type_modifiable_bies.where(role_id: maintainer_role.id).first_or_create
 at = ans.attrib_types.where(name: 'DelegateRequestTarget').first_or_create
-at.attrib_type_modifiable_bies.where(user_id: maintainer_role.id).first_or_create
+at.attrib_type_modifiable_bies.where(role_id: maintainer_role.id).first_or_create
 at = ans.attrib_types.where(name: 'AllowSubmitToMaintenanceRelease').first_or_create
-at.attrib_type_modifiable_bies.where(user_id: maintainer_role.id).first_or_create
+at.attrib_type_modifiable_bies.where(role_id: maintainer_role.id).first_or_create
```
Comment (adrianschroeter) [inline src/api/db/seeds.rb:156]: ups ... sorry ... and thanks

**Review by hennevogel — APPROVED** [review]

**Review by andrewshadura — COMMENTED** [review]
This is more or less what I'd have done, thanks!
