### PR TITLE
Do not try fetching the project maintainers for a deleted project

### LINKED ISSUE #13414: Internal Server Error when displaying delete request
Issue/Feature Description
====================
Admin-generated delete request:
Visit https://build.opensuse.org/request/show/1036863

Description:
This is a humble request to remove this project.
...

DR was accepted, clicking on Request (e.g. in notification section) throws up 500: Internal server error

Expected Result
============
display DR

How to Reproduce
===============
Click on DR

### PR DESCRIPTION
**Pull request by dmarcoux**
Fixes #13414

### CODE REVIEW

File: src/api/app/controllers/webui/request_controller.rb [hunk 1]
```diff
@@ -41,7 +41,11 @@ def show
       @package_maintainers = target_package_maintainers
 
       # retrieve a list of all project maintainers
-      @project_maintainers = Project.find_by_name(@bs_request.target_project_name).maintainers
+      @project_maintainers = if Project.deleted?(@bs_request.target_project_name)
```
Comment (dmarcoux) [inline src/api/app/controllers/webui/request_controller.rb:44]: While I agree this code isn't amazing, refactoring how maintainers of a project are fetched is clearly out of scope for this PR. It would involve changing the [HasRelationships mixin](https://github.com/openSUSE/open-build-service/blob/fe7cdbf25f2e6a73774b6d66e499af66475e69f5/src/api/app/mixins/has_relationships.rb#L77-L82), which I won't do now.

**Review by krauselukas — APPROVED** [review]

**Review by saraycp — APPROVED** [review]
@dmarcoux  Apart from the linter complaining, LGTM, I tested locally and the fix works.

**Review by ncounter — APPROVED** [review]

**Comment by dmarcoux** [comment]
I fixed the issue reported by RuboCop.

**Review by krauselukas — APPROVED** [review]
