### PR TITLE
Destroy dependent label templates when removing the owning project

### LINKED ISSUE #17745: [production][delayed_job#BsRequestAutoAcceptJob] Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails (`obs_product...
[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/680117c184bf460a581701fb)
# Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails (`obs_production`.`label_globals`, CONSTRAINT `fk_rails_a6eb87ca74` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`)) #
### Where ###
delayed_job#BsRequestAutoAcceptJob

### Occured ###
Apr 17  3:01pm

### Similar ###
7023

## Params ##
~~~
{
  &quot;active_job&quot; =&gt; {
    &quot;arguments&quot; =&gt; [2999068],
    &quot;enqueued_at&quot; =&gt; &quot;2025-04-17T14:36:23.361784896Z&quot;,
    &quot;exception_executions&quot; =&gt; {},
    &quot;executions&quot; =&gt; 0,
    &quot;job_class&quot; =&gt; &quot;BsRequestAutoAcceptJob&quot;,
    &quot;job_id&quot; =&gt; &quot;56a472cd-be1e-4c24-848d-f09cd8573bee&quot;,
    &quot;locale&quot; =&gt; &quot;en&quot;,
    &quot;priority&quot; =&gt; nil,
    &quot;provider_job_id&quot; =&gt; nil,
    &quot;queue_name&quot; =&gt; &quot;default&quot;,
    &quot;scheduled_at&quot; =&gt; nil,
    &quot;timezone&quot; =&gt; &quot;UTC&quot;
  },
  &quot;attempts&quot; =&gt; 0,
  &quot;failed_at&quot; =&gt; nil,
  &quot;handler&quot; =&gt; &quot;--- !ruby/object:ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper\njob_data:\n  job_class: BsRequestAutoAcceptJob\n  job_id: 56a472cd-be1e-4c24-848d-f09cd8573bee\n  provider_job_id: \n  queue_name: default\n  priority: \n  arguments:\n  - 2999068\n  executions: 0\n  exception_executions: {}\n  locale: en\n  timezone: UTC\n  enqueued_at: &#39;2025-04-17T14:36:23.361784896Z&#39;\n  scheduled_at: \n&quot;,
  &quot;id&quot; =&gt; 1834315462,
  &quot;last_error&quot; =&gt; nil,
  &quot;locked_at&quot; =&gt; &quot;2025-04-17T15:01:20.000Z&quot;,
  &quot;locked_by&quot; =&gt; &quot;delayed_job.1030 host:api pid:11345&quot;,
  &quot;priority&quot; =&gt; 0,
  &quot;queue&quot; =&gt; &quot;default&quot;,
  &quot;run_at&quot; =&gt; &quot;2025-04-17T14:36:23.000Z&quot;
}
~~~

## Session ##
~~~
{}
~~~

## Backtrace ##
~~~
151:  /GEM_ROOT/gems/mysql2-0.5.6/lib/mysql2/client.rb -> **&#39;Mysql2::Client#_query&#39;**
151:  /GEM_ROOT/gems/mysql2-0.5.6/lib/mysql2/client.rb -> **&#39;block in Mysql2::Client#query&#39;**
150:  /GEM_ROOT/gems/mysql2-0.5.6/lib/mysql2/client.rb -> **&#39;Thread.handle_interrupt&#39;**
150:  /GEM_ROOT/gems/mysql2-0.5.6/lib/mysql2/client.rb -> **&#39;Mysql2::Client#query&#39;**
100:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/connection_adapters/mysql2/database_statements.rb -> **&#39;block (2 levels) in ActiveRecord::ConnectionAdapters::Mysql2::DatabaseStatements#raw_execute&#39;**
1027:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/connection_adapters/abstract_adapter.rb -> **&#39;block in ActiveRecord::ConnectionAdapters::AbstractAdapter#with_raw_connection&#39;**
9:  /GEM_ROOT/gems/activesupport-7.1.5.1/lib/active_support/concurrency/null_lock.rb -> **&#39;ActiveSupport::Concurrency::NullLock#synchronize&#39;**
999:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/connection_adapters/abstract_adapter.rb -> **&#39;ActiveRecord::ConnectionAdapters::AbstractAdapter#with_raw_connection&#39;**
98:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/connection_adapters/mysql2/database_statements.rb -> **&#39;block in ActiveRecord::ConnectionAdapters::Mysql2::DatabaseStatements#raw_execute&#39;**
58:  /GEM_ROOT/gems/activesupport-7.1.5.1/lib/active_support/notifications/instrumenter.rb -> **&#39;ActiveSupport::Notifications::Instrumenter#instrument&#39;**
1142:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/connection_adapters/abstract_adapter.rb -> **&#39;ActiveRecord::ConnectionAdapters::AbstractAdapter#log&#39;**
97:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/connection_adapters/mysql2/database_statements.rb -> **&#39;ActiveRecord::ConnectionAdapters::Mysql2::DatabaseStatements#raw_execute&#39;**
233:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb -> **&#39;ActiveRecord::ConnectionAdapters::AbstractMysqlAdapter#execute_and_free&#39;**
45:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/connection_adapters/mysql2/database_statements.rb -> **&#39;block in ActiveRecord::ConnectionAdapters::Mysql2::DatabaseStatements#exec_delete&#39;**
1027:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/connection_adapters/abstract_adapter.rb -> **&#39;block in ActiveRecord::ConnectionAdapters::AbstractAdapter#with_raw_connection&#39;**
9:  /GEM_ROOT/gems/activesupport-7.1.5.1/lib/active_support/concurrency/null_lock.rb -> **&#39;ActiveSupport::Concurrency::NullLock#synchronize&#39;**
999:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/connection_adapters/abstract_adapter.rb -> **&#39;ActiveRecord::ConnectionAdapters::AbstractAdapter#with_raw_connection&#39;**
43:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/connection_adapters/mysql2/database_statements.rb -> **&#39;ActiveRecord::ConnectionAdapters::Mysql2::DatabaseStatements#exec_delete&#39;**
208:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb -> **&#39;ActiveRecord::ConnectionAdapters::DatabaseStatements#delete&#39;**
25:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/connection_adapters/abstract/query_cache.rb -> **&#39;ActiveRecord::ConnectionAdapters::AbstractAdapter#delete&#39;**
624:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/persistence.rb -> **&#39;ActiveRecord::Persistence::ClassMethods#_delete_record&#39;**
1198:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/persistence.rb -> **&#39;ActiveRecord::Persistence#_delete_row&#39;**
1194:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/persistence.rb -> **&#39;ActiveRecord::Persistence#destroy_row&#39;**
198:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/counter_cache.rb -> **&#39;ActiveRecord::CounterCache#destroy_row&#39;**
125:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/locking/optimistic.rb -> **&#39;ActiveRecord::Locking::Optimistic#destroy_row&#39;**
783:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/persistence.rb -> **&#39;ActiveRecord::Persistence#destroy&#39;**
423:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/callbacks.rb -> **&#39;block in ActiveRecord::Callbacks#destroy&#39;**
110:  /GEM_ROOT/gems/activesupport-7.1.5.1/lib/active_support/callbacks.rb -> **&#39;ActiveSupport::Callbacks#run_callbacks&#39;**
20:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rails/active_record.rb -> **&#39;Airbrake::Rails::ActiveRecord#run_callbacks&#39;**
952:  /GEM_ROOT/gems/activesupport-7.1.5.1/lib/active_support/callbacks.rb -> **&#39;ActiveRecord::Base#_run_destroy_callbacks&#39;**
423:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/callbacks.rb -> **&#39;ActiveRecord::Callbacks#destroy&#39;**
305:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/transactions.rb -> **&#39;block in ActiveRecord::Transactions#destroy&#39;**
365:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/transactions.rb -> **&#39;block in ActiveRecord::Transactions#with_transaction_returning_status&#39;**
342:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb -> **&#39;ActiveRecord::ConnectionAdapters::DatabaseStatements#transaction&#39;**
361:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/transactions.rb -> **&#39;ActiveRecord::Transactions#with_transaction_returning_status&#39;**
305:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/transactions.rb -> **&#39;ActiveRecord::Transactions#destroy&#39;**
67:  app/models/bs_request_action_delete.rb -> **&#39;BsRequestActionDelete#execute_accept&#39;**
516:  app/models/bs_request.rb -> **&#39;block in BsRequest#changestate_accepted&#39;**
100:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/relation/delegation.rb -> **&#39;Array#each&#39;**
100:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/relation/delegation.rb -> **&#39;ActiveRecord::Delegation#each&#39;**
515:  app/models/bs_request.rb -> **&#39;BsRequest#changestate_accepted&#39;**
542:  app/models/bs_request.rb -> **&#39;block in BsRequest#change_state&#39;**
97:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/locking/pessimistic.rb -> **&#39;block in ActiveRecord::Locking::Pessimistic#with_lock&#39;**
342:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb -> **&#39;ActiveRecord::ConnectionAdapters::DatabaseStatements#transaction&#39;**
212:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/transactions.rb -> **&#39;ActiveRecord::Transactions::ClassMethods#transaction&#39;**
301:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/transactions.rb -> **&#39;ActiveRecord::Transactions#transaction&#39;**
95:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/locking/pessimistic.rb -> **&#39;ActiveRecord::Locking::Pessimistic#with_lock&#39;**
539:  app/models/bs_request.rb -> **&#39;BsRequest#change_state&#39;**
850:  app/models/bs_request.rb -> **&#39;block (2 levels) in BsRequest#auto_accept&#39;**
809:  app/models/user.rb -> **&#39;User#run_as&#39;**
846:  app/models/bs_request.rb -> **&#39;block in BsRequest#auto_accept&#39;**
97:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/locking/pessimistic.rb -> **&#39;block in ActiveRecord::Locking::Pessimistic#with_lock&#39;**
535:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/connection_adapters/abstract/transaction.rb -> **&#39;block in ActiveRecord::ConnectionAdapters::TransactionManager#within_new_transaction&#39;**
9:  /GEM_ROOT/gems/activesupport-7.1.5.1/lib/active_support/concurrency/null_lock.rb -> **&#39;ActiveSupport::Concurrency::NullLock#synchronize&#39;**
532:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/connection_adapters/abstract/transaction.rb -> **&#39;ActiveRecord::ConnectionAdapters::TransactionManager#within_new_transaction&#39;**
344:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb -> **&#39;ActiveRecord::ConnectionAdapters::DatabaseStatements#transaction&#39;**
212:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/transactions.rb -> **&#39;ActiveRecord::Transactions::ClassMethods#transaction&#39;**
301:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/transactions.rb -> **&#39;ActiveRecord::Transactions#transaction&#39;**
95:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/locking/pessimistic.rb -> **&#39;ActiveRecord::Locking::Pessimistic#with_lock&#39;**
840:  app/models/bs_request.rb -> **&#39;BsRequest#auto_accept&#39;**
4:  app/jobs/bs_request_auto_accept_job.rb -> **&#39;BsRequestAutoAcceptJob#perform&#39;**
68:  /GEM_ROOT/gems/activejob-7.1.5.1/lib/active_job/execution.rb -> **&#39;block in ActiveJob::Execution#_perform_job&#39;**
121:  /GEM_ROOT/gems/activesupport-7.1.5.1/lib/active_support/callbacks.rb -> **&#39;block in ActiveSupport::Callbacks#run_callbacks&#39;**
353:  /GEM_ROOT/gems/i18n-1.14.7/lib/i18n.rb -> **&#39;I18n::Base#with_locale&#39;**
9:  /GEM_ROOT/gems/activejob-7.1.5.1/lib/active_job/translation.rb -> **&#39;block (2 levels) in &lt;module:Translation&gt;&#39;**
130:  /GEM_ROOT/gems/activesupport-7.1.5.1/lib/active_support/callbacks.rb -> **&#39;BasicObject#instance_exec&#39;**
130:  /GEM_ROOT/gems/activesupport-7.1.5.1/lib/active_support/callbacks.rb -> **&#39;block in ActiveSupport::Callbacks#run_callbacks&#39;**
65:  /GEM_ROOT/gems/activesupport-7.1.5.1/lib/active_support/core_ext/time/zones.rb -> **&#39;Time.use_zone&#39;**
9:  /GEM_ROOT/gems/activejob-7.1.5.1/lib/active_job/timezones.rb -> **&#39;block (2 levels) in &lt;module:Timezones&gt;&#39;**
130:  /GEM_ROOT/gems/activesupport-7.1.5.1/lib/active_support/callbacks.rb -> **&#39;BasicObject#instance_exec&#39;**
130:  /GEM_ROOT/gems/activesupport-7.1.5.1/lib/active_support/callbacks.rb -> **&#39;block in ActiveSupport::Callbacks#run_callbacks&#39;**
141:  /GEM_ROOT/gems/activesupport-7.1.5.1/lib/active_support/callbacks.rb -> **&#39;ActiveSupport::Callbacks#run_callbacks&#39;**
67:  /GEM_ROOT/gems/activejob-7.1.5.1/lib/active_job/execution.rb -> **&#39;ActiveJob::Execution#_perform_job&#39;**
32:  /GEM_ROOT/gems/activejob-7.1.5.1/lib/active_job/instrumentation.rb -> **&#39;ActiveJob::Instrumentation#_perform_job&#39;**
51:  /GEM_ROOT/gems/activejob-7.1.5.1/lib/active_job/execution.rb -> **&#39;ActiveJob::Execution#perform_now&#39;**
26:  /GEM_ROOT/gems/activejob-7.1.5.1/lib/active_job/instrumentation.rb -> **&#39;block in ActiveJob::Instrumentation#perform_now&#39;**
13:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/railties/job_runtime.rb -> **&#39;block in ActiveRecord::Railties::JobRuntime#instrument&#39;**
40:  /GEM_ROOT/gems/activejob-7.1.5.1/lib/active_job/instrumentation.rb -> **&#39;block in ActiveJob::Instrumentation#instrument&#39;**
206:  /GEM_ROOT/gems/activesupport-7.1.5.1/lib/active_support/notifications.rb -> **&#39;block in ActiveSupport::Notifications.instrument&#39;**
58:  /GEM_ROOT/gems/activesupport-7.1.5.1/lib/active_support/notifications/instrumenter.rb -> **&#39;ActiveSupport::Notifications::Instrumenter#instrument&#39;**
206:  /GEM_ROOT/gems/activesupport-7.1.5.1/lib/active_support/notifications.rb -> **&#39;ActiveSupport::Notifications.instrument&#39;**
39:  /GEM_ROOT/gems/activejob-7.1.5.1/lib/active_job/instrumentation.rb -> **&#39;ActiveJob::Instrumentation#instrument&#39;**
11:  /GEM_ROOT/gems/activerecord-7.1.5.1/lib/active_record/railties/job_runtime.rb -> **&#39;ActiveRecord::Railties::JobRuntime#instrument&#39;**
26:  /GEM_ROOT/gems/activejob-7.1.5.1/lib/active_job/instrumentation.rb -> **&#39;ActiveJob::Instrumentation#perform_now&#39;**
18:  /GEM_ROOT/gems/activejob-7.1.5.1/lib/active_job/logging.rb -> **&#39;block in ActiveJob::Logging#perform_now&#39;**
139:  /GEM_ROOT/gems/activesupport-7.1.5.1/lib/active_support/tagged_logging.rb -> **&#39;block in ActiveSupport::TaggedLogging#tagged&#39;**
39:  /GEM_ROOT/gems/activesupport-7.1.5.1/lib/active_support/tagged_logging.rb -> **&#39;ActiveSupport::TaggedLogging::Formatter#tagged&#39;**
139:  /GEM_ROOT/gems/activesupport-7.1.5.1/lib/active_support/tagged_logging.rb -> **&#39;ActiveSupport::TaggedLogging#tagged&#39;**
241:  /GEM_ROOT/gems/activesupport-7.1.5.1/lib/active_support/broadcast_logger.rb -> **&#39;ActiveSupport::BroadcastLogger#method_missing&#39;**
25:  /GEM_ROOT/gems/activejob-7.1.5.1/lib/active_job/logging.rb -> **&#39;ActiveJob::Logging#tag_logger&#39;**
18:  /GEM_ROOT/gems/activejob-7.1.5.1/lib/active_job/logging.rb -> **&#39;ActiveJob::Logging#perform_now&#39;**
29:  /GEM_ROOT/gems/activejob-7.1.5.1/lib/active_job/execution.rb -> **&#39;block in ActiveJob::Execution::ClassMethods#execute&#39;**
121:  /GEM_ROOT/gems/activesupport-7.1.5.1/lib/active_support/callbacks.rb -> **&#39;block in ActiveSupport::Callbacks#run_callbacks&#39;**
67:  /GEM_ROOT/gems/activejob-7.1.5.1/lib/active_job/railtie.rb -> **&#39;block (4 levels) in &lt;class:Railtie&gt;&#39;**
77:  /GEM_ROOT/gems/activesupport-7.1.5.1/lib/active_support/reloader.rb -> **&#39;block in ActiveSupport::Reloader.wrap&#39;**
92:  /GEM_ROOT/gems/activesupport-7.1.5.1/lib/active_support/execution_wrapper.rb -> **&#39;ActiveSupport::ExecutionWrapper.wrap&#39;**
74:  /GEM_ROOT/gems/activesupport-7.1.5.1/lib/active_support/reloader.rb -> **&#39;ActiveSupport::Reloader.wrap&#39;**
66:  /GEM_ROOT/gems/activejob-7.1.5.1/lib/active_job/railtie.rb -> **&#39;block (3 levels) in &lt;class:Railtie&gt;&#39;**
130:  /GEM_ROOT/gems/activesupport-7.1.5.1/lib/active_support/callbacks.rb -> **&#39;BasicObject#instance_exec&#39;**
130:  /GEM_ROOT/gems/activesupport-7.1.5.1/lib/active_support/callbacks.rb -> **&#39;block in ActiveSupport::Callbacks#run_callbacks&#39;**
141:  /GEM_ROOT/gems/activesupport-7.1.5.1/lib/active_support/callbacks.rb -> **&#39;ActiveSupport::Callbacks#run_callbacks&#39;**
27:  /GEM_ROOT/gems/activejob-7.1.5.1/lib/active_job/execution.rb -> **&#39;ActiveJob::Execution::ClassMethods#execute&#39;**
47:  /GEM_ROOT/gems/activejob-7.1.5.1/lib/active_job/queue_adapters/delayed_job_adapter.rb -> **&#39;ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper#perform&#39;**
81:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/backend/base.rb -> **&#39;block in Delayed::Backend::Base#invoke_job&#39;**
10:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/delayed_job.rb -> **&#39;block (2 levels) in &lt;class:Airbrake&gt;&#39;**
79:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/lifecycle.rb -> **&#39;block (2 levels) in Delayed::Callback#add&#39;**
61:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/lifecycle.rb -> **&#39;block in Delayed::Callback#initialize&#39;**
79:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/lifecycle.rb -> **&#39;block in Delayed::Callback#add&#39;**
66:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/lifecycle.rb -> **&#39;Delayed::Callback#execute&#39;**
40:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/lifecycle.rb -> **&#39;Delayed::Lifecycle#run_callbacks&#39;**
78:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/backend/base.rb -> **&#39;Delayed::Backend::Base#invoke_job&#39;**
231:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/worker.rb -> **&#39;block (2 levels) in Delayed::Worker#run&#39;**
185:  /GEM_ROOT/gems/timeout-0.4.3/lib/timeout.rb -> **&#39;block in Timeout.timeout&#39;**
192:  /GEM_ROOT/gems/timeout-0.4.3/lib/timeout.rb -> **&#39;Timeout.timeout&#39;**
231:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/worker.rb -> **&#39;block in Delayed::Worker#run&#39;**
323:  /GEM_ROOT/gems/benchmark-0.4.0/lib/benchmark.rb -> **&#39;Benchmark.realtime&#39;**
230:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/worker.rb -> **&#39;Delayed::Worker#run&#39;**
313:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/worker.rb -> **&#39;block in Delayed::Worker#reserve_and_run_one_job&#39;**
61:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/lifecycle.rb -> **&#39;block in Delayed::Callback#initialize&#39;**
66:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/lifecycle.rb -> **&#39;Delayed::Callback#execute&#39;**
40:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/lifecycle.rb -> **&#39;Delayed::Lifecycle#run_callbacks&#39;**
313:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/worker.rb -> **&#39;Delayed::Worker#reserve_and_run_one_job&#39;**
214:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/worker.rb -> **&#39;block in Delayed::Worker#work_off&#39;**
257:  &lt;internal:numeric&gt; -> **&#39;Integer#times&#39;**
213:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/worker.rb -> **&#39;Delayed::Worker#work_off&#39;**
176:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/worker.rb -> **&#39;block (4 levels) in Delayed::Worker#start&#39;**
323:  /GEM_ROOT/gems/benchmark-0.4.0/lib/benchmark.rb -> **&#39;Benchmark.realtime&#39;**
175:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/worker.rb -> **&#39;block (3 levels) in Delayed::Worker#start&#39;**
61:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/lifecycle.rb -> **&#39;block in Delayed::Callback#initialize&#39;**
66:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/lifecycle.rb -> **&#39;Delayed::Callback#execute&#39;**
40:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/lifecycle.rb -> **&#39;Delayed::Lifecycle#run_callbacks&#39;**
174:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/worker.rb -> **&#39;block (2 levels) in Delayed::Worker#start&#39;**
168:  &lt;internal:kernel&gt; -> **&#39;Kernel#loop&#39;**
173:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/worker.rb -> **&#39;block in Delayed::Worker#start&#39;**
7:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/plugins/clear_locks.rb -> **&#39;block (2 levels) in &lt;class:ClearLocks&gt;&#39;**
79:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/lifecycle.rb -> **&#39;block (2 levels) in Delayed::Callback#add&#39;**
61:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/lifecycle.rb -> **&#39;block in Delayed::Callback#initialize&#39;**
79:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/lifecycle.rb -> **&#39;block in Delayed::Callback#add&#39;**
66:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/lifecycle.rb -> **&#39;Delayed::Callback#execute&#39;**
40:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/lifecycle.rb -> **&#39;Delayed::Lifecycle#run_callbacks&#39;**
172:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/worker.rb -> **&#39;Delayed::Worker#start&#39;**
137:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/command.rb -> **&#39;Delayed::Command#run&#39;**
125:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/command.rb -> **&#39;block in Delayed::Command#run_process&#39;**
277:  /GEM_ROOT/gems/daemons-1.4.1/lib/daemons/application.rb -> **&#39;block in Daemons::Application#start_proc&#39;**
84:  /GEM_ROOT/gems/daemons-1.4.1/lib/daemons/daemonize.rb -> **&#39;Daemonize.call_as_daemon&#39;**
281:  /GEM_ROOT/gems/daemons-1.4.1/lib/daemons/application.rb -> **&#39;Daemons::Application#start_proc&#39;**
307:  /GEM_ROOT/gems/daemons-1.4.1/lib/daemons/application.rb -> **&#39;Daemons::Application#start&#39;**
56:  /GEM_ROOT/gems/daemons-1.4.1/lib/daemons/controller.rb -> **&#39;Daemons::Controller#run&#39;**
199:  /GEM_ROOT/gems/daemons-1.4.1/lib/daemons.rb -> **&#39;block in Daemons.run_proc&#39;**
124:  /GEM_ROOT/gems/daemons-1.4.1/lib/daemons/cmdline.rb -> **&#39;Daemons::Controller#catch_exceptions&#39;**
198:  /GEM_ROOT/gems/daemons-1.4.1/lib/daemons.rb -> **&#39;Daemons.run_proc&#39;**
123:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/command.rb -> **&#39;Delayed::Command#run_process&#39;**
98:  /GEM_ROOT/gems/delayed_job-4.1.13/lib/delayed/command.rb -> **&#39;Delayed::Command#daemonize&#39;**
5:  script/delayed_job.api.rb -> **&#39;&lt;top (required)&gt;&#39;**
59:  /usr/lib64/ruby/3.4.0/bundler/cli/exec.rb -> **&#39;Kernel.load&#39;**
59:  /usr/lib64/ruby/3.4.0/bundler/cli/exec.rb -> **&#39;Bundler::CLI::Exec#kernel_load&#39;**
23:  /usr/lib64/ruby/3.4.0/bundler/cli/exec.rb -> **&#39;Bundler::CLI::Exec#run&#39;**
452:  /usr/lib64/ruby/3.4.0/bundler/cli.rb -> **&#39;Bundler::CLI#exec&#39;**
28:  /usr/lib64/ruby/3.4.0/bundler/vendor/thor/lib/thor/command.rb -> **&#39;Bundler::Thor::Command#run&#39;**
127:  /usr/lib64/ruby/3.4.0/bundler/vendor/thor/lib/thor/invocation.rb -> **&#39;Bundler::Thor::Invocation#invoke_command&#39;**
538:  /usr/lib64/ruby/3.4.0/bundler/vendor/thor/lib/thor.rb -> **&#39;Bundler::Thor.dispatch&#39;**
35:  /usr/lib64/ruby/3.4.0/bundler/cli.rb -> **&#39;Bundler::CLI.dispatch&#39;**
584:  /usr/lib64/ruby/3.4.0/bundler/vendor/thor/lib/thor/base.rb -> **&#39;Bundler::Thor::Base::ClassMethods#start&#39;**
29:  /usr/lib64/ruby/3.4.0/bundler/cli.rb -> **&#39;Bundler::CLI.start&#39;**
28:  /usr/lib64/ruby/gems/3.4.0/gems/bundler-2.6.2/exe/bundle -> **&#39;block in &lt;top (required)&gt;&#39;**
117:  /usr/lib64/ruby/3.4.0/bundler/friendly_errors.rb -> **&#39;Bundler.with_friendly_errors&#39;**
20:  /usr/lib64/ruby/gems/3.4.0/gems/bundler-2.6.2/exe/bundle -> **&#39;&lt;top (required)&gt;&#39;**
25:  /usr/bin/bundle.ruby3.4 -> **&#39;Kernel#load&#39;**
25:  /usr/bin/bundle.ruby3.4 -> **&#39;&lt;main&gt;&#39;**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| program_name | delayed_job.1030 |
| HTTP_USER_AGENT |  |

### PR DESCRIPTION
**Pull request by danidoni**
Fixes #17745

### CODE REVIEW

**Review by hennevogel — APPROVED** [review]

**Comment by hennevogel** [comment]
So we never destroy projects in the test suite?

File: src/api/app/models/project.rb [hunk 1]
```diff
@@ -89,7 +89,7 @@ def staging_history
   has_many :notified_projects, dependent: :destroy
   has_many :notifications, through: :notified_projects
   has_many :reports, as: :reportable, dependent: :nullify
-  has_many :label_templates
+  has_many :label_templates, dependent: :destroy
   has_many :label_globals
```
Comment (eduardoj) [inline src/api/app/models/project.rb:93]:
```suggestion
  has_many :label_globals, dependent: :destroy
```

We should also destroy dependent `label_globals`, I guess... Not tested, tough.

**Comment by danidoni** [comment]
> So we never destroy projects in the test suite?

No, with `label_templates` we don't

File: src/api/app/models/project.rb (hunk 1 above)
Comment (danidoni) [reply src/api/app/models/project.rb:93]: No, Global labels are shared between all projects, if I remove a Global label, then I remove it from all the projects. I think that's not what we want.

**Review by hellcp-work — APPROVED** [review]

**Comment by hennevogel** [comment]
There have been 8970 projects with labels?

File: src/api/app/models/project.rb (hunk 1 above)
Comment (danidoni) [reply src/api/app/models/project.rb:93]: You are right, I always get confused between labels and label templates :facepalm: I'm going to follow-up this one

**Comment by danidoni** [comment]
> There have been 8970 projects with labels? Also what about `label_globals`?

`label_globals` are taken care here https://github.com/openSUSE/open-build-service/pull/17756
