### PR TITLE
[backend] Add `tos_url` to configuration

### LINKED ISSUE #11436: [production][delayed_job#ConfigurationWriteToBackendJob] <status code="400">
  <summary>unknown element 'tos_url'</summary>
</status>
delayed_job#ConfigurationWriteToBackendJob threw this 14 times
<pre>
&lt;status code=&quot;400&quot;&gt;
  &lt;summary&gt;unknown element &#39;tos_url&#39;&lt;/summary&gt;
&lt;/status&gt;

</pre>

[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/6100236e84bf4607e9fd7372)

### PR DESCRIPTION
**Pull request by krauselukas**
The OBS frontend introduced an new field to the configuration
table (https://github.com/openSUSE/open-build-service/pull/11437)
in order to save a URL for the terms of services.
The frontend writes this configuration to the backend through
a delayed job. The backend currently throws an 400 http code,
since it is not aware of the new field.

Fixes #11436

### CODE REVIEW

File: src/backend/BSXML.pm [hunk 1]
```diff
@@ -1650,6 +1650,7 @@ our $configuration = [
     'configuration' =>
 	[],
 	'title',        #webui only
+	'tos_url',      #webui only
```
Comment (krauselukas) [inline src/backend/BSXML.pm:1653]: Sorry my editor removed the trailing spaces, this is the line the I actually added.

Comment (danidoni) [reply src/backend/BSXML.pm:1653]: You can append `?diff=split&w=1` to this PR's url to see the actual changes and discard the whitespaces

**Review by danidoni — APPROVED** [review]

**Review by M0ses — APPROVED** [review]
LGTM
