### PR TITLE
[webui] Trim carriage return characters from attribute values

### LINKED ISSUE #5311: Online edited the attribute that webui saves &#13; in the suffix of each line in value
# Issue Description
Online edited the attribute that webui saves ` &#13; ` in the suffix for each line. I've tried update openSUSE:Leap:15.1/_attribute/OSRT:Config attribute, ` &#13; ` appears in the each line when I dump the content by osc api.

    # osc api /source/openSUSE:Leap:15.1/_attribute/OSRT:Config
    
    <attributes>
      <attribute name="Config" namespace="OSRT">
        <value># restricts what stagings the staging-bot will use, when available, for --try-strategies&#13;
    splitter-whitelist = A C D E&#13;
    &#13;
    # these issues should be resolved, see dashboard/repo_checker for details&#13;
    repo_checker-binary-whitelist = patterns-media-rest_dvd&#13;
    &#13;
    # May be removed once defaults have been distributed via:&#13;
    #   https://github.com/openSUSE/openSUSE-release-tools/pull/1529&#13;
    nocleanup-packages = bootstrap-copy 000product 000release-packages&#13;
    pkglistgen-include-suggested = False&#13;
    &#13;
    check-source-in-air-rename-allow = True&#13;
    &#13;
    # ring 2 was removed, this disables various conditions related to it&#13;
    staging-dvd-archs =&#13;
    </value>
      </attribute>
    </attributes>

Expected Result
============
` &#13; ` should not be there.

How to Reproduce
===============
1. Go to attribute page
2. Click on edit attribute
3. Change something and save
4. Check the result from osc api

Further Information
===============
* https://build.opensuse.org/attribs/openSUSE:Leap:15.1

### PR DESCRIPTION
**Pull request by coolo**
Fixes #5311

### CODE REVIEW

File: src/api/app/models/attrib_value.rb [hunk 1]
```diff
@@ -24,6 +25,10 @@ def default_value
       ''
     end
   end
+
+  def normalize_newlines
+    value.gsub!("\r\n", "\n")
```
Comment (bgeuken) [inline src/api/app/models/attrib_value.rb]: Why does this depend on the newlines?

Comment (coolo) [reply src/api/app/models/attrib_value.rb]: Because I normalize newlines: https://en.wikipedia.org/wiki/Newline

Comment (Ana06) [reply src/api/app/models/attrib_value.rb]: I think what you really want to do is `value.gsub!("\r\n?", "\n")` because you want to convert any of the standard line endings (`\n`, `\r\n`, `\r`) to `\n`, don't you? :thinking: I think that is also what @bgeuken means.

But there is IMO a better approach: using `String#encode` with the `universal_newline` option which is more readable and abstract us of how this happen (the regular expression needed)

Comment (coolo) [reply src/api/app/models/attrib_value.rb]: I was actually looking for such a function and couldn't find any - and stackoverflow suggested gsub

**Comment by coolo** [comment]
@Ana06 changed to encode

**Comment by coolo** [comment]
@Ana06 @bgeuken please rereview

**Comment by coolo** [comment]
@Ana06 - please review
