### PR TITLE
Set review for staged requests if request state new or review

### LINKED ISSUE #8522: Unstaging revoked requests gives 403
Testing #8507 on build-test I noticed that unstaging a request not in `review` gives a misleading response. It returns a 403, but funnily enough still unstage it from the staging project. 

```
coolo@f102#~>tosc request revoke 1760 -m oops
Result of change request state: ok
coolo@f102#~>tosc ps request delete openSUSE:Factory -s openSUSE:Factory:Staging:A -r 1760
Server returned an error: HTTP Error 403: Forbidden
The request is not in state new or review
coolo@f102#~>tosc -d ps request delete openSUSE:Factory -s openSUSE:Factory:Staging:A -r 1760
DELETE https://api-test.opensuse.org/staging/openSUSE:Factory/staging_projects/openSUSE:Factory:Staging:A/staged_requests
Server returned an error: HTTP Error 400: Bad Request
```

### PR DESCRIPTION
**Pull request by vpereira**
Fixes #8522 

Just update the reviews in a request if the request state is `new` or `review`

Add a spec to test to cover the case where request state is `revoked`

### CODE REVIEW

File: src/api/app/models/staging/staged_requests.rb [hunk 1]
```diff
@@ -29,7 +29,7 @@ def destroy
     not_deleted_packages = package_names - result.pluck(:name)
 
     requests.each do |request|
-      add_review_for_unstaged_request(request)
+      add_review_for_unstaged_request(request) if [:review, :new].include?(request.state.to_sym)
```
Comment (coolo) [inline src/api/app/models/staging/staged_requests.rb]: there is tons of code like `req.state.in?([:review, :new])` and `@bs_request.state.in?([:new, :review])` so I don't think you need .to_sym, but should prefer `.in?` for consistency.

And btw, I found this gem:
```
app/models/bs_request.rb:    unless state == :review || (state == :new && state == :new)
```

Comment (vpereira) [reply src/api/app/models/staging/staged_requests.rb]: > there is tons of code like `req.state.in?([:review, :new])` and `@bs_request.state.in?([:new, :review])` so I don't think you need .to_sym, but should prefer `.in?` for consistency.

Yup, i will do it like that, thanks!

> And btw, I found this gem:
> 
> ```
> app/models/bs_request.rb:    unless state == :review || (state == :new && state == :new)
> ```
:pray: TGIF :pray:

Comment (vpereira) [reply src/api/app/models/staging/staged_requests.rb]: done @coolo
