### PR TITLE
Fix reporting of BsRequests by using internal ID

### LINKED ISSUE #19236: "Report Request" dialog appears to be broken
# Issue Description
https://build.opensuse.org/requests/1330302  Appears to be a Spam/Scam/Something delete request
As a moderator, I had a user attempt to file a report on this DR, and it didn't work

I went and attempted to report it myself, by clicking the "Report Request" link in the sidebar, and the Report Dialog comes up, but the Submit button does nothing, and as a Moderator, I never recieve the report, to take action on.

Expected Result
============
Fill out the information in the Report, and press the submit button, and the report shows up in the moderation requests.

How to Reproduce
===============
1. Go to https://build.opensuse.org/requests/1330302
2. Click on "Report Request"
3. Fill out the Report Dialog
4. Press Submit

### PR DESCRIPTION
**Pull request by geetxnshgoyal**
This PR resolves issue #19236 where the "Report Request" dialog was broken and non-functional for moderators and users.

The failure was caused by two main issues:

1. **Polymorphic ID Mismatch**: The sidebar link for "Report Request" was passing `bs_request.number` (the business number) as the `reportable-id`. Because the [Report](cci:2://file:///Users/geetanshgoyal/open-build-service/src/api/app/models/report.rb:1:0-88:3) model uses a polymorphic [reportable](cci:1://file:///Users/geetanshgoyal/open-build-service/src/api/app/models/report.rb:40:2-44:5) association, Rails expects the internal database [id](cci:1://file:///Users/geetanshgoyal/open-build-service/src/api/app/models/bs_request.rb:361:2-364:5). On instances where the request number and internal ID differ, the backend would fail to find the request, causing a validation error (`Reportable must exist`) and preventing the report from being saved.
2. **Missing UI Elements**: The [_report_modal.html.haml](cci:7://file:///Users/geetanshgoyal/open-build-service/src/api/app/views/webui/shared/_report_modal.html.haml:0:0-0:0) partial was missing the `.modal-header` and `.modal-title` elements. The JavaScript in [report.js](cci:7://file:///Users/geetanshgoyal/open-build-service/src/api/app/assets/javascripts/webui/report.js:0:0-0:0) specifically looks for `.modal-title` to dynamically set the header (e.g., "Report 1330302"). Without these, the modal would appear without a title or a proper close button.

I have also added a guard clause in `ReportPolicy#create?` to return `false` if the reportable object is `nil`, preventing potential `NoMethodError` crashes if an invalid ID is passed to the reports controller.

#### Verification Steps
1. Ensure the `content_moderation` feature toggle is enabled for your user.
2. Navigate to any request that you did not create (e.g., `https://localhost:3000/requests/1`).
3. Click the **"Report Request"** flag in the sidebar.
4. **Verify**: The modal title should correctly display "Report [Request Number]".
5. Fill out the radio buttons and reason, then click **Submit**.
6. **Verify**: A success flash message should appear, the "Report" link should disappear (replaced by a "You reported this" message), and a new [Report](cci:2://file:///Users/geetanshgoyal/open-build-service/src/api/app/models/report.rb:1:0-88:3) record should be created in the database.

Fixes #19236

### CODE REVIEW

File: src/api/app/controllers/webui/groups/users_controller.rb [hunk 1]
```diff
@@ -15,7 +15,7 @@ def create
           return
         end
 
-        group_user = GroupsUser.create(user: user, group: @group)
+        group_user = GroupsUser.create(user: user, group: @group, user_session_login: User.session.login)
```
Comment (hennevogel) [inline src/api/app/controllers/webui/groups/users_controller.rb]: `User.session` is a thread variable that you for sure not need to pass around. And if no one is signed in, it's `nil`.

Comment (geetxnshgoyal) [reply src/api/app/controllers/webui/groups/users_controller.rb]: You're right, passing `User.session` manually was redundant I've refactored the implementation to rely on the thread-local `User.session` directly within the model and event layer The controllers have been reverted to their original state, and the `who` payload is now correctly populated within `Group#delete_user`

Comment (geetxnshgoyal) [reply src/api/app/controllers/webui/groups/users_controller.rb]: please check #19247

Comment (geetxnshgoyal) [reply src/api/app/controllers/webui/groups/users_controller.rb]: i mistakenly made pushed my changes in wrong branch

File: src/api/app/policies/report_policy.rb [hunk 2]
```diff
@@ -23,6 +23,7 @@ def show?
   # rubocop:disable Metrics/CyclomaticComplexity
   def create?
     return false unless Flipper.enabled?(:content_moderation, user)
+    return false if record.reportable.nil?
```
Comment (hennevogel) [inline src/api/app/policies/report_policy.rb]: This is a validation that is already happening in [`Report`](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/models/report.rb#L14) and not something the policy should be concerned with.

Comment (geetxnshgoyal) [reply src/api/app/policies/report_policy.rb]: i have removed this duplicate change!!
