### PR TITLE
Handle the Psych::SyntaxError exception in case workflows.yml isnt a …

### LINKED ISSUE #11279: [production][trigger_workflow#create] (<unknown>): mapping values are not allowed in this context at line 4 column 38
trigger_workflow#create threw this 1 times
<pre>
(&lt;unknown&gt;): mapping values are not allowed in this context at line 4 column 38
</pre>
[https://build.opensuse.org/trigger/workflow?id=5032](https://build.opensuse.org/trigger/workflow?id=5032)"

[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/60cb66d384bf4607a859d062)

### PR DESCRIPTION
**Pull request by vpereira**
Fixes #11279

### CODE REVIEW

File: src/api/app/services/workflows/yaml_to_workflows_service.rb [hunk 1]
```diff
@@ -13,7 +13,12 @@ def call
     private
 
     def create_workflows
-      parsed_workflows_yaml = YAML.safe_load(File.read(@yaml_file))
+      begin
+        parsed_workflows_yaml = YAML.safe_load(File.read(@yaml_file))
+      rescue Psych::SyntaxError
```
Comment (dmarcoux) [inline src/api/app/services/workflows/yaml_to_workflows_service.rb:18]: Could it be useful to put the message from `Psych::SyntaxError`? I'm wondering because I don't know what exactly the message could be.

So the code would then be:
```ruby
      rescue Psych::SyntaxError => e
        raise WorkflowsYamlNotParsable, "Unable to parse .obs/workflows.yml: #{e.message}"
      end
```

Comment (vpereira) [reply src/api/app/services/workflows/yaml_to_workflows_service.rb]: the message is what we see in the errbit error.. maybe useful for the user, not sure. Without having the yaml file is definitely not useful.

File: src/api/app/models/token/errors.rb [hunk 2]
```diff
@@ -12,4 +12,8 @@ class NonExistentWorkflowsFile < APIError
   class SCMTokenInvalid < APIError
     setup 401
   end
+
+  class WorkflowsYamlNotParsable < APIError
```
Comment (dmarcoux) [inline src/api/app/models/token/errors.rb:16]: This error isn't really related to the `Token` models. Maybe `src/api/app/models/workflow/errors.rb` would be a better location. That file doesn't exist yet, so it needs to be created.

File: src/api/app/services/workflows/yaml_to_workflows_service.rb [hunk 3]
```diff
@@ -13,7 +13,12 @@ def call
     private
 
     def create_workflows
-      parsed_workflows_yaml = YAML.safe_load(File.read(@yaml_file))
+      begin
+        parsed_workflows_yaml = YAML.safe_load(File.read(@yaml_file))
+      rescue Psych::SyntaxError => e
+        raise WorkflowsYamlNotParsable, "Unable to parse .obs/workflows.yml: #{e.message}"
```
Comment (dmarcoux) [inline src/api/app/services/workflows/yaml_to_workflows_service.rb:19]: This line is wrong:

```
NameError: uninitialized constant Workflows::YAMLToWorkflowsService::WorkflowsYamlNotParsable
```

We should have a spec to cover that this line correctly raises.

**Review by dmarcoux — CHANGES_REQUESTED** [review]

File: src/api/app/services/workflows/yaml_to_workflows_service.rb (hunk 1 above)
Comment (dmarcoux) [reply src/api/app/services/workflows/yaml_to_workflows_service.rb]: They know that it's the `.obs/workflows.yml` file from their SCM repository, so it can help them.

File: src/api/app/models/token/errors.rb (hunk 2 above)
Comment (vpereira) [reply src/api/app/models/token/errors.rb:16]: yes, later maybe

File: src/api/spec/services/workflows/yaml_to_workflows_service_spec.rb [hunk 4]
```diff
@@ -19,5 +20,12 @@
         expect(service.call.first).to be_a(Workflow)
       end
     end
+
+    context 'with a invalid workflows.yml' do
+      it 'initializes a workflow object' do
```
Comment (dmarcoux) [inline src/api/spec/services/workflows/yaml_to_workflows_service_spec.rb:25]:
```suggestion
      it 'raises a user-friendly error' do
```

**Review by dmarcoux — APPROVED** [review]

**Comment by vpereira** [comment]
[Error reporting in TriggerWorkflowController](https://trello.com/c/0pqiG1zx/1698-error-reporting-in-triggerworkflowcontroller)
