### PR TITLE
[frontend] Skip diff generation if source is on remote

### LINKED ISSUE #3587: EventMailer: Requests from remote projects
When submitting packages from remote projects to local projects `EventMailer` tries to generate a diff but that fails in a [access check](../blob/master/src/api/app/models/bs_request_action.rb#L922) because the it uses

```
Package.find_by_project_and_name(source_project, source_package)
```

which returns nil for remote projects. It the wanders off into the `if sp.nil?` and tries `User.-current.can_modify_project?` which fails miserably because there is no user logged in during delayed jobs.

### PR DESCRIPTION
**Pull request by hennevogel**
Fixes #3587

### CODE REVIEW

File: src/api/app/models/event/request.rb [hunk 1]
```diff
@@ -70,11 +70,14 @@ def calculate_diff(a)
     end
   end
 
-  def payload_with_diff
-    source_projects = payload['actions'].map { |action| action[:source_project] }.uniq.compact
-    source_projects.each do |source_project|
-      return payload if Project.unscoped.is_remote_project?(source_project, true)
+  def source_from_remote?
```
Comment (Ana06) [inline src/api/app/models/event/request.rb]: this will return `true` or `nil`, I would prefer returning `true` or `false`. So:

``` Ruby
def source_from_remote?
  payload['actions'].each do |action|
    return true if Project.unscoped.is_remote_project?(action['sourceproject'], true)
  end
  false
end
```

Comment (hennevogel) [reply src/api/app/models/event/request.rb]: done
