### PR TITLE
Pass API requests with a valid `view` parameter to the backend

### LINKED ISSUE #8797: route GET /source/<project>?view is broken
# Issue Description

The route `GET /source/<package>?view` appears to be broken:
``` ShellSession
$ curl --user $OBS_USERNAME:$OBS_PASSWORD 'https://api.opensuse.org/source/openSUSE:Factory?view'
<status code="400">
  <summary>unknown parameter 'view'</summary>
</status>
```

Expected Result
============

Should return a list of issues as described [here](https://build.opensuse.org/apidocs/index#49).

### PR DESCRIPTION
**Pull request by eduardoj**
This PR improves the error message returned when the `view` parameter has not a valid value for `GET /source/{project_name}` API endpoint requests.

To see the permited values the `view` parameter can be passed to the backend take a look at the backend router, [here](https://github.com/openSUSE/open-build-service/blob/81eca94d4516ac656c842a6e0f845963f88dda09/src/backend/bs_srcserver#L7648).

Fixes #8797.

## Before

```
> curl -u Admin:opensuse "http://localhost:3000/source/home:Admin?view"
<status code="400">
  <summary>unknown parameter 'view'</summary>
</status>
```

## After

```
> curl -u Admin:opensuse "http://localhost:3000/source/home:Admin?view"
<status code="invalid_parameter">
  <summary>Parameter 'view' doesn't accept value ''</summary>
</status>
```

### CODE REVIEW

File: src/api/app/controllers/source_project_controller.rb [hunk 1]
```diff
@@ -33,8 +33,10 @@ def show
         return
       when 'issues'
         render_project_issues
-      else
+      when 'info'
         pass_to_backend
+      else
+        raise InvalidParameterError, "Parameter 'view' doesn't accept value '#{params[:view]}'"
```
Comment (ncounter) [inline src/api/app/controllers/source_project_controller.rb:39]:
```suggestion
        raise InvalidParameterError, "'#{params[:view]}' is not a valid 'view' parameter value."
```

**Review by ncounter — APPROVED** [review]

File: src/api/app/controllers/source_project_controller.rb (hunk 1 above)
Comment (eduardoj) [reply src/api/app/controllers/source_project_controller.rb]: Applied. Thanks!

**Review by saraycp — APPROVED** [review]
