### PR TITLE
Avoid duplicated index in watchlist

### LINKED ISSUE #14700: [production][watched_items#toggle_watched_item] Mysql2::Error: Duplicate entry 'Package-345246-56888' for key 'index_watched_items_on_type_id_and...
[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/639ea74584bf460521649a9d)
# Mysql2::Error: Duplicate entry &#39;Package-345246-56888&#39; for key &#39;index_watched_items_on_type_id_and_user_id&#39; #
### URL ###
[https://build.opensuse.org/projects/devel:tools:building/packages/jenkins/toggle_watched_item](https://build.opensuse.org/projects/devel:tools:building/packages/jenkins/toggle_watched_item)"
### Where ###
watched_items#toggle_watched_item

### Occured ###
Dec 18  5:38am

### Similar ###
15

## Params ##
~~~
{
  &quot;action&quot; =&gt; &quot;toggle_watched_item&quot;,
  &quot;controller&quot; =&gt; &quot;webui/watched_items&quot;,
  &quot;package_name&quot; =&gt; &quot;jenkins&quot;,
  &quot;project_name&quot; =&gt; &quot;devel:tools:building&quot;
}
~~~

## Session ##
~~~
{
  &quot;_csrf_token&quot; =&gt; &quot;ulqJbiXteKhiWKOZela5DaQGUirnMz1f2GzCWuwPo-g&quot;,
  &quot;session_id&quot; =&gt; &quot;f2f5e2424ca0fbf40285cfcbdbb96bf3&quot;
}
~~~

## Backtrace ##
~~~
148:  /GEM_ROOT/gems/mysql2-0.5.4/lib/mysql2/client.rb -> **_query**
148:  /GEM_ROOT/gems/mysql2-0.5.4/lib/mysql2/client.rb -> **block in query**
147:  /GEM_ROOT/gems/mysql2-0.5.4/lib/mysql2/client.rb -> **handle_interrupt**
147:  /GEM_ROOT/gems/mysql2-0.5.4/lib/mysql2/client.rb -> **query**
632:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb -> **block (2 levels) in raw_execute**
187:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/concurrency/share_lock.rb -> **yield_shares**
41:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/dependencies/interlock.rb -> **permit_concurrent_loads**
631:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb -> **block in raw_execute**
25:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **handle_interrupt**
25:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **block in synchronize**
21:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **handle_interrupt**
21:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **synchronize**
765:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract_adapter.rb -> **block in log**
24:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/notifications/instrumenter.rb -> **instrument**
756:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract_adapter.rb -> **log**
630:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb -> **raw_execute**
96:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/connection_adapters/mysql/database_statements.rb -> **raw_execute**
47:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/connection_adapters/mysql/database_statements.rb -> **execute**
207:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb -> **execute_and_free**
52:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/connection_adapters/mysql/database_statements.rb -> **exec_query**
132:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/database_statements.rb -> **exec_insert**
167:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/database_statements.rb -> **insert**
22:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/query_cache.rb -> **insert**
496:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/persistence.rb -> **_insert_record**
1096:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/persistence.rb -> **_create_record**
166:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/counter_cache.rb -> **_create_record**
79:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/locking/optimistic.rb -> **_create_record**
222:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/attribute_methods/dirty.rb -> **_create_record**
461:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/callbacks.rb -> **block in _create_record**
99:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/callbacks.rb -> **run_callbacks**
20:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rails/active_record.rb -> **run_callbacks**
929:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/callbacks.rb -> **_run_create_callbacks**
461:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/callbacks.rb -> **_create_record**
108:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/timestamp.rb -> **_create_record**
1067:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/persistence.rb -> **create_or_update**
457:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/callbacks.rb -> **block in create_or_update**
107:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/callbacks.rb -> **run_callbacks**
20:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rails/active_record.rb -> **run_callbacks**
929:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/callbacks.rb -> **_run_save_callbacks**
457:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/callbacks.rb -> **create_or_update**
126:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/timestamp.rb -> **create_or_update**
615:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/persistence.rb -> **save**
47:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/validations.rb -> **save**
298:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/transactions.rb -> **block in save**
354:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/transactions.rb -> **block in with_transaction_returning_status**
314:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/database_statements.rb -> **transaction**
350:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/transactions.rb -> **with_transaction_returning_status**
298:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/transactions.rb -> **save**
50:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/suppressor.rb -> **save**
367:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/associations/collection_association.rb -> **insert_record**
58:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/associations/has_many_association.rb -> **insert_record**
352:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/associations/collection_association.rb -> **block (2 levels) in _create_record**
456:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/associations/collection_association.rb -> **replace_on_target**
272:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/associations/collection_association.rb -> **add_to_target**
351:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/associations/collection_association.rb -> **block in _create_record**
319:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/transaction.rb -> **block in within_new_transaction**
25:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **handle_interrupt**
25:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **block in synchronize**
21:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **handle_interrupt**
21:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **synchronize**
317:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/transaction.rb -> **within_new_transaction**
316:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/database_statements.rb -> **transaction**
209:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/transactions.rb -> **transaction**
308:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/associations/collection_association.rb -> **transaction**
349:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/associations/collection_association.rb -> **_create_record**
140:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/associations/has_many_association.rb -> **_create_record**
204:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/associations/association.rb -> **create**
348:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/associations/collection_proxy.rb -> **create**
19:  app/controllers/webui/watched_items_controller.rb -> **toggle_watched_item**
6:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_controller/metal/basic_implicit_render.rb -> **send_action**
215:  /GEM_ROOT/gems/actionpack-7.0.4/lib/abstract_controller/base.rb -> **process_action**
53:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_controller/metal/rendering.rb -> **process_action**
234:  /GEM_ROOT/gems/actionpack-7.0.4/lib/abstract_controller/callbacks.rb -> **block in process_action**
107:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/callbacks.rb -> **run_callbacks**
233:  /GEM_ROOT/gems/actionpack-7.0.4/lib/abstract_controller/callbacks.rb -> **process_action**
22:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_controller/metal/rescue.rb -> **process_action**
67:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_controller/metal/instrumentation.rb -> **block in process_action**
206:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/notifications/instrumenter.rb -> **instrument**
206:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/notifications.rb -> **instrument**
66:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_controller/metal/instrumentation.rb -> **process_action**
259:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_controller/metal/params_wrapper.rb -> **process_action**
27:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/railties/controller_runtime.rb -> **process_action**
151:  /GEM_ROOT/gems/actionpack-7.0.4/lib/abstract_controller/base.rb -> **process**
39:  /GEM_ROOT/gems/actionview-7.0.4/lib/action_view/rendering.rb -> **process**
188:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_controller/metal.rb -> **dispatch**
251:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_controller/metal.rb -> **dispatch**
49:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/routing/route_set.rb -> **dispatch**
32:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/routing/route_set.rb -> **serve**
18:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/routing/mapper.rb -> **block in &lt;class:Constraints&gt;**
48:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/routing/mapper.rb -> **serve**
50:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/journey/router.rb -> **block in serve**
32:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/journey/router.rb -> **each**
32:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/journey/router.rb -> **serve**
852:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/routing/route_set.rb -> **call**
72:  /GEM_ROOT/gems/flipper-0.26.0/lib/flipper/middleware/memoizer.rb -> **memoized_call**
37:  /GEM_ROOT/gems/flipper-0.26.0/lib/flipper/middleware/memoizer.rb -> **call**
15:  config/initializers/prefer_xml_over_html.rb -> **call**
44:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/deflater.rb -> **call**
15:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/tempfile_reaper.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/etag.rb -> **call**
40:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/conditional_get.rb -> **call**
12:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/head.rb -> **call**
38:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/http/permissions_policy.rb -> **call**
36:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/http/content_security_policy.rb -> **call**
266:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/session/abstract/id.rb -> **context**
260:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/session/abstract/id.rb -> **call**
696:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/middleware/cookies.rb -> **call**
27:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/middleware/callbacks.rb -> **block in call**
99:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/callbacks.rb -> **run_callbacks**
26:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/middleware/callbacks.rb -> **call**
32:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call!**
21:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call**
28:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/middleware/debug_exceptions.rb -> **call**
26:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/middleware/show_exceptions.rb -> **call**
18:  /GEM_ROOT/gems/lograge-0.12.0/lib/lograge/rails_ext/rack/logger.rb -> **call_app**
25:  /GEM_ROOT/gems/railties-7.0.4/lib/rails/rack/logger.rb -> **block in call**
99:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/tagged_logging.rb -> **block in tagged**
37:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/tagged_logging.rb -> **tagged**
99:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/tagged_logging.rb -> **tagged**
25:  /GEM_ROOT/gems/railties-7.0.4/lib/rails/rack/logger.rb -> **call**
93:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/middleware/remote_ip.rb -> **call**
93:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/middleware/remote_ip.rb -> **call**
19:  /GEM_ROOT/gems/request_store-1.5.1/lib/request_store/middleware.rb -> **call**
26:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/middleware/request_id.rb -> **call**
24:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/method_override.rb -> **call**
22:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/runtime.rb -> **call**
29:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/cache/strategy/local_cache_middleware.rb -> **call**
14:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/middleware/executor.rb -> **call**
18:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/lock.rb -> **call**
110:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/sendfile.rb -> **call**
131:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/middleware/host_authorization.rb -> **call**
530:  /GEM_ROOT/gems/railties-7.0.4/lib/rails/engine.rb -> **call**
226:  /GEM_ROOT/gems/railties-7.0.4/lib/rails/railtie.rb -> **public_send**
226:  /GEM_ROOT/gems/railties-7.0.4/lib/rails/railtie.rb -> **method_missing**
74:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/urlmap.rb -> **block in call**
58:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/urlmap.rb -> **each**
58:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/urlmap.rb -> **call**
107:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb -> **process_request**
157:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **accept_and_process_next_request**
110:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **main_loop**
419:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/request_handler.rb -> **block (3 levels) in start_threads**
113:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/utils.rb -> **block in create_thread_and_abort_on_exception**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| program_name | Passenger RubyApp: /srv/www/obs/api (production) |
| HTTP_USER_AGENT | Mozilla/5.0 (X11; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0 |

### PR DESCRIPTION
**Pull request by saraycp**
If somehow the item was added to the watchlist in between the existence check and the creation attempt, we return the existing one instead of trying to create it and fail.
Adapt the flash message to fit both cases: just created or previously created.

Fixes #14700.

### CODE REVIEW

File: src/api/app/controllers/webui/watched_items_controller.rb [hunk 1]
```diff
@@ -17,8 +17,8 @@ def toggle_watched_item
       watched_item.destroy
       flash[:success] = "Removed #{FLASH_PER_WATCHABLE_TYPE[@watchable.class]} from the watchlist"
     else
-      User.session.watched_items.create(watchable: @watchable)
-      flash[:success] = "Added #{FLASH_PER_WATCHABLE_TYPE[@watchable.class]} to the watchlist"
+      User.session.watched_items.find_or_create_by(watchable: @watchable)
+      flash[:success] = "The #{FLASH_PER_WATCHABLE_TYPE[@watchable.class]} has already been added to your watchlist"
```
Comment (danidoni) [inline src/api/app/controllers/webui/watched_items_controller.rb]: This message is valid when the watchlist item already exists, but if the item is new is misleading... I would leave the message as it was...

Comment (saraycp) [reply src/api/app/controllers/webui/watched_items_controller.rb]: I understand it as "has already been added" like right now but also like a few seconds ago.
But maybe it's just my interpretation. As it isn't a big deal, I'm going to leave it as it was.
