### PR TITLE
Return authorization error if email header is not present

### LINKED ISSUE #17764: [production][main#index] Mysql2::Error: Column 'email' cannot be null
[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/5eba5dcab6e04100081c11de)
# Mysql2::Error: Column &#39;email&#39; cannot be null #
### URL ###
[https://build.opensuse.org/](https://build.opensuse.org/)"
### Where ###
main#index

### Occured ###
May 12  8:26am

### Similar ###
1361

## Params ##
~~~
{
  &quot;action&quot; =&gt; &quot;index&quot;,
  &quot;controller&quot; =&gt; &quot;webui/main&quot;
}
~~~

## Session ##
~~~
{
  &quot;_csrf_token&quot; =&gt; &quot;Qi7xN0us+VNf2Sw4yETmdf5gGO4Yz1+nf7tWvNzA74o=&quot;,
  &quot;session_id&quot; =&gt; &quot;2a340f4f49a6170bd79f50ceb879d465&quot;
}
~~~

## Backtrace ##
~~~
131:  /GEM_ROOT/gems/mysql2-0.5.3/lib/mysql2/client.rb -> **_query**
131:  /GEM_ROOT/gems/mysql2-0.5.3/lib/mysql2/client.rb -> **block in query**
130:  /GEM_ROOT/gems/mysql2-0.5.3/lib/mysql2/client.rb -> **handle_interrupt**
130:  /GEM_ROOT/gems/mysql2-0.5.3/lib/mysql2/client.rb -> **query**
6:  /GEM_ROOT/gems/peek-mysql2-1.2.0/lib/peek-mysql2/timing.rb -> **query**
202:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb -> **block (2 levels) in execute**
48:  /GEM_ROOT/gems/activesupport-6.0.2.2/lib/active_support/dependencies/interlock.rb -> **block in permit_concurrent_loads**
187:  /GEM_ROOT/gems/activesupport-6.0.2.2/lib/active_support/concurrency/share_lock.rb -> **yield_shares**
47:  /GEM_ROOT/gems/activesupport-6.0.2.2/lib/active_support/dependencies/interlock.rb -> **permit_concurrent_loads**
201:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb -> **block in execute**
718:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract_adapter.rb -> **block (2 levels) in log**
235:  /usr/lib64/ruby/2.5.0/monitor.rb -> **mon_synchronize**
717:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract_adapter.rb -> **block in log**
24:  /GEM_ROOT/gems/activesupport-6.0.2.2/lib/active_support/notifications/instrumenter.rb -> **instrument**
708:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract_adapter.rb -> **log**
200:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb -> **execute**
41:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/mysql/database_statements.rb -> **execute**
211:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb -> **execute_and_free**
46:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/mysql/database_statements.rb -> **exec_query**
135:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb -> **exec_insert**
166:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb -> **insert**
22:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/query_cache.rb -> **insert**
375:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/persistence.rb -> **_insert_record**
933:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/persistence.rb -> **_create_record**
163:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/counter_cache.rb -> **_create_record**
70:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/locking/optimistic.rb -> **_create_record**
211:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/attribute_methods/dirty.rb -> **_create_record**
332:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/callbacks.rb -> **block in _create_record**
135:  /GEM_ROOT/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb -> **run_callbacks**
20:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rails/active_record.rb -> **run_callbacks**
827:  /GEM_ROOT/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb -> **_run_create_callbacks**
332:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/callbacks.rb -> **_create_record**
111:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/timestamp.rb -> **_create_record**
906:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/persistence.rb -> **create_or_update**
328:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/callbacks.rb -> **block in create_or_update**
135:  /GEM_ROOT/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb -> **run_callbacks**
20:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rails/active_record.rb -> **run_callbacks**
827:  /GEM_ROOT/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb -> **_run_save_callbacks**
328:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/callbacks.rb -> **create_or_update**
129:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/timestamp.rb -> **create_or_update**
503:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/persistence.rb -> **save!**
53:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/validations.rb -> **save!**
319:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/transactions.rb -> **block in save!**
375:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/transactions.rb -> **block in with_transaction_returning_status**
281:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb -> **block in transaction**
280:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/transaction.rb -> **block in within_new_transaction**
235:  /usr/lib64/ruby/2.5.0/monitor.rb -> **mon_synchronize**
278:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/transaction.rb -> **within_new_transaction**
281:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb -> **transaction**
212:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/transactions.rb -> **transaction**
366:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/transactions.rb -> **with_transaction_returning_status**
319:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/transactions.rb -> **save!**
48:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/suppressor.rb -> **save!**
55:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/persistence.rb -> **create!**
175:  app/models/user.rb -> **create_user_with_fake_pw!**
23:  app/services/webui_controller_service/user_checker.rb -> **find_or_create_user!**
184:  app/controllers/webui/webui_controller.rb -> **check_user**
429:  /GEM_ROOT/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb -> **block in make_lambda**
201:  /GEM_ROOT/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb -> **block (2 levels) in halting**
34:  /GEM_ROOT/gems/actionpack-6.0.2.2/lib/abstract_controller/callbacks.rb -> **block (2 levels) in &lt;module:Callbacks&gt;**
202:  /GEM_ROOT/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb -> **block in halting**
514:  /GEM_ROOT/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb -> **block in invoke_before**
514:  /GEM_ROOT/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb -> **each**
514:  /GEM_ROOT/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb -> **invoke_before**
134:  /GEM_ROOT/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb -> **run_callbacks**
41:  /GEM_ROOT/gems/actionpack-6.0.2.2/lib/abstract_controller/callbacks.rb -> **process_action**
22:  /GEM_ROOT/gems/actionpack-6.0.2.2/lib/action_controller/metal/rescue.rb -> **process_action**
33:  /GEM_ROOT/gems/actionpack-6.0.2.2/lib/action_controller/metal/instrumentation.rb -> **block in process_action**
180:  /GEM_ROOT/gems/activesupport-6.0.2.2/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-6.0.2.2/lib/active_support/notifications/instrumenter.rb -> **instrument**
180:  /GEM_ROOT/gems/activesupport-6.0.2.2/lib/active_support/notifications.rb -> **instrument**
32:  /GEM_ROOT/gems/actionpack-6.0.2.2/lib/action_controller/metal/instrumentation.rb -> **process_action**
245:  /GEM_ROOT/gems/actionpack-6.0.2.2/lib/action_controller/metal/params_wrapper.rb -> **process_action**
27:  /GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/railties/controller_runtime.rb -> **process_action**
136:  /GEM_ROOT/gems/actionpack-6.0.2.2/lib/abstract_controller/base.rb -> **process**
39:  /GEM_ROOT/gems/actionview-6.0.2.2/lib/action_view/rendering.rb -> **process**
191:  /GEM_ROOT/gems/actionpack-6.0.2.2/lib/action_controller/metal.rb -> **dispatch**
252:  /GEM_ROOT/gems/actionpack-6.0.2.2/lib/action_controller/metal.rb -> **dispatch**
51:  /GEM_ROOT/gems/actionpack-6.0.2.2/lib/action_dispatch/routing/route_set.rb -> **dispatch**
33:  /GEM_ROOT/gems/actionpack-6.0.2.2/lib/action_dispatch/routing/route_set.rb -> **serve**
18:  /GEM_ROOT/gems/actionpack-6.0.2.2/lib/action_dispatch/routing/mapper.rb -> **block in &lt;class:Constraints&gt;**
48:  /GEM_ROOT/gems/actionpack-6.0.2.2/lib/action_dispatch/routing/mapper.rb -> **serve**
49:  /GEM_ROOT/gems/actionpack-6.0.2.2/lib/action_dispatch/journey/router.rb -> **block in serve**
32:  /GEM_ROOT/gems/actionpack-6.0.2.2/lib/action_dispatch/journey/router.rb -> **each**
32:  /GEM_ROOT/gems/actionpack-6.0.2.2/lib/action_dispatch/journey/router.rb -> **serve**
837:  /GEM_ROOT/gems/actionpack-6.0.2.2/lib/action_dispatch/routing/route_set.rb -> **call**
38:  config/initializers/wrap_parameters.rb -> **call**
44:  /GEM_ROOT/gems/rack-2.2.2/lib/rack/deflater.rb -> **call**
15:  /GEM_ROOT/gems/rack-2.2.2/lib/rack/tempfile_reaper.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.2/lib/rack/etag.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.2/lib/rack/conditional_get.rb -> **call**
12:  /GEM_ROOT/gems/rack-2.2.2/lib/rack/head.rb -> **call**
18:  /GEM_ROOT/gems/actionpack-6.0.2.2/lib/action_dispatch/http/content_security_policy.rb -> **call**
266:  /GEM_ROOT/gems/rack-2.2.2/lib/rack/session/abstract/id.rb -> **context**
260:  /GEM_ROOT/gems/rack-2.2.2/lib/rack/session/abstract/id.rb -> **call**
648:  /GEM_ROOT/gems/actionpack-6.0.2.2/lib/action_dispatch/middleware/cookies.rb -> **call**
27:  /GEM_ROOT/gems/actionpack-6.0.2.2/lib/action_dispatch/middleware/callbacks.rb -> **block in call**
101:  /GEM_ROOT/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb -> **run_callbacks**
26:  /GEM_ROOT/gems/actionpack-6.0.2.2/lib/action_dispatch/middleware/callbacks.rb -> **call**
17:  /GEM_ROOT/gems/actionpack-6.0.2.2/lib/action_dispatch/middleware/actionable_exceptions.rb -> **call**
32:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call!**
21:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call**
32:  /GEM_ROOT/gems/actionpack-6.0.2.2/lib/action_dispatch/middleware/debug_exceptions.rb -> **call**
33:  /GEM_ROOT/gems/actionpack-6.0.2.2/lib/action_dispatch/middleware/show_exceptions.rb -> **call**
15:  /GEM_ROOT/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb -> **call_app**
26:  /GEM_ROOT/gems/railties-6.0.2.2/lib/rails/rack/logger.rb -> **block in call**
80:  /GEM_ROOT/gems/activesupport-6.0.2.2/lib/active_support/tagged_logging.rb -> **block in tagged**
28:  /GEM_ROOT/gems/activesupport-6.0.2.2/lib/active_support/tagged_logging.rb -> **tagged**
80:  /GEM_ROOT/gems/activesupport-6.0.2.2/lib/active_support/tagged_logging.rb -> **tagged**
26:  /GEM_ROOT/gems/railties-6.0.2.2/lib/rails/rack/logger.rb -> **call**
81:  /GEM_ROOT/gems/actionpack-6.0.2.2/lib/action_dispatch/middleware/remote_ip.rb -> **call**
81:  /GEM_ROOT/gems/actionpack-6.0.2.2/lib/action_dispatch/middleware/remote_ip.rb -> **call**
19:  /GEM_ROOT/gems/request_store-1.5.0/lib/request_store/middleware.rb -> **call**
27:  /GEM_ROOT/gems/actionpack-6.0.2.2/lib/action_dispatch/middleware/request_id.rb -> **call**
24:  /GEM_ROOT/gems/rack-2.2.2/lib/rack/method_override.rb -> **call**
22:  /GEM_ROOT/gems/rack-2.2.2/lib/rack/runtime.rb -> **call**
29:  /GEM_ROOT/gems/activesupport-6.0.2.2/lib/active_support/cache/strategy/local_cache_middleware.rb -> **call**
14:  /GEM_ROOT/gems/actionpack-6.0.2.2/lib/action_dispatch/middleware/executor.rb -> **call**
18:  /GEM_ROOT/gems/rack-2.2.2/lib/rack/lock.rb -> **call**
110:  /GEM_ROOT/gems/rack-2.2.2/lib/rack/sendfile.rb -> **call**
77:  /GEM_ROOT/gems/actionpack-6.0.2.2/lib/action_dispatch/middleware/host_authorization.rb -> **call**
526:  /GEM_ROOT/gems/railties-6.0.2.2/lib/rails/engine.rb -> **call**
190:  /GEM_ROOT/gems/railties-6.0.2.2/lib/rails/railtie.rb -> **public_send**
190:  /GEM_ROOT/gems/railties-6.0.2.2/lib/rails/railtie.rb -> **method_missing**
74:  /GEM_ROOT/gems/rack-2.2.2/lib/rack/urlmap.rb -> **block in call**
58:  /GEM_ROOT/gems/rack-2.2.2/lib/rack/urlmap.rb -> **each**
58:  /GEM_ROOT/gems/rack-2.2.2/lib/rack/urlmap.rb -> **call**
97:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.4/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb -> **process_request**
149:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.4/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **accept_and_process_next_request**
110:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.4/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **main_loop**
415:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.4/src/ruby_supportlib/phusion_passenger/request_handler.rb -> **block (3 levels) in start_threads**
113:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.4/src/ruby_supportlib/phusion_passenger/utils.rb -> **block in create_thread_and_abort_on_exception**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| program_name | Passenger AppPreloader: /srv/www/obs/api (forking...) |
| HTTP_USER_AGENT | Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0 |

### PR DESCRIPTION
**Pull request by danidoni**
Fixes #17764

### CODE REVIEW

File: src/api/app/services/webui_controller_service/user_checker.rb [hunk 1]
```diff
@@ -1,17 +1,18 @@
 module WebuiControllerService
   class UserChecker
-    attr_reader :user_login, :http_request
+    attr_reader :user_login, :user_email, :http_request
 
     def initialize(http_request:)
       @http_request = http_request
-      @user_login = extract_user_login_from_http_request
+      @user_login = http_request.env['HTTP_X_USERNAME']
+      @user_email = http_request.env['HTTP_X_EMAIL']
```
Comment (hennevogel) [inline src/api/app/services/webui_controller_service/user_checker.rb:8]: Can you just get rid of those and use the request object directly? There is no real cost associated to doing `http_request.env['HTTP_X_USERNAME']`

**Review by hennevogel — APPROVED** [review]

**Comment by danidoni** [comment]
Fixed the specs
