### PR TITLE
[webui] Fix sorting in job history table

### LINKED ISSUE #3986: webui: job_history table sorting has strange sorting
The default is sorting alphabetically md5sums, which doesn't make *any* sense - and if you sort by time the sort order is August, October, September - also alphabetically by month, which makes *little* sense.

https://build.opensuse.org/packages/curl/job_history/openSUSE:Factory:Staging:C/standard/i586

### PR DESCRIPTION
**Pull request by eduardoj**
Fix sorting in job history table:

- Disable sorting in first (Revision) and last column.
- Enable sorting by default with "Time" column, descending.
- fix sorting by "Time" column.
- Also fix sorting in "Build time" column.
- Prevent searching for the introduced hidden columns with no formatted
data.
- Minor code styling changes.

This should fix #3986.

### CODE REVIEW

File: src/api/app/assets/javascripts/webui/application/package.js [hunk 1]
```diff
@@ -1,149 +1,148 @@
...
+          $("#services_container").html(data);
+          $("#services").sortable('enable');
+          $("#services").animate({opacity: 1}, 500);
+          makeServicesDragable();
+        },
+        error: function(data) {
+          $("#services").text(data);
+        }
+      });
+    }
```
Comment (evanrolfe) [inline src/api/app/assets/javascripts/webui/application/package.js]: Small suggestion: In the future it would be nice to make indentation and style changes like this in its own PR. Otherwise its hard to see if you have actually changed any code or not here or if its just the indentation thats changed.

File: src/api/app/assets/javascripts/webui/application/package.js [hunk 2]
```diff
@@ -156,6 +155,12 @@ $( document ).ready(function() {
...
 
   $('#jobhistory-table').dataTable({
-    order: [[0, 'desc']]
+    columnDefs: [
+      { orderable: false, targets: [0, 8] },
+      { visible: false, searchable: false, targets: [1, 5] },
+      { orderData: 1, targets: 2 },
+      { orderData: 5, targets: 6 },
+    ],
+    order: [[2, 'desc']]
```
Comment (evanrolfe) [inline src/api/app/assets/javascripts/webui/application/package.js]: Is this the only javascript code thats changed? (Apart from indentation)
