### PR TITLE
Fix autocomplete filters showing empty values

### LINKED ISSUE #18826: Request index filter wrong behaviour
# Issue Description

When you filter by Project name and after the filtering is performed, if you click on the magnifier again it will introduce empty values.

This is happening with all the filters using autocomplete except Labels.

Image

Expected Result
============
Only names are displayed in the check-boxes.

How to Reproduce
===============
1. Go to 'Your Requests''
2. Go to the Project filter and type a correct project name
3. Click on the magnifier and wait a few seconds for the result
4. Click again on the magnifier and wait a few seconds more
5. You'll see an empty checkbox

If after these 5 steps you do the same in the packages filter, you not only get an empty checkbox in the package but the number of empty check-boxes in the project increases.

### PR DESCRIPTION
**Pull request by geetxnshgoyal**
## Description

This PR fixes a bug where autocomplete filters (Projects, Packages, Creators, Reviewers, Staging Projects, and Priorities) were showing empty checkboxes after clicking the magnifier button to submit a search.

## Problem

When using autocomplete filters on the requests page:
1. User types a value in an autocomplete field (e.g., Project name)
2. User clicks the magnifier (🔍) button to submit
3. Filter dropdown shows the selected value
4. User clicks magnifier again (with or without typing a new value)
5. **Bug**: Empty checkboxes appear in the filter dropdown

This happened because when the form was submitted, empty string values were being added to the params array and stored in `@selected_filter` without being cleaned up.

## Solution

Modified `Webui::RequestsFilter` concern to use `.compact_blank` when assigning filter parameters to `@selected_filter`, ensuring empty strings are removed before rendering checkboxes in the view.

**Changed methods:**
- `filter_creators`
- `filter_priorities`
- `filter_staging_projects`
- `filter_reviewers`
- `filter_project_names`
- `filter_package_names`

This brings all filter methods in line with the `filter_labels` method, which was already correctly using `compact_blank`.

## Testing

Added comprehensive tests in `spec/controllers/webui/users/bs_requests_controller_spec.rb` to verify:
- Empty strings in filter parameters are properly removed
- Valid filter values continue to work correctly
- `@selected_filter` hash doesn't contain empty strings
- All 6 affected filters behave consistently

## Verification Steps

1. Navigate to a requests page with filters (e.g., `/my/requests`)
2. Open the "Projects" filter dropdown
3. Type a project name in the search box
4. Click the magnifier (🔍) button
5. Open the Projects filter dropdown again
6. Click the magnifier button again (with empty search or new value)
7. Open the Projects filter dropdown
8. **Expected**: Only valid project names appear as checkboxes (no empty checkboxes)
9. Repeat for Packages, Creators, Reviewers, Staging Projects, and Priorities filters

## Files Changed

- `app/controllers/concerns/webui/requests_filter.rb` - Added `.compact_blank` to 6 filter methods
- `spec/controllers/webui/users/bs_requests_controller_spec.rb` - Added tests for empty value handling

## Related Issues

Fixes #18826

### CODE REVIEW

**Comment by geetxnshgoyal** [comment]
@hennevogel @eduardoj please look into it :)

**Comment by geetxnshgoyal** [comment]
@eduardoj please update

File: src/api/spec/controllers/webui/users/bs_requests_controller_spec.rb [hunk 1]
```diff
@@ -191,6 +191,68 @@
...
+        context 'with empty priorities' do
+          let(:context_params) { { priorities: ['', 'critical', ''] } }
+
+          it 'filters out empty values and only uses valid priorities' do
+            expect(assigns[:bs_requests]).to contain_exactly(request_with_review)
+            expect(assigns[:selected_filter][:priorities]).not_to include('')
+            expect(assigns[:selected_filter][:priorities]).to eq(['critical'])
+          end
+        end
+      end
```
Comment (eduardoj) [inline src/api/spec/controllers/webui/users/bs_requests_controller_spec.rb]:
```suggestion
```
Let's remove these specs. Although they help validate the suggested changes in the `webui/requests_filter.rb` concern, they don't cover the 'happy path' we prioritize in our test suite. Minimizing unnecessary tests helps optimize our testing pipeline and, consequently, saves developer time.

The rest of the changes look good to me. :+1:

**Comment by geetxnshgoyal** [comment]
@eduardoj please check now i have committed your suggested changes !

**Comment by eduardoj** [comment]
> @eduardoj please check now i have committed your suggested changes !

Thanks for the prompt response. Please merge your commits into only one and the PR will be ready to be merged.

**Comment by geetxnshgoyal** [comment]
@eduardoj please check now!

**Review by eduardoj — APPROVED** [review]
