### PR TITLE
[api][webui] Refactors and fixes Project#has_distribution

### LINKED ISSUE #2054: Project#has_distribution not working for remote projects
```
project = Project.find_by(name: project_name)
```
is always ``nil`` for remote projects.

Instead we should do sth like that:

```
    repositories.each do |repository|
      repository.path_elements.each do |path_element|
        return true if (path_element.link.name == input_repo ||
            path_element.link.remote_project_name == input_repo)
      end
```

(can be simplified and needs some more testing ...)

### PR DESCRIPTION
**Pull request by ChrisBr**
- Make Project.has_distribution working for remote distributions (fixes #2054)
- Refactors the whole method
- Introduces model spec

### CODE REVIEW

File: src/api/app/models/project.rb [hunk 1]
```diff
@@ -168,11 +168,26 @@ def maintained_project_names
 
   # Check if the project has a path_element matching project and repository
   def has_distribution(project_name, repository)
-    project = Project.find_by(name: project_name)
-    return false unless project
+    has_local_distribution(repository) || has_remote_distribution(project_name, repository)
+  end
+
+  def has_remote_distribution(project_name, repository)
+    get_linked_repositories.remote.each do |linked_repository|
```
Comment (mdeniz) [inline src/api/app/models/project.rb]: Can you use `any?` instead `each + return` for this loop?
Something like:
```ruby
get_linked_repositories.remote.any? do |linked_repository|
  project_name.end_with?(linked_repository.remote_project_name) && linked_repository.name == repository
end
```

http://apidock.com/ruby/Enumerable/any%3F

File: src/api/app/models/project.rb [hunk 2]
```diff
@@ -168,11 +168,26 @@ def maintained_project_names
...
+      return true if project_name.end_with?(linked_repository.remote_project_name) && linked_repository.name == repository
+    end
+    false
+  end
+
+  def has_local_distribution(repository)
+    get_linked_repositories.not_remote.each do |linked_repository|
```
Comment (mdeniz) [inline src/api/app/models/project.rb]: Same here, use `any?`

File: src/api/app/models/repository.rb [hunk 3]
```diff
@@ -17,6 +17,7 @@ class Repository < ApplicationRecord
   has_many :architectures, -> { order("position") }, :through => :repository_architectures
 
   scope :not_remote, -> { where(:remote_project_name => nil) }
```
Comment (mdeniz) [inline src/api/app/models/repository.rb]: If you created the :remote scope... why don't you change this to the new hash syntax too? :smile: 
```ruby
scope :not_remote, -> { where(remote_project_name: nil) }
```

File: src/api/app/models/project.rb (hunk 1 above)
Comment (ChrisBr) [inline src/api/app/models/project.rb]: Neat :+1:

**Comment by ChrisBr** [comment]
@mdeniz fixed your suggestions! Thanks!
