### PR TITLE
Always display the requested view format

### LINKED ISSUE #17171: [production][bs_requests#index] undefined method `zero?' for nil:NilClass
[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/6751a47484bf460c5bef5725)
# undefined method `zero?&#39; for nil:NilClass #
### URL ###
[https://build.opensuse.org/users/$USER/requests?draw=1&amp;columns%5B0%5D%5Bdata%5D=0&amp;columns%5B0%5D%5Bname%5D=&amp;columns%5B0%5D%5Bsearchable%5D=true&amp;columns%5B0%5D%5Borderable%5D=true&amp;columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&amp;columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&amp;columns%5B1%5D%5Bdata%5D=1&amp;columns%5B1%5D%5Bname%5D=&amp;columns%5B1%5D%5Bsearchable%5D=true&amp;columns%5B1%5D%5Borderable%5D=true&amp;columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&amp;columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&amp;columns%5B2%5D%5Bdata%5D=2&amp;columns%5B2%5D%5Bname%5D=&amp;columns%5B2%5D%5Bsearchable%5D=true&amp;columns%5B2%5D%5Borderable%5D=true&amp;columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&amp;columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&amp;columns%5B3%5D%5Bdata%5D=3&amp;columns%5B3%5D%5Bname%5D=&amp;columns%5B3%5D%5Bsearchable%5D=true&amp;columns%5B3%5D%5Borderable%5D=true&amp;columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&amp;columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&amp;columns%5B4%5D%5Bdata%5D=4&amp;columns%5B4%5D%5Bname%5D=&amp;columns%5B4%5D%5Bsearchable%5D=true&amp;columns%5B4%5D%5Borderable%5D=true&amp;columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&amp;columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&amp;columns%5B5%5D%5Bdata%5D=5&amp;columns%5B5%5D%5Bname%5D=&amp;columns%5B5%5D%5Bsearchable%5D=true&amp;columns%5B5%5D%5Borderable%5D=true&amp;columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&amp;columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&amp;columns%5B6%5D%5Bdata%5D=6&amp;columns%5B6%5D%5Bname%5D=&amp;columns%5B6%5D%5Bsearchable%5D=true&amp;columns%5B6%5D%5Borderable%5D=false&amp;columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&amp;columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&amp;order%5B0%5D%5Bcolumn%5D=0&amp;order%5B0%5D%5Bdir%5D=desc&amp;start=0&amp;length=10&amp;search%5Bvalue%5D=&amp;search%5Bregex%5D=false&amp;dataTableId=reviews_in_table&amp;_=1733403755237](https://build.opensuse.org/users/$USER/requests?draw=1&amp;columns%5B0%5D%5Bdata%5D=0&amp;columns%5B0%5D%5Bname%5D=&amp;columns%5B0%5D%5Bsearchable%5D=true&amp;columns%5B0%5D%5Borderable%5D=true&amp;columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&amp;columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&amp;columns%5B1%5D%5Bdata%5D=1&amp;columns%5B1%5D%5Bname%5D=&amp;columns%5B1%5D%5Bsearchable%5D=true&amp;columns%5B1%5D%5Borderable%5D=true&amp;columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&amp;columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&amp;columns%5B2%5D%5Bdata%5D=2&amp;columns%5B2%5D%5Bname%5D=&amp;columns%5B2%5D%5Bsearchable%5D=true&amp;columns%5B2%5D%5Borderable%5D=true&amp;columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&amp;columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&amp;columns%5B3%5D%5Bdata%5D=3&amp;columns%5B3%5D%5Bname%5D=&amp;columns%5B3%5D%5Bsearchable%5D=true&amp;columns%5B3%5D%5Borderable%5D=true&amp;columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&amp;columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&amp;columns%5B4%5D%5Bdata%5D=4&amp;columns%5B4%5D%5Bname%5D=&amp;columns%5B4%5D%5Bsearchable%5D=true&amp;columns%5B4%5D%5Borderable%5D=true&amp;columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&amp;columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&amp;columns%5B5%5D%5Bdata%5D=5&amp;columns%5B5%5D%5Bname%5D=&amp;columns%5B5%5D%5Bsearchable%5D=true&amp;columns%5B5%5D%5Borderable%5D=true&amp;columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&amp;columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&amp;columns%5B6%5D%5Bdata%5D=6&amp;columns%5B6%5D%5Bname%5D=&amp;columns%5B6%5D%5Bsearchable%5D=true&amp;columns%5B6%5D%5Borderable%5D=false&amp;columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&amp;columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&amp;order%5B0%5D%5Bcolumn%5D=0&amp;order%5B0%5D%5Bdir%5D=desc&amp;start=0&amp;length=10&amp;search%5Bvalue%5D=&amp;search%5Bregex%5D=false&amp;dataTableId=reviews_in_table&amp;_=1733403755237)"
### Where ###
bs_requests#index

### Occured ###
Dec 05  1:02pm

### Similar ###
25

## Params ##
~~~
{
  &quot;_&quot; =&gt; &quot;1733403755237&quot;,
  &quot;action&quot; =&gt; &quot;index&quot;,
  &quot;columns&quot; =&gt; {
    &quot;0&quot; =&gt; {
      &quot;data&quot; =&gt; &quot;0&quot;,
      &quot;name&quot; =&gt; &quot;&quot;,
      &quot;orderable&quot; =&gt; &quot;true&quot;,
      &quot;search&quot; =&gt; {
        &quot;regex&quot; =&gt; &quot;false&quot;,
        &quot;value&quot; =&gt; &quot;&quot;
      },
      &quot;searchable&quot; =&gt; &quot;true&quot;
    },
    &quot;1&quot; =&gt; {
      &quot;data&quot; =&gt; &quot;1&quot;,
      &quot;name&quot; =&gt; &quot;&quot;,
      &quot;orderable&quot; =&gt; &quot;true&quot;,
      &quot;search&quot; =&gt; {
        &quot;regex&quot; =&gt; &quot;false&quot;,
        &quot;value&quot; =&gt; &quot;&quot;
      },
      &quot;searchable&quot; =&gt; &quot;true&quot;
    },
    &quot;2&quot; =&gt; {
      &quot;data&quot; =&gt; &quot;2&quot;,
      &quot;name&quot; =&gt; &quot;&quot;,
      &quot;orderable&quot; =&gt; &quot;true&quot;,
      &quot;search&quot; =&gt; {
        &quot;regex&quot; =&gt; &quot;false&quot;,
        &quot;value&quot; =&gt; &quot;&quot;
      },
      &quot;searchable&quot; =&gt; &quot;true&quot;
    },
    &quot;3&quot; =&gt; {
      &quot;data&quot; =&gt; &quot;3&quot;,
      &quot;name&quot; =&gt; &quot;&quot;,
      &quot;orderable&quot; =&gt; &quot;true&quot;,
      &quot;search&quot; =&gt; {
        &quot;regex&quot; =&gt; &quot;false&quot;,
        &quot;value&quot; =&gt; &quot;&quot;
      },
      &quot;searchable&quot; =&gt; &quot;true&quot;
    },
    &quot;4&quot; =&gt; {
      &quot;data&quot; =&gt; &quot;4&quot;,
      &quot;name&quot; =&gt; &quot;&quot;,
      &quot;orderable&quot; =&gt; &quot;true&quot;,
      &quot;search&quot; =&gt; {
        &quot;regex&quot; =&gt; &quot;false&quot;,
        &quot;value&quot; =&gt; &quot;&quot;
      },
      &quot;searchable&quot; =&gt; &quot;true&quot;
    },
    &quot;5&quot; =&gt; {
      &quot;data&quot; =&gt; &quot;5&quot;,
      &quot;name&quot; =&gt; &quot;&quot;,
      &quot;orderable&quot; =&gt; &quot;true&quot;,
      &quot;search&quot; =&gt; {
        &quot;regex&quot; =&gt; &quot;false&quot;,
        &quot;value&quot; =&gt; &quot;&quot;
      },
      &quot;searchable&quot; =&gt; &quot;true&quot;
    },
    &quot;6&quot; =&gt; {
      &quot;data&quot; =&gt; &quot;6&quot;,
      &quot;name&quot; =&gt; &quot;&quot;,
      &quot;orderable&quot; =&gt; &quot;false&quot;,
      &quot;search&quot; =&gt; {
        &quot;regex&quot; =&gt; &quot;false&quot;,
        &quot;value&quot; =&gt; &quot;&quot;
      },
      &quot;searchable&quot; =&gt; &quot;true&quot;
    }
  },
  &quot;controller&quot; =&gt; &quot;webui/users/bs_requests&quot;,
  &quot;dataTableId&quot; =&gt; &quot;reviews_in_table&quot;,
  &quot;draw&quot; =&gt; &quot;1&quot;,
  &quot;length&quot; =&gt; &quot;10&quot;,
  &quot;order&quot; =&gt; {
    &quot;0&quot; =&gt; {
      &quot;column&quot; =&gt; &quot;0&quot;,
      &quot;dir&quot; =&gt; &quot;desc&quot;
    }
  },
  &quot;search&quot; =&gt; {
    &quot;regex&quot; =&gt; &quot;false&quot;,
    &quot;value&quot; =&gt; &quot;&quot;
  },
  &quot;start&quot; =&gt; &quot;0&quot;,
  &quot;user_login&quot; =&gt; &quot;$USER&quot;
}
~~~

## Session ##
~~~
{
  &quot;_csrf_token&quot; =&gt; &quot;kf0Hpn9qIgtSmmP4mM_8a-usAr-QCxMWJvnIx82JxuQ&quot;,
  &quot;session_id&quot; =&gt; &quot;f6d9d201c27622f0b65dfd6f776e81e6&quot;
}
~~~

## Backtrace ##
~~~
3:  app/views/layouts/webui/_unread_notifications_counter.html.haml -> **_app_views_layouts_webui__unread_notifications_counter_html_haml__4170902470039606409_218520**
244:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/base.rb -> **public_send**
244:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/base.rb -> **_run**
157:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/template.rb -> **block in render**
208:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **instrument**
361:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/template.rb -> **instrument_render_template**
155:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/template.rb -> **render**
251:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/partial_renderer.rb -> **block in render_partial_template**
206:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications/instrumenter.rb -> **instrument**
206:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **instrument**
246:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/partial_renderer.rb -> **render_partial_template**
237:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/partial_renderer.rb -> **render**
81:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/renderer.rb -> **render_partial_to_object**
27:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/renderer.rb -> **render_to_object**
22:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/renderer.rb -> **render**
37:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/helpers/rendering_helper.rb -> **block in render**
270:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/base.rb -> **in_rendering_context**
33:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/helpers/rendering_helper.rb -> **render**
14:  app/views/layouts/webui/_top_navigation.html.haml -> **block in _app_views_layouts_webui__top_navigation_html_haml___1517269677604657159_114940**
45:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/helpers/capture_helper.rb -> **block in capture**
209:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/helpers/capture_helper.rb -> **with_output_buffer**
45:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/helpers/capture_helper.rb -> **capture**
371:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/helpers/tag_helper.rb -> **content_tag**
218:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/helpers/url_helper.rb -> **link_to**
13:  app/views/layouts/webui/_top_navigation.html.haml -> **_app_views_layouts_webui__top_navigation_html_haml___1517269677604657159_114940**
244:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/base.rb -> **public_send**
244:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/base.rb -> **_run**
157:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/template.rb -> **block in render**
208:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **instrument**
361:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/template.rb -> **instrument_render_template**
155:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/template.rb -> **render**
251:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/partial_renderer.rb -> **block in render_partial_template**
206:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications/instrumenter.rb -> **instrument**
206:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **instrument**
246:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/partial_renderer.rb -> **render_partial_template**
237:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/partial_renderer.rb -> **render**
81:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/renderer.rb -> **render_partial_to_object**
27:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/renderer.rb -> **render_to_object**
22:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/renderer.rb -> **render**
37:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/helpers/rendering_helper.rb -> **block in render**
270:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/base.rb -> **in_rendering_context**
33:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/helpers/rendering_helper.rb -> **render**
44:  app/views/layouts/webui/webui.html.haml -> **_app_views_layouts_webui_webui_html_haml__561791307979379675_114920**
244:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/base.rb -> **public_send**
244:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/base.rb -> **_run**
157:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/template.rb -> **block in render**
208:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **instrument**
361:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/template.rb -> **instrument_render_template**
155:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/template.rb -> **render**
76:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/template_renderer.rb -> **block in render_with_layout**
208:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **instrument**
74:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/template_renderer.rb -> **render_with_layout**
59:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/template_renderer.rb -> **render_template**
11:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/template_renderer.rb -> **render**
61:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/renderer.rb -> **render_template_to_object**
29:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/renderer/renderer.rb -> **render_to_object**
117:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/rendering.rb -> **block in _render_template**
270:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/base.rb -> **in_rendering_context**
116:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/rendering.rb -> **_render_template**
216:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/streaming.rb -> **_render_template**
103:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/rendering.rb -> **render_to_body**
158:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/rendering.rb -> **render_to_body**
141:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/renderers.rb -> **render_to_body**
27:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/abstract_controller/rendering.rb -> **render**
139:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/rendering.rb -> **render**
22:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/instrumentation.rb -> **block (2 levels) in render**
311:  /usr/lib64/ruby/3.1.0/benchmark.rb -> **realtime**
14:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/core_ext/benchmark.rb -> **ms**
22:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/instrumentation.rb -> **block in render**
91:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/instrumentation.rb -> **cleanup_view_runtime**
34:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/railties/controller_runtime.rb -> **cleanup_view_runtime**
21:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/instrumentation.rb -> **render**
35:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/implicit_render.rb -> **default_render**
7:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/basic_implicit_render.rb -> **send_action**
215:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/abstract_controller/base.rb -> **process_action**
165:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/rendering.rb -> **process_action**
234:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/abstract_controller/callbacks.rb -> **block in process_action**
107:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb -> **run_callbacks**
233:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/abstract_controller/callbacks.rb -> **process_action**
23:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/rescue.rb -> **process_action**
67:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/instrumentation.rb -> **block in process_action**
206:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications/instrumenter.rb -> **instrument**
206:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **instrument**
66:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/instrumentation.rb -> **process_action**
259:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/params_wrapper.rb -> **process_action**
27:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/railties/controller_runtime.rb -> **process_action**
151:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/abstract_controller/base.rb -> **process**
39:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/rendering.rb -> **process**
188:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal.rb -> **dispatch**
251:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal.rb -> **dispatch**
49:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/route_set.rb -> **dispatch**
32:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/route_set.rb -> **serve**
18:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/mapper.rb -> **block in &lt;class:Constraints&gt;**
48:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/mapper.rb -> **serve**
50:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/journey/router.rb -> **block in serve**
32:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/journey/router.rb -> **each**
32:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/journey/router.rb -> **serve**
852:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/route_set.rb -> **call**
87:  /GEM_ROOT/gems/flipper-1.3.2/lib/flipper/middleware/memoizer.rb -> **memoized_call**
45:  /GEM_ROOT/gems/flipper-1.3.2/lib/flipper/middleware/memoizer.rb -> **call**
15:  config/initializers/prefer_xml_over_html.rb -> **call**
44:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/deflater.rb -> **call**
15:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/tempfile_reaper.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/etag.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/conditional_get.rb -> **call**
12:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/head.rb -> **call**
38:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/http/permissions_policy.rb -> **call**
36:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/http/content_security_policy.rb -> **call**
266:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/session/abstract/id.rb -> **context**
260:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/session/abstract/id.rb -> **call**
704:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/cookies.rb -> **call**
27:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/callbacks.rb -> **block in call**
99:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb -> **run_callbacks**
26:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/callbacks.rb -> **call**
32:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call!**
21:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call**
28:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/debug_exceptions.rb -> **call**
29:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/show_exceptions.rb -> **call**
18:  /GEM_ROOT/gems/lograge-0.14.0/lib/lograge/rails_ext/rack/logger.rb -> **call_app**
25:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/rack/logger.rb -> **block in call**
99:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/tagged_logging.rb -> **block in tagged**
37:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/tagged_logging.rb -> **tagged**
99:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/tagged_logging.rb -> **tagged**
25:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/rack/logger.rb -> **call**
93:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/remote_ip.rb -> **call**
93:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/remote_ip.rb -> **call**
19:  /GEM_ROOT/gems/request_store-1.7.0/lib/request_store/middleware.rb -> **call**
26:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/request_id.rb -> **call**
24:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/method_override.rb -> **call**
22:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/runtime.rb -> **call**
29:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/cache/strategy/local_cache_middleware.rb -> **call**
14:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/executor.rb -> **call**
18:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/lock.rb -> **call**
110:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/sendfile.rb -> **call**
131:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/host_authorization.rb -> **call**
530:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/engine.rb -> **call**
226:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/railtie.rb -> **public_send**
226:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/railtie.rb -> **method_missing**
74:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/urlmap.rb -> **block in call**
58:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/urlmap.rb -> **each**
58:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/urlmap.rb -> **call**
107:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb -> **process_request**
149:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **accept_and_process_next_request**
110:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **main_loop**
419:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/request_handler.rb -> **block (3 levels) in start_threads**
113:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/utils.rb -> **block in create_thread_and_abort_on_exception**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| program_name | Passenger RubyApp: /srv/www/obs/api (production) |
| HTTP_USER_AGENT | Mozilla/5.0 (X11; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0 |

### PR DESCRIPTION
**Pull request by hellcp-work**
Fixes #17171

### CODE REVIEW

File: src/api/app/controllers/webui/users/bs_requests_controller.rb [hunk 1]
```diff
@@ -15,16 +15,24 @@ class BsRequestsController < WebuiController
...
+        respond_to do |format|
+          format.html do
+            filter_requests
+
+            # TODO: Temporarily disable list of creators due to performance issues
+            # @bs_requests_creators = @bs_requests.distinct.pluck(:creator)
+            @bs_requests = @bs_requests.order('number DESC').page(params[:page])
+            @bs_requests = @bs_requests.includes(:bs_request_actions, :comments, :reviews)
+            @bs_requests = @bs_requests.includes(:labels) if Flipper.enabled?(:labels, User.session)
+          end
```
Comment (rubhanazeem) [inline src/api/app/controllers/webui/users/bs_requests_controller.rb:27]: This belongs to `request_index` only.

Comment (hellcp-work) [reply src/api/app/controllers/webui/users/bs_requests_controller.rb:27]: It does, however if we want to avoid errors when a user refreshes after a logout for instance, we can't just selectively render different formats, we would be much better off handling that as a redirect in a before action instead

Comment (hellcp-work) [reply src/api/app/controllers/webui/users/bs_requests_controller.rb:28]: I implemented a redirect

Comment (rubhanazeem) [reply src/api/app/controllers/webui/users/bs_requests_controller.rb:28]: You have redirect to `my_tasks_path` but I believe this action is used for both `my tasks` and `/requests`

File: src/api/app/controllers/webui/users/bs_requests_controller.rb [hunk 2]
```diff
@@ -54,15 +63,8 @@ def request_method
...
-      # TODO: Remove this old index action when request_index feature is rolled-over
-      def index_legacy
-        parsed_params = BsRequest::DataTable::ParamsParser.new(params).parsed_params
-        requests_query = BsRequest::DataTable::FindForUserOrGroupQuery.new(@user_or_group, request_method, parsed_params)
-        @requests_data_table = BsRequest::DataTable::Table.new(requests_query, parsed_params[:draw])
-
-        respond_to do |format|
-          format.json { render 'webui/shared/bs_requests/index' }
-        end
+      def redirect_beta
```
Comment (eduardoj) [inline src/api/app/controllers/webui/users/bs_requests_controller.rb:66]: Naming... `redirect_beta` is kind of confusing. The code redirects if the user is **not** in beta.

Maybe `redirect_legacy` is better?

File: src/api/app/controllers/webui/users/bs_requests_controller.rb (hunk 1 above)
Comment (hellcp-work) [reply src/api/app/controllers/webui/users/bs_requests_controller.rb:28]: It's used for my_tasks' datatable, so I can still redirect to it

Comment (hennevogel) [reply src/api/app/controllers/webui/users/bs_requests_controller.rb:28]: If someone is logged out should they see this page at all?

Comment (hellcp-work) [reply src/api/app/controllers/webui/users/bs_requests_controller.rb:28]: Sure, logged out example is bad, but if you switch beta state and then refresh, or if somebody sends you a link to this page, you are going to have the same issue
