### PR TITLE
Move calculation of download for binaries to a dedicated action

### LINKED ISSUE #4736: regression in time to display webui "binaries" page since new layout
Since the introduction of the new layout on the binaries page (combining both details and download link for each package), it takes several seconds to load this page for packages containing a lot of subpackages. 

I noticed this on IBS / SUSE:SLE-15:GA

### PR DESCRIPTION
**Pull request by mdeniz**
We show a download link per file in the binaries view, but the
calculation of the url is expensive and can end up in performing up to
2 http request to external servers.

Now we use an internal url and there in that action we calculate the url
to redirect the user to the right place.

That way in the lis of binaries we just show simple links

This closes #4736

### CODE REVIEW

**Comment by ChrisBr** [comment]
I think the Hakiri issue is a false positive but might be good if somebody else also has a look. Also there are many tests failing :cry: 

Otherwise good idea!

File: src/api/app/controllers/webui/package_controller.rb [hunk 1]
```diff
@@ -1021,6 +1021,18 @@ def save_meta
 
   def edit; end
 
+  def binary_download
+    filename = File.basename(params[:filename]) # Ensure it really is just a file name, no '/..', etc.
+    repository = Repository.find_by_project_and_name(@project.to_s, params[:repository].to_s)
+
+    download_url = download_url_for_file_in_repo(@project, @package, repository, params[:arch], filename)
+    if download_url
```
Comment (bgeuken) [inline src/api/app/controllers/webui/package_controller.rb]: This can be nil for two reasons, the file not being [available](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/controllers/webui/package_controller.rb#L1125) and the user not being [logged in](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/controllers/webui/package_controller.rb#L1127).
For the latter case I would first check if the user is logged in and only then check for the file, etc.

File: src/api/test/functional/webui/spider_test.rb [hunk 2]
```diff
@@ -53,6 +53,7 @@ def getlinks(baseuri, body)
   def raiseit(message, url)
     # known issues
     return if url =~ %r{/package/binary/BinaryprotectedProject/.*}
+    return if url =~ %r{/package/binary/download/*}
```
Comment (bgeuken) [inline src/api/test/functional/webui/spider_test.rb]: This probably changed because we now always show the link, while before it was only visible to logged in users. We should either hide the link like it was before or disable it when the user is not logged in.

That way we also avoid that bots click non-working links.

Comment (bgeuken) [reply src/api/test/functional/webui/spider_test.rb]: Hm, that sucks.

Thanks for explaining

**Comment by bgeuken** [comment]
According to [this](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/controllers/webui/package_controller.rb#L1126) comment this depends on whether the mirror is available or not:
` # only use API for logged in users if the mirror is not available - return nil otherwise `

If that's true, we could ping the mirror once per request to reduce the number of requests that make this page slow.
And if every project uses the same mirror we could even cache the ping result for some seconds.

**Comment by mdeniz** [comment]
Thanks @bgeuken for reviewing it.

> If that's true, we could ping the mirror once per request to reduce the number of requests that make this page slow.

We cannot ping the mirror once per listing of the binaries... we need to ping it for each file.

> And if every project uses the same mirror we could even cache the ping result for some seconds.

Creating a cache looks to me way too complicated for  saving requests just if the next listing of binaries come in the next seconds. We would need to cache each individual ping for every file in the list, we can't know if all the files in a binaries list is in the mirror in one shot. 

BTW, can you also take a look at the Hakiri issue?

**Comment by bgeuken** [comment]
> mdeniz commented 2 hours ago
> Thanks @bgeuken for reviewing it.
> 
>> If that's true, we could ping the mirror once per request to reduce the number of requests that make this page slow.
>
> We cannot ping the mirror once per listing of the binaries... we need to ping it for each file.

Are you sure? It might be that, if there is a mirror it's used for all binaries and if not than not. Why would such a mirror only have some files and others not?


> BTW, can you also take a look at the Hakiri issue?

Sure, I'll have a look.
