### PR TITLE
Enforce login for packages/branches_controller

### LINKED ISSUE #9603: [production][branches#new] Requiring user, but found nobody
branches#new threw this 1 times
<pre>
Requiring user, but found nobody
</pre>
[https://build.opensuse.org/packages/obs-server/branches/OBS:Server:Unstable?revision=10812](https://build.opensuse.org/packages/obs-server/branches/OBS:Server:Unstable?revision=10812)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5ec53a7eb123500010c0ed04)

### PR DESCRIPTION
**Pull request by dmarcoux**
Fixes #9603

### CODE REVIEW

File: src/api/app/controllers/webui/packages/branches_controller.rb [hunk 1]
```diff
@@ -1,6 +1,8 @@
 module Webui
   module Packages
     class BranchesController < Packages::MainController
+      before_action :require_login
+      before_action :lockout_spiders
```
Comment (hennevogel) [inline src/api/app/controllers/webui/packages/branches_controller.rb:5]: Why? This carries a ranking penalty.
