### PR TITLE
Make the data migration's left join update compatible

### LINKED ISSUE #17354: [production][rake#db:migrate:with_data] An error has occurred, all later migrations canceled:

Mysql2::Error: You have an error in your S...
[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/67a5f5cf84bf460beb376784)
# An error has occurred, all later migrations canceled:

Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near &#39;WHERE bs_request_actions.target_project_id IS NOT NULL AND projects.id IS NUL...&#39; at line 1 #
### Where ###
rake#db:migrate:with_data

### Occured ###
Feb 07 12:00pm

### Similar ###
0

## Params ##
~~~
{
  &quot;argv&quot; =&gt; &quot;db:migrate:with_data VERSION=20250131094818&quot;,
  &quot;execute_args&quot; =&gt; [],
  &quot;rake_task&quot; =&gt; {
    &quot;full_comment&quot; =&gt; &quot;Migrate the database data and schema (options: VERSION=x, VERBOSE=false).&quot;,
    &quot;investigation&quot; =&gt; &quot;------------------------------\nInvestigating db:migrate:with_data\nclass: Rake::Task\ntask needed: true\ntimestamp: 2025-02-07 12:00:15 +0000\npre-requisites: \n--db:load_config (2025-02-07 12:00:15 +0000)\nlatest-prerequisite time: 2025-02-07 12:00:15 +0000\n................................\n\n&quot;,
    &quot;locations&quot; =&gt; [&quot;/usr/lib64/obs-api/ruby/3.1.0/gems/data_migrate-11.2.0/tasks/databases.rake:8:in `block (2 levels) in &lt;top (required)&gt;&#39;&quot;],
    &quot;name&quot; =&gt; &quot;db:migrate:with_data&quot;,
    &quot;prerequisite_tasks&quot; =&gt; [{&quot;name&quot;=&gt;&quot;db:load_config&quot;, &quot;timestamp&quot;=&gt;&quot;2025-02-07 12:00:15 +0000&quot;, &quot;investigation&quot;=&gt;&quot;------------------------------\nInvestigating db:load_config\nclass: Rake::Task\ntask needed: true\ntimestamp: 2025-02-07 12:00:15 +0000\npre-requisites: \n--environment (2025-02-07 12:00:15 +0000)\nlatest-prerequisite time: 2025-02-07 12:00:15 +0000\n................................\n\n&quot;, &quot;locations&quot;=&gt;[&quot;/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.8.1/lib/active_record/railtie.rb:45:in `block (2 levels) in &lt;class:Railtie&gt;&#39;&quot;, &quot;/usr/lib64/obs-api/ruby/3.1.0/gems/activerecord-7.0.8.1/lib/active_record/railties/databases.rake:21:in `block in &lt;top (required)&gt;&#39;&quot;], &quot;sources&quot;=&gt;[&quot;environment&quot;], &quot;prerequisite_tasks&quot;=&gt;[{&quot;name&quot;=&gt;&quot;environment&quot;, &quot;timestamp&quot;=&gt;&quot;2025-02-07 12:00:15 +0000&quot;, &quot;investigation&quot;=&gt;&quot;------------------------------\nInvestigating environment\nclass: Rake::Task\ntask needed: true\ntimestamp: 2025-02-07 12:00:15 +0000\npre-requisites: \nlatest-prerequisite time: \n................................\n\n&quot;, &quot;locations&quot;=&gt;[&quot;/usr/lib64/obs-api/ruby/3.1.0/gems/railties-7.0.8.1/lib/rails/application.rb:503:in `run_tasks_blocks&#39;&quot;]}]}],
    &quot;sources&quot; =&gt; [&quot;load_config&quot;],
    &quot;timestamp&quot; =&gt; &quot;2025-02-07 12:00:15 +0000&quot;
  }
}
~~~

## Session ##
~~~
{}
~~~

## Backtrace ##
~~~
151:  /GEM_ROOT/gems/mysql2-0.5.6/lib/mysql2/client.rb -> **_query**
151:  /GEM_ROOT/gems/mysql2-0.5.6/lib/mysql2/client.rb -> **block in query**
150:  /GEM_ROOT/gems/mysql2-0.5.6/lib/mysql2/client.rb -> **handle_interrupt**
150:  /GEM_ROOT/gems/mysql2-0.5.6/lib/mysql2/client.rb -> **query**
638:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb -> **block (2 levels) in raw_execute**
187:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/concurrency/share_lock.rb -> **yield_shares**
41:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/dependencies/interlock.rb -> **permit_concurrent_loads**
637:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb -> **block in raw_execute**
25:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **handle_interrupt**
25:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **block in synchronize**
21:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **handle_interrupt**
21:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **synchronize**
752:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract_adapter.rb -> **block in log**
24:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications/instrumenter.rb -> **instrument**
743:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract_adapter.rb -> **log**
636:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb -> **raw_execute**
96:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/mysql/database_statements.rb -> **raw_execute**
47:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/mysql/database_statements.rb -> **execute**
202:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb -> **execute_and_free**
73:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/mysql/database_statements.rb -> **block in exec_delete**
25:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **handle_interrupt**
25:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **block in synchronize**
21:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **handle_interrupt**
21:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **synchronize**
72:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/mysql/database_statements.rb -> **exec_delete**
175:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/database_statements.rb -> **update**
22:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/query_cache.rb -> **update**
485:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/relation.rb -> **update_all**
74:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/relation/batches/batch_enumerator.rb -> **block in update_all**
245:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/relation/batches.rb -> **block in in_batches**
229:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/relation/batches.rb -> **loop**
229:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/relation/batches.rb -> **in_batches**
94:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/relation/batches/batch_enumerator.rb -> **each**
94:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/relation/batches/batch_enumerator.rb -> **each**
78:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/core_ext/enumerable.rb -> **map**
78:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/core_ext/enumerable.rb -> **sum**
73:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/relation/batches/batch_enumerator.rb -> **update_all**
9:  db/data/20250131094818_nullify_targets_on_bs_request_actions.rb -> **up**
908:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/migration.rb -> **public_send**
908:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/migration.rb -> **exec_migration**
889:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/migration.rb -> **block (2 levels) in migrate**
296:  /usr/lib64/ruby/3.1.0/benchmark.rb -> **measure**
888:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/migration.rb -> **block in migrate**
215:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/connection_pool.rb -> **with_connection**
887:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/migration.rb -> **migrate**
5:  /GEM_ROOT/gems/strong_migrations-2.2.0/lib/strong_migrations/migration.rb -> **migrate**
1095:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/migration.rb -> **migrate**
1409:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/migration.rb -> **block in execute_migration_in_transaction**
1462:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/migration.rb -> **ddl_transaction**
4:  /GEM_ROOT/gems/strong_migrations-2.2.0/lib/strong_migrations/migrator.rb -> **ddl_transaction**
1408:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/migration.rb -> **execute_migration_in_transaction**
1370:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/migration.rb -> **run_without_lock**
1323:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/migration.rb -> **block in run**
1481:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/migration.rb -> **block in with_advisory_lock**
215:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/connection_pool.rb -> **with_connection**
1496:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/migration.rb -> **with_advisory_lock_connection**
1477:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/migration.rb -> **with_advisory_lock**
1323:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/migration.rb -> **run**
32:  /GEM_ROOT/gems/data_migrate-11.2.0/lib/data_migrate/migration_context.rb -> **run**
61:  /GEM_ROOT/gems/data_migrate-11.2.0/lib/data_migrate/data_migrator.rb -> **run**
206:  /GEM_ROOT/gems/data_migrate-11.2.0/lib/data_migrate/database_tasks.rb -> **block (3 levels) in migrate_with_data**
215:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/connection_pool.rb -> **with_connection**
27:  /GEM_ROOT/gems/data_migrate-11.2.0/lib/data_migrate/database_tasks.rb -> **block in with_temporary_connection**
43:  /GEM_ROOT/gems/data_migrate-11.2.0/lib/data_migrate/database_tasks.rb -> **with_temporary_pool**
26:  /GEM_ROOT/gems/data_migrate-11.2.0/lib/data_migrate/database_tasks.rb -> **with_temporary_connection**
204:  /GEM_ROOT/gems/data_migrate-11.2.0/lib/data_migrate/database_tasks.rb -> **block (2 levels) in migrate_with_data**
199:  /GEM_ROOT/gems/data_migrate-11.2.0/lib/data_migrate/database_tasks.rb -> **each**
199:  /GEM_ROOT/gems/data_migrate-11.2.0/lib/data_migrate/database_tasks.rb -> **block in migrate_with_data**
198:  /GEM_ROOT/gems/data_migrate-11.2.0/lib/data_migrate/database_tasks.rb -> **each**
198:  /GEM_ROOT/gems/data_migrate-11.2.0/lib/data_migrate/database_tasks.rb -> **migrate_with_data**
9:  /GEM_ROOT/gems/data_migrate-11.2.0/tasks/databases.rake -> **block (3 levels) in &lt;top (required)&gt;**
281:  /GEM_ROOT/gems/rake-13.0.6/lib/rake/task.rb -> **block in execute**
281:  /GEM_ROOT/gems/rake-13.0.6/lib/rake/task.rb -> **each**
281:  /GEM_ROOT/gems/rake-13.0.6/lib/rake/task.rb -> **execute**
17:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rake.rb -> **execute**
219:  /GEM_ROOT/gems/rake-13.0.6/lib/rake/task.rb -> **block in invoke_with_call_chain**
199:  /GEM_ROOT/gems/rake-13.0.6/lib/rake/task.rb -> **synchronize**
199:  /GEM_ROOT/gems/rake-13.0.6/lib/rake/task.rb -> **invoke_with_call_chain**
188:  /GEM_ROOT/gems/rake-13.0.6/lib/rake/task.rb -> **invoke**
160:  /GEM_ROOT/gems/rake-13.0.6/lib/rake/application.rb -> **invoke_task**
116:  /GEM_ROOT/gems/rake-13.0.6/lib/rake/application.rb -> **block (2 levels) in top_level**
116:  /GEM_ROOT/gems/rake-13.0.6/lib/rake/application.rb -> **each**
116:  /GEM_ROOT/gems/rake-13.0.6/lib/rake/application.rb -> **block in top_level**
125:  /GEM_ROOT/gems/rake-13.0.6/lib/rake/application.rb -> **run_with_threads**
110:  /GEM_ROOT/gems/rake-13.0.6/lib/rake/application.rb -> **top_level**
83:  /GEM_ROOT/gems/rake-13.0.6/lib/rake/application.rb -> **block in run**
186:  /GEM_ROOT/gems/rake-13.0.6/lib/rake/application.rb -> **standard_exception_handling**
80:  /GEM_ROOT/gems/rake-13.0.6/lib/rake/application.rb -> **run**
27:  /GEM_ROOT/gems/rake-13.0.6/exe/rake -> **&lt;top (required)&gt;**
25:  /GEM_ROOT/bin/rake -> **load**
25:  /GEM_ROOT/bin/rake -> **&lt;top (required)&gt;**
58:  /usr/lib64/ruby/3.1.0/bundler/cli/exec.rb -> **load**
58:  /usr/lib64/ruby/3.1.0/bundler/cli/exec.rb -> **kernel_load**
23:  /usr/lib64/ruby/3.1.0/bundler/cli/exec.rb -> **run**
486:  /usr/lib64/ruby/3.1.0/bundler/cli.rb -> **exec**
27:  /usr/lib64/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb -> **run**
127:  /usr/lib64/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb -> **invoke_command**
392:  /usr/lib64/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb -> **dispatch**
31:  /usr/lib64/ruby/3.1.0/bundler/cli.rb -> **dispatch**
485:  /usr/lib64/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb -> **start**
25:  /usr/lib64/ruby/3.1.0/bundler/cli.rb -> **start**
48:  /usr/lib64/ruby/gems/3.1.0/gems/bundler-2.3.27/libexec/bundle -> **block in &lt;top (required)&gt;**
120:  /usr/lib64/ruby/3.1.0/bundler/friendly_errors.rb -> **with_friendly_errors**
36:  /usr/lib64/ruby/gems/3.1.0/gems/bundler-2.3.27/libexec/bundle -> **&lt;top (required)&gt;**
113:  bin/bundle -> **load**
113:  bin/bundle -> **&lt;main&gt;**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| program_name | /usr/lib64/obs-api/ruby/3.1.0/bin/rake |
| HTTP_USER_AGENT |  |

### PR DESCRIPTION
**Pull request by danidoni**
Looks like writing it by hand needs a bit more sql statements to make it compatible with an update statement, so we let ActiveRecord craft it for us.

Fixes #17354

### CODE REVIEW

File: src/api/db/data/20250131094818_nullify_targets_on_bs_request_actions.rb [hunk 1]
```diff
@@ -4,14 +4,17 @@ class NullifyTargetsOnBsRequestActions < ActiveRecord::Migration[7.0]
   # rubocop:disable Rails/SkipsModelValidations
   def up
     BsRequestAction
-      .joins('LEFT JOIN projects ON bs_request_actions.target_project_id = projects.id WHERE bs_request_actions.target_project_id IS NOT NULL AND projects.id IS NULL')
+      .left_joins(:target_project_object)
```
Comment (danidoni) [inline src/api/db/data/20250131094818_nullify_targets_on_bs_request_actions.rb:7]: Instead of the table name, we need to use the association name: [this one](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/models/bs_request_action.rb#L20)

**Review by eduardoj — APPROVED** [review]
