### PR TITLE
[webui] Refactoring user requests datatables

### LINKED ISSUE #2572: Sorting in request lists broken
At least in outgoing requests the oldest request is on top and there is a an arrow to sort - but no matter how the arrow points, the oldest is always on top.

### PR DESCRIPTION
**Pull request by ChrisBr**
- Moved logic from controller to RequestsDatatable class
- Fix request sorting ordering by column (introduced by 509370a)
Fixes #2572

### CODE REVIEW

**Comment by ChrisBr** [comment]
@evanrolfe please have a look!

File: src/api/app/models/requests_datatable.rb [hunk 1]
```diff
@@ -0,0 +1,140 @@
+class RequestsDatatable
+  delegate :sprite_tag, :common_parts, :user_with_realname_and_icon, :fuzzy_time,
+           :project_or_package_link, :params, :link_to, :request_show_path, to: :@view
```
Comment (evanrolfe) [inline src/api/app/models/requests_datatable.rb]: I dont understand what this is for?

Comment (ChrisBr) [inline src/api/app/models/requests_datatable.rb]: These are view helper methods which I use e.g. in ``show_column`` or ``requester_column``

**Comment by evanrolfe** [comment]
Nice work on this, the code is definitely not easy to work with! I have some suggestions with your class design though, the `RequestsDatatable` is too complicated and does not follow [SOLID](https://en.wikipedia.org/wiki/SOLID_(object-oriented_design)) principles.

I would split `RequestsDatatable` into two classes: `RequestsDatatable` and `RequestsDatatableRow`. Also I don't think you should have any view methods like `link_to`, `project_or_package_link` inside a model because it doesn't follow the MVC pattern. Those methods should only ever be in views or helpers.

So I would use move the view methods to a json erb view file like it was done originally i.e.
https://gist.github.com/evanrolfe/ca834754a183f75986d825458ed55d21

(Warning: Code not tested.)

File: src/api/spec/models/requests_data_table_spec.rb [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+             source_project: source_project,
+             source_package: source_package,
+             target_project: target_project,
+             target_package: target_package)
+    }
+
+    context 'sort direction' do
+      context 'defaults to sort by :created_at :desc' do
+        before do
+          @data = RequestsDataTable.new({ format: :json, length: 10, start: 0 }, user).rows
```
Comment (evanrolfe) [inline src/api/spec/models/requests_data_table_spec.rb]: Why is `format: :json` a param here? It doesn't ever get used by this class does it?

File: src/api/spec/models/requests_data_table_spec.rb [hunk 3]
```diff
@@ -0,0 +1,96 @@
...
+      create(:bs_request_with_submit_action,
+             created_at: 2.days.ago,
+             creator: user,
+             source_project: source_project,
+             source_package: source_package,
+             target_project: target_project,
+             target_package: target_package)
+    }
+
+    context 'sort direction' do
```
Comment (evanrolfe) [inline src/api/spec/models/requests_data_table_spec.rb]: Can you please have a look at the [betterspecs guidelines](http://betterspecs.org/#contexts) for rspec because this isn't the way context is meant to be used.

Here is an example of how the spec could be written to follow the rspec guidelines (and also I've added tests for the untested public methods on this class - `draw`, `records_total`, `count_requests`:

https://gist.github.com/evanrolfe/eb422ca6766cd063b1f90012e9a97bf9

File: src/api/app/controllers/webui/user_controller.rb [hunk 4]
```diff
@@ -71,42 +71,10 @@ def home
...
-      'requests_declined_table' => :declined_requests,
-      'requests_in_table'       => :incoming_requests,
-      'reviews_in_table'        => :involved_reviews
-    }
-    # Depending on the table that is requesting we call the appropiate user method
-    request_method = request_methods[params[:dataTableId]] || :requests
-    @requests = @displayed_user.send(request_method, search)
-    @requests_count = @requests.count
-    @requests = @requests.offset(params[:start].to_i).limit(params[:length].to_i).reorder(sorting_field => sorting_dir)
+    @data = RequestsDataTable.new(params, @displayed_user)
```
Comment (evanrolfe) [inline src/api/app/controllers/webui/user_controller.rb]: Can we call this something more descriptive? i.e. `@requests_data_table`?

File: src/api/app/views/webui/user/requests.json.erb [hunk 5]
```diff
@@ -0,0 +1,21 @@
...
+      "<%= escape_javascript(project_or_package_link(project: row.source_project, package: row.source_package, creator: row.creator, trim_to: 40, short: true)) %>",
+      "<%= escape_javascript(target_project_link(row)) %>",
+      "<%= escape_javascript(user_with_realname_and_icon(row.creator, short: true)) %>",
+      "<%= escape_javascript(row.request_type) %>",
+      "<%= escape_javascript(row.priority) %>",
+      "<%= escape_javascript(link_to(sprite_tag('req-showdiff', title: "Show request ##{row.number}"), request_show_path(row.number), { class: :request_link })) %>"
+    ]
+    <% unless index == @data.rows.length - 1 %>
+  ,
+    <% end %>
```
Comment (evanrolfe) [inline src/api/app/views/webui/user/requests.json.erb]: looks like something is wrong with the indentation here?

**Comment by evanrolfe** [comment]
LGTM (assuming the build passes)
