### PR TITLE
Prevent errors for a BsRequest without a description in NotificationExcerptComponent

### LINKED ISSUE #12224: [production][notifications#index] undefined method `index' for nil:NilClass
[See this exception on Errbit](https://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/620e5edd84bf46054d0887ee)
# undefined method `index&#39; for nil:NilClass #
### URL ###
[https://build.opensuse.org/my/notifications](https://build.opensuse.org/my/notifications)"
### Where ###
notifications#index

### Occured ###
Feb 17  2:42pm

### Similar ###
0

## Params ##
~~~
{
  &quot;action&quot; =&gt; &quot;index&quot;,
  &quot;controller&quot; =&gt; &quot;webui/users/notifications&quot;
}
~~~

## Session ##
~~~
{
  &quot;_csrf_token&quot; =&gt; &quot;4jI47akyJop+/xVDHeI8H/w/33AkJY2bqXOCO08ntZg=&quot;,
  &quot;session_id&quot; =&gt; &quot;08bf18e18d8f91d5e82a18c1b7853716&quot;
}
~~~

## Backtrace ##
~~~
27:  app/components/notification_excerpt_component.rb -> **truncate_to_first_new_line**
21:  app/components/notification_excerpt_component.rb -> **call**
130:  /GEM_ROOT/gems/view_component-2.49.0/lib/view_component/compiler.rb -> **render_template_for**
90:  /GEM_ROOT/gems/view_component-2.49.0/lib/view_component/base.rb -> **render_in**
43:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/helpers/rendering_helper.rb -> **render**
13:  /GEM_ROOT/gems/haml-5.2.2/lib/haml/helpers/action_view_mods.rb -> **block in render**
93:  /GEM_ROOT/gems/haml-5.2.2/lib/haml/helpers.rb -> **non_haml**
13:  /GEM_ROOT/gems/haml-5.2.2/lib/haml/helpers/action_view_mods.rb -> **render**
141:  /GEM_ROOT/gems/view_component-2.49.0/lib/view_component/base.rb -> **render**
30:  app/components/notification_component.html.haml -> **call**
130:  /GEM_ROOT/gems/view_component-2.49.0/lib/view_component/compiler.rb -> **render_template_for**
90:  /GEM_ROOT/gems/view_component-2.49.0/lib/view_component/base.rb -> **render_in**
15:  /GEM_ROOT/gems/view_component-2.49.0/lib/view_component/collection.rb -> **block in render_in**
14:  /GEM_ROOT/gems/view_component-2.49.0/lib/view_component/collection.rb -> **map**
14:  /GEM_ROOT/gems/view_component-2.49.0/lib/view_component/collection.rb -> **render_in**
43:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/helpers/rendering_helper.rb -> **render**
13:  /GEM_ROOT/gems/haml-5.2.2/lib/haml/helpers/action_view_mods.rb -> **block in render**
93:  /GEM_ROOT/gems/haml-5.2.2/lib/haml/helpers.rb -> **non_haml**
13:  /GEM_ROOT/gems/haml-5.2.2/lib/haml/helpers/action_view_mods.rb -> **render**
24:  app/views/webui/users/notifications/_notifications_list.html.haml -> **block in _app_views_webui_users_notifications__notifications_list_html_haml___2779251568080979217_46963695264200**
118:  /GEM_ROOT/gems/haml-5.2.2/lib/haml/helpers/action_view_mods.rb -> **block (2 levels) in form_tag_with_haml**
289:  /GEM_ROOT/gems/haml-5.2.2/lib/haml/helpers.rb -> **with_tabs**
118:  /GEM_ROOT/gems/haml-5.2.2/lib/haml/helpers/action_view_mods.rb -> **block in form_tag_with_haml**
693:  /GEM_ROOT/gems/haml-5.2.2/lib/haml/helpers.rb -> **block in haml_bind_proc**
379:  /GEM_ROOT/gems/haml-5.2.2/lib/haml/helpers.rb -> **block in capture_haml**
670:  /GEM_ROOT/gems/haml-5.2.2/lib/haml/helpers.rb -> **with_haml_buffer**
375:  /GEM_ROOT/gems/haml-5.2.2/lib/haml/helpers.rb -> **capture_haml**
66:  /GEM_ROOT/gems/haml-5.2.2/lib/haml/helpers/xss_mods.rb -> **capture_haml_with_haml_xss**
46:  /GEM_ROOT/gems/haml-5.2.2/lib/haml/helpers/action_view_mods.rb -> **capture_with_haml**
75:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/helpers/form_tag_helper.rb -> **form_tag**
121:  /GEM_ROOT/gems/haml-5.2.2/lib/haml/helpers/action_view_mods.rb -> **form_tag_with_haml**
20:  /GEM_ROOT/gems/haml-5.2.2/lib/haml/helpers/action_view_xss_mods.rb -> **form_tag_with_haml_xss**
16:  app/views/webui/users/notifications/_notifications_list.html.haml -> **_app_views_webui_users_notifications__notifications_list_html_haml___2779251568080979217_46963695264200**
247:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/base.rb -> **public_send**
247:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/base.rb -> **_run**
154:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/template.rb -> **block in render**
205:  /GEM_ROOT/gems/activesupport-6.1.4.6/lib/active_support/notifications.rb -> **instrument**
345:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/template.rb -> **instrument_render_template**
152:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/template.rb -> **render**
285:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/renderer/partial_renderer.rb -> **block in render_partial_template**
203:  /GEM_ROOT/gems/activesupport-6.1.4.6/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-6.1.4.6/lib/active_support/notifications/instrumenter.rb -> **instrument**
203:  /GEM_ROOT/gems/activesupport-6.1.4.6/lib/active_support/notifications.rb -> **instrument**
280:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/renderer/partial_renderer.rb -> **render_partial_template**
271:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/renderer/partial_renderer.rb -> **render**
81:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/renderer/renderer.rb -> **render_partial_to_object**
27:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/renderer/renderer.rb -> **render_to_object**
22:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/renderer/renderer.rb -> **render**
38:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/helpers/rendering_helper.rb -> **block in render**
273:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/base.rb -> **in_rendering_context**
34:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/helpers/rendering_helper.rb -> **render**
13:  /GEM_ROOT/gems/haml-5.2.2/lib/haml/helpers/action_view_mods.rb -> **block in render**
93:  /GEM_ROOT/gems/haml-5.2.2/lib/haml/helpers.rb -> **non_haml**
13:  /GEM_ROOT/gems/haml-5.2.2/lib/haml/helpers/action_view_mods.rb -> **render**
16:  app/views/webui/users/notifications/index.html.haml -> **_app_views_webui_users_notifications_index_html_haml___361970216248377275_46963663121120**
247:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/base.rb -> **public_send**
247:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/base.rb -> **_run**
154:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/template.rb -> **block in render**
205:  /GEM_ROOT/gems/activesupport-6.1.4.6/lib/active_support/notifications.rb -> **instrument**
345:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/template.rb -> **instrument_render_template**
152:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/template.rb -> **render**
61:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/renderer/template_renderer.rb -> **block (2 levels) in render_template**
203:  /GEM_ROOT/gems/activesupport-6.1.4.6/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-6.1.4.6/lib/active_support/notifications/instrumenter.rb -> **instrument**
203:  /GEM_ROOT/gems/activesupport-6.1.4.6/lib/active_support/notifications.rb -> **instrument**
56:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/renderer/template_renderer.rb -> **block in render_template**
71:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/renderer/template_renderer.rb -> **block in render_with_layout**
205:  /GEM_ROOT/gems/activesupport-6.1.4.6/lib/active_support/notifications.rb -> **instrument**
70:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/renderer/template_renderer.rb -> **render_with_layout**
55:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/renderer/template_renderer.rb -> **render_template**
11:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/renderer/template_renderer.rb -> **render**
61:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/renderer/renderer.rb -> **render_template_to_object**
29:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/renderer/renderer.rb -> **render_to_object**
117:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/rendering.rb -> **block in _render_template**
273:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/base.rb -> **in_rendering_context**
116:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/rendering.rb -> **_render_template**
218:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal/streaming.rb -> **_render_template**
103:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/rendering.rb -> **render_to_body**
52:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal/rendering.rb -> **render_to_body**
142:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal/renderers.rb -> **render_to_body**
25:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/abstract_controller/rendering.rb -> **render**
36:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal/rendering.rb -> **render**
46:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal/instrumentation.rb -> **block (2 levels) in render**
308:  /usr/lib64/ruby/2.5.0/benchmark.rb -> **realtime**
14:  /GEM_ROOT/gems/activesupport-6.1.4.6/lib/active_support/core_ext/benchmark.rb -> **ms**
46:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal/instrumentation.rb -> **block in render**
86:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal/instrumentation.rb -> **cleanup_view_runtime**
34:  /GEM_ROOT/gems/activerecord-6.1.4.6/lib/active_record/railties/controller_runtime.rb -> **cleanup_view_runtime**
45:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal/instrumentation.rb -> **render**
35:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal/implicit_render.rb -> **default_render**
6:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal/basic_implicit_render.rb -> **block in send_action**
6:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal/basic_implicit_render.rb -> **tap**
6:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal/basic_implicit_render.rb -> **send_action**
228:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/abstract_controller/base.rb -> **process_action**
30:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal/rendering.rb -> **process_action**
42:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/abstract_controller/callbacks.rb -> **block in process_action**
106:  /GEM_ROOT/gems/activesupport-6.1.4.6/lib/active_support/callbacks.rb -> **run_callbacks**
41:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/abstract_controller/callbacks.rb -> **process_action**
22:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal/rescue.rb -> **process_action**
34:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal/instrumentation.rb -> **block in process_action**
203:  /GEM_ROOT/gems/activesupport-6.1.4.6/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-6.1.4.6/lib/active_support/notifications/instrumenter.rb -> **instrument**
203:  /GEM_ROOT/gems/activesupport-6.1.4.6/lib/active_support/notifications.rb -> **instrument**
33:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal/instrumentation.rb -> **process_action**
249:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal/params_wrapper.rb -> **process_action**
27:  /GEM_ROOT/gems/activerecord-6.1.4.6/lib/active_record/railties/controller_runtime.rb -> **process_action**
165:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/abstract_controller/base.rb -> **process**
39:  /GEM_ROOT/gems/actionview-6.1.4.6/lib/action_view/rendering.rb -> **process**
190:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal.rb -> **dispatch**
254:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_controller/metal.rb -> **dispatch**
50:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/routing/route_set.rb -> **dispatch**
33:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/routing/route_set.rb -> **serve**
19:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/routing/mapper.rb -> **block in &lt;class:Constraints&gt;**
49:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/routing/mapper.rb -> **serve**
50:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/journey/router.rb -> **block in serve**
32:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/journey/router.rb -> **each**
32:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/journey/router.rb -> **serve**
842:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/routing/route_set.rb -> **call**
77:  /GEM_ROOT/gems/flipper-0.23.1/lib/flipper/middleware/memoizer.rb -> **memoized_call**
42:  /GEM_ROOT/gems/flipper-0.23.1/lib/flipper/middleware/memoizer.rb -> **call**
37:  config/initializers/wrap_parameters.rb -> **call**
44:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/deflater.rb -> **call**
15:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/etag.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/conditional_get.rb -> **call**
12:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/head.rb -> **call**
22:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/http/permissions_policy.rb -> **call**
18:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/http/content_security_policy.rb -> **call**
266:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/session/abstract/id.rb -> **context**
260:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/session/abstract/id.rb -> **call**
689:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/middleware/cookies.rb -> **call**
27:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/middleware/callbacks.rb -> **block in call**
98:  /GEM_ROOT/gems/activesupport-6.1.4.6/lib/active_support/callbacks.rb -> **run_callbacks**
26:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/middleware/callbacks.rb -> **call**
18:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/middleware/actionable_exceptions.rb -> **call**
32:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call!**
21:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call**
29:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/middleware/debug_exceptions.rb -> **call**
33:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/middleware/show_exceptions.rb -> **call**
15:  /GEM_ROOT/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb -> **call_app**
26:  /GEM_ROOT/gems/railties-6.1.4.6/lib/rails/rack/logger.rb -> **block in call**
99:  /GEM_ROOT/gems/activesupport-6.1.4.6/lib/active_support/tagged_logging.rb -> **block in tagged**
37:  /GEM_ROOT/gems/activesupport-6.1.4.6/lib/active_support/tagged_logging.rb -> **tagged**
99:  /GEM_ROOT/gems/activesupport-6.1.4.6/lib/active_support/tagged_logging.rb -> **tagged**
26:  /GEM_ROOT/gems/railties-6.1.4.6/lib/rails/rack/logger.rb -> **call**
81:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/middleware/remote_ip.rb -> **call**
81:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/middleware/remote_ip.rb -> **call**
19:  /GEM_ROOT/gems/request_store-1.5.1/lib/request_store/middleware.rb -> **call**
26:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/middleware/request_id.rb -> **call**
24:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/method_override.rb -> **call**
22:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/runtime.rb -> **call**
29:  /GEM_ROOT/gems/activesupport-6.1.4.6/lib/active_support/cache/strategy/local_cache_middleware.rb -> **call**
14:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/middleware/executor.rb -> **call**
18:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/lock.rb -> **call**
110:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/sendfile.rb -> **call**
113:  /GEM_ROOT/gems/actionpack-6.1.4.6/lib/action_dispatch/middleware/host_authorization.rb -> **call**
539:  /GEM_ROOT/gems/railties-6.1.4.6/lib/rails/engine.rb -> **call**
207:  /GEM_ROOT/gems/railties-6.1.4.6/lib/rails/railtie.rb -> **public_send**
207:  /GEM_ROOT/gems/railties-6.1.4.6/lib/rails/railtie.rb -> **method_missing**
74:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/urlmap.rb -> **block in call**
58:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/urlmap.rb -> **each**
58:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/urlmap.rb -> **call**
107:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.12/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb -> **process_request**
149:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.12/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **accept_and_process_next_request**
110:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.12/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **main_loop**
419:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.12/src/ruby_supportlib/phusion_passenger/request_handler.rb -> **block (3 levels) in start_threads**
113:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.12/src/ruby_supportlib/phusion_passenger/utils.rb -> **block in create_thread_and_abort_on_exception**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| program_name | Passenger RubyApp: /srv/www/obs/api (production) |
| HTTP_USER_AGENT | Mozilla/5.0 (X11; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0 |

### PR DESCRIPTION
**Pull request by dmarcoux**
Fixes #12224

### CODE REVIEW

File: src/api/spec/components/notification_excerpt_component_spec.rb [hunk 1]
```diff
@@ -2,21 +2,32 @@
 
 RSpec.describe NotificationExcerptComponent, type: :component do
   let(:user) { create(:user) }
-  let(:notification_for_projects_comment) { create(:web_notification, :comment_for_project, notifiable: comment, subscriber: user) }
 
-  context 'with short excerpt' do
+  context 'notification for a BsRequest without a description' do
```
Comment (dmarcoux) [inline src/api/spec/components/notification_excerpt_component_spec.rb:6]: This new spec reproduces the issue and proves the fix is working.

File: src/api/app/components/notification_excerpt_component.rb [hunk 2]
```diff
@@ -11,7 +11,7 @@ def initialize(notification)
   def call
     text = case @notification.notifiable_type
            when 'BsRequest'
-             @notification.notifiable.description
+             @notification.notifiable.description.to_s # description can be nil
            when 'Comment'
              helpers.render_without_markdown(@notification.notifiable.body)
```
Comment (dmarcoux) [inline src/api/app/components/notification_excerpt_component.rb:16]: There's a validation on the `Comment` model to prevent `body` from being `nil`.

File: src/api/spec/components/notification_excerpt_component_spec.rb [hunk 3]
```diff
@@ -2,21 +2,32 @@
...
+    let(:bs_request) { create(:bs_request_with_submit_action, description: nil) }
+    let(:notification) { create(:web_notification, :request_created, notifiable: bs_request, subscriber: user) }
+
+    it do
+      expect(render_inline(described_class.new(notification))).not_to have_text('...')
+    end
+  end
+
+
+  context 'notification for a short comment' do
```
Comment (dmarcoux) [inline src/api/spec/components/notification_excerpt_component_spec.rb:16]: I reworked the specs a bit.

File: src/api/spec/components/notification_excerpt_component_spec.rb [hunk 4]
```diff
@@ -2,21 +2,31 @@
...
   let(:user) { create(:user) }
-  let(:notification_for_projects_comment) { create(:web_notification, :comment_for_project, notifiable: comment, subscriber: user) }
 
-  context 'with short excerpt' do
+  context 'notification for a BsRequest without a description' do
+    let(:bs_request) { create(:bs_request_with_submit_action, description: nil) }
+    let(:notification) { create(:web_notification, :request_created, notifiable: bs_request, subscriber: user) }
+
+    it do
+      expect(render_inline(described_class.new(notification))).not_to have_text('...')
```
Comment (eduardoj) [inline src/api/spec/components/notification_excerpt_component_spec.rb:11]: This is checking the string for not having the text `...`. With a description with a `nil` value, shouldn't we check for the empty string?

Comment (dmarcoux) [reply src/api/spec/components/notification_excerpt_component_spec.rb:11]: Good point, I changed the specs to check for an empty string.

**Review by krauselukas — APPROVED** [review]

**Review by eduardoj — APPROVED** [review]
