### PR TITLE
Fix pre-filling of the Submit Request Form

### LINKED ISSUE #7551: Submit request form is not pre-filled with target project
As far as I remember this form used to be filled out with the target project. This was at least the case when the source project was branched from another one.

How to Reproduce
===============
1. Branch a project
2. Edit the sources
3. Submit the project

=> The target project field is empty

### PR DESCRIPTION
**Pull request by danidoni**
After branching and submitting a package, the form was not pre-filled with the
project and package.

This fix, pre-fills the Submit when hitting the Project overview's
"Submit package" link.

Fixes #7551

Co-authored-by: Eduardo Navarro <enavarro@suse.com>

### CODE REVIEW

**Comment by danidoni** [comment]
[Address Feedback (Sprint 61)](https://trello.com/c/ZdIgWr3T/1179-address-feedback-sprint-61)

**Comment by vpereira** [comment]
Hey @danidoni looks like you need to refresh the VCR. Sadly I couldn't find a wiki page to provide you. Maybe @eduardoj can help you to do it tomorrow.

**Comment by danidoni** [comment]
> Hey @danidoni looks like you need to refresh the VCR. Sadly I couldn't find a wiki page to provide you. Maybe @eduardoj can help you to do it tomorrow.

Thanks! Let me take a look.

**Comment by vpereira** [comment]
Hi @danidoni, I created a wiki to try to document how we work with *VCR*. https://github.com/openSUSE/open-build-service/wiki/Testing-with-VCR feel free to extend it if you feel that some bit of information was missing.

Something that is important to note is: As soon as you enabled the `global_write_through` you should run just the specific specs, limiting to specific line or context for example, that you want to have the cassette refreshed or generated. If you run for example the whole spec, you will endup updating cassettes that shouldn't be touched (which looks like its the case here)

**Comment by danidoni** [comment]
> That's an awful lot of new cassettes and requests. Something isn't right.

Yes, that's what I'm afraid of... This is the outcome of setting the VCR configuration to `:new-episodes` to record the new requests.

File: src/api/app/controllers/webui2/package_controller.rb [hunk 1]
```diff
@@ -25,4 +28,11 @@ def webui2_statistics
                                                       repository: @repository,
                                                       architecture: params[:arch]).results
   end
+
+  private
+
+  def backend_linked_project_package(package)
+    lt = package.backend_package.links_to
```
Comment (vpereira) [inline src/api/app/controllers/webui2/package_controller.rb]: maybe we could come up with a better name than `lt` here? `link_to_package` ?

File: src/api/app/controllers/webui2/package_controller.rb [hunk 2]
```diff
@@ -1,5 +1,8 @@
 module Webui2::PackageController
   def webui2_show
+    @tprj, @tpkg = backend_linked_project_package(@package)
+    @tprj = params[:targetproject] if params[:targetproject] # allow to override by parameter
+    @tpkg = params[:targetpackage] if params[:targetpackage] # allow to override by parameter
```
Comment (vpereira) [inline src/api/app/controllers/webui2/package_controller.rb]: With the strong typing hat on: Are we storing in `@tprj` and `@tpkg` information of the same type?

**Comment by danidoni** [comment]
Ouch, I closed the PR by mistake. Reopening

File: src/api/app/controllers/webui2/package_controller.rb (hunk 1 above)
Comment (danidoni) [reply src/api/app/controllers/webui2/package_controller.rb]: Sure, I'm returning the project and package names, so what about `project_and_package_names`?

File: src/api/app/controllers/webui2/package_controller.rb (hunk 2 above)
Comment (danidoni) [reply src/api/app/controllers/webui2/package_controller.rb]: Yes, both are strings if they are present

File: src/api/app/controllers/webui2/package_controller.rb (hunk 1 above)
Comment (vpereira) [reply src/api/app/controllers/webui2/package_controller.rb]: great!

File: src/api/app/controllers/webui2/package_controller.rb (hunk 2 above)
Comment (vpereira) [reply src/api/app/controllers/webui2/package_controller.rb]: ok

File: src/api/app/controllers/webui2/package_controller.rb (hunk 1 above)
Comment (danidoni) [reply src/api/app/controllers/webui2/package_controller.rb]: Fixed

**Comment by danidoni** [comment]
> I'm missing more things. This is how it looked in bento:
> 
> Screenshot from 2019-08-26 15-15-51

I'll check it out now.

**Comment by danidoni** [comment]
For the record, @vpereira and me spoke offline and agreed that the generation of all those changes in the cassettes are indeed expected, because the feature specs visit the package show page, and pick up the new code that is calling the backend.

I'll check the ones that are returning 404 because I'm pretty sure those are wrong.

**Comment by danidoni** [comment]
Updated the cassettes that were recorded with the 404 error codes. @vpereira check it out again please.

**Comment by vpereira** [comment]
> Updated the cassettes that were recorded with the 404 error codes. @vpereira check it out again please.

for me it's ok, just @hennevogel mentioned that there are more fields that we can pre-fill https://github.com/openSUSE/open-build-service/pull/7934#pullrequestreview-279583704

**Comment by hennevogel** [comment]
Any news here?

**Comment by danidoni** [comment]
> Any news here?

Yes, I'm working on a commit to address the rest of the fields that were pre-filled in the old UI. I'll push it soon.

File: src/api/app/models/project.rb [hunk 3]
```diff
@@ -1568,6 +1568,10 @@ def missing_checks
     @missing_checks ||= calculate_missing_checks
   end
 
+  def branch?
+    name.include?(':branches:')
```
Comment (hennevogel) [inline src/api/app/models/project.rb]: Please also 'port' over the comment ;-) Otherwise people might start to use this for other things.

File: src/api/spec/cassettes/Packages/editing_package_files/editing_an_existing_file.yml [hunk 4]
```diff
@@ -148,22 +150,94 @@ http_interactions:
...
+      Accept-Encoding:
+      - identity
+      Accept:
+      - "*/*"
+      User-Agent:
+      - Ruby
+  response:
+    status:
+      code: 404
+      message: _service  no such file
```
Comment (danidoni) [inline src/api/spec/cassettes/Packages/editing_package_files/editing_an_existing_file.yml]: I don't know how to fix this... Not the haziest clue. Any help would be very appreciated.

Comment (coolo) [reply src/api/spec/cassettes/Packages/editing_package_files/editing_an_existing_file.yml]: Upvote #5308 to ease test development would be my first advise

File: src/api/spec/cassettes/Packages/editing_package_files/editing_an_existing_file.yml [hunk 5]
```diff
@@ -756,16 +1132,16 @@ http_interactions:
       Connection:
       - close
       Content-Length:
-      - '122'
+      - '309'
     body:
       encoding: UTF-8
       string: |
-        <status code="404">
-          <summary>_service: no such file</summary>
```
Comment (coolo) [inline src/api/spec/cassettes/Packages/editing_package_files/editing_an_existing_file.yml]: but you can see here that the 404 was there before - you just changed the order. And this is what puzzles me: tons of your  vcr additions are from 2018. Did you edit that or just fight with vcr madness?

File: src/api/spec/cassettes/Packages/editing_package_files/editing_an_existing_file.yml (hunk 4 above)
Comment (vpereira) [reply src/api/spec/cassettes/Packages/editing_package_files/editing_an_existing_file.yml]: if it was a 404 before then it should be ok...

File: src/api/app/controllers/webui2/package_controller.rb [hunk 6]
```diff
@@ -1,6 +1,11 @@
 module Webui2::PackageController
   def webui2_show
+    @tprj, @tpkg = project_and_package_names(@package)
```
Comment (hennevogel) [inline src/api/app/controllers/webui2/package_controller.rb]: Please do not use these awful variable names.

File: src/api/app/controllers/webui2/package_controller.rb [hunk 7]
```diff
@@ -1,6 +1,11 @@
...
+    @tprj = params[:targetproject] if params[:targetproject] # allow to override by parameter
+    @tpkg = params[:targetpackage] if params[:targetpackage] # allow to override by parameter
```
Comment (hennevogel) [inline src/api/app/controllers/webui2/package_controller.rb]: Why? There is no one making use of this feature in our app.

File: src/api/app/controllers/webui2/package_controller.rb [hunk 8]
```diff
@@ -25,4 +30,11 @@ def webui2_statistics
                                                       repository: @repository,
                                                       architecture: params[:arch]).results
   end
+
+  private
+
+  def project_and_package_names(package)
```
Comment (hennevogel) [inline src/api/app/controllers/webui2/package_controller.rb]: This belongs into `Package`.

File: src/api/app/models/project.rb [hunk 9]
```diff
@@ -1535,6 +1535,10 @@ def missing_checks
     @missing_checks ||= calculate_missing_checks
   end
 
+  def branch?
```
Comment (hennevogel) [inline src/api/app/models/project.rb]:
```suggestion
  # This is not what makes a Package a branch, we only use this to prefill the submit request
  # dialog in the UI. Please do not relay on this!
  def branch?
```

File: src/api/spec/cassettes/Packages/editing_package_files/editing_an_existing_file.yml (hunk 4 above)
Comment (danidoni) [reply src/api/spec/cassettes/Packages/editing_package_files/editing_an_existing_file.yml]: > Upvote #5308 to ease test development would be my first advise

Hm, that would make sense, yeah...

Comment (danidoni) [reply src/api/spec/cassettes/Packages/editing_package_files/editing_an_existing_file.yml]: > if it was a 404 before then it should be ok...

Its true, didn't notice...

File: src/api/spec/cassettes/Packages/editing_package_files/editing_an_existing_file.yml (hunk 5 above)
Comment (danidoni) [reply src/api/spec/cassettes/Packages/editing_package_files/editing_an_existing_file.yml]: Just fighting...

File: src/api/app/controllers/webui2/package_controller.rb (hunk 6 above)
Comment (danidoni) [reply src/api/app/controllers/webui2/package_controller.rb]: I have some improvements here, but I wanted to fix the tests before introducing more changes

File: src/api/app/controllers/webui2/package_controller.rb (hunk 7 above)
Comment (danidoni) [reply src/api/app/controllers/webui2/package_controller.rb]: Not even while using it from `osc`?

Comment (hennevogel) [reply src/api/app/controllers/webui2/package_controller.rb]: Using the webui from osc? Never happens.

Comment (danidoni) [reply src/api/app/controllers/webui2/package_controller.rb]: ok!

File: src/api/app/controllers/webui2/package_controller.rb (hunk 8 above)
Comment (danidoni) [reply src/api/app/controllers/webui2/package_controller.rb]: Yes, so true.

**Comment by dmarcoux** [comment]
Regarding the Rubocop offenses, `Style/StringLiterals` is dead simple. For `Lint/UselessAssignment`, I would go for this instead of using `||=`:

```
defined? target_project ? target_project : ''
```

Same thing for the package and description.

File: src/api/app/controllers/webui2/package_controller.rb [hunk 10]
```diff
@@ -27,18 +27,21 @@ def webui2_statistics
...
     end
-    cleanup_source = @project.branch? # We should remove the package if this request is a branch
 
     render json: {
-      'targetProject': target_project ||= "",
-      'targetPackage': target_package ||= "",
-      'description': description ||= "",
+      'targetProject': target_project,
+      'targetPackage': target_package,
+      'description': description,
```
Comment (vpereira) [inline src/api/app/controllers/webui2/package_controller.rb]: I just fail to see why these temporary variable is better than call ` linked_package.project.name`,  `linked_package.name` and `@package.commit_message(target_project, target_package)`  direct in the render?

Comment (danidoni) [reply src/api/app/controllers/webui2/package_controller.rb]: Because using `linked_package.project.name` and friends should only be done when there is actually a `linked_package`. I could move the render inside the if and provide an else branch with another render with blank values, but then I'll be repeating the render block. It's a matter of taste which version to use I guess as both versions have pros and cons.

**Comment by dmarcoux** [comment]
Regarding the `Style/UnneededCondition`, it's a false positive in this case. I will report it to upstream.

File: src/api/app/controllers/webui/package_controller.rb [hunk 11]
```diff
@@ -10,6 +10,7 @@ class Webui::PackageController < Webui::WebuiController
 
   before_action :set_project, only: [:show, :index, :users, :linking_packages, :dependency, :binary, :binaries,
                                      :requests, :statistics, :commit, :revisions, :submit_request_dialog,
+                                     :prefill,
```
Comment (hennevogel) [inline src/api/app/controllers/webui/package_controller.rb]: :thought_balloon: I really don't like this naming. Should include some reference to what is actually prefilled. It's not the package...

Comment (danidoni) [reply src/api/app/controllers/webui/package_controller.rb]: Hm, good point.

File: src/api/app/controllers/webui2/package_controller.rb (hunk 10 above)
Comment (vpereira) [reply src/api/app/controllers/webui2/package_controller.rb]: yes, sure. But I think there are better ways to achieve it, other than initialize an empty string. Either you encapsulate this logic in method or render what you have and make sure in the view you validate if the data exists before to try to render it.

i.e: Add keys to a hash and render the hash as it is, and in the view you do a `hash.fetch(:key, $DEFAULT_VALUE)`

File: src/api/app/controllers/webui/package_controller.rb (hunk 11 above)
Comment (danidoni) [reply src/api/app/controllers/webui/package_controller.rb]: How about `:prefill_submit_request_form`?

Comment (hennevogel) [reply src/api/app/controllers/webui/package_controller.rb]: Hm, maybe something more generic like `:branch_diff_info`?

File: src/api/app/controllers/webui2/package_controller.rb [hunk 12]
```diff
@@ -25,4 +25,24 @@ def webui2_statistics
...
+  def webui2_prefill
+    target_project = ''
+    target_package = ''
+    description = ''
+    cleanup_source = @project.branch? # We should remove the package if this request is a branch
+    linked_package = @package.backend_package.links_to
+    if linked_package
+      target_project = linked_package.project.name
+      target_package = linked_package.name
+      description = @package.commit_message(target_project, target_package)
```
Comment (dmarcoux) [inline src/api/app/controllers/webui2/package_controller.rb]: It looks like the description isn't filled. I just tried it again to be sure in the review app.

To reproduce this:
- Go to https://obs-reviewlab.opensuse.org/danidoni-submit-request-form-is-not-pre-filled-with-target-project/package/show/home:Admin:branches:home:Admin/ruby
- See the `I improved the text` in the `Latest Revision` box. (this should be the description)
- Click on `Submit package`
- The project and package fields are pre-filled. The description is not.

Comment (hennevogel) [reply src/api/app/controllers/webui2/package_controller.rb]: This is based on `.changes` files, no on commit messages.

Comment (dmarcoux) [reply src/api/app/controllers/webui2/package_controller.rb]: We should rename the method from the `Package` model then. It's literally called `commit_message`.

Comment (hennevogel) [reply src/api/app/controllers/webui2/package_controller.rb]: Feel free to refactor this, afterward :)

Comment (dmarcoux) [reply src/api/app/controllers/webui2/package_controller.rb]: https://github.com/openSUSE/open-build-service/issues/8306

Comment (danidoni) [reply src/api/app/controllers/webui2/package_controller.rb]: I'll check it out

File: src/api/app/controllers/webui/package_controller.rb (hunk 11 above)
Comment (danidoni) [reply src/api/app/controllers/webui/package_controller.rb]: I like it

File: src/api/app/controllers/webui2/package_controller.rb (hunk 12 above)
Comment (dmarcoux) [reply src/api/app/controllers/webui2/package_controller.rb]: Don't bother with this now, we can tackle the issue later and it doesn't have to be in this deliverable.

File: src/api/app/controllers/webui2/package_controller.rb (hunk 10 above)
Comment (danidoni) [reply src/api/app/controllers/webui2/package_controller.rb]: We've found some other way to refactor this without initializing the variables. Will this work for you @vpereira ?

File: src/api/app/controllers/webui2/package_controller.rb [hunk 13]
```diff
@@ -25,4 +25,21 @@ def webui2_statistics
...
+    end
+
+    render json: {
+      'targetProject': defined?(target_project) ? target_project : '',
```
Comment (vpereira) [inline src/api/app/controllers/webui2/package_controller.rb]: is that better than `linked_package ? linked_package.project.name : ' '` ?

**Comment by danidoni** [comment]
Squashed and rebased

File: src/api/app/controllers/webui2/package_controller.rb (hunk 13 above)
Comment (danidoni) [reply src/api/app/controllers/webui2/package_controller.rb]: Yes, I need the `target_project` and `target_package` for the `description`, so there is no reason to not use them there...
