### PR TITLE
Fix invalid byte sequence in UTF-8 in event mailer

### LINKED ISSUE #6872: Invalid byte sequence in UTF-8
threw this 11 times
<pre>
invalid byte sequence in UTF-8
</pre>

~[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5d3ef14282c14400087c7214)~

[See this exception on Errbit](https://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/5d3ef14282c14400087c7214)

### PR DESCRIPTION
**Pull request by danidoni**
Sometimes the build log contains invalid UTF-8 characters that raise an exception during email composing.

Fixes #6872

### CODE REVIEW

File: src/api/app/mailers/event_mailer.rb [hunk 1]
```diff
@@ -52,4 +52,20 @@ def event(subscribers, e)
...
+  private
+
+  # Reencode the fail log replacing invalid UTF-8 characters with the default unicode replacement character: '\ufffd'
+  # source: https://stackoverflow.com/a/24493972
+  def reencode_faillog(faillog)
+    faillog.encode!('UTF-8', 'UTF-8', invalid: :replace)
+  end
+
+  def sanitize_expanded_payload(payload)
+    if payload['faillog']
```
Comment (krauselukas) [inline src/api/app/mailers/event_mailer.rb:65]: @danidoni are the invalid characters only in the `faillog`? just by looking at the backtrace and issue it is not clear to me :)

Comment (danidoni) [reply src/api/app/mailers/event_mailer.rb:65]: The invalid characters are only rendered in the email notifying of the failures, which only uses the `faillog`. So yes, only in the `faillog`.

Comment (krauselukas) [reply src/api/app/mailers/event_mailer.rb:65]: alright :+1:

File: src/api/app/mailers/event_mailer.rb [hunk 2]
```diff
@@ -26,7 +26,7 @@ def event(subscribers, e)
 
     set_headers
     begin
-      locals = { event: e.expanded_payload }
+      locals = { event: sanitize_expanded_payload(e.expanded_payload) }
```
[the remark this answers is not in the document]
Comment (danidoni) [reply src/api/app/mailers/event_mailer.rb:29]: You have a point there, let me check

[the remark this answers is not in the document]
Comment (danidoni) [reply src/api/app/mailers/event_mailer.rb]: @krauselukas check it out now, please!

**Review by krauselukas — APPROVED** [review]
