### PR TITLE
[api] raise a proper error on missconfigured update project

### LINKED ISSUE #10116: [production][submissions#create] undefined method `packages' for nil:NilClass
submissions#create threw this 2 times
<pre>
undefined method `packages&#39; for nil:NilClass
</pre>
[https://build.opensuse.org/projects/Base:System/packages/coreutils/submissions](https://build.opensuse.org/projects/Base:System/packages/coreutils/submissions)"

[See this exception on Errbit](https://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/5f491bd05ad1a80008c1d0bf)

### PR DESCRIPTION
**Pull request by adrianschroeter**
raise a proper error (not just crash with 500) when an update project
got configured, but does not exist.

Fixes #10116.

### CODE REVIEW

File: src/api/app/models/project.rb [hunk 1]
```diff
@@ -608,7 +608,11 @@ def find_repos(sym)
   def update_instance(namespace = 'OBS', name = 'UpdateProject')
     # check if a newer instance exists in a defined update project
     a = find_attribute(namespace, name)
-    return Project.find_by_name(a.values[0].value) if a && a.values[0]
+    if a && a.values[0]
+      update_instance = Project.find_by_name(a.values[0].value)
+      return update_instance if update_instance
```
Comment (danidoni) [inline src/api/app/models/project.rb:613]: Just add an empty line and [rubocop](https://app.circleci.com/pipelines/github/openSUSE/open-build-service/2242/workflows/4a54f33d-b4b5-434b-a23e-509c8a95547a/jobs/54477) will be happy
```suggestion
      return update_instance if update_instance
      
```

**Comment by danidoni** [comment]
Rebased to pick up new dependencies in OBS
