### PR TITLE
Don't error when checking user roles on a project

### LINKED ISSUE #17176: [production][request#beta_show] undefined method `user_has_role?' for nil:NilClass

    projects.any? { |project| Project.find_by...
[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/6751d0ab84bf460c62ed8278)
# undefined method `user_has_role?&#39; for nil:NilClass

    projects.any? { |project| Project.find_by_name(project).user_has_role?(User.possibly_nobody, maintainer_role) }
                                                           ^^^^^^^^^^^^^^^ #
### URL ###
[https://build.opensuse.org/requests/1149944](https://build.opensuse.org/requests/1149944)"
### Where ###
request#beta_show

### Occured ###
Dec 05  4:11pm

### Similar ###
1

## Params ##
~~~
{
  &quot;action&quot; =&gt; &quot;beta_show&quot;,
  &quot;controller&quot; =&gt; &quot;webui/request&quot;,
  &quot;number&quot; =&gt; &quot;1149944&quot;
}
~~~

## Session ##
~~~
{
  &quot;_csrf_token&quot; =&gt; &quot;rcZ15hDP_SfkOGOKQMx1gSO1J-E-vlR6QuIKUcHupWI&quot;,
  &quot;csrf&quot; =&gt; &quot;c4Q_f6gNG8fgtWUwG-k1LF6fpYlpYzYailJIZHtaHmc=&quot;,
  &quot;session_id&quot; =&gt; &quot;4faa3b0a378c97f2d8c90ed9581765af&quot;,
  &quot;tracking&quot; =&gt; {
    &quot;HTTP_USER_AGENT&quot; =&gt; &quot;mozilla/5.0 (x11; linux x86_64; rv:121.0) gecko/20100101 firefox/121.0&quot;
  }
}
~~~

## Backtrace ##
~~~
357:  app/controllers/webui/request_controller.rb -> **block in any_project_maintained_by_current_user?**
357:  app/controllers/webui/request_controller.rb -> **any?**
357:  app/controllers/webui/request_controller.rb -> **any_project_maintained_by_current_user?**
548:  app/controllers/webui/request_controller.rb -> **prepare_request_data**
400:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb -> **block in make_lambda**
180:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb -> **block (2 levels) in halting_and_conditional**
34:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/abstract_controller/callbacks.rb -> **block (2 levels) in &lt;module:Callbacks&gt;**
181:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb -> **block in halting_and_conditional**
595:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb -> **block in invoke_before**
595:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb -> **each**
595:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb -> **invoke_before**
106:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb -> **run_callbacks**
233:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/abstract_controller/callbacks.rb -> **process_action**
23:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/rescue.rb -> **process_action**
67:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/instrumentation.rb -> **block in process_action**
206:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications/instrumenter.rb -> **instrument**
206:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **instrument**
66:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/instrumentation.rb -> **process_action**
259:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/params_wrapper.rb -> **process_action**
27:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/railties/controller_runtime.rb -> **process_action**
151:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/abstract_controller/base.rb -> **process**
39:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/rendering.rb -> **process**
188:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal.rb -> **dispatch**
251:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal.rb -> **dispatch**
49:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/route_set.rb -> **dispatch**
32:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/route_set.rb -> **serve**
18:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/mapper.rb -> **block in &lt;class:Constraints&gt;**
48:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/mapper.rb -> **serve**
50:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/journey/router.rb -> **block in serve**
32:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/journey/router.rb -> **each**
32:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/journey/router.rb -> **serve**
852:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/route_set.rb -> **call**
87:  /GEM_ROOT/gems/flipper-1.3.2/lib/flipper/middleware/memoizer.rb -> **memoized_call**
45:  /GEM_ROOT/gems/flipper-1.3.2/lib/flipper/middleware/memoizer.rb -> **call**
15:  config/initializers/prefer_xml_over_html.rb -> **call**
44:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/deflater.rb -> **call**
15:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/tempfile_reaper.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/etag.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/conditional_get.rb -> **call**
12:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/head.rb -> **call**
38:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/http/permissions_policy.rb -> **call**
36:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/http/content_security_policy.rb -> **call**
266:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/session/abstract/id.rb -> **context**
260:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/session/abstract/id.rb -> **call**
704:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/cookies.rb -> **call**
27:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/callbacks.rb -> **block in call**
99:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb -> **run_callbacks**
26:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/callbacks.rb -> **call**
32:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call!**
21:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call**
28:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/debug_exceptions.rb -> **call**
29:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/show_exceptions.rb -> **call**
18:  /GEM_ROOT/gems/lograge-0.14.0/lib/lograge/rails_ext/rack/logger.rb -> **call_app**
25:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/rack/logger.rb -> **block in call**
99:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/tagged_logging.rb -> **block in tagged**
37:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/tagged_logging.rb -> **tagged**
99:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/tagged_logging.rb -> **tagged**
25:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/rack/logger.rb -> **call**
93:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/remote_ip.rb -> **call**
93:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/remote_ip.rb -> **call**
19:  /GEM_ROOT/gems/request_store-1.7.0/lib/request_store/middleware.rb -> **call**
26:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/request_id.rb -> **call**
24:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/method_override.rb -> **call**
22:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/runtime.rb -> **call**
29:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/cache/strategy/local_cache_middleware.rb -> **call**
14:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/executor.rb -> **call**
18:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/lock.rb -> **call**
110:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/sendfile.rb -> **call**
131:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/host_authorization.rb -> **call**
530:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/engine.rb -> **call**
226:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/railtie.rb -> **public_send**
226:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/railtie.rb -> **method_missing**
74:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/urlmap.rb -> **block in call**
58:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/urlmap.rb -> **each**
58:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/urlmap.rb -> **call**
107:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb -> **process_request**
149:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **accept_and_process_next_request**
110:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **main_loop**
419:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/request_handler.rb -> **block (3 levels) in start_threads**
113:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/utils.rb -> **block in create_thread_and_abort_on_exception**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| program_name | Passenger RubyApp: /srv/www/obs/api (production) |
| HTTP_USER_AGENT | Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0 |

### PR DESCRIPTION
**Pull request by eduardoj**
Substitute the call to the overwritten `Project.find_by_name` finder method with plain ActiveRecord finder methods.

Fix #17176.

### CODE REVIEW

**Comment by hennevogel** [comment]
> The overwritten Project.find_by_name finder method could return nil in certain cases.

Then don't use it?

**Comment by eduardoj** [comment]
> > The overwritten Project.find_by_name finder method could return nil in certain cases.
> 
> Then don't use it?

I changed the approach. Please take a look again.

File: src/api/app/controllers/webui/request_controller.rb [hunk 1]
```diff
@@ -352,9 +352,11 @@ def addreview_opts
   end
 
   def any_project_maintained_by_current_user?
-    projects = @actions.select(:target_project).distinct.pluck(:target_project)
+    projects = Project.where(name: @actions.select(:target_project)).distinct
     maintainer_role = Role.find_by_title('maintainer')
-    projects.any? { |project| Project.find_by_name(project).user_has_role?(User.possibly_nobody, maintainer_role) }
+    user = User.possibly_nobody
+
+    projects.any? { |project| project.user_has_role?(user, maintainer_role) }
```
Comment (hennevogel) [inline src/api/app/controllers/webui/request_controller.rb:359]: Sounds to me like this could be a one liner:

`Project.for_user(User.possibly_nobody).where(name: @actions.select(:target_project)).any?`

**Review by hennevogel — DISMISSED** [review]

File: src/api/app/controllers/webui/request_controller.rb (hunk 1 above)
Comment (eduardoj) [reply src/api/app/controllers/webui/request_controller.rb:359]: Yeah... I thought about some one-liner refactoring using `Relationship` instead of `Project`... Then I realized `user_has_role?` also checks for permissions of the groups a user belongs to. See: https://github.com/openSUSE/open-build-service/blob/3c92fcda6b248dc8ad059476c81673fd76c60955/src/api/app/models/concerns/has_relationships.rb#L42-L46

That option could work if we stop taking in account maintainer roles given to groups...

Comment (hennevogel) [reply src/api/app/controllers/webui/request_controller.rb:359]: There is also `Project.for_groups`, you can combine those.

Comment (eduardoj) [reply src/api/app/controllers/webui/request_controller.rb:359]: Sure. But that is not the purpose of the pull request. This PR fixes the issue. We can leave the possible refactoring for later on.

Comment (hennevogel) [reply src/api/app/controllers/webui/request_controller.rb:359]: You are already significantly refactoring the code in this PR.

Comment (eduardoj) [reply src/api/app/controllers/webui/request_controller.rb]: What about this alternative?

```ruby
Relationship.maintainers.where(project: projects, user: user).or(Relationship.where(group: [user.groups.unscope(:order)])).any?
```

A trigger of this query in my development environment returned:
```
Relationship Exists? (0.6ms)  SELECT 1 AS one FROM `relationships` WHERE (
  `relationships`.`role_id` = 2 AND
  `relationships`.`project_id` IN (
    SELECT `projects`.`id` FROM `projects` WHERE `projects`.`id` != 0 AND `projects`.`id` = 7
  ) AND
  `relationships`.`user_id` = 4 OR
  `relationships`.`group_id` IN (
    SELECT DISTINCT `groups`.`id` FROM `groups` INNER JOIN `groups_users` ON `groups`.`id` = `groups_users`.`group_id` WHERE `groups_users`.`user_id` = 4
  )
) LIMIT 1
```
