### PR TITLE
[webui][api] Fix ChangeRepositoriesRemoteProjectNameToNotNull migration

### LINKED ISSUE #4761: Upgrading from OBS 2.8 to 2.9 causes lots of project meta references to change to 'deleted' and break ability to build
Issue description
====================
When upgrading from OBS 2.8 to OBS 2.9, projects wind up losing random parts of the meta configuration to getting marked as `deleted`.

### OBS 2.8 
screenshot_20180328_151511

### OBS 2.9: 
screenshot_20180328_151432

The entries that break are somewhat random, but it renders the build service instance completely broken.

Expected result
============
OBS upgrades don't lead to broken project meta

How to Reproduce
===============
1. Set up an OBS system on 2.8 interconnected with build.opensuse.org
2. Set up some projects with targets and repos interconnected used
3. Upgrade to OBS 2.9

Further information
===============
* Exact server version: 2.9.1-37.1

### PR DESCRIPTION
**Pull request by ChrisBr**
The migration `ChangeRepositoriesRemoteProjectNameToNotNull` changes the default
of `remote_project_name` to `''` (empty string) instead of NULL.

This was necessary in order to make the combination of `remote_project_name`,
`db_project_id` and `name` unique because MySQL does not consider rows with same column content
but one NULL value as equal. The migration back then was removing duplicates, however,
it also migrated repositories which are associated with remote projects. These
repositories do not need to get migrated as they're anyway unique
(there can not be a NULL value for these repositories).

This commit splits this migration in a schema and a data migration and introduces specs
for the data migration.

The data migration gets changed to NOT migrate repositories of a remote project.
If there is duplicate repository found, we simply destroy it as the data is already inconsistent
and it is not possible to do a full migration.

Fix #4761.

### CODE REVIEW

File: src/api/db/data/20170306084550_remove_duplicate_repositories.rb [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+        SQL
+        
+        duplicate_repos = Repository.find_by_sql(sql)
+        # We simply destroy the duplicate repository
+        # A full migration is not possible and does not make sense
+        # as it would probably corrupt even more data
+        # Because of that it must be a ruby loop for the path_elements and reference cleanup
+        duplicate_repos.each(&:destroy)
+      end
+      execute('UPDATE repositories SET remote_project_name = "" WHERE remote_project_name is null')
```
Comment (hennevogel) [inline src/api/db/data/20170306084550_remove_duplicate_repositories.rb]: This should be outside the `if`

File: src/api/db/migrate/20170306084558_change_repositories_remote_project_name_to_not_null.rb [hunk 2]
```diff
@@ -1,48 +1,14 @@
...
-      execute 'UPDATE repositories SET remote_project_name = "" WHERE remote_project_name is null'
-
-      change_column_null :repositories, :remote_project_name, false
-      change_column_default :repositories, :remote_project_name, ''
-    end
-
-    CONFIG['global_write_through'] = old
+    # We need to run src/api/db/data/20170306084550_remove_duplicate_repositories.rb first,
+    # otherwise we will get duplicate entry exception when we set remote_project_name to an empty string
+    raise ActiveRecord::ActiveRecordError.new('Pending data migration 20170306084550.') unless DataMigrate::DataMigrator.get_all_versions.include?(20170306084550)
```
Comment (hennevogel) [inline src/api/db/migrate/20170306084558_change_repositories_remote_project_name_to_not_null.rb]: Please tell people what to do in this case.

File: src/api/spec/db/data/remove_duplicate_repositories_spec.rb [hunk 3]
```diff
@@ -0,0 +1,77 @@
+require 'rails_helper'
+require Rails.root.join('db/data/20170306084550_remove_duplicate_repositories.rb')
+require Rails.root.join('db/migrate/20170306084558_change_repositories_remote_project_name_to_not_null.rb')
+
+RSpec.describe RemoveDuplicateRepositories, type: :migration do
+  # This migration does not allow NULL values for remote_project_name column
+  # We need this migration to not be run to create test data
+  # 20170306084558_change_repositories_remote_project_name_to_not_null.rb
+  let(:schema_migration_version) { 20_170_306_084_558 }
```
Comment (hennevogel) [inline src/api/spec/db/data/remove_duplicate_repositories_spec.rb]: This seem unused?

File: src/api/spec/db/data/remove_duplicate_repositories_spec.rb [hunk 4]
```diff
@@ -0,0 +1,77 @@
...
+  let(:data_migration_version) { 20_170_306_084_550 }
+  let(:data_migration) { RemoveDuplicateRepositories.new }
+
+  describe '.up' do
+    before do
+      schema_migration.down
+    end
+
+    after do
+      DataMigrate::DataSchemaMigration.find_or_create_by(version: data_migration_version.to_s)
```
Comment (hennevogel) [inline src/api/spec/db/data/remove_duplicate_repositories_spec.rb]: I would like `data_migration_version` not to be a variable. One less indirection to track.

File: src/api/db/data/20170306084550_remove_duplicate_repositories.rb [hunk 5]
```diff
@@ -0,0 +1,50 @@
+class RemoveDuplicateRepositories < ActiveRecord::Migration[5.1]
+  def up
+    old = CONFIG['global_write_through']
+    CONFIG['global_write_through'] = false
+
+    Repository.transaction do
+      sql = <<-SQL
+        SELECT a.*
```
Comment (bgeuken) [inline src/api/db/data/20170306084550_remove_duplicate_repositories.rb]: Not sure if that's relevant here (performancewise) but seems like a.id would be enough.

File: src/api/spec/db/data/remove_duplicate_repositories_spec.rb [hunk 6]
```diff
@@ -0,0 +1,77 @@
...
+      r
+    end
+    let!(:duplicate_repository) do
+      # we need to bypass the validation
+      r = build(:repository, project: project, name: 'standard', remote_project_name: nil, architectures: ['x86_64', 'i586'])
+      r.save(validate: false)
+      r
+    end
+    # We need to set remote_project_name = '', otherwise Repository.deleted_instance will fail because of not nil validation
+    let!(:deleted_repository) { create(:repository, name: 'deleted', remote_project_name: '', project: Project.deleted_instance) }
```
Comment (hennevogel) [inline src/api/spec/db/data/remove_duplicate_repositories_spec.rb]: Can you move this up a couple of lines? Before all the other data? I think the comment should also explain a bit more why this is needed. In 2 weeks you won't remember what `Repository.deleted_instance` does.

File: src/api/spec/db/data/remove_duplicate_repositories_spec.rb [hunk 7]
```diff
@@ -0,0 +1,77 @@
...
+    let!(:duplicate_path_element) { create(:path_element, link: duplicate_repository, repository: remote_repository) }
+
+    it 'removes the local and duplicate repository' do
+      expect do
+        data_migration.up
+      end.to change { Repository.count }.by(-1)
+
+      expect do
+        duplicate_repository.reload
+      end.to raise_error(ActiveRecord::RecordNotFound)
```
Comment (hennevogel) [inline src/api/spec/db/data/remove_duplicate_repositories_spec.rb]: I find this rather indirect. Can't you just test directly that the right one is there, the duplicated is gone? I know technically this is the same...

**Comment by adrianschroeter** [comment]
LGTM

File: src/api/spec/support/database_cleaner.rb [hunk 8]
```diff
@@ -24,7 +24,7 @@
   config.before(:each) do |example|
     # For feature test we use truncation instead of transactions because the
     # test suite and the capybara driver do not use the same server thread.
-    if example.metadata[:type] == :feature
+    if example.metadata[:type] == :feature || example.metadata[:type] == :migration
```
Comment (hennevogel) [inline src/api/spec/support/database_cleaner.rb]: Why is this needed?

Comment (ChrisBr) [reply src/api/spec/support/database_cleaner.rb]: Does not work with ``:transaction`` strategy. 

```
ActiveRecord::StatementInvalid: Mysql2::Error: SAVEPOINT active_record_1 does not exist: ROLLBACK TO SAVEPOINT active_record_1
```

File: src/api/db/migrate/20170306084558_change_repositories_remote_project_name_to_not_null.rb (hunk 2 above)
Comment (adrianschroeter) [reply src/api/db/migrate/20170306084558_change_repositories_remote_project_name_to_not_null.rb]: right ... IMHO it should be done here by default, since aborting db:migrate must not happen...

File: src/api/spec/support/database_cleaner.rb (hunk 8 above)
Comment (ChrisBr) [reply src/api/spec/support/database_cleaner.rb]: Created a dedicated commit for it to explain it!

File: src/api/db/migrate/20170306084558_change_repositories_remote_project_name_to_not_null.rb (hunk 2 above)
Comment (ChrisBr) [reply src/api/db/migrate/20170306084558_change_repositories_remote_project_name_to_not_null.rb]: We want to split data and schema migration to also write specs for it.

File: src/api/db/data/20170306084550_remove_duplicate_repositories.rb [hunk 9]
```diff
@@ -0,0 +1,50 @@
...
+          ON a.db_project_id = b.db_project_id
+          AND a.name = b.name
+          WHERE a.id != b.id
+          AND a.remote_project_name IS NULL
+          AND b.remote_project_name IS NULL
+          AND a.id IN (#{repos_with_duplicates.map(&:id).join(', ')})
+        SQL
+        
+        duplicate_repos = Repository.find_by_sql(sql)
+        # We simply destroy the duplicate repository
```
Comment (Ana06) [inline src/api/db/data/20170306084550_remove_duplicate_repositories.rb]: I think this 4 lines comment is not really clear to me. can you maybe rephrase it? And summarise it/short it would also be nice, I have the feeling that things like _simply_ and _does not make sense_ do not really add more information.

Comment (Ana06) [reply src/api/db/data/20170306084550_remove_duplicate_repositories.rb]: There are also some typos: We simply destroy the **duplicated** **repositories**

File: src/api/spec/db/data/remove_duplicate_repositories_spec.rb (hunk 3 above)
Comment (Ana06) [reply src/api/spec/db/data/remove_duplicate_repositories_spec.rb]: unused variable :wink:

File: src/api/spec/db/data/remove_duplicate_repositories_spec.rb [hunk 10]
```diff
@@ -0,0 +1,77 @@
...
+
+    let(:remote_project) { create(:remote_project) }
+    let!(:remote_repository) { create(:repository, project: remote_project, name: 'standard', remote_project_name: 'openSUSE.org:Foo') }
+    let!(:remote_repository_with_same_name) do
+      create(:repository, project: remote_project, name: 'standard', remote_project_name: 'openSUSE.org:Bar')
+    end
+
+    let(:project) { create(:project) }
+    let!(:repository) do
+      # we need to bypass the validation
```
Comment (Ana06) [inline src/api/spec/db/data/remove_duplicate_repositories_spec.rb]: why?

File: src/api/db/migrate/20170306084558_change_repositories_remote_project_name_to_not_null.rb (hunk 2 above)
Comment (adrianschroeter) [reply src/api/db/migrate/20170306084558_change_repositories_remote_project_name_to_not_null.rb]: I don't mind the split, but the exception, it must just not abort and confuse the user with rails internals ...

File: src/api/db/data/20170306084550_remove_duplicate_repositories.rb [hunk 11]
```diff
@@ -0,0 +1,50 @@
...
+        # A full migration is not possible and does not make sense
+        # as it would probably corrupt even more data
+        # Because of that it must be a ruby loop for the path_elements and reference cleanup
+        duplicate_repos.each(&:destroy)
+      end
+    end
+
+    execute('UPDATE repositories SET remote_project_name = "" WHERE remote_project_name is null')
```
[the remark this answers is not in the document]
Comment (ChrisBr) [reply src/api/db/data/20170306084550_remove_duplicate_repositories.rb]: This is just a c&p from the invalid migration, only changed the invalid stuff and left the other stuff untouched.
Usually we avoid to rely on models in the migration (in this migration in doesn't matter as we already use Repostory ...)

File: src/api/spec/db/data/remove_duplicate_repositories_spec.rb (hunk 10 above)
Comment (ChrisBr) [reply src/api/spec/db/data/remove_duplicate_repositories_spec.rb]: Because it is the main point of this migration and test: we want to generate invalid data which gets migrated in the data migration :smile: 
Should I add it to the comment?

File: src/api/db/data/20170306084550_remove_duplicate_repositories.rb [hunk 12]
```diff
@@ -0,0 +1,50 @@
...
+    CONFIG['global_write_through'] = old
+    nil # rails migrations return nil
```
[the remark this answers is not in the document]
Comment (ChrisBr) [reply src/api/db/data/20170306084550_remove_duplicate_repositories.rb]: At least ```ActiveRecord::ConnectionAdapters::SchemaStatements``` like ``change_column_default`` do it. Point was that this migration returned ``CONFIG['global_write_through'] = old`` which is ``false`` in most cases which looked strange and wrong.

**Comment by Conan-Kudo** [comment]
> The data migration gets changed to NOT migrate repositories of a remote project.
If there is duplicate repository found, we simply destroy it as the data is already inconsistent
and it is not possible to do a full migration.

Maybe I'm missing something here, but wouldn't this cause problems when multiple projects have the same "repository" name?

For example, from my OBS 2.8 DB:
```
MariaDB [api_production]> select * from repositories order by db_project_id;
+------+---------------+---------------------+------------------------+---------+-------+-------------+---------------+
| id   | db_project_id | name                | remote_project_name    | rebuild | block | linkedbuild | hostsystem_id |
+------+---------------+---------------------+------------------------+---------+-------+-------------+---------------+
| 1025 |             1 | standard            | openSUSE:Leap:42.2     | NULL    | NULL  | NULL        |          NULL |
| 1027 |             1 | openSUSE_Leap_42.3  | devel:languages:python | NULL    | NULL  | NULL        |          NULL |
| 1028 |             1 | openSUSE_Leap_42.2  | devel:languages:python | NULL    | NULL  | NULL        |          NULL |
| 1029 |             1 | update              | Fedora:26              | NULL    | NULL  | NULL        |          NULL |
| 1030 |             1 | standard            | Fedora:EPEL:6          | NULL    | NULL  | NULL        |          NULL |
|   10 |             1 | standard            | openSUSE:13.2          | NULL    | NULL  | NULL        |          NULL |
|   11 |             1 | standard            | openSUSE:13.1          | NULL    | NULL  | NULL        |          NULL |
|  523 |             1 | universe            | Ubuntu:16.10           | NULL    | NULL  | NULL        |          NULL |
|   12 |             1 | standard            | Debian:7.0             | NULL    | NULL  | NULL        |          NULL |
|   13 |             1 | standard            | Fedora:22              | NULL    | NULL  | NULL        |          NULL |                                                                                                                      
|   14 |             1 | standard            | Fedora:21              | NULL    | NULL  | NULL        |          NULL |                                                                                                                      
|   15 |             1 | standard            | CentOS:CentOS-7        | NULL    | NULL  | NULL        |          NULL |                                                                                                                      
|   16 |             1 | standard            | CentOS:CentOS-6        | NULL    | NULL  | NULL        |          NULL |                                                                                                                      
|   17 |             1 | standard            | Ubuntu:14.04           | NULL    | NULL  | NULL        |          NULL |                                                                                                                      
|   18 |             1 | standard            | Ubuntu:12.04           | NULL    | NULL  | NULL        |          NULL |                                                                                                                      
|   22 |             1 | standard            | CentOS:CentOS-5        | NULL    | NULL  | NULL        |          NULL |                                                                                                                      
|  793 |             1 | update              | Ubuntu:16.04           | NULL    | NULL  | NULL        |          NULL |                                                                                                                      
|  801 |             1 | updates             | Ubuntu:14.04           | NULL    | NULL  | NULL        |          NULL |                                                                                                                      
|   34 |             1 | standard            | Fedora:20              | NULL    | NULL  | NULL        |          NULL |                                                                                                                      
|   38 |             1 | standard            | openSUSE:Leap:42.1     | NULL    | NULL  | NULL        |          NULL |                                                                                                                      
|   39 |             1 | standard            | SUSE:SLE-12:GA         | NULL    | NULL  | NULL        |          NULL |                                                                                                                      
|   40 |             1 | standard            | SUSE:SLE-11:SP4        | NULL    | NULL  | NULL        |          NULL |                                                                                                                      
|   43 |             1 | Ubuntu_14.04        | Ubuntu:debbuild        | NULL    | NULL  | NULL        |          NULL |                                                                                                                      
|  815 |             1 | standard            | Mageia:6               | NULL    | NULL  | NULL        |          NULL |                                                                                                                      
|   57 |             1 | standard            | Debian:8.0             | NULL    | NULL  | NULL        |          NULL |                                                                                                                      
|   67 |             1 | standard            | SUSE:SLE-11:SP3        | NULL    | NULL  | NULL        |          NULL |
|   71 |             1 | standard            | Fedora:23              | NULL    | NULL  | NULL        |          NULL |
| 1097 |             1 | xUbuntu_16.04       | Ubuntu:debbuild        | NULL    | NULL  | NULL        |          NULL |
|  330 |             1 | standard            | Ubuntu:16.04           | NULL    | NULL  | NULL        |          NULL |
| 1099 |             1 | standard            | SUSE:SLE-12-SP2:GA     | NULL    | NULL  | NULL        |          NULL |
|  332 |             1 | Ubuntu_16.04        | Ubuntu:debbuild        | NULL    | NULL  | NULL        |          NULL |
|  845 |             1 | universe            | Ubuntu:17.04           | NULL    | NULL  | NULL        |          NULL |
| 1106 |             1 | standard            | SUSE:SLE-12-SP3:GA     | NULL    | NULL  | NULL        |          NULL |
|  339 |             1 | universe            | Ubuntu:16.04           | NULL    | NULL  | NULL        |          NULL |
|  859 |             1 | Ubuntu_17.04        | Ubuntu:debbuild        | NULL    | NULL  | NULL        |          NULL |
|   96 |             1 | standard            | Ubuntu:15.10           | NULL    | NULL  | NULL        |          NULL |
|  869 |             1 | CentOS              | Fedora:EPEL:7          | NULL    | NULL  | NULL        |          NULL |
|  870 |             1 | standard            | Fedora:EPEL:7          | NULL    | NULL  | NULL        |          NULL |
|  108 |             1 | Ubuntu_12.04        | Ubuntu:debbuild        | NULL    | NULL  | NULL        |          NULL |
|  109 |             1 | Debian_8.0          | Debian:debbuild        | NULL    | NULL  | NULL        |          NULL |
|  365 |             1 | standard            | Fedora:24              | NULL    | NULL  | NULL        |          NULL |
|  110 |             1 | update              | Debian:8               | NULL    | NULL  | NULL        |          NULL |
|  111 |             1 | ga                  | Debian:8               | NULL    | NULL  | NULL        |          NULL |
|  112 |             1 | Debian_7.0          | Debian:debbuild        | NULL    | NULL  | NULL        |          NULL |
|  113 |             1 | update              | Debian:7               | NULL    | NULL  | NULL        |          NULL |
|  114 |             1 | ga                  | Debian:7               | NULL    | NULL  | NULL        |          NULL |
|  632 |             1 | Fedora_25           | Ubuntu:debbuild        | NULL    | NULL  | NULL        |          NULL |
|  633 |             1 | CentOS_7            | Ubuntu:debbuild        | NULL    | NULL  | NULL        |          NULL |
|  647 |             1 | update              | Ubuntu:14.04           | NULL    | NULL  | NULL        |          NULL |
|  648 |             1 | ga                  | Ubuntu:14.04           | NULL    | NULL  | NULL        |          NULL |
|  655 |             1 | trusty-updates      | Ubuntu:14.04           | NULL    | NULL  | NULL        |          NULL |
|  426 |             1 | standard            | Fedora:Rawhide         | NULL    | NULL  | NULL        |          NULL |
|  427 |             1 | update              | Fedora:24              | NULL    | NULL  | NULL        |          NULL |
| 1199 |             1 | update              | Fedora:27              | NULL    | NULL  | NULL        |          NULL |
|  693 |             1 | standard            | RedHat:RHEL-7          | NULL    | NULL  | NULL        |          NULL |
|  438 |             1 | universe            | Ubuntu:14.04           | NULL    | NULL  | NULL        |          NULL |
|  710 |             1 | Ubuntu_16.04        | Debian:debbuild        | NULL    | NULL  | NULL        |          NULL |
| 1222 |             1 | standard            | RedHat:RHEL-6          | NULL    | NULL  | NULL        |          NULL |
|  969 |             1 | universe            | Ubuntu:17.10           | NULL    | NULL  | NULL        |          NULL |
|  971 |             1 | Ubuntu_17.10        | Ubuntu:debbuild        | NULL    | NULL  | NULL        |          NULL |
| 1237 |             1 | Ubuntu_18.04        | Ubuntu:debbuild        | NULL    | NULL  | NULL        |          NULL |
| 1238 |             1 | universe            | Ubuntu:18.04           | NULL    | NULL  | NULL        |          NULL |
|  476 |             1 | standard            | Fedora:25              | NULL    | NULL  | NULL        |          NULL |
|  484 |             1 | universe            | Ubuntu:12.04           | NULL    | NULL  | NULL        |          NULL |
|  491 |             1 | update              | Fedora:25              | NULL    | NULL  | NULL        |          NULL |
|  752 |             1 | standard            | Fedora:26              | NULL    | NULL  | NULL        |          NULL |
|  754 |             1 | standard            | Debian:9.0             | NULL    | NULL  | NULL        |          NULL |
|  757 |             1 | Debian_9.0          | Debian:debbuild        | NULL    | NULL  | NULL        |          NULL |
|  759 |             1 | standard            | Debian:9               | NULL    | NULL  | NULL        |          NULL |
|  760 |             1 | ga                  | Debian:9               | NULL    | NULL  | NULL        |          NULL |
| 1016 |             1 | snapshot            | openSUSE:Factory       | NULL    | NULL  | NULL        |          NULL |
| 1019 |             1 | CentOS_7            | openSUSE:Tools         | NULL    | NULL  | NULL        |          NULL |
| 1022 |             1 | standard            | Fedora:27              | NULL    | NULL  | NULL        |          NULL |
| 1023 |             1 | standard            | openSUSE:Leap:42.3     | NULL    | NULL  | NULL        |          NULL |
+------+---------------+---------------------+------------------------+---------+-------+-------------+---------------+
```
And from my OBS 2.9 test upgrade:
```
MariaDB [api_production]> select * from repositories order by db_project_id;
+------+---------------+---------------------+------------------------+---------+-------+-------------+---------------+
| id   | db_project_id | name                | remote_project_name    | rebuild | block | linkedbuild | hostsystem_id |
+------+---------------+---------------------+------------------------+---------+-------+-------------+---------------+
| 1027 |             1 | openSUSE_Leap_42.3  | devel:languages:python | NULL    | NULL  | NULL        |          NULL |
| 1028 |             1 | openSUSE_Leap_42.2  | devel:languages:python | NULL    | NULL  | NULL        |          NULL |
|   10 |             1 | standard            | openSUSE:13.2          | NULL    | NULL  | NULL        |          NULL |
|  801 |             1 | updates             | Ubuntu:14.04           | NULL    | NULL  | NULL        |          NULL |
|   43 |             1 | Ubuntu_14.04        | Ubuntu:debbuild        | NULL    | NULL  | NULL        |          NULL |
| 1097 |             1 | xUbuntu_16.04       | Ubuntu:debbuild        | NULL    | NULL  | NULL        |          NULL |
|  332 |             1 | Ubuntu_16.04        | Ubuntu:debbuild        | NULL    | NULL  | NULL        |          NULL |
|  339 |             1 | universe            | Ubuntu:16.04           | NULL    | NULL  | NULL        |          NULL |
|  859 |             1 | Ubuntu_17.04        | Ubuntu:debbuild        | NULL    | NULL  | NULL        |          NULL |
|  869 |             1 | CentOS              | Fedora:EPEL:7          | NULL    | NULL  | NULL        |          NULL |
|  108 |             1 | Ubuntu_12.04        | Ubuntu:debbuild        | NULL    | NULL  | NULL        |          NULL |
|  109 |             1 | Debian_8.0          | Debian:debbuild        | NULL    | NULL  | NULL        |          NULL |
|  110 |             1 | update              | Debian:8               | NULL    | NULL  | NULL        |          NULL |
|  111 |             1 | ga                  | Debian:8               | NULL    | NULL  | NULL        |          NULL |
|  112 |             1 | Debian_7.0          | Debian:debbuild        | NULL    | NULL  | NULL        |          NULL |
|  632 |             1 | Fedora_25           | Ubuntu:debbuild        | NULL    | NULL  | NULL        |          NULL |
|  633 |             1 | CentOS_7            | Ubuntu:debbuild        | NULL    | NULL  | NULL        |          NULL |
|  655 |             1 | trusty-updates      | Ubuntu:14.04           | NULL    | NULL  | NULL        |          NULL |
|  971 |             1 | Ubuntu_17.10        | Ubuntu:debbuild        | NULL    | NULL  | NULL        |          NULL |
| 1237 |             1 | Ubuntu_18.04        | Ubuntu:debbuild        | NULL    | NULL  | NULL        |          NULL |
|  757 |             1 | Debian_9.0          | Debian:debbuild        | NULL    | NULL  | NULL        |          NULL |
| 1016 |             1 | snapshot            | openSUSE:Factory       | NULL    | NULL  | NULL        |          NULL |
+------+---------------+---------------------+------------------------+---------+-------+-------------+---------------+
```

And here's the actual diff:
```diff
--- obs28-remoteprj-repos.txt   2018-04-04 11:53:13.200760864 -0400
+++ obs29-remoteprj-repos.txt   2018-04-04 11:54:39.703865479 -0400
@@ -2,78 +2,26 @@ MariaDB [api_production]> select * from
 +------+---------------+---------------------+------------------------+---------+-------+-------------+---------------+
 | id   | db_project_id | name                | remote_project_name    | rebuild | block | linkedbuild | hostsystem_id |
 +------+---------------+---------------------+------------------------+---------+-------+-------------+---------------+
-| 1025 |             1 | standard            | openSUSE:Leap:42.2     | NULL    | NULL  | NULL        |          NULL |
 | 1027 |             1 | openSUSE_Leap_42.3  | devel:languages:python | NULL    | NULL  | NULL        |          NULL |
 | 1028 |             1 | openSUSE_Leap_42.2  | devel:languages:python | NULL    | NULL  | NULL        |          NULL |
-| 1029 |             1 | update              | Fedora:26              | NULL    | NULL  | NULL        |          NULL |
-| 1030 |             1 | standard            | Fedora:EPEL:6          | NULL    | NULL  | NULL        |          NULL |
 |   10 |             1 | standard            | openSUSE:13.2          | NULL    | NULL  | NULL        |          NULL |
-|   11 |             1 | standard            | openSUSE:13.1          | NULL    | NULL  | NULL        |          NULL |
-|  523 |             1 | universe            | Ubuntu:16.10           | NULL    | NULL  | NULL        |          NULL |
-|   12 |             1 | standard            | Debian:7.0             | NULL    | NULL  | NULL        |          NULL |
-|   13 |             1 | standard            | Fedora:22              | NULL    | NULL  | NULL        |          NULL |                                                                                                                      
-|   14 |             1 | standard            | Fedora:21              | NULL    | NULL  | NULL        |          NULL |                                                                                                                      
-|   15 |             1 | standard            | CentOS:CentOS-7        | NULL    | NULL  | NULL        |          NULL |                                                                                                                      
-|   16 |             1 | standard            | CentOS:CentOS-6        | NULL    | NULL  | NULL        |          NULL |                                                                                                                      
-|   17 |             1 | standard            | Ubuntu:14.04           | NULL    | NULL  | NULL        |          NULL |                                                                                                                      
-|   18 |             1 | standard            | Ubuntu:12.04           | NULL    | NULL  | NULL        |          NULL |                                                                                                                      
-|   22 |             1 | standard            | CentOS:CentOS-5        | NULL    | NULL  | NULL        |          NULL |                                                                                                                      
-|  793 |             1 | update              | Ubuntu:16.04           | NULL    | NULL  | NULL        |          NULL |                                                                                                                      
-|  801 |             1 | updates             | Ubuntu:14.04           | NULL    | NULL  | NULL        |          NULL |                                                                                                                      
-|   34 |             1 | standard            | Fedora:20              | NULL    | NULL  | NULL        |          NULL |                                                                                                                      
-|   38 |             1 | standard            | openSUSE:Leap:42.1     | NULL    | NULL  | NULL        |          NULL |                                                                                                                      
-|   39 |             1 | standard            | SUSE:SLE-12:GA         | NULL    | NULL  | NULL        |          NULL |                                                                                                                      
-|   40 |             1 | standard            | SUSE:SLE-11:SP4        | NULL    | NULL  | NULL        |          NULL |                                                                                                                      
-|   43 |             1 | Ubuntu_14.04        | Ubuntu:debbuild        | NULL    | NULL  | NULL        |          NULL |                                                                                                                      
-|  815 |             1 | standard            | Mageia:6               | NULL    | NULL  | NULL        |          NULL |                                                                                                                      
-|   57 |             1 | standard            | Debian:8.0             | NULL    | NULL  | NULL        |          NULL |                                                                                                                      
-|   67 |             1 | standard            | SUSE:SLE-11:SP3        | NULL    | NULL  | NULL        |          NULL |
-|   71 |             1 | standard            | Fedora:23              | NULL    | NULL  | NULL        |          NULL |
+|  801 |             1 | updates             | Ubuntu:14.04           | NULL    | NULL  | NULL        |          NULL |
+|   43 |             1 | Ubuntu_14.04        | Ubuntu:debbuild        | NULL    | NULL  | NULL        |          NULL |
 | 1097 |             1 | xUbuntu_16.04       | Ubuntu:debbuild        | NULL    | NULL  | NULL        |          NULL |
-|  330 |             1 | standard            | Ubuntu:16.04           | NULL    | NULL  | NULL        |          NULL |
-| 1099 |             1 | standard            | SUSE:SLE-12-SP2:GA     | NULL    | NULL  | NULL        |          NULL |
 |  332 |             1 | Ubuntu_16.04        | Ubuntu:debbuild        | NULL    | NULL  | NULL        |          NULL |
-|  845 |             1 | universe            | Ubuntu:17.04           | NULL    | NULL  | NULL        |          NULL |
-| 1106 |             1 | standard            | SUSE:SLE-12-SP3:GA     | NULL    | NULL  | NULL        |          NULL |
 |  339 |             1 | universe            | Ubuntu:16.04           | NULL    | NULL  | NULL        |          NULL |
 |  859 |             1 | Ubuntu_17.04        | Ubuntu:debbuild        | NULL    | NULL  | NULL        |          NULL |
-|   96 |             1 | standard            | Ubuntu:15.10           | NULL    | NULL  | NULL        |          NULL |
 |  869 |             1 | CentOS              | Fedora:EPEL:7          | NULL    | NULL  | NULL        |          NULL |
-|  870 |             1 | standard            | Fedora:EPEL:7          | NULL    | NULL  | NULL        |          NULL |
 |  108 |             1 | Ubuntu_12.04        | Ubuntu:debbuild        | NULL    | NULL  | NULL        |          NULL |
 |  109 |             1 | Debian_8.0          | Debian:debbuild        | NULL    | NULL  | NULL        |          NULL |
-|  365 |             1 | standard            | Fedora:24              | NULL    | NULL  | NULL        |          NULL |
 |  110 |             1 | update              | Debian:8               | NULL    | NULL  | NULL        |          NULL |
 |  111 |             1 | ga                  | Debian:8               | NULL    | NULL  | NULL        |          NULL |
 |  112 |             1 | Debian_7.0          | Debian:debbuild        | NULL    | NULL  | NULL        |          NULL |
-|  113 |             1 | update              | Debian:7               | NULL    | NULL  | NULL        |          NULL |
-|  114 |             1 | ga                  | Debian:7               | NULL    | NULL  | NULL        |          NULL |
 |  632 |             1 | Fedora_25           | Ubuntu:debbuild        | NULL    | NULL  | NULL        |          NULL |
 |  633 |             1 | CentOS_7            | Ubuntu:debbuild        | NULL    | NULL  | NULL        |          NULL |
-|  647 |             1 | update              | Ubuntu:14.04           | NULL    | NULL  | NULL        |          NULL |
-|  648 |             1 | ga                  | Ubuntu:14.04           | NULL    | NULL  | NULL        |          NULL |
 |  655 |             1 | trusty-updates      | Ubuntu:14.04           | NULL    | NULL  | NULL        |          NULL |
-|  426 |             1 | standard            | Fedora:Rawhide         | NULL    | NULL  | NULL        |          NULL |
-|  427 |             1 | update              | Fedora:24              | NULL    | NULL  | NULL        |          NULL |
-| 1199 |             1 | update              | Fedora:27              | NULL    | NULL  | NULL        |          NULL |
-|  693 |             1 | standard            | RedHat:RHEL-7          | NULL    | NULL  | NULL        |          NULL |
-|  438 |             1 | universe            | Ubuntu:14.04           | NULL    | NULL  | NULL        |          NULL |
-|  710 |             1 | Ubuntu_16.04        | Debian:debbuild        | NULL    | NULL  | NULL        |          NULL |
-| 1222 |             1 | standard            | RedHat:RHEL-6          | NULL    | NULL  | NULL        |          NULL |
-|  969 |             1 | universe            | Ubuntu:17.10           | NULL    | NULL  | NULL        |          NULL |
 |  971 |             1 | Ubuntu_17.10        | Ubuntu:debbuild        | NULL    | NULL  | NULL        |          NULL |
 | 1237 |             1 | Ubuntu_18.04        | Ubuntu:debbuild        | NULL    | NULL  | NULL        |          NULL |
-| 1238 |             1 | universe            | Ubuntu:18.04           | NULL    | NULL  | NULL        |          NULL |
-|  476 |             1 | standard            | Fedora:25              | NULL    | NULL  | NULL        |          NULL |
-|  484 |             1 | universe            | Ubuntu:12.04           | NULL    | NULL  | NULL        |          NULL |
-|  491 |             1 | update              | Fedora:25              | NULL    | NULL  | NULL        |          NULL |
-|  752 |             1 | standard            | Fedora:26              | NULL    | NULL  | NULL        |          NULL |
-|  754 |             1 | standard            | Debian:9.0             | NULL    | NULL  | NULL        |          NULL |
 |  757 |             1 | Debian_9.0          | Debian:debbuild        | NULL    | NULL  | NULL        |          NULL |
-|  759 |             1 | standard            | Debian:9               | NULL    | NULL  | NULL        |          NULL |
-|  760 |             1 | ga                  | Debian:9               | NULL    | NULL  | NULL        |          NULL |
 | 1016 |             1 | snapshot            | openSUSE:Factory       | NULL    | NULL  | NULL        |          NULL |
-| 1019 |             1 | CentOS_7            | openSUSE:Tools         | NULL    | NULL  | NULL        |          NULL |
-| 1022 |             1 | standard            | Fedora:27              | NULL    | NULL  | NULL        |          NULL |
-| 1023 |             1 | standard            | openSUSE:Leap:42.3     | NULL    | NULL  | NULL        |          NULL |
 +------+---------------+---------------------+------------------------+---------+-------+-------------+---------------+
```

**Comment by ChrisBr** [comment]
@Conan-Kudo is this result with this migration?

So the intention of this migration was to drop duplicate LOCAL repositories (with the same name but different ID), this is not allowed. This migration did not cover the column ``remote_project_name`` (this column is only set for repositories associated with a remote project -> in your case ``openSUSE.org``) and migrated them as well. We altered the migration to only migrate repositories where ``remote_project_name``  IS NOT NULL, see line:
https://github.com/openSUSE/open-build-service/pull/4800/files#diff-048bdc3412b960afbb875a1fb7680774R14

We also added tests for this case:
https://github.com/openSUSE/open-build-service/pull/4800/files#diff-bc5b3f004b3fcb30bc237ce92f8acbefR59

**Comment by Conan-Kudo** [comment]
@ChrisBr This is not with this currently proposed migration. I have not tested with this migration.

File: src/api/db/data/20170306084550_remove_duplicate_repositories.rb (hunk 12 above)
[the remark this answers is not in the document]
Comment (Ana06) [reply src/api/db/data/20170306084550_remove_duplicate_repositories.rb]: `change_column_default` raises a `NotImplementedError` :confused: Most of the migrations implementing in Rails (includeding the ones in the class you point) has at last statement an `execute` which in most cases return an object of the class `Mysql2::Result`, which is not `nil`. Or do I miss something? :thinking: 

I think that the returned value of migrations is not used at all. I do not find in the Rails documentation anything about it and we have already migrations that return something different (and the defaults from Rails too). Being that the case, there is no point on having this line.

File: src/api/spec/db/data/remove_duplicate_repositories_spec.rb (hunk 10 above)
Comment (Ana06) [reply src/api/spec/db/data/remove_duplicate_repositories_spec.rb]: Yes, I think it would be useful :wink:
