### PR TITLE
Fix form path when dealing with service tokens

### LINKED ISSUE #13853: [production][tokens#create] undefined method `token_services_path' for #<ActionView::Base:0x00000000031b78>

              re...
[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/63ee43b484bf460526845d7d)
# undefined method `token_services_path&#39; for #&lt;ActionView::Base:0x00000000031b78&gt;

              recipient.public_send(method, *args, options)
                       ^^^^^^^^^^^^
Did you mean?  token_users_path #
### URL ###
[https://build.opensuse.org/my/tokens](https://build.opensuse.org/my/tokens)"
### Where ###
tokens#create

### Occured ###
Feb 16  2:54pm

### Similar ###
0

## Params ##
~~~
{
  &quot;action&quot; =&gt; &quot;create&quot;,
  &quot;authenticity_token&quot; =&gt; &quot;nvWdpfuNheIly6IBvPTSfmSRmflY6tJovfuf3_bsC9riqWZ0j5ucRKqpW12ZL4NSF7hXrQ36Rvsjy9MFBv4jCg&quot;,
  &quot;commit&quot; =&gt; &quot;Create&quot;,
  &quot;controller&quot; =&gt; &quot;webui/users/tokens&quot;,
  &quot;project_name&quot; =&gt; &quot;&quot;,
  &quot;token&quot; =&gt; {
    &quot;description&quot; =&gt; &quot;Rebuild Hello World Github projectRebuild Hello World Github projectRebuild Hello World Github projectRebuild Hello World Github project&quot;,
    &quot;scm_token&quot; =&gt; &quot;[Filtered]&quot;,
    &quot;type&quot; =&gt; &quot;service&quot;,
    &quot;workflow_configuration_path&quot; =&gt; &quot;.obs/workflows.yml&quot;,
    &quot;workflow_configuration_url&quot; =&gt; &quot;&quot;
  }
}
~~~

## Session ##
~~~
{
  &quot;_csrf_token&quot; =&gt; &quot;VqAPda03ABFrlOQH06evFtj1ozG8x4I4ixj1ObIkC1o&quot;,
  &quot;session_id&quot; =&gt; &quot;8b3c04dc8b65898f9b3528808d0b23f9&quot;
}
~~~

## Backtrace ##
~~~
233:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/routing/polymorphic_routes.rb -> **public_send**
233:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/routing/polymorphic_routes.rb -> **polymorphic_method**
139:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/routing/polymorphic_routes.rb -> **polymorphic_path**
759:  /GEM_ROOT/gems/actionview-7.0.4/lib/action_view/helpers/form_helper.rb -> **form_with**
10:  app/views/webui/users/tokens/new.html.haml -> **_app_views_webui_users_tokens_new_html_haml___566941599653300317_101800**
244:  /GEM_ROOT/gems/actionview-7.0.4/lib/action_view/base.rb -> **public_send**
244:  /GEM_ROOT/gems/actionview-7.0.4/lib/action_view/base.rb -> **_run**
157:  /GEM_ROOT/gems/actionview-7.0.4/lib/action_view/template.rb -> **block in render**
208:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/notifications.rb -> **instrument**
361:  /GEM_ROOT/gems/actionview-7.0.4/lib/action_view/template.rb -> **instrument_render_template**
155:  /GEM_ROOT/gems/actionview-7.0.4/lib/action_view/template.rb -> **render**
65:  /GEM_ROOT/gems/actionview-7.0.4/lib/action_view/renderer/template_renderer.rb -> **block (2 levels) in render_template**
206:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/notifications/instrumenter.rb -> **instrument**
206:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/notifications.rb -> **instrument**
60:  /GEM_ROOT/gems/actionview-7.0.4/lib/action_view/renderer/template_renderer.rb -> **block in render_template**
75:  /GEM_ROOT/gems/actionview-7.0.4/lib/action_view/renderer/template_renderer.rb -> **block in render_with_layout**
208:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/notifications.rb -> **instrument**
74:  /GEM_ROOT/gems/actionview-7.0.4/lib/action_view/renderer/template_renderer.rb -> **render_with_layout**
59:  /GEM_ROOT/gems/actionview-7.0.4/lib/action_view/renderer/template_renderer.rb -> **render_template**
11:  /GEM_ROOT/gems/actionview-7.0.4/lib/action_view/renderer/template_renderer.rb -> **render**
61:  /GEM_ROOT/gems/actionview-7.0.4/lib/action_view/renderer/renderer.rb -> **render_template_to_object**
29:  /GEM_ROOT/gems/actionview-7.0.4/lib/action_view/renderer/renderer.rb -> **render_to_object**
117:  /GEM_ROOT/gems/actionview-7.0.4/lib/action_view/rendering.rb -> **block in _render_template**
270:  /GEM_ROOT/gems/actionview-7.0.4/lib/action_view/base.rb -> **in_rendering_context**
116:  /GEM_ROOT/gems/actionview-7.0.4/lib/action_view/rendering.rb -> **_render_template**
216:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_controller/metal/streaming.rb -> **_render_template**
103:  /GEM_ROOT/gems/actionview-7.0.4/lib/action_view/rendering.rb -> **render_to_body**
46:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_controller/metal/rendering.rb -> **render_to_body**
141:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_controller/metal/renderers.rb -> **render_to_body**
25:  /GEM_ROOT/gems/actionpack-7.0.4/lib/abstract_controller/rendering.rb -> **render**
30:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_controller/metal/rendering.rb -> **render**
22:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_controller/metal/instrumentation.rb -> **block (2 levels) in render**
311:  /usr/lib64/ruby/3.1.0/benchmark.rb -> **realtime**
14:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/core_ext/benchmark.rb -> **ms**
22:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_controller/metal/instrumentation.rb -> **block in render**
91:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_controller/metal/instrumentation.rb -> **cleanup_view_runtime**
34:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/railties/controller_runtime.rb -> **cleanup_view_runtime**
21:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_controller/metal/instrumentation.rb -> **render**
38:  app/controllers/webui/users/tokens_controller.rb -> **block (2 levels) in create**
214:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_controller/metal/mime_responds.rb -> **respond_to**
30:  app/controllers/webui/users/tokens_controller.rb -> **create**
6:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_controller/metal/basic_implicit_render.rb -> **send_action**
215:  /GEM_ROOT/gems/actionpack-7.0.4/lib/abstract_controller/base.rb -> **process_action**
53:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_controller/metal/rendering.rb -> **process_action**
234:  /GEM_ROOT/gems/actionpack-7.0.4/lib/abstract_controller/callbacks.rb -> **block in process_action**
107:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/callbacks.rb -> **run_callbacks**
233:  /GEM_ROOT/gems/actionpack-7.0.4/lib/abstract_controller/callbacks.rb -> **process_action**
22:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_controller/metal/rescue.rb -> **process_action**
67:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_controller/metal/instrumentation.rb -> **block in process_action**
206:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/notifications/instrumenter.rb -> **instrument**
206:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/notifications.rb -> **instrument**
66:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_controller/metal/instrumentation.rb -> **process_action**
259:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_controller/metal/params_wrapper.rb -> **process_action**
27:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/railties/controller_runtime.rb -> **process_action**
151:  /GEM_ROOT/gems/actionpack-7.0.4/lib/abstract_controller/base.rb -> **process**
39:  /GEM_ROOT/gems/actionview-7.0.4/lib/action_view/rendering.rb -> **process**
188:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_controller/metal.rb -> **dispatch**
251:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_controller/metal.rb -> **dispatch**
49:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/routing/route_set.rb -> **dispatch**
32:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/routing/route_set.rb -> **serve**
18:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/routing/mapper.rb -> **block in &lt;class:Constraints&gt;**
48:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/routing/mapper.rb -> **serve**
50:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/journey/router.rb -> **block in serve**
32:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/journey/router.rb -> **each**
32:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/journey/router.rb -> **serve**
852:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/routing/route_set.rb -> **call**
72:  /GEM_ROOT/gems/flipper-0.26.0/lib/flipper/middleware/memoizer.rb -> **memoized_call**
37:  /GEM_ROOT/gems/flipper-0.26.0/lib/flipper/middleware/memoizer.rb -> **call**
15:  config/initializers/prefer_xml_over_html.rb -> **call**
44:  /GEM_ROOT/gems/rack-2.2.6.2/lib/rack/deflater.rb -> **call**
15:  /GEM_ROOT/gems/rack-2.2.6.2/lib/rack/tempfile_reaper.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.6.2/lib/rack/etag.rb -> **call**
40:  /GEM_ROOT/gems/rack-2.2.6.2/lib/rack/conditional_get.rb -> **call**
12:  /GEM_ROOT/gems/rack-2.2.6.2/lib/rack/head.rb -> **call**
38:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/http/permissions_policy.rb -> **call**
36:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/http/content_security_policy.rb -> **call**
266:  /GEM_ROOT/gems/rack-2.2.6.2/lib/rack/session/abstract/id.rb -> **context**
260:  /GEM_ROOT/gems/rack-2.2.6.2/lib/rack/session/abstract/id.rb -> **call**
696:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/middleware/cookies.rb -> **call**
27:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/middleware/callbacks.rb -> **block in call**
99:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/callbacks.rb -> **run_callbacks**
26:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/middleware/callbacks.rb -> **call**
32:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call!**
21:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call**
28:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/middleware/debug_exceptions.rb -> **call**
26:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/middleware/show_exceptions.rb -> **call**
18:  /GEM_ROOT/gems/lograge-0.12.0/lib/lograge/rails_ext/rack/logger.rb -> **call_app**
25:  /GEM_ROOT/gems/railties-7.0.4/lib/rails/rack/logger.rb -> **block in call**
99:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/tagged_logging.rb -> **block in tagged**
37:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/tagged_logging.rb -> **tagged**
99:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/tagged_logging.rb -> **tagged**
25:  /GEM_ROOT/gems/railties-7.0.4/lib/rails/rack/logger.rb -> **call**
93:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/middleware/remote_ip.rb -> **call**
93:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/middleware/remote_ip.rb -> **call**
19:  /GEM_ROOT/gems/request_store-1.5.1/lib/request_store/middleware.rb -> **call**
26:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/middleware/request_id.rb -> **call**
24:  /GEM_ROOT/gems/rack-2.2.6.2/lib/rack/method_override.rb -> **call**
22:  /GEM_ROOT/gems/rack-2.2.6.2/lib/rack/runtime.rb -> **call**
29:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/cache/strategy/local_cache_middleware.rb -> **call**
14:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/middleware/executor.rb -> **call**
18:  /GEM_ROOT/gems/rack-2.2.6.2/lib/rack/lock.rb -> **call**
110:  /GEM_ROOT/gems/rack-2.2.6.2/lib/rack/sendfile.rb -> **call**
131:  /GEM_ROOT/gems/actionpack-7.0.4/lib/action_dispatch/middleware/host_authorization.rb -> **call**
530:  /GEM_ROOT/gems/railties-7.0.4/lib/rails/engine.rb -> **call**
226:  /GEM_ROOT/gems/railties-7.0.4/lib/rails/railtie.rb -> **public_send**
226:  /GEM_ROOT/gems/railties-7.0.4/lib/rails/railtie.rb -> **method_missing**
74:  /GEM_ROOT/gems/rack-2.2.6.2/lib/rack/urlmap.rb -> **block in call**
58:  /GEM_ROOT/gems/rack-2.2.6.2/lib/rack/urlmap.rb -> **each**
58:  /GEM_ROOT/gems/rack-2.2.6.2/lib/rack/urlmap.rb -> **call**
107:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb -> **process_request**
157:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **accept_and_process_next_request**
110:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **main_loop**
419:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/request_handler.rb -> **block (3 levels) in start_threads**
113:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/utils.rb -> **block in create_thread_and_abort_on_exception**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| program_name | Passenger RubyApp: /srv/www/obs/api (production) |
| HTTP_USER_AGENT | Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0 |

### PR DESCRIPTION
**Pull request by danidoni**
When dealing with errors on the form, the view would crash with an:

	undefined method `token_services_path'

trying to build the form action url, because we don't use tokens but its subclasses (like Token::Service)

Forcing the path ensure we use existing route.

Fixes #13853

## How can you review this PR?

- From [Admin's tokens page in the Review App instance](https://obs-reviewlab.opensuse.org/danidoni-fix-token-service-description-too-large-errors/my/tokens)
- Create a Service token and try to set a description that is longer than 64 characters
- It should not crash. It should flash you an error saying that the `Description is too long (maximum is 64 characters).`

### CODE REVIEW

File: src/api/spec/controllers/webui/users/tokens_controller_spec.rb [hunk 1]
```diff
@@ -95,6 +95,18 @@
...
       end
     end
+
+    context 'type is service' do
+      context 'and the description is larger than 64 characters' do
+        render_views
+
+        let(:form_parameters) { { token: { type: 'service', description: 'Something' * 20 } } }
+
+        include_examples 'check for flashing an error'
```
Comment (hennevogel) [inline src/api/spec/controllers/webui/users/tokens_controller_spec.rb:105]: CI time is developer time. You are testing an activerecord validation with a click test.

Comment (danidoni) [reply src/api/spec/controllers/webui/users/tokens_controller_spec.rb:105]: I'm testing that the form reacts correctly to validation errors. Before this change, the form crashed.

I will remove this test because it served it's purpose to confirm the bug presence and ensure the fix works.

File: src/api/spec/controllers/webui/users/tokens_controller_spec.rb [hunk 2]
```diff
@@ -95,6 +95,18 @@
         it { expect { subject }.not_to change(Token, :count) }
       end
     end
+
+    context 'type is service' do
+      context 'and the description is larger than 64 characters' do
```
Comment (danidoni) [inline src/api/spec/controllers/webui/users/tokens_controller_spec.rb:100]: Ah, this context is wrong... changing...

Comment (danidoni) [reply src/api/spec/controllers/webui/users/tokens_controller_spec.rb]: In the end I removed it...

**Comment by dmarcoux** [comment]
This was an issue with all token classes, right?

**Comment by danidoni** [comment]
> This was an issue with all token classes, right?

Yes.

**Comment by dmarcoux** [comment]
> Create a Service token and try to set a description that is longer than 64 characters

To prevent this in the first place, the input should only accept up to 64 characters. This is already what we have in the edit form for tokens, but somehow, not for the create form.

**Comment by danidoni** [comment]
> > Create a Service token and try to set a description that is longer than 64 characters
> 
> To prevent this in the first place, the input should only accept up to 64 characters. This is already what we have in the edit form for tokens, but somehow, not for the create form.

This was already fixed on #13855. But I believe it's not wise to rely on client side validation only I want to fix it on server side too.

**Comment by dmarcoux** [comment]
I looked at the lines here in this PR and it doesn't show the `maxlength` attribute since this PR is out-of-date with the default branch.

**Review by dmarcoux — APPROVED** [review]
