### PR TITLE
Handle duplicate repository in distributions toggle gracefully

### LINKED ISSUE #18959: [production][distributions#toggle] Mysql2::Error: Duplicate entry '923949-15.3-' for key 'projects_name_index'
[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/6936c4a284bf460d19e8f7df)
# Mysql2::Error: Duplicate entry &#39;923949-15.3-&#39; for key &#39;projects_name_index&#39; #
### URL ###
[https://build.opensuse.org/projects/home:$USER/distributions/toggle](https://build.opensuse.org/projects/home:USER/distributions/toggle)"
### Where ###
distributions#toggle

### Occured ###
Oct 03  9:27am

### Similar ###
18

## Params ##
~~~
{
  &quot;action&quot; =&gt; &quot;toggle&quot;,
  &quot;controller&quot; =&gt; &quot;webui/distributions&quot;,
  &quot;distribution&quot; =&gt; &quot;19086&quot;,
  &quot;project_name&quot; =&gt; &quot;home:USER&quot;
}
~~~

## Session ##
~~~
{
  &quot;_csrf_token&quot; =&gt; &quot;fwVR6QSKogdSuW0yAcPO5AL1nO5uWjiBbULDqaFUpBs=&quot;,
  &quot;session_id&quot; =&gt; &quot;cc067d492199bb65a11f2dad0e562308&quot;
}
~~~

## Backtrace ##
~~~
131:  /GEM_ROOT/gems/mysql2-0.5.3/lib/mysql2/client.rb -> **_query**
131:  /GEM_ROOT/gems/mysql2-0.5.3/lib/mysql2/client.rb -> **block in query**
130:  /GEM_ROOT/gems/mysql2-0.5.3/lib/mysql2/client.rb -> **handle_interrupt**
130:  /GEM_ROOT/gems/mysql2-0.5.3/lib/mysql2/client.rb -> **query**
206:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb -> **block (2 levels) in execute**
48:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/dependencies/interlock.rb -> **block in permit_concurrent_loads**
187:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/concurrency/share_lock.rb -> **yield_shares**
47:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/dependencies/interlock.rb -> **permit_concurrent_loads**
205:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb -> **block in execute**
696:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/connection_adapters/abstract_adapter.rb -> **block (2 levels) in log**
26:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **block (2 levels) in synchronize**
25:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **handle_interrupt**
25:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **block in synchronize**
21:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **handle_interrupt**
21:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **synchronize**
695:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/connection_adapters/abstract_adapter.rb -> **block in log**
24:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/notifications/instrumenter.rb -> **instrument**
687:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/connection_adapters/abstract_adapter.rb -> **log**
204:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb -> **execute**
50:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/connection_adapters/mysql/database_statements.rb -> **execute**
215:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb -> **execute_and_free**
55:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/connection_adapters/mysql/database_statements.rb -> **exec_query**
136:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb -> **exec_insert**
171:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb -> **insert**
22:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/connection_adapters/abstract/query_cache.rb -> **insert**
375:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/persistence.rb -> **_insert_record**
929:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/persistence.rb -> **_create_record**
166:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/counter_cache.rb -> **_create_record**
79:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/locking/optimistic.rb -> **_create_record**
201:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/attribute_methods/dirty.rb -> **_create_record**
461:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/callbacks.rb -> **block in _create_record**
106:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/callbacks.rb -> **run_callbacks**
20:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rails/active_record.rb -> **run_callbacks**
824:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/callbacks.rb -> **_run_create_callbacks**
461:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/callbacks.rb -> **_create_record**
108:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/timestamp.rb -> **_create_record**
900:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/persistence.rb -> **create_or_update**
457:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/callbacks.rb -> **block in create_or_update**
117:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/callbacks.rb -> **block in run_callbacks**
385:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/autosave_association.rb -> **around_save_collection_association**
126:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/callbacks.rb -> **block in run_callbacks**
137:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/callbacks.rb -> **run_callbacks**
20:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rails/active_record.rb -> **run_callbacks**
824:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/callbacks.rb -> **_run_save_callbacks**
457:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/callbacks.rb -> **create_or_update**
126:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/timestamp.rb -> **create_or_update**
474:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/persistence.rb -> **save**
47:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/validations.rb -> **save**
298:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/transactions.rb -> **block in save**
354:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/transactions.rb -> **block in with_transaction_returning_status**
320:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb -> **block in transaction**
319:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/connection_adapters/abstract/transaction.rb -> **block in within_new_transaction**
26:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **block (2 levels) in synchronize**
25:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **handle_interrupt**
25:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **block in synchronize**
21:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **handle_interrupt**
21:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **synchronize**
317:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/connection_adapters/abstract/transaction.rb -> **within_new_transaction**
320:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb -> **transaction**
350:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/transactions.rb -> **with_transaction_returning_status**
298:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/transactions.rb -> **save**
44:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/suppressor.rb -> **save**
39:  app/controllers/webui/distributions_controller.rb -> **create_repository_from_distribution**
29:  app/controllers/webui/distributions_controller.rb -> **toggle**
6:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal/basic_implicit_render.rb -> **send_action**
228:  /GEM_ROOT/gems/actionpack-6.1.4/lib/abstract_controller/base.rb -> **process_action**
30:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal/rendering.rb -> **process_action**
42:  /GEM_ROOT/gems/actionpack-6.1.4/lib/abstract_controller/callbacks.rb -> **block in process_action**
106:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/callbacks.rb -> **run_callbacks**
41:  /GEM_ROOT/gems/actionpack-6.1.4/lib/abstract_controller/callbacks.rb -> **process_action**
22:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal/rescue.rb -> **process_action**
34:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal/instrumentation.rb -> **block in process_action**
203:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/notifications/instrumenter.rb -> **instrument**
203:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/notifications.rb -> **instrument**
33:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal/instrumentation.rb -> **process_action**
249:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal/params_wrapper.rb -> **process_action**
27:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/railties/controller_runtime.rb -> **process_action**
165:  /GEM_ROOT/gems/actionpack-6.1.4/lib/abstract_controller/base.rb -> **process**
39:  /GEM_ROOT/gems/actionview-6.1.4/lib/action_view/rendering.rb -> **process**
190:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal.rb -> **dispatch**
254:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal.rb -> **dispatch**
50:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/routing/route_set.rb -> **dispatch**
33:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/routing/route_set.rb -> **serve**
19:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/routing/mapper.rb -> **block in &lt;class:Constraints&gt;**
49:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/routing/mapper.rb -> **serve**
50:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/journey/router.rb -> **block in serve**
32:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/journey/router.rb -> **each**
32:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/journey/router.rb -> **serve**
842:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/routing/route_set.rb -> **call**
77:  /GEM_ROOT/gems/flipper-0.22.1/lib/flipper/middleware/memoizer.rb -> **memoized_call**
42:  /GEM_ROOT/gems/flipper-0.22.1/lib/flipper/middleware/memoizer.rb -> **call**
37:  config/initializers/wrap_parameters.rb -> **call**
44:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/deflater.rb -> **call**
15:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/etag.rb -> **call**
40:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/conditional_get.rb -> **call**
12:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/head.rb -> **call**
22:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/http/permissions_policy.rb -> **call**
18:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/http/content_security_policy.rb -> **call**
266:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/session/abstract/id.rb -> **context**
260:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/session/abstract/id.rb -> **call**
689:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/cookies.rb -> **call**
27:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/callbacks.rb -> **block in call**
98:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/callbacks.rb -> **run_callbacks**
26:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/callbacks.rb -> **call**
18:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/actionable_exceptions.rb -> **call**
32:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call!**
21:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call**
29:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/debug_exceptions.rb -> **call**
33:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/show_exceptions.rb -> **call**
15:  /GEM_ROOT/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb -> **call_app**
26:  /GEM_ROOT/gems/railties-6.1.4/lib/rails/rack/logger.rb -> **block in call**
99:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/tagged_logging.rb -> **block in tagged**
37:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/tagged_logging.rb -> **tagged**
99:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/tagged_logging.rb -> **tagged**
26:  /GEM_ROOT/gems/railties-6.1.4/lib/rails/rack/logger.rb -> **call**
81:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/remote_ip.rb -> **call**
81:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/remote_ip.rb -> **call**
19:  /GEM_ROOT/gems/request_store-1.5.0/lib/request_store/middleware.rb -> **call**
26:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/request_id.rb -> **call**
24:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/method_override.rb -> **call**
22:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/runtime.rb -> **call**
29:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/cache/strategy/local_cache_middleware.rb -> **call**
14:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/executor.rb -> **call**
18:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/lock.rb -> **call**
110:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/sendfile.rb -> **call**
92:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/host_authorization.rb -> **call**
539:  /GEM_ROOT/gems/railties-6.1.4/lib/rails/engine.rb -> **call**
207:  /GEM_ROOT/gems/railties-6.1.4/lib/rails/railtie.rb -> **public_send**
207:  /GEM_ROOT/gems/railties-6.1.4/lib/rails/railtie.rb -> **method_missing**
74:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/urlmap.rb -> **block in call**
58:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/urlmap.rb -> **each**
58:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/urlmap.rb -> **call**
107:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.8/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb -> **process_request**
157:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.8/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **accept_and_process_next_request**
110:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.8/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **main_loop**
416:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.8/src/ruby_supportlib/phusion_passenger/request_handler.rb -> **block (3 levels) in start_threads**
113:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.8/src/ruby_supportlib/phusion_passenger/utils.rb -> **block in create_thread_and_abort_on_exception**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| program_name | Passenger RubyApp: /srv/www/obs/api (production) |
| HTTP_USER_AGENT | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15 |

### PR DESCRIPTION
**Pull request by Digvijay-x1**
This PR adds a `begin/rescue` block around `repository.save` to catch `ActiveRecord::RecordNotUnique` errors and display a friendly error message instead.

Fixes: #18959

### CODE REVIEW

File: src/api/app/controllers/webui/distributions_controller.rb [hunk 1]
```diff
@@ -36,10 +36,14 @@ def create_repository_from_distribution
...
-    else
-      flash.now[:error] = "Can't add repository: #{repository.errors.full_messages.to_sentence}"
+    begin
+      if repository.save
+        @project.store(comment: "Added #{repository.name} repository")
+      else
+        flash.now[:error] = "Can't add repository: #{repository.errors.full_messages.to_sentence}"
+      end
+    rescue ActiveRecord::RecordNotUnique
+      flash.now[:error] = "Repository #{repository.name} already exists"
```
Comment (eduardoj) [inline src/api/app/controllers/webui/distributions_controller.rb]: Even though rescuing from `ActiveRecord::RecordNotUnique` works, there must be something odd with the current repository validation. We already have code that validates a repository, so `repository.save`  return `false`, instead of raising an exception.

See:

https://github.com/openSUSE/open-build-service/blob/8e4fb628b5b671984f280e74011fffd63194101a/src/api/app/models/repository.rb#L48-L53

Could you take a look?

Comment (Digvijay-x1) [reply src/api/app/controllers/webui/distributions_controller.rb]: The validation is working correctly for normal use cases :+1: . This exception only occurs during concurrent requests when both pass validation before either inserts the record.

**Review by hennevogel — CHANGES_REQUESTED** [review]
Instead of doing this in individual controllers we should do this in `Webui::RescueHandler` for all records.

File: src/api/app/controllers/concerns/webui/rescue_handler.rb [hunk 2]
```diff
@@ -38,5 +38,17 @@ module Webui::RescueHandler
     rescue_from RegistrationDisabledError do
       redirect_to root_path, error: RegistrationDisabledError.new.default_message
     end
+
+    rescue_from ActiveRecord::RecordNotUnique do |exception|
+      Airbrake.notify(exception)
```
Comment (hennevogel) [inline src/api/app/controllers/concerns/webui/rescue_handler.rb]: Why? What are the developers supposed to do about this? :)

File: src/api/app/controllers/concerns/webui/rescue_handler.rb [hunk 3]
```diff
@@ -38,5 +38,17 @@ module Webui::RescueHandler
...
+      message = 'This record already exists. Please try again.'
```
Comment (hennevogel) [inline src/api/app/controllers/concerns/webui/rescue_handler.rb]:
```suggestion
      message = "This #{exception.record.class.to_s} already exists."
```

Comment (Digvijay-x1) [reply src/api/app/controllers/concerns/webui/rescue_handler.rb]: `#{exception.record.class.to_s}` is same as `#{exception.record.class}`, linter was feeling bad about it. Applied the suggestions.

**Review by hennevogel — APPROVED** [review]

**Comment by hennevogel** [comment]
@Digvijay-x1 👍🏿 nice work
