### PR TITLE
[webui] Fix possible XSS attack on project title

### LINKED ISSUE #1218: Cross-Site Scripting Warning in app/views/webui/user/show.html.erb
[Security issue from Hakiri](https://hakiri.io/projects/24a4980a727941/stacks/beceb185080072/builds/9f4cab3b56e087/warnings/46677b296014a8): Unescaped model attribute in app/views/webui/user/show.html.erb

### PR DESCRIPTION
**Pull request by ChrisBr**
Project.title can contain html / js tags which will be rendered.
Close #1218

### CODE REVIEW

File: src/api/app/controllers/webui/project_controller.rb [hunk 1]
```diff
@@ -48,7 +48,7 @@ def index
     @show_all = params[:show_all]
     projects = Project.all
     projects = projects.not_home unless @show_all
-    @projects = projects.pluck(:name, :title)
+    @projects = projects.select(:name, :title)
```
Comment (ChrisBr) [inline src/api/app/controllers/webui/project_controller.rb]: ``select`` is probably a little bit slower than ``pluck`` but for better readability I use select now. The index list is cached anyway, so I don't think this will cause performance issues.

File: src/api/app/helpers/webui/project_helper.rb [hunk 2]
```diff
@@ -4,10 +4,6 @@ module Webui::ProjectHelper
 
   protected
 
-  def escape_project_list(arr)
-    arr.map { |p| "['#{p[0]}','#{escape_javascript(p[1])}']" }.join(",\n").html_safe
```
Comment (ChrisBr) [inline src/api/app/helpers/webui/project_helper.rb]: This was used on the project index page! Now we use the new helper from `` src/api/app/helpers/webui/webui_helper.rb ``

**Comment by bgeuken** [comment]
@ChrisBr :+1: Please add some tests for this later on
