### PR TITLE
Avoid crashing when checking permissions to create a new status message

### LINKED ISSUE #16187: [production][status_messages#new] Requiring user, but found nobody
[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/664fef7284bf4608c2d82c7d)
# Requiring user, but found nobody #
### URL ###
[https://build.opensuse.org/news_items/new](https://build.opensuse.org/news_items/new)"
### Where ###
status_messages#new

### Occured ###
May 24  1:37am

### Similar ###
3

## Params ##
~~~
{
  &quot;action&quot; =&gt; &quot;new&quot;,
  &quot;controller&quot; =&gt; &quot;webui/status_messages&quot;
}
~~~

## Session ##
~~~
{}
~~~

## Backtrace ##
~~~
244:  app/models/user.rb -> **session!**
175:  app/controllers/webui/webui_controller.rb -> **require_staff**
400:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb -> **block in make_lambda**
199:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb -> **block (2 levels) in halting**
34:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/abstract_controller/callbacks.rb -> **block (2 levels) in &lt;module:Callbacks&gt;**
200:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb -> **block in halting**
595:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb -> **block in invoke_before**
595:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb -> **each**
595:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb -> **invoke_before**
106:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb -> **run_callbacks**
233:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/abstract_controller/callbacks.rb -> **process_action**
23:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/rescue.rb -> **process_action**
67:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/instrumentation.rb -> **block in process_action**
206:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications/instrumenter.rb -> **instrument**
206:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **instrument**
66:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/instrumentation.rb -> **process_action**
259:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/params_wrapper.rb -> **process_action**
27:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/railties/controller_runtime.rb -> **process_action**
151:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/abstract_controller/base.rb -> **process**
39:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/rendering.rb -> **process**
188:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal.rb -> **dispatch**
251:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal.rb -> **dispatch**
49:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/route_set.rb -> **dispatch**
32:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/route_set.rb -> **serve**
18:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/mapper.rb -> **block in &lt;class:Constraints&gt;**
48:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/mapper.rb -> **serve**
50:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/journey/router.rb -> **block in serve**
32:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/journey/router.rb -> **each**
32:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/journey/router.rb -> **serve**
852:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/route_set.rb -> **call**
87:  /GEM_ROOT/gems/flipper-1.3.0/lib/flipper/middleware/memoizer.rb -> **memoized_call**
45:  /GEM_ROOT/gems/flipper-1.3.0/lib/flipper/middleware/memoizer.rb -> **call**
15:  config/initializers/prefer_xml_over_html.rb -> **call**
44:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/deflater.rb -> **call**
15:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/tempfile_reaper.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/etag.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/conditional_get.rb -> **call**
12:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/head.rb -> **call**
38:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/http/permissions_policy.rb -> **call**
36:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/http/content_security_policy.rb -> **call**
266:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/session/abstract/id.rb -> **context**
260:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/session/abstract/id.rb -> **call**
704:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/cookies.rb -> **call**
27:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/callbacks.rb -> **block in call**
99:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb -> **run_callbacks**
26:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/callbacks.rb -> **call**
32:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call!**
21:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call**
28:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/debug_exceptions.rb -> **call**
29:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/show_exceptions.rb -> **call**
18:  /GEM_ROOT/gems/lograge-0.14.0/lib/lograge/rails_ext/rack/logger.rb -> **call_app**
25:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/rack/logger.rb -> **block in call**
99:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/tagged_logging.rb -> **block in tagged**
37:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/tagged_logging.rb -> **tagged**
99:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/tagged_logging.rb -> **tagged**
25:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/rack/logger.rb -> **call**
93:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/remote_ip.rb -> **call**
93:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/remote_ip.rb -> **call**
19:  /GEM_ROOT/gems/request_store-1.7.0/lib/request_store/middleware.rb -> **call**
26:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/request_id.rb -> **call**
24:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/method_override.rb -> **call**
22:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/runtime.rb -> **call**
29:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/cache/strategy/local_cache_middleware.rb -> **call**
14:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/executor.rb -> **call**
18:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/lock.rb -> **call**
110:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/sendfile.rb -> **call**
131:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/host_authorization.rb -> **call**
530:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/engine.rb -> **call**
226:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/railtie.rb -> **public_send**
226:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/railtie.rb -> **method_missing**
74:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/urlmap.rb -> **block in call**
58:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/urlmap.rb -> **each**
58:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/urlmap.rb -> **call**
107:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb -> **process_request**
149:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **accept_and_process_next_request**
110:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **main_loop**
419:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/request_handler.rb -> **block (3 levels) in start_threads**
113:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/utils.rb -> **block in create_thread_and_abort_on_exception**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| program_name | Passenger RubyApp: /srv/www/obs/api (production) |
| HTTP_USER_AGENT | Mozilla/5.0 (Linux; Android 5.0) AppleWebKit/537.36 (KHTML, like Gecko) Mobile Safari/537.36 (compatible; Bytespider; spider-feedback@bytedance.com) |

### PR DESCRIPTION
**Pull request by danidoni**
We should flash back an error and redirecting the user to the main page instead of crashing.

Fixes #16187

### CODE REVIEW

File: src/api/app/controllers/webui/status_messages_controller.rb [hunk 1]
```diff
@@ -71,6 +71,14 @@ def preview
 
   private
 
+  def require_staff
+    return if User.session.blank?
```
Comment (eduardoj) [inline src/api/app/controllers/webui/status_messages_controller.rb:75]: With this line, we prevent from crashing for not logged in users for the `index`, `new` and `edit` actions. But we start permitting them.

```suggestion
```
Removing that line will make not logged in users will be shown the "Require staff privileges" message, at least. There would be better options, I guess.

Comment (danidoni) [reply src/api/app/controllers/webui/status_messages_controller.rb:75]: Hm, I thought I removed that... Anyway, I'll fix it now

Comment (eduardoj) [reply src/api/app/controllers/webui/status_messages_controller.rb]: You even fixed the linter previously, same line...

**Review by eduardoj — APPROVED** [review]
