### PR TITLE
Show project title in staging projects table

### LINKED ISSUE #8278: [production][public_key#key_dialog] undefined method `remove_dialog_tag' for #<#<Class:0x00007fcc7da8b5f0>:0x00007fcc3c295df0>
Did yo...
public_key#key_dialog threw this 0 times
<pre>
undefined method `remove_dialog_tag&#39; for #&lt;#&lt;Class:0x00007fcc7da8b5f0&gt;:0x00007fcc3c295df0&gt;
Did you mean?  remove_flag
</pre>
[https://build.opensuse.org/projects/home:Zigmund_Freud/public_key/key_dialog](https://build.opensuse.org/projects/home:Zigmund_Freud/public_key/key_dialog)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5d70ef616e905f0008f4b707)

### LINKED ISSUE #8787: Staging dashboard redundant project name
Looking at the staging dashboard of 15.2 the screen is pretty busy and certainly costs brain power to digest. More than the old one.
staging

There is a headline stating "Staging for openSUSE Leap 15.2". But then all rows in the table have openSUSE:Leap:15.2 again. Looks redundant, eg "A" should be sufficient.

### PR DESCRIPTION
**Pull request by krauselukas**
Fixes #8787  

Showing the full project name again in the staging projects
table is redundant and usually not needed.
Now in case a project title is set, it will use it in the staging projects table instead of
the project name. This allows the staging managers to customize the naming.

Also, since some staging projects are meant for specific packages the description
of the project is now shown in a tooltip when hovering over the link to the staging project 
in the table. This makes it easier to get an quick overview.

Screenshot_2020-01-09 Open Build Service
Screenshot_2020-01-09_18-06-36

### staging projects without title
Screenshot_2020-01-20 Open Build Service(2)

### staging projects with title
Screenshot_2020-01-20 Open Build Service

### staging projects with title: A,B,C,...
Screenshot_2020-01-20 Open Build Service(3)

### CODE REVIEW

**Comment by coolo** [comment]
How will clone behave?

**Comment by vpereira** [comment]
is that ready to merge @krauselukas or still a WIP?

**Comment by DavidKang** [comment]
### Current state
Screenshot_2020-01-13 Open Build Service

Is still WIP

**Comment by coolo** [comment]
I find this very dangerous to rely on users to keep the name of the project aligned with the title. RMs refer to 'Staging S' because S is displayed in the dashboard - and they mean ....:Staging:S. If that's no longer guarnateed to stay in sync, there is a problem.

I like showing the description as annotation though.

**Comment by hennevogel** [comment]
> I find this very dangerous to rely on users to keep the name of the project aligned with the title.

I don't get it. Why does it have to be aligned?

**Comment by coolo** [comment]
The project shown as S in the dashboard should be ...:Staging:S

**Comment by hennevogel** [comment]
> The project shown as S in the dashboard should be ...:Staging:S

Why?

**Comment by coolo** [comment]
That's a requirement for the staging dashboard. I don't want to discuss it.

**Comment by hennevogel** [comment]
We are not going to hardcode `:Staging:` into this workflow, sorry. I understand this is your convention. 
I guess we need a third way

1. If the staging project has a title we use this
2. If the staging project has no title
    - is a subproject of the workflow project: remove the workflow project name from the string
    - isn't a subproject of the workflow project: name

**Comment by coolo** [comment]
my proposal to this is still open at https://github.com/openSUSE/open-build-service/pull/8803

**Comment by DavidKang** [comment]
I updated the PR description with new screenshots

File: src/api/app/decorators/workflow/staging_project_decorator.rb [hunk 1]
```diff
@@ -0,0 +1,15 @@
+module Workflow
```
Comment (hennevogel) [inline src/api/app/decorators/workflow/staging_project_decorator.rb]: Workflow?

Comment (hennevogel) [reply src/api/app/decorators/workflow/staging_project_decorator.rb]:
```shell
➜  api git:(bugfix/staging-tab) ls -ld app/*/staging
drwxr-xr-x - hvogel 10 Jan 15:11 app/controllers/staging
drwxr-xr-x - hvogel 10 Jan 15:11 app/policies/staging
drwxr-xr-x - hvogel 15 Jan 13:47 app/models/staging
drwxr-xr-x - hvogel  7 Jan 13:19 app/services/staging
drwxr-xr-x - hvogel  7 Jan 13:19 app/views/staging
➜  api git:(bugfix/staging-tab) ls -ld app/*/workflow
zsh: no matches found: app/*/workflow
```

**Comment by DavidKang** [comment]
@hennevogel, could you review it again?

**Comment by hennevogel** [comment]
@DavidKang do you have a screenshot with project with title A, B, C, D....?

**Comment by DavidKang** [comment]
@hennevogel, I put the screenshot on the description of the PR
