### PR TITLE
[webui] Redirects /apidocs to /apidocs/index

### LINKED ISSUE #952: Apidocs Broken
Most of the apidocs example links don't work anymore, except those where by accident the real API responds. This is because the apidocs tool (restility) does not know about linking files in sub-directories. 

@adrianschroeter is it possible that we switch to some other tool like [helphelp](https://github.com/SUSESTUDIO/studio-help) or is there more involved. We're not completely sure...

@cornelius  Or can you tell restility to prepend a path for an XmlResult?

### PR DESCRIPTION
**Pull request by eduardoj**
This should fix #952.

### CODE REVIEW

File: src/api/config/routes.rb [hunk 1]
```diff
@@ -345,7 +345,8 @@ def self.public_or_about_path?(request)
     resources :comments, constraints: cons, only: [:create, :destroy], controller: 'webui/comments'
 
     ### /apidocs
-    get 'apidocs(/index)' => 'webui/apidocs#index'
+    get 'apidocs', to: redirect('/apidocs/index')
+    get 'apidocs/(index)' => 'webui/apidocs#index', as: 'apidocs_index'
```
Comment (bgeuken) [inline src/api/config/routes.rb]: Why separating this? 'apidocs(/index)' should cover both cases, with and without /index

Comment (bgeuken) [inline src/api/config/routes.rb]: Then you probably want this: ``` get 'apidocs((/)index)' => 'webui/apidocs#index' ```

Although it would be nicer to use the expected url schema instead.

Comment (bgeuken) [inline src/api/config/routes.rb]: We talked in person now and Eduardo convinced me that using a redirect is the more feasible approach.
