### PR TITLE
[frontend] Report review validation details

### LINKED ISSUE #5152: Reviewers: Error message when a user doesn't exist is not clear
# Issue Description
I tried to add a reviewer on a request but the API responds with `400 bad request` and the WebUi says `Unable add review to '617333': Validation failed: Reviews is invalid`. @coolo later found out that the username was wrong.

The message `Validation failed: Reviews is invalid` doesn't say that. It should be more verbose.

Expected Result
============
Error message shows the actual error.

How to Reproduce
===============
1. Create a request
2. Request a review from a non-existent user

### PR DESCRIPTION
**Pull request by coolo**
'Reviews invalid' is little helpful, 'User not found' makes
it more obvious you had a typo

Fixes #5152

### CODE REVIEW

File: src/api/app/models/bs_request.rb [hunk 1]
```diff
@@ -781,15 +797,7 @@ def addreview(opts)
...
-      newreview = reviews.create(
-        reason:     opts[:comment],
-        by_user:    opts[:by_user],
-        by_group:   opts[:by_group],
-        by_project: opts[:by_project],
-        by_package: opts[:by_package],
-        creator:    User.current.try(:login),
-        reviewer:    User.current.try(:login)
-      )
+      newreview = _create_new_review(opts)
```
Comment (Ana06) [inline src/api/app/models/bs_request.rb]: why with underscore? :confused:

Comment (coolo) [reply src/api/app/models/bs_request.rb]: just to see if the test suite catches it
