### PR TITLE
[webui] redirect to home after login from /user/do_login

### LINKED ISSUE #1557: OBS 2.6.8: login from /user/do_login page redirects to 404 page
Reproducible with OBS appliance (obs-server.x86_64-2.6.8-Build1.10.install.iso).

Steps to reproduce:

1. click on login button at top-right of webui
2. try to login with the wrong password
3. you are redirected to the /user/do_login page
4. try to login with the correct password
5. get 404 page

Problem introduced in commit f6c9a14e6370596daaabc82bde3a119a06d81f22

### PR DESCRIPTION
**Pull request by cschneemann**
If a user enters wrong credentials in login widget and he gets redirected to /user/do_login.
If login happens with correct credentials now the user is logged in but stays on the page and sees the login form again in master, or gets an 404 in 2.6.

Now he gets redirected into home if the user comes from the login page.

fixes #1557
closes #1615

### CODE REVIEW

File: src/api/test/functional/webui/user_controller_test.rb [hunk 1]
```diff
@@ -181,6 +181,22 @@ def test_that_redirect_after_login_works # spec/controllers/webui/users_spec.rb
     assert_equal search_path, current_path
   end
 
+  def test_that_redirect_from_user_do_login_works # spec/controllers/webui/users_spec.rb
```
Comment (bgeuken) [inline src/api/test/functional/webui/user_controller_test.rb]: Please remove the comment. Those are just used by us to mark tests we already moved to rspec. 

See https://github.com/openSUSE/open-build-service/tree/master/src/api/spec for details

File: src/api/test/functional/webui/user_controller_test.rb [hunk 2]
```diff
@@ -181,6 +181,22 @@ def test_that_redirect_after_login_works # spec/controllers/webui/users_spec.rb
...
+    use_js
+
+    visit search_path
+    click_link("Log In")
+    fill_in 'Username', with: "tom"
+    fill_in 'Password', with: "brokenpassword"
+    click_button 'Log In'
```
Comment (bgeuken) [inline src/api/test/functional/webui/user_controller_test.rb]: You can replace this block by directly going to the /user/login page

File: src/api/test/functional/webui/user_controller_test.rb [hunk 3]
```diff
@@ -181,6 +181,22 @@ def test_that_redirect_after_login_works # spec/controllers/webui/users_spec.rb
...
+
+    fill_in 'Username', with: "tom"
+    fill_in 'Password', with: "buildservice"
+    click_button 'Log In'
+
+    assert_equal "tom", find('#home-username').text
```
Comment (bgeuken) [inline src/api/test/functional/webui/user_controller_test.rb]: To also test the redirect you might want to add something like this:
assert_equal home_path, page.current_path

**Comment by bgeuken** [comment]
LGTM

Once you've updated the PR we can merge it. Thanks:+1:

File: src/api/test/functional/webui/user_controller_test.rb (hunk 2 above)
Comment (cschneemann) [inline src/api/test/functional/webui/user_controller_test.rb]: added this to be as accurately as possible. But can change that, how is the page called in the testcases?

Comment (bgeuken) [inline src/api/test/functional/webui/user_controller_test.rb]: You could use "/user/login", but if there is a named route we usually use them. In this case it would be user_login_path.

That's how you can get information about routes in a rails app: ```rake routes | grep login```

Comment (bgeuken) [inline src/api/test/functional/webui/user_controller_test.rb]: http://guides.rubyonrails.org/routing.html#path-and-url-helpers

**Comment by cschneemann** [comment]
@bgeuken added/changed your remarks, thanks for the references

**Comment by bgeuken** [comment]
Thanks again

**Comment by cschneemann** [comment]
@bgeuken is an additional task needed to submit the fix into 2.6 branch or will you take it for the next release?

**Comment by bgeuken** [comment]
@cschneemann We are going to add it to the next 2.6 release.
