### PR TITLE
Fix error message of an 'accept' permission check

### LINKED ISSUE #8846: Strange error on permission problem for accept
POST https://api.opensuse.org/staging/openSUSE:Factory/staging_projects/openSUSE:Factory:Staging:adi:7/accept

as non authorized user leads to:

```
Status: 403 Forbidden
<status code="accept?_project_not_authorized">
   <summary>You are not authorized to accept? this Project.</summary>
</status>
```

"You are not authorized to accept? this Project." is a strange sentense.

### PR DESCRIPTION
**Pull request by eduardoj**
Intead of showing "You are not authorized to accept? this Project." show "You are not authorized to accept this Project."

Fixes #8846.

### CODE REVIEW

File: src/api/app/controllers/application_controller.rb [hunk 1]
```diff
@@ -256,6 +256,7 @@ def pass_to_backend(path = nil)
       when 'edit?' then 'edit'
       when 'destroy?' then 'delete'
       when 'branch?' then 'branch'
+      when 'accept?' then 'accept'
```
Comment (coolo) [inline src/api/app/controllers/application_controller.rb]: this looks like a low hanging fruit to DRY :)
