### PR TITLE
Fix syntax error in haml view

### LINKED ISSUE #6807: Ruby code is not interpreted correctly
# Issue Description
Your ruby code is not parsed correctly.

Expected Result
============
I don't see it anymore.

How to Reproduce
===============
1. Go to a maintenance incident on the internal build service
2. scroll down

Further Information
===============
See screenshot.
ruby_code

### PR DESCRIPTION
**Pull request by bgeuken**
Fixes #6807

### CODE REVIEW

**Comment by bgeuken** [comment]
@ChrisBr I moved it to a helper now

File: src/api/app/helpers/webui/project_helper.rb [hunk 1]
```diff
@@ -142,4 +142,8 @@ def show_package_actions?
                        @has_patchinfo && @open_release_requests.empty?
     false
   end
+
+  def can_be_released?(project, package, open_release_requests, has_patchinfo)
```
Comment (DavidKang) [inline src/api/app/helpers/webui/project_helper.rb]: package**s**

File: src/api/app/views/webui2/webui/project/show.html.haml [hunk 2]
```diff
@@ -77,8 +77,7 @@
       = render partial: 'new_package_modal', locals: { project: @project }
       = render partial: 'new_package_branch_modal', locals: { project: @project, remote_projects: @remote_projects }
 
-    - if !@project.defines_remote_instance? && @project.is_maintenance_incident? && @packages.present? && @has_patchinfo
-      && @open_release_requests.blank?
+    - if can_be_released?(@project, @package, @open_release_requests, @has_patchinfo)
```
Comment (DavidKang) [inline src/api/app/views/webui2/webui/project/show.html.haml]: @ package**s**
