### PR TITLE
[api] Handle multibuilds in API call to _result

### LINKED ISSUE #3026: Add multibuild support to lastsuccess call
Issue/Feature description
====================

repochecker bot is rely on lastsuccess call[1] heavily, in order to support multbuild into repochecker, we need lastsuccess able to process multbuild package. Currently passing PACKAGE_NAME:FLAVOR as package parameter does not work.

```
osc api "/build/system:install:head/_result?lastsuccess&package=installation-images:openSUSE&pathproject=openSUSE:Factory&srcmd5=ca76a1a9ecc243ca7ba2ae9d1cdfa0d9"
Server returned an error: HTTP Error 404: Not Found
system:install:head/installation-images:openSUSE
```

[1] https://github.com/openSUSE/osc-plugin-factory/blob/master/osclib/checkrepo.py#L302

Expected result
============

lastsuccess call able to support multibuild result. either

1) feed ``package=PACKAGE_NAME:FLAVOR`` does work  for multibuild package, or
2) ``package=PACKAGE_NAME&multbuild=1`` can given all multibuild result.

How to Reproduce
===============
```
osc api "/build/system:install:head/_result?lastsuccess&package=installation-images:openSUSE&pathproject=openSUSE:Factory&srcmd5=ca76a1a9ecc243ca7ba2ae9d1cdfa0d9"
Server returned an error: HTTP Error 404: Not Found
system:install:head/installation-images:openSUSE
```

### PR DESCRIPTION
**Pull request by bgeuken**
Fixes #3026

In case of multibuilds we need to fetch the sources of the package
container, but the build results of the queried multibuild package.
This commit should do the trick.

Kudos to Michael for pointing me towards the right direction.

### CODE REVIEW

File: src/api/app/controllers/build_controller.rb [hunk 1]
```diff
@@ -168,12 +168,19 @@ def result
   def result_lastsuccess
     required_parameters :package, :pathproject
 
-    pkg = Package.get_by_project_and_name(params[:project], params[:package],
+    if params[:multibuild]
```
Comment (ChrisBr) [inline src/api/app/controllers/build_controller.rb]: Looking at the issue there is no multibuild parameter.

Other solution:

Set ``follow_multibuild:    true`` in Package.get_by_project_and_name will return always the package container. If the package parameter does not package pkg.name it is a multibuild.

Comment (bgeuken) [inline src/api/app/controllers/build_controller.rb]: Right, that was from the other solution. I got confused.

**Comment by ChrisBr** [comment]
LGTM (provided tests succeed!)
