### PR TITLE
Coerce sensible params to string

### LINKED ISSUE #16379: [production][package#index] can't quote ActionController::Parameters
[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/665cd63384bf4608c4d82c59)
# can&#39;t quote ActionController::Parameters #
### URL ###
[https://build.openbuildservice.org/package?_=1717359210615&amp;columns%5B0%5D%5Bdata%5D=name&amp;columns%5B0%5D%5Bname%5D=&amp;columns%5B0%5D%5Borderable%5D=true&amp;columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&amp;columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&amp;columns%5B0%5D%5Bsearchable%5D=true&amp;columns%5B1%5D%5Bdata%5D=changed&amp;columns%5B1%5D%5Bname%5D=&amp;columns%5B1%5D%5Borderable%5D=true&amp;columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&amp;columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&amp;columns%5B1%5D%5Bsearchable%5D=true&amp;draw=1&amp;length=25&amp;order%5B0%5D%5Bcolumn%5D=0&amp;order%5B0%5D%5Bdir%5D=asc&amp;project%5B%24testing%5D=1&amp;search%5Bregex%5D=false&amp;search%5Bvalue%5D=&amp;start=0](https://build.openbuildservice.org/package?_=1717359210615&amp;columns%5B0%5D%5Bdata%5D=name&amp;columns%5B0%5D%5Bname%5D=&amp;columns%5B0%5D%5Borderable%5D=true&amp;columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&amp;columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&amp;columns%5B0%5D%5Bsearchable%5D=true&amp;columns%5B1%5D%5Bdata%5D=changed&amp;columns%5B1%5D%5Bname%5D=&amp;columns%5B1%5D%5Borderable%5D=true&amp;columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&amp;columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&amp;columns%5B1%5D%5Bsearchable%5D=true&amp;draw=1&amp;length=25&amp;order%5B0%5D%5Bcolumn%5D=0&amp;order%5B0%5D%5Bdir%5D=asc&amp;project%5B%24testing%5D=1&amp;search%5Bregex%5D=false&amp;search%5Bvalue%5D=&amp;start=0)"
### Where ###
package#index

### Occured ###
Jun 02  8:29pm

### Similar ###
9

## Params ##
~~~
{
  &quot;_&quot; =&gt; &quot;1717359210615&quot;,
  &quot;action&quot; =&gt; &quot;index&quot;,
  &quot;columns&quot; =&gt; {
    &quot;0&quot; =&gt; {
      &quot;data&quot; =&gt; &quot;name&quot;,
      &quot;name&quot; =&gt; &quot;&quot;,
      &quot;orderable&quot; =&gt; &quot;true&quot;,
      &quot;search&quot; =&gt; {
        &quot;regex&quot; =&gt; &quot;false&quot;,
        &quot;value&quot; =&gt; &quot;&quot;
      },
      &quot;searchable&quot; =&gt; &quot;true&quot;
    },
    &quot;1&quot; =&gt; {
      &quot;data&quot; =&gt; &quot;changed&quot;,
      &quot;name&quot; =&gt; &quot;&quot;,
      &quot;orderable&quot; =&gt; &quot;true&quot;,
      &quot;search&quot; =&gt; {
        &quot;regex&quot; =&gt; &quot;false&quot;,
        &quot;value&quot; =&gt; &quot;&quot;
      },
      &quot;searchable&quot; =&gt; &quot;true&quot;
    }
  },
  &quot;controller&quot; =&gt; &quot;webui/package&quot;,
  &quot;draw&quot; =&gt; &quot;1&quot;,
  &quot;length&quot; =&gt; &quot;25&quot;,
  &quot;order&quot; =&gt; {
    &quot;0&quot; =&gt; {
      &quot;column&quot; =&gt; &quot;0&quot;,
      &quot;dir&quot; =&gt; &quot;asc&quot;
    }
  },
  &quot;project&quot; =&gt; {
    &quot;&amp;#36;testing&quot; =&gt; &quot;1&quot;
  },
  &quot;search&quot; =&gt; {
    &quot;regex&quot; =&gt; &quot;false&quot;,
    &quot;value&quot; =&gt; &quot;&quot;
  },
  &quot;start&quot; =&gt; &quot;0&quot;
}
~~~

## Session ##
~~~
{
  &quot;_csrf_token&quot; =&gt; &quot;eXF-WZelzQCOlcfZO4xvAH3J_4u4wVxwtKgzRAZOTEs&quot;,
  &quot;session_id&quot; =&gt; &quot;aa870937a223f6832ea34ba65934b369&quot;
}
~~~

## Backtrace ##
~~~
25:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/quoting.rb -> **quote**
20:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/arel/collectors/substitute_binds.rb -> **add_bind**
743:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/arel/visitors/to_sql.rb -> **visit_ActiveModel_Attribute**
30:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/arel/visitors/visitor.rb -> **visit**
654:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/arel/visitors/to_sql.rb -> **visit_Arel_Nodes_Equality**
30:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/arel/visitors/visitor.rb -> **visit**
827:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/arel/visitors/to_sql.rb -> **block in inject_join**
825:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/arel/visitors/to_sql.rb -> **each**
825:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/arel/visitors/to_sql.rb -> **each_with_index**
825:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/arel/visitors/to_sql.rb -> **inject_join**
612:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/arel/visitors/to_sql.rb -> **visit_Arel_Nodes_And**
30:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/arel/visitors/visitor.rb -> **visit**
827:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/arel/visitors/to_sql.rb -> **block in inject_join**
825:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/arel/visitors/to_sql.rb -> **each**
825:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/arel/visitors/to_sql.rb -> **each_with_index**
825:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/arel/visitors/to_sql.rb -> **inject_join**
179:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/arel/visitors/to_sql.rb -> **collect_nodes_for**
159:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/arel/visitors/to_sql.rb -> **visit_Arel_Nodes_SelectCore**
30:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/arel/visitors/mysql.rb -> **visit_Arel_Nodes_SelectCore**
124:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/arel/visitors/to_sql.rb -> **block in visit_Arel_Nodes_SelectStatement**
123:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/arel/visitors/to_sql.rb -> **each**
123:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/arel/visitors/to_sql.rb -> **inject**
123:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/arel/visitors/to_sql.rb -> **visit_Arel_Nodes_SelectStatement**
25:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/arel/visitors/mysql.rb -> **visit_Arel_Nodes_SelectStatement**
30:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/arel/visitors/visitor.rb -> **visit**
11:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/arel/visitors/visitor.rb -> **accept**
18:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/arel/visitors/to_sql.rb -> **compile**
37:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/database_statements.rb -> **to_sql_and_binds**
102:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/query_cache.rb -> **select_all**
12:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/mysql/database_statements.rb -> **select_all**
54:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/querying.rb -> **_query_by_sql**
942:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/relation.rb -> **block in exec_main_query**
962:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/relation.rb -> **skip_query_cache_if_necessary**
928:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/relation.rb -> **exec_main_query**
914:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/relation.rb -> **block in exec_queries**
962:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/relation.rb -> **skip_query_cache_if_necessary**
908:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/relation.rb -> **exec_queries**
695:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/relation.rb -> **load**
250:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/relation.rb -> **records**
520:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/relation/finder_methods.rb -> **find_take**
98:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/relation/finder_methods.rb -> **take**
81:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/relation/finder_methods.rb -> **find_by**
22:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/querying.rb -> **find_by**
288:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/core.rb -> **find_by**
51:  app/controllers/webui/webui_controller.rb -> **set_project**
400:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb -> **block in make_lambda**
180:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb -> **block (2 levels) in halting_and_conditional**
34:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/abstract_controller/callbacks.rb -> **block (2 levels) in &lt;module:Callbacks&gt;**
181:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb -> **block in halting_and_conditional**
595:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb -> **block in invoke_before**
595:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb -> **each**
595:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb -> **invoke_before**
106:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb -> **run_callbacks**
233:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/abstract_controller/callbacks.rb -> **process_action**
23:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/rescue.rb -> **process_action**
67:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/instrumentation.rb -> **block in process_action**
206:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications/instrumenter.rb -> **instrument**
206:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb -> **instrument**
66:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/instrumentation.rb -> **process_action**
259:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal/params_wrapper.rb -> **process_action**
27:  /GEM_ROOT/gems/activerecord-7.0.8.1/lib/active_record/railties/controller_runtime.rb -> **process_action**
151:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/abstract_controller/base.rb -> **process**
39:  /GEM_ROOT/gems/actionview-7.0.8.1/lib/action_view/rendering.rb -> **process**
188:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal.rb -> **dispatch**
251:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_controller/metal.rb -> **dispatch**
49:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/route_set.rb -> **dispatch**
32:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/route_set.rb -> **serve**
18:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/mapper.rb -> **block in &lt;class:Constraints&gt;**
48:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/mapper.rb -> **serve**
50:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/journey/router.rb -> **block in serve**
32:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/journey/router.rb -> **each**
32:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/journey/router.rb -> **serve**
852:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/routing/route_set.rb -> **call**
87:  /GEM_ROOT/gems/flipper-1.3.0/lib/flipper/middleware/memoizer.rb -> **memoized_call**
45:  /GEM_ROOT/gems/flipper-1.3.0/lib/flipper/middleware/memoizer.rb -> **call**
15:  config/initializers/prefer_xml_over_html.rb -> **call**
44:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/deflater.rb -> **call**
15:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/tempfile_reaper.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/etag.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/conditional_get.rb -> **call**
12:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/head.rb -> **call**
38:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/http/permissions_policy.rb -> **call**
36:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/http/content_security_policy.rb -> **call**
266:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/session/abstract/id.rb -> **context**
260:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/session/abstract/id.rb -> **call**
704:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/cookies.rb -> **call**
27:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/callbacks.rb -> **block in call**
99:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb -> **run_callbacks**
26:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/callbacks.rb -> **call**
32:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call!**
21:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call**
28:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/debug_exceptions.rb -> **call**
29:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/show_exceptions.rb -> **call**
18:  /GEM_ROOT/gems/lograge-0.14.0/lib/lograge/rails_ext/rack/logger.rb -> **call_app**
25:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/rack/logger.rb -> **block in call**
99:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/tagged_logging.rb -> **block in tagged**
37:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/tagged_logging.rb -> **tagged**
99:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/tagged_logging.rb -> **tagged**
25:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/rack/logger.rb -> **call**
93:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/remote_ip.rb -> **call**
93:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/remote_ip.rb -> **call**
19:  /GEM_ROOT/gems/request_store-1.7.0/lib/request_store/middleware.rb -> **call**
26:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/request_id.rb -> **call**
24:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/method_override.rb -> **call**
22:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/runtime.rb -> **call**
29:  /GEM_ROOT/gems/activesupport-7.0.8.1/lib/active_support/cache/strategy/local_cache_middleware.rb -> **call**
14:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/executor.rb -> **call**
18:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/lock.rb -> **call**
110:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/sendfile.rb -> **call**
131:  /GEM_ROOT/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/host_authorization.rb -> **call**
530:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/engine.rb -> **call**
226:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/railtie.rb -> **public_send**
226:  /GEM_ROOT/gems/railties-7.0.8.1/lib/rails/railtie.rb -> **method_missing**
74:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/urlmap.rb -> **block in call**
58:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/urlmap.rb -> **each**
58:  /GEM_ROOT/gems/rack-2.2.9/lib/rack/urlmap.rb -> **call**
107:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb -> **process_request**
149:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **accept_and_process_next_request**
110:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **main_loop**
419:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/request_handler.rb -> **block (3 levels) in start_threads**
113:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.20/src/ruby_supportlib/phusion_passenger/utils.rb -> **block in create_thread_and_abort_on_exception**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| program_name | Passenger RubyApp: /srv/www/obs/api (production) |
| HTTP_USER_AGENT | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 |

### PR DESCRIPTION
**Pull request by danidoni**
We don't want to crash with

    can't quote ActionController::Parameters

whenever people put garbage inside parameters

Follow up of #16377
Fixes #16379

### CODE REVIEW

File: src/api/app/controllers/webui/monitor_controller.rb [hunk 1]
```diff
@@ -44,7 +44,8 @@ def update_building
   def events
     data = {}
 
-    arch = Architecture.find_by(name: params.fetch(:arch, @default_architecture))
+    arch = Architecture.find_by(name: params.fetch(:arch, @default_architecture).to_s)
```
Comment (eduardoj) [inline src/api/app/controllers/webui/monitor_controller.rb:47]:
```suggestion
    arch = Architecture.find_by(name: params.fetch(:arch, @default_architecture))
```
Later on in this file we use `arch.name`...

Comment (eduardoj) [reply src/api/app/controllers/webui/monitor_controller.rb:47]: Opss... now I get it. `.to_s` is not applied to the result of the `find_by`. Sorry for the noise.

**Review by eduardoj — APPROVED** [review]
